### ISSUE TITLE
教程有误

### ISSUE THREAD

**Issue by LolitaOT** [koishijs/koishi#10]
**Describe the bug**

npm init -y的时候package中项目名为koishi
下一步安装koishi时会报错
**To Reproduce**

npm init -y
npm init koishi -D
**Expected behavior**

建议修改默认项目名称
**Screenshots**

**Versions**

- Node Version: [e.g. 10.16.0]
- CoolQ Version: [e.g. 5.15.4]
- CQHTTP Version: [e.g. 4.13.2]
- Koishi Version: [e.g. 1.0.0]

**Additional context**

**Comment by Shigma** [comment]
感觉这是你自己的问题吧，本地项目名不能和要安装的包名一样。要么文件夹别叫 koishi，要么手动修改本地项目名。

以及我没看到文档哪里写了 npm init -y，能说明一下吗？

**Comment by LolitaOT** [comment]
> 感觉这是你自己的问题吧，本地项目名不能和要安装的包名一样。要么文件夹别叫 koishi，要么手动修改本地项目名。
> 
> 以及我没看到文档哪里写了 npm init -y，能说明一下吗？

https://koishijs.github.io/guide/getting-started.html#%E8%B0%83%E7%94%A8-koishi

**Comment by LolitaOT** [comment]
> 感觉这是你自己的问题吧，本地项目名不能和要安装的包名一样。要么文件夹别叫 koishi，要么手动修改本地项目名。
> 
> 以及我没看到文档哪里写了 npm init -y，能说明一下吗？

抱歉，是我的问题，我的项目文件夹重名了
