### ISSUE TITLE
Feature: 优化错误输出

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1002]
### Describe the problem related to the feature request

![88e77d3ae929641cc7aeb4652d118ee](https://user-images.githubusercontent.com/25239977/222777308-2e8db4bc-e634-41c4-b082-c74b3b8c4841.png)

日志根本看不出是哪个插件的问题，然后无限重启，手动 hook 了 axios 才知道是哪个接口 timeout 了

### Describe the solution you'd like

优化错误日志输出

**Comment by shigma** [comment]
所以是哪个插件的问题（

**Comment by Ice-Hazymoon** [comment]
> 所以是哪个插件的问题（

T。。。Telegram

**Comment by shigma** [comment]
tg 需要你配个代理。不过这个优化确实可以做。

**Comment by shigma** [comment]
tg 需要你配个代理。不过这个优化确实可以做。

**Comment by Ice-Hazymoon** [comment]
我认为不是配代理的问题，主要是这个错误 log 没有提供任何有意义的帮助，一报错就无限重启，应该在报错的时候输出插件名，让开发者能更好的定位错误。

**Comment by shigma** [comment]
我知道你的意思。但这个优化并不好做，一个错误可能来自一个插件触发的事件在第二个插件注册的回调函数里，事件的成因又是第三个插件提供的 API。目前很难说完全判定某个错误的来源。

所以我希望在保留这个 issue 的同时先尽量解决你的问题本身，再慢慢考虑万全之策。

**Comment by ilharp** [comment]
不过我也很好奇，为什么其他报错都带有带有插件名的堆栈，为什么唯独网络请求没有呢？网络请求是使用事件实现的吗？

**Comment by Anillc** [comment]
大概是因为 `polling` 是通过 setTimeout 实现的，抛出异常也是在 node 的事件循环里了，所以堆栈不会显示代码的具体位置

**Comment by shigma** [comment]
或许用 error.cause 可以解决。

**Comment by CyanChanges** [comment]
之前找了挺久才知道哪里有问题，改了有时间试试
