### ISSUE TITLE
Bug: koishi 的指令系统不会处理 telegram 的指令

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1004]
### Describe the bug

在 botfather 设置机器人的指令后，于群组内点击 Telegram 提示的指令， koishi 不会对其反应。
Telegram 指令格式：`/name@user_id`

### Steps to reproduce

1.
![qq_pic_merged_1677994722258](https://user-images.githubusercontent.com/96647698/222943665-209016ef-1f7d-4d7e-ae5e-6e23aa49ff88.jpg)

2.
![qq_pic_merged_1677994768493(1)](https://user-images.githubusercontent.com/96647698/222943697-9ac2f0d1-06ff-40c0-b2ac-124d314641a4.jpg)

### Expected behavior

反应 Telrgram 的指令

### Versions

- OS: Windows 11
- Platform: Telegram
- Node version: 19.7.0
- Koishi version: 4.11.8

**Comment by shigma** [comment]
之后会做。

**Comment by idanran** [comment]
> 之后会做。

嗯呐

**Comment by shigma** [comment]
4.14.2 版本已经支持。
