### ISSUE TITLE
Feature: 有办法实现插件的优先级吗

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1007]
### Describe the problem related to the feature request

例如消息先通过 A 插件，再通过 B 插件。
在文档里没搜到，不知道该如何实现。

还有一个问题，如何扩展 ctx 对象。
例如我在 A 插件中为 ctx 对象增加了一个 $user_rate 属性。
我在 B 插件可以获取到这个属性。

### Describe the solution you'd like

为插件增加一个优先级

**Comment by shigma** [comment]
你没有把问题表达清楚，「消息先通过 A 插件，再通过 B 插件」是指中间件吗？

**Comment by Ice-Hazymoon** [comment]
是的

**Comment by shigma** [comment]
那么有多种解决方案，你可以根据你的需求自行选择。

### 方案 A：使用前置中间件

```ts
// plugin-1
ctx.middleware((session, next) => {
  if (某些条件) {
    session['$user_rate'] = 某个值
  }
  return next()
}, true /* 注意看，这个参数叫小真，表示前置中间件 */)
```

```ts
// plugin-2
ctx.middleware((session, next) => {
  if (session['$user_rate']) {
    做某件事
  } else {
    return next()
  }
})
```

- 优点：写法最简单
- 缺点：plugin-1 的中间件里不能使用某些会话属性 (如 session.user)

**Comment by shigma** [comment]
不借助前置中间件，仅仅使用一点小技巧，也能达到方案 A 的效果。

### 方案 B：一点中间件技巧

```ts
// plugin-1
ctx.middleware((session, next) => {
  if (某些条件) {
    session['$user_rate'] = 某个值
  }
  return next()
})
```

```ts
// plugin-2
ctx.middleware(async (session, next) => {
  const result = await next()
  if (session['$user_rate']) {
    做某件事
  } else {
    return result
  }
})
```

- 优点：解决了方案 A 中 plugin-1 无法访问某些属性的问题
- 缺点：理解起来复杂一些

**Comment by Ice-Hazymoon** [comment]
扩展 ctx 的问题明白了，但如果我有多个插件（中间件），如何确保他们能够按照顺序调用呢。

**Comment by shigma** [comment]
还有一种最直接的办法就是通过限制插件的加载顺序来限制中间件的加载顺序。

### 方案 C：高射炮打蚊子

```ts
// plugin-1
// 提供某个名为 foo 的服务
ctx.middleware((session, next) => {
  if (某些条件) {
    session['$user_rate'] = 某个值
  }
  return next()
})
```

```ts
// plugin-2
// 依赖某个名为 foo 的服务
ctx.middleware((session, next) => {
  if (session['$user_rate']) {
    做某件事
  } else {
    return next()
  }
})
```

- 优点：不动脑子
- 缺点：需要额外提供服务，方案比较笨重

**Comment by shigma** [comment]
> 扩展 ctx 的问题明白了，但如果我有多个插件（中间件），如何确保他们能够按照顺序调用呢。

上述三个方案都能对于两个中间件的情况确保调用顺序。

- A 方案是通过前置中间件来确保的
- B 方案是通过 plugin-2 中的 `await next()` 来确保的
- C 方案是通过限制插件加载顺序的方式来确保的

**Comment by shigma** [comment]
个人推荐 A 或者 B，C 的话感觉有点滥用服务了（除非你本来就像把 plugin-1 设计成服务）。

**Comment by Ice-Hazymoon** [comment]
感谢回答，但还是有些不明白
方案A，如果我有多个前置中间件，那么如何控制这些前置中间件的调用顺序呢。
方案B，如何确保koishi 是先调用的 plugin-2，如果先调用了 plugin-2，那么 plugin-2 将永远无法获取 session['$user_rate'] 的内容不是吗。

**Comment by Ice-Hazymoon** [comment]
我的理想情况是，为每一个插件增加一个 Priority 字段来代表优先级，koishi 按照优先级来一次调用这些插件

**Comment by shigma** [comment]
> 方案 A，如果我有多个前置中间件，那么如何控制这些前置中间件的调用顺序呢

没有办法控制。可以切换到方案 B。

> 方案 B，如果先调用了 plugin-2，那么 plugin-2 将永远无法获取 session['$user_rate'] 的内容

可以获取，方案 B 的核心是 `await next()`。你可以想一下：

- 如果先 1 后 2，那么 2 的时候已经有这个值了
- 如果先 2 后 1，那么 2 的时候先执行 next，执行完 1 就跑过了，下面也有这个值了

**Comment by Ice-Hazymoon** [comment]
方案B，如果我有 2 个以上的中间件呢。

**Comment by shigma** [comment]
> 为每一个插件增加一个 Priority 字段来代表优先级，koishi 按照优先级来一次调用这些插件

首先应该是为中间件而不是为插件。

你提的方案作为通用解决方案是可行的。但目前来看需求面比较窄，中间件系统运行至今也没有遇到什么解决不了的需求。你是 Koishi 的老用户了，应该能理解这一点。

至于你说的我有很多中间件的情况。这 2 个以上的中间件真的需要强制确定先后关系吗？如果是这样，我认为就不应通过中间件实现，而是由插件 1 编写一个中间件，并触发自定义事件，交给插件 2/3 来监听。

```ts
// plugin-1
ctx.middleware(async (session, next) => {
  if (!某些条件) return next()
  session['$user_rate'] = 某个值
  ctx.emit('事件1', session)
  return 做某件事()
})
```

```ts
// plugin-2
ctx.on('事件1', (session) => {
  做其他事()
})
```

如果插件 2 还需要提供属性给插件 3 用，那可以继续设置事件：

```ts
// plugin-2
ctx.on('事件1', (session) => {
  做其他事()
  ctx.emit('事件2', session)
})
```

```ts
// plugin-3
ctx.on('事件2', (session) => {
  做更多事()
})
```

以我的理解，你试图把插件自定义的逻辑移交给中间件系统来完成。中间件系统不可能也不应该处理无限复杂的逻辑。引入优先级能解决一部分，但这里的优先级数值仅仅对你的插件生态有效，对其他插件是没有意义的，我并不认为能解决更多的问题。

**Comment by Seidko** [comment]
是的，这个 `Priority` api 完全不能带来实际的效果，反而会造成混乱。

`z-index: 100000000000;`.jpg

**Comment by Ice-Hazymoon** [comment]
确实引入优先级对于社区插件估计没多大意义，毕竟每个都是单独的，没有互相依赖，但在稍微大一些的独立系统中会起到重要作用，需要许多中间件来处理上下文，一层接一层。

单独加 Priority API 或许不现实，可能也会给你们带来额外的维护负担，但哪怕是加载顺序按照 **“插件名称”** 加载也行，都能对这“少部分”开发者有很大的帮助。

题外话：20 年接触的 Koishi，那时候也问过一样的问题（如何扩展上下文对象），本以为现在新增了一些奇奇怪怪的 API 能实现这一点，所以重新来问问，没想到还是祖传的处理方式，不过确实完全够用了，有各种曲线的方法来处理 99% 的需求。

最后希望 Koishi 越来越好（Bug 也越来越少）

**Comment by Seidko** [comment]
我还是认为有许多别的方法能实现中间件的效果，中间件的目的就是为了逐层处理事件，同级别的中间件本来就应该被当作是具有相同优先级的。

> 但哪怕是加载顺序按照 “插件名称” 加载也行

这里要考虑一些边界情况，并不是所有插件都是在同一时间加载的。比如用户中途启用了一个插件，这样的名称优先级就会带来各种非预期的行为，这是十分麻烦且不必要的。

**Comment by Ice-Hazymoon** [comment]
> 比如用户中途启用了一个插件

你这么一说，还挺有道理，我要是开发者我也不愿意加 Priority
