### ISSUE TITLE
Bug: @koishijs/plugin-adapter-feishu飞书无法发送图片消息，日志看到400

### ISSUE THREAD

**Issue by RyanKKKKKKKk** [koishijs/koishi#1008]
### Describe the bug

用novelai生成图片的时候可以返回生成步骤，但是图片无法返回
![image](https://user-images.githubusercontent.com/125950356/223055267-766bd4b1-7bf0-46fa-9961-f1c566297cd2.png)
日志看到有400的报错
![image](https://user-images.githubusercontent.com/125950356/223055319-09d2aed2-1928-499f-bc84-58e96328ec6d.png)

### Steps to reproduce

对接飞书后，用novelai生成图片

### Expected behavior

对接飞书后，用novelai生成图片正常返回图片

### Versions

- OS: Linux Docker
- Koishi version: 4.11.9
- @koishijs/plugin-adapter-feishu 1.2.2

**Comment by RyanKKKKKKKk** [comment]
![image](https://user-images.githubusercontent.com/125950356/223056389-24961614-353b-443c-a7c2-7612e9ec9d2b.png)
问题找到了，是飞书的权限管理，建议文档增加一下。

**Comment by MaikoTan** [comment]
Good catch, thanks for the reporting.

**Comment by RyanKKKKKKKk** [comment]
@MaikoTan By the way, I would like to ask if there is an issue with the image generation feature in Feishu currently, Unable to upload image, parsing error occurs. Is this a bug or something that was not previously planned?
![image](https://user-images.githubusercontent.com/125950356/223067535-88826c21-9962-4338-998b-f3866a3c1d93.png)

**Comment by MaikoTan** [comment]
> @MaikoTan By the way, I would like to ask if there is an issue with the image generation feature in Feishu currently, Unable to upload image, parsing error occurs. Is this a bug or something that was not previously planned?
> ![image](https://user-images.githubusercontent.com/125950356/223067535-88826c21-9962-4338-998b-f3866a3c1d93.png)
> 

Okay, I'll take a look later when I have time. Could you check if your `encryptKey` set-up was incorrect or lacking letters? If you have confirmed that the configuration is correct but still got errors, you could open a new issue in https://github.com/satorijs/satori
