### ISSUE TITLE
Bug: 重载失效

### ISSUE THREAD

**Issue by Kabuda-czh** [koishijs/koishi#1014]
### Describe the bug

在当前版本中, 生产环境重载插件或开发环境中热重载, 均会让 `help` 以及插件的 `option` 失效!

### Steps to reproduce

将任意插件重载/安装/卸载, 即可复现

### Expected behavior

插件的重载行为应该正常加载运行

### Versions

- OS:  `Windows 11`
- Platform:  `N/A`
- Node version:  `N/A`
- Koishi version:  `4.11.9`

**Comment by shigma** [comment]
最新版应该已修复此问题。
