### ISSUE TITLE
Bug: QQ频道无法进行Bind绑定

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi#1015]
### Describe the bug

QQ频道无法进行第二次bind绑定
![image](https://user-images.githubusercontent.com/40047545/223492093-a1a641c0-b4bc-4a15-bfa4-049c78b7a23e.png)

### Steps to reproduce

使用QQGUILD适配器，然后进行bind绑定

### Expected behavior

可以进行跨平台绑定

### Versions

- OS: linux
- Platform: qqguild
- Node version: 17.9
- Koishi version: 4.11

**Comment by shigma** [comment]
cc @NWYLZW

**Comment by NWYLZW** [comment]
这个没看出来，多给点日志？

**Comment by KuroshioDev** [comment]
> 这个没看出来，多给点日志？

第二次认证，发送 @bot koishi/224476， 没有任何反应

**Comment by shigma** [comment]
哦这个得完全匹配的，不接受 at。at 是非要发的吗？

**Comment by NWYLZW** [comment]
不必要吧？

**Comment by NWYLZW** [comment]
频道能接受非 @ 请求呀？并不一定要 @ 前缀机器人才能收到诶？
你是什么类型的机器人，公域吗，那个有这个限制？

**Comment by shigma** [comment]
bind 插件目前没有提供 at 识别的功能，也没有在文档或提示语中告知输入 at。

**Comment by KuroshioDev** [comment]
> 频道能接受非 @ 请求呀？并不一定要 @ 前缀机器人才能收到诶？ 你是什么类型的机器人，公域吗，那个有这个限制？

公域必须要@机器人

**Comment by NWYLZW** [comment]
> > 频道能接受非 @ 请求呀？并不一定要 @ 前缀机器人才能收到诶？ 你是什么类型的机器人，公域吗，那个有这个限制？
> 
> 公域必须要@机器人

可以优化，我得想一下，有思路但是并不是很合适

**Comment by shigma** [comment]
此问题可以在 bind 测解决。加上 at 的识别即可。不过我不认为是一种通用的解决方案。类似的插件应该还有别的。

**Comment by NWYLZW** [comment]
> 此问题可以在 bind 测解决。加上 at 的识别即可。不过我不认为是一种通用的解决方案。类似的插件应该还有别的。

是的，我是准备在 adapter 层加个默认参数过滤掉公域的 @ 消息
你觉得如何？

**Comment by shigma** [comment]
> 我是准备在 adapter 层加个默认参数过滤掉公域的 @ 消息

不太同意。这会导致指令调用方式受限。

其实最坏情况下，一个个实现也没啥问题……

**Comment by NWYLZW** [comment]
> > 我是准备在 adapter 层加个默认参数过滤掉公域的 @ 消息
> 
> 不太同意。这会导致指令调用方式受限。
> 
> 其实最坏情况下，一个个实现也没啥问题……

我大概能理解为什么限制公域的消息接收机制，不管怎么样都是被受限的

**Comment by shigma** [comment]
那就先解决问题吧，我觉得改进一下 bind 并不困难，改进完题主的需求就算实现了，至于 qqguild 如何优化我们还有很多 issue 可以从长计议。

**Comment by NWYLZW** [comment]
可以做，但是觉得成本比较高，改造范围比较大
我觉得 satori 的 session 功能其实蛮强大的
大部分插件使用的时候也并不需要在前面 @机器人 触发
satori 会托管当前的 session，并不需要去在连续的会话中做状态保持

**Comment by NWYLZW** [comment]
我不清楚是否有一个全局前缀的功能，因为我没有使用过

如果有的话，在全局前缀的处理逻辑是如何的？
应该也是直接剔除掉全局前缀吧

**Comment by shigma** [comment]
前缀功能只对指令有效，并且 bind 这种插件使用的前置中间件，拿不到相关信息。

**Comment by ghostcatu** [comment]
> 我不清楚是否有一个全局前缀的功能，因为我没有使用过
> 
> 如果有的话，在全局前缀的处理逻辑是如何的？ 应该也是直接剔除掉全局前缀吧

你好，请问QQ频道适配器有重连机制吗，经常用着用着就不响应了但是其他平台还可以响应，也没有报错日志

**Comment by NWYLZW** [comment]
> > 我不清楚是否有一个全局前缀的功能，因为我没有使用过
> > 如果有的话，在全局前缀的处理逻辑是如何的？ 应该也是直接剔除掉全局前缀吧
> 
> 你好，请问QQ频道适配器有重连机制吗，经常用着用着就不响应了但是其他平台还可以响应，也没有报错日志

有的，不过建议你单独开一个 issue 讨论相关问题

**Comment by shigma** [comment]
已修复。下个版本实装。
