### ISSUE TITLE
Bug: gocq-http无法连接到qq频道

### ISSUE THREAD

**Issue by KD-T100** [koishijs/koishi#1018]
### Describe the bug

3月份后onebot提示账号被冻结或密码错误，根据论坛的方法改了accounts 文件夹里的文件后，私聊和qq群都可以响应，但在qq频道未有响应，日志里也接受不到内容。猜测是gocq的问题，在accounts 文件夹的device.json文件中将protocol改为2后因为用的是手表协议，接收不到来自qq频道的内容，应该是手表上的qq未支持qq频道的使用。另外戳一戳功能也无法正常使用

device.json文件中的protocol改成除了2以外的数字都提示密码错误或账号冻结，扫码和密码登录都不行

### Steps to reproduce

把gocq-http登陆协议改为2，重新登录账号，在qq频道内输入指令或者at都没有反应

### Expected behavior

以前的版本不需要更改协议也能用，而且也能在qq频道响应。希望能解决一下

### Screenshots

![QQ图片20230308111514](https://user-images.githubusercontent.com/36659293/223610704-163d611b-25dd-4ee0-9dbe-799dbd234ec8.png)

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by Lipraty** [comment]
这是 gocq 问题，你可以去 go-cqhttp 发。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by HsiangNianian** [comment]
解决不了，QQ协议变了，你只能用Android Watch，你也说了手表协议不支持频道，也不支持戳一戳，该怎么修，只能看gocq下个版本了，或者你要求一下tx

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by SaarChaffee** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/1939

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
gocq 通常有两种登录方式：账密登录和扫码登录。目前由于协议改动，gocq 的账密登录无效，扫码登录又只能使用 protocol 2，故产生了上面的问题。

目前据我所知，gocq dev 已经修复了账密登录但并未发版，扫码登录仍未修复。如果情况没有改善，我们会在未来的一段时间内对接 gocq 的 artifact 版本，来解决登录问题。

**Comment by shigma** [comment]
最新版本的 gocqhttp 已经能使用其他 protocol 登录了，此问题视为解决。
