### ISSUE TITLE
Koishi v3 特性征集

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#102]
### user

| 键 | 类型 | 描述 |
| :-: | :-: | :-: |
| name | string | 供机器人使用的昵称 |
| qqid | string | QQ 号，当使用了 adapter-cqhttp 时使用，其他平台类似 |
| flag | number | 状态标记 |
| authority | integer | 权限等级 |
| usage | object | 调用记录 |
| timers | object | 定时器记录 |

这种设计允许了每个账号绑定到多个平台。

**Comment by Shigma** [comment]
## 多平台支持

尽管目前只支持了 cqhttp (onebot)，但未来还是会考虑做更多平台的支持的。为此有必要做下列更改：

- 将 userId / groupId / selfId 类型变为 string
- 减少 session 中原生属性的数量，或将其中的一部分抽象化
- 将 session.$send 等更多方法的定义交给 adapter 负责

此外，还需要考虑 CQ Code 的兼容性问题。

**Comment by Ice-Hazymoon** [comment]
希望能先完善下V2的文档，`koishi init` 完随便撸个demo都跑不起来www

**Comment by Shigma** [comment]
确实，我紫菜（

**Comment by masnn** [comment]
> 将 session.$send 等更多方法的定义交给 adapter 负责

建议： 对adapter建立规范（session.$send所有adapter都应实现？）

> 将用户系统改为使用 name 作为主键，然后用 qqid 等代替 id，以实现多平台账号的互通。

建议： 使用诸如 `qq/123456` `telegram/-123456` 的 ID。
另，需要允许用户绑定账号（如 `qq/123456` 与 `telegram/-123456` 使用同一组用户数据。

Config建议：

```ts
bots:{
  cqhttp:[
    // cqhttp accounts  
  ],
  telegram:[
    // telegram accounts
  ]
}
```

> CQ Code 兼容性

继续使用onebot协议的messageString。 具体如何发送交给adapter转换。

另： 应定义更多判断函数接口。
`canSendImage() canSendRecord() canSendVideo() canSendPoll() canSendFile() canUseMarkdown() canUseActionButton()`

**Comment by masnn** [comment]
Need Discussion: 是否仍有必要区分 private 和 group 逻辑

Private 可理解为仅有两人的群组且 groupId = userId。
若合并可大大简化逻辑且便于存储（仅需根据 chatId 区分 context）

**Comment by Shigma** [comment]
@masnn 我觉得可以通过 trap 实现，即在数据库中存储 qq, tg 这些 id，但是当使用了 type qq 的 bot 时，bot.selfId, session.userId 自动对应 qq，反之亦然。

**Comment by Shigma** [comment]
> Need Discussion: 是否仍有必要区分 private 和 group 逻辑

有的平台直接使用 channel id 同时管理私聊和群消息，所以你说的很有道理。

> Private 可理解为仅有两人的群组且 groupId = userId

这个不太行，有的 QQ 号和群号是相同的。

**Comment by masnn** [comment]
koishi内部不是用另一套id吗（

**Comment by masnn** [comment]
那么应该提供转换api，用户很可能会绕开getUser/setUser方法手动操作数据库。

**Comment by purerosefallen** [comment]
In fact I rarely use the database inside the bot.
I often use TypeORM for database needed, becuase It's better to allow me constructing my own data model, including many relations, one-to-one, or one-to-many, etc.
In addition, I hope the table injection could support adding (unique) indexes in database, for better performance.

**Comment by undefined-moe** [comment]
添加pipe语法
e.g.

- `.echo a b c | md5`
- `getGroupMemberList | length`

**Comment by Shigma** [comment]
> In fact I rarely use the database inside the bot.
> I often use TypeORM for database needed, becuase It's better to allow me constructing my own data model, including many relations, one-to-one, or one-to-many, etc.
> In addition, I hope the table injection could support adding (unique) indexes in database, for better performance.

Maybe we can write plugin like `koishi-plugin-typeorm` to support general databases.

**Comment by Shigma** [comment]
close in favor of #131
