### ISSUE TITLE
Bug: 文字 + \n + @消息元素, 换行符会丢失

### ISSUE THREAD

**Issue by mice33** [koishijs/koishi#1027]
### Describe the bug

文字 + \n + @消息元素, 换行符会丢失

### Steps to reproduce

创建模板项目，再使用 yarn setup 新建插件
插件内容为
```
  ctx.middleware((meta, next) => {
    return 'Hello, world!\n' + h('at', { id: '123', name: '123' })
  });
```
使用 yarn dev 启动开发模式
进沙盒发送信息

### Expected behavior

换行符正确显示

### Screenshots

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4945433/225245047-815db4c1-abc4-4528-8912-ea96b59d4837.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/4945433/225242110-9ab9d71a-a411-4b28-836f-4e9ea15adefc.png">

```
  ctx.middleware((meta, next) => {
    return 'Hello, world!\n1' + h('at', { id: '123', name: '123' })
  });
```

<img width="487" alt="image" src="https://user-images.githubusercontent.com/4945433/225242543-6e3ddb25-c085-449a-ab8c-8c7a85b13845.png">

```
  ctx.middleware((meta, next) => {
    return 'Hello, world!\n' + h('at', { id: '123', name: '123' })
  });
```

### Versions

- Node version: 14.18.3
- Koishi version: 4.12.0

**Comment by shigma** [comment]
这是预期行为：https://koishi.chat/api/message/syntax.html#%E5%85%83%E7%B4%A0

请使用 `&lt;p&gt;` 来实现换行。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by mice33** [comment]
按照上面写的代码, 我应该如何改写呢
