### ISSUE TITLE
Bug: 执行`yarn create koishi`报错

### ISSUE THREAD

**Issue by holk-h** [koishijs/koishi#1030]
### Describe the bug

在macos中执行`yarn create koishi`报错

### Steps to reproduce

执行`yarn create koishi`

### Expected behavior

项目创建成功

### Screenshots

<img width="937" alt="40632833c78ed9f13c40c85baad40f76" src="https://user-images.githubusercontent.com/29571233/225806037-93ac63c2-d308-478a-801e-51f08e90cc13.png">

### Versions

- OS: macos 13.2.1
- Node version: v18.15.0

**Comment by shigma** [comment]
我们刚刚更新了模板项目，你试试用最新版的 create 会不会报错。

**Comment by holk-h** [comment]
> 我们刚刚更新了模板项目，你试试用最新版的 create 会不会报错。

还是报这个错...同样的输出，一模一样

**Comment by ymy139** [comment]
在arm64平台的树莓派上 create 也会报这个错，项目同样创建成功，正常使用，但是onebot无法链接go-cqhttp

**Comment by shigma** [comment]
现在应该已经不会报错。
