### ISSUE TITLE
Bug: 在windows下，QQ频道适配器无法发送图片

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi#1034]
### Describe the bug

在windows os下 QQ频道适配器无法发送图片，**在linux下可以发送**
1. 图片肯定存在
2. linux下正常发送，如下图
![image](https://user-images.githubusercontent.com/40047545/226164774-b49ef8e0-a3b7-4367-bb69-1f601e54cc38.png)
3. 沙盒下也正常
![image](https://user-images.githubusercontent.com/40047545/226168971-ce79405d-cc3e-47fa-a9d8-90529e4a55b0.png)

在windows下的报错：
![image](https://user-images.githubusercontent.com/40047545/226164673-db4df5e0-c92d-45d8-be87-cbfe733a8bf5.png)

### Steps to reproduce

1.在windows下安装koishi
2.安装qqguidld插件
2.往频道发送一张图片

### Expected behavior

windows下不报错

### Versions

- OS: windows
- Platform: qqguild
- Node version: 17
- Koishi version: 4.12.0

**Comment by shigma** [comment]
fixed by https://github.com/satorijs/satori/pull/79

**Comment by KuroshioDev** [comment]
fix
