### ISSUE TITLE
Bug: command 无法隐藏选项

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1036]
### Describe the bug

https://koishi.chat/guide/basic/command.html#%E5%AE%9A%E4%B9%89%E5%8F%82%E6%95%B0

```
ctx.command('bar 一条看不见的指令', { hidden: true })
  .option('foo', '<text> 一个看不见的选项')
  .action(({ options }) => 'secret: ' + options.foo)
```

依旧会返回选项

```
$ help bar

指令：bar 一条看不见的指令
可用的选项有：
    --foo <text>  一个看不见的选项
```

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

- Koishi version: "koishi": "^4.12.1"

**Comment by shigma** [comment]
这是预期的行为，指令的 hidden 意味着这个指令不出现在全局指令列表（或其父指令的子指令列表）中。你仍然可以通过 help + 指令名的方式插件其用法。

**Comment by Ice-Hazymoon** [comment]
了解，文档内容有误或过时。

**Comment by shigma** [comment]
哦，文档的例子只写了指令没写选项，我去补一下。
