### ISSUE TITLE
Bug: gocq rc5 更改 terminal 标题

### ISSUE THREAD

**Issue by Kabuda-czh** [koishijs/koishi#1037]
### Describe the bug

新版 `gocq` 在 koishi 启动后更改命令行窗口标题

### Steps to reproduce

使用 terminal 启动 koishi

### Expected behavior

不更改标题

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by dragon-fish** [comment]
设置 [`process.title`](https://nodejs.org/dist/latest-v18.x/docs/api/process.html#processtitle)，干它！

**Comment by MaikoTan** [comment]
Since `go-cqhttp` and related plugins are not maintained anymore, this issue was obsolete.
