### ISSUE TITLE
Feature: 数据库操作如何进行分页和排序操作

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#1039]
### Describe the problem related to the feature request

数据库操作如何进行分页和排序操作

### Describe the solution you'd like

增加排序和分页的参数

**Comment by MaikoTan** [comment]
Although this issue is closed, but I think it would be helpful to answer here before docs update:

```ts
ctx.database
  // Pagination:
  // or `.limit(limit)`
  // while `offset` and `limit` are both `number`
  .limit(offset, limit)
  // Sort:
  // `direction` could be 'asc' or 'desc'
  .orderBy(key, direction)
```

It is also possible to issue on https://github.com/koishijs/docs for the docs update.
