### ISSUE TITLE
Bug: 最新版koishi数据库user表没有qq号

### ISSUE THREAD

**Issue by Haku530** [koishijs/koishi#1040]
### Describe the bug

![image](https://user-images.githubusercontent.com/124163849/227771824-482531ca-9f9a-46a7-a182-a43ab9a9baef.png)
如图，导致需要权限的指令无法使用

### Steps to reproduce

复现：所有插件更到最新

### Expected behavior

恢复user表

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by ilharp** [comment]
这是预期的行为。提权的方法可以看 [这里](https://forum.koishi.xyz/t/topic/1055)。

另请注意不要在 issue 版块询问使用问题。使用问题请前往 discussion 版。
