### ISSUE TITLE
Feature: Matrix (synapse) support

### ISSUE THREAD

**Issue by NoverNobida** [koishijs/koishi#1044]
### Describe the problem related to the feature request

[Matrix](https://github.com/matrix-org/synapse) is an open standard for communications on the internet, supporting federation, encryption and VoIP. But now koishi doesn't support it.

### Describe the solution you'd like

Add support for Matrix (synapse).

**Comment by MaikoTan** [comment]
Is [koishi-plugin-adapter-matrix](https://www.npmjs.com/package/koishi-plugin-adapter-matrix) what you need?

**Comment by NoverNobida** [comment]
Thank you so much. I searched before and couldn't find it.
