### ISSUE TITLE
Feature: telegram 支持 bot.editMessage()

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1048]
### Describe the problem related to the feature request

我想要实现 telegram 流式输出（类似 openai 的 stream，一个字一个字的出现），我不知道 Koishi 是否有这方面的 API，或者是否有 Hack 的实现思路，例如

```js
session.tg.send_message(chat_id, text)
```

### Describe the solution you'd like

如题

**Comment by Seidko** [comment]
没太懂你的意思……你是想修改消息吗？

**Comment by Ice-Hazymoon** [comment]
啊对对对

**Comment by Seidko** [comment]
> 啊对对对

😕 这句话是网络用语的意义，还是其本意？

**Comment by Seidko** [comment]
有edit message api啊
https://koishi.chat/api/core/bot.html#bot-editmessage

**Comment by shigma** [comment]
不，telegram 是不是本来就没支持 editMessage……

**Comment by shigma** [comment]
关于流式渲染：未来会直接支持流式输出（虽然时间不一定很近）

**Comment by ilharp** [comment]
题外话，我觉得可以封装一个流式 API，类似 ~下面这样~

梦梦好快  竟然打算做这个功能  支持

**Comment by Seidko** [comment]
没有吗？我看看官方文档是有的

**Comment by shigma** [comment]
确认了一下，有这个 API 但是 tg 目前没有实现，可以 @Anillc 。

备选方案：目前可以使用 internal API 访问 editMessageText。

**Comment by shigma** [comment]
我不知道该开还是关了，我改下名字吧。

**Comment by Seidko** [comment]
~~可以嫖一个pr（x~~

**Comment by shigma** [comment]
> ~可以嫖一个pr（x~

你想做的话非常欢迎，成本较低适合蹭 PR。

**Comment by Seidko** [comment]
> 你想做的话非常欢迎，成本较低适合蹭 PR。
好耶！
