### ISSUE TITLE
Feature: 能否在不安装其他库的前提下在 koishi 中对 bot 设置一些快捷菜单

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1049]
### Describe the problem related to the feature request

例如 TG / Discord 等平台

![image](https://user-images.githubusercontent.com/25239977/228601970-1b0d28ff-1447-4dc7-ac92-d7ab75ea1768.png)

### Describe the solution you'd like

如题

**Comment by shigma** [comment]
预计在 4.13 中实现。

**Comment by shigma** [comment]
已经支持。
