### ISSUE TITLE
Bug: kook上接收到的部分字符有误

### ISSUE THREAD

**Issue by 9cats** [koishijs/koishi#1050]
### Describe the bug

在kook上，输入以下三个字符：  `[` `]` 还有 \`，机器人在处理信息时分别变为了 `\\[` `\\]` 和 \\\\`

### Steps to reproduce

1.添加以下测试代码
```typescript
ctx.command("echoargs").action((_, ...args) => {
  console.log(args)
  return args
})
```
2.在kook上发送测试消息 
```
echoargs [ ] `
```
3.在终端得到以下内容
```
[ '\\[', '\\]', '\\`' ]
```

### Expected behavior

在终端得到的内容应该如下
```
[ '[', ']', '`' ]
```

### Screenshots

![image](https://user-images.githubusercontent.com/58725483/228728955-6c51baeb-ad69-4e61-955b-6df988cfc531.png)
![image](https://user-images.githubusercontent.com/58725483/228728926-21f58940-c322-41d5-aa29-ff45d4778ab5.png)

### Versions

- OS:  Windows 11
- Platform:  KOOK
- Node version:  16.19.0
- Koishi version:  4.12.2
- @koishijs/plugin-adapter-kook version:   3.6.4

**Comment by shigma** [comment]
这是因为 kook 默认将用户输入理解成 markdown，后续会考虑引入 markdown 解析库进行处理。

**Comment by shigma** [comment]
已修复。

**Comment by maxoyed** [comment]
> 已修复。

直接把content里面的markdown字符转义处理，会导致发送消息的时候 kmarkdown 几乎所有语法都被转义，从而失效了

**Comment by shigma** [comment]
> 直接把content里面的markdown字符转义处理，会导致发送消息的时候 kmarkdown 几乎所有语法都被转义，从而失效了

无关问题请单独提交 issue。根据 Satori 的标准，从来没有说过文本就是 kmarkdown，要发送富文本内容应当使用消息元素。
