### ISSUE TITLE
Feature: Commend管理提供面向使用者的snapshot

### ISSUE THREAD

**Issue by Coin0804** [koishijs/koishi#1052]
### Describe the problem related to the feature request

我使用了`koishi-plugin-translator-baidu`这个插件，当我想将文本翻译成中文的时候，我只需要输入`translate text`即可。但是我想把中文翻译成其他语言的时候，我就要输入例如`translate -t jp 文本`的指令。
在翻译中文文本的时候，我是不想打英文的，更不用说减号了，我想要实现的目标是，当我输入`翻译 文本`时，直接调用上述指令。从`translate`到`翻译`的过程可以通过配置别名解决，但是从无法省略option。
我的这个特定问题可以从插件层面解决，直接提供配置默认目标文本的config。
但是koishi有大量使用option的指令，而用户的需求各种各样，是否可以从用户端直接完成类似snapshot的配置？这样的话，用户的使用将更加便捷，并且契合每一个用户。

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/45031391/228784455-f045729f-f683-49d7-9255-194e67dae7bf.png)
在这个地方，如果有可以调整snapshot的地方，就好了。
实际上，snapshot功能极其强大，用户端可以不需要这么多强大而复杂的功能。
所以如果需要提供的话，只需要“省略的参数”以及“省略的选项和参数”（然后选择和参数可以从列表里选并且用schema做类型限制——如果开发者写了的话）
具体的实现方式可以再考虑。

**Comment by ilharp** [comment]
目前，用户侧可以通过 dialogue 插件实现指令的柯里化，如图所示：

![image](https://user-images.githubusercontent.com/20179549/228789931-c2581942-ffbc-4f21-ac48-465b7e57abcd.png)

对于你的需求，可以通过设置一条这样的问答来解决：

```
# "翻译(.*)" -x "$(translate -t jp $1)"
```

这样甚至可以实现不带空格的指令调用，做到了和 [快捷匹配](https://koishi.chat/guide/basic/command.html#%E5%BF%AB%E6%8D%B7%E5%8C%B9%E9%85%8D) 相同的便捷性。

Dialogue 插件的文档： <https://dialogue.koishi.chat/>

**Comment by Coin0804** [comment]
Dialogue有个致命的问题，那就是在私聊环境下无法使用。我无法私聊机器人来获取翻译。
*对于这个问题，其实也有办法解决，那就是拉一个和机器人两个人的群就好了。*
dialogue功能也非常强大，但如果是按照这样的使用方式（使用正则）对于一些用户可能会形成障碍吧。
