### ISSUE TITLE
Bug: nginx反代后无法访问

### ISSUE THREAD

**Issue by xiaowine** [koishijs/koishi#1053]
### Describe the bug

nginx反向代理，并且https后
无法访问，打开网页一片白
控制台报错
![image](https://user-images.githubusercontent.com/68009112/228913618-3f6fc0bd-c592-4470-b486-24e705036e73.png)

### Steps to reproduce

nginx反向代理，并且https后
无法访问，打开网页一片白
控制台报错
![image](https://user-images.githubusercontent.com/68009112/228913618-3f6fc0bd-c592-4470-b486-24e705036e73.png)

### Expected behavior

nginx反向代理，并且https后
无法访问，打开网页一片白
控制台报错
![image](https://user-images.githubusercontent.com/68009112/228913618-3f6fc0bd-c592-4470-b486-24e705036e73.png)

### Versions

- OS: Ubuntu
- Platform: 
- Node version: docker镜像自带版本
- Koishi version: docker镜像自带版本 4.12.2

**Comment by ilharp** [comment]
nginx 是否按照 [文档](https://koishi.chat/manual/recipe/server.html) 中提供的范例进行了配置？

**Comment by xiaowine** [comment]
> nginx 是否按照 [文档](https://koishi.chat/manual/recipe/server.html) 中提供的范例进行了配置？
我认为是的

**Comment by xiaowine** [comment]
这是我的nginx配置
![image](https://user-images.githubusercontent.com/68009112/228916596-001d1a02-a572-4ec7-a092-d5590336ee19.png)

**Comment by xiaowine** [comment]
> > nginx 是否按照 [文档](https://koishi.chat/manual/recipe/server.html) 中提供的范例进行了配置？
> > 我认为是的

这是我的配置文件

**Comment by ilharp** [comment]
为什么 [assign 给我](https://github.com/koishijs/koishi/issues/1053#event-8891049783) 了，我并没有什么头绪

**Comment by simon300000** [comment]
你可以考虑暂时性的关闭你浏览器的 Content-Security-Policy

**Comment by xiaowine** [comment]
这是解决办法，留个碰到同样的小伙伴吧
https://blog.csdn.net/m0_46266503/article/details/108500504

**Comment by shigma** [comment]
或许可以同步一个 QA 到论坛？

**Comment by ilharp** [comment]
我个人其实尚未弄懂这个 bug 的原因是哪方造成的，是 Koishi 的一次更新后要求在浏览器执行 eval 吗？如果是这样的话，我们需要更新 console 插件以使响应中自带 CSP；而如果是客户端或浏览器的设置问题的话则应该等待更多人复现此问题，确定问题是客户端配置问题后再发布在论坛。

**Comment by simon300000** [comment]
> 我个人其实尚未弄懂这个 bug 的原因是哪方造成的，是 Koishi 的一次更新后要求在浏览器执行 eval 吗？如果是这样的话，我们需要更新 console 插件以使响应中自带 CSP；而如果是客户端或浏览器的设置问题的话则应该等待更多人复现此问题，确定问题是客户端配置问题后再发布在论坛。

是的 https://github.com/satorijs/satori/blob/a5076c4cea0925c32a659f437215324e73d58ca6/packages/element/src/index.ts#L91

我也觉得很奇怪，为什么会有CSP，据我所知这个东西应该要手动开启

**Comment by xiaowine** [comment]
> 我个人其实尚未弄懂这个 bug 的原因是哪方造成的，是 Koishi 的一次更新后要求在浏览器执行 eval 吗？如果是这样的话，我们需要更新 console 插件以使响应中自带 CSP；而如果是客户端或浏览器的设置问题的话则应该等待更多人复现此问题，确定问题是客户端配置问题后再发布在论坛。

这是第一次安装，不是更新

**Comment by MaikoTan** [comment]
> 这是第一次安装，不是更新

He is not talking about the "Update" you made, but the "Version Updates" by us Koishi Team.

Also, I didn't see there are contents of configurations or logs uploaded, so it is hard to investigate how this happened.
