### ISSUE TITLE
Feature: Telegram 支持 callback_query 消息，监听用户点击

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1055]
### Describe the problem related to the feature request

![image](https://user-images.githubusercontent.com/25239977/229144957-1800e686-a113-4150-a252-b1baf0fe6794.png)

当前点击按钮后 koishi 无法收到任何相应

### Describe the solution you'd like

如题

**Comment by Ice-Hazymoon** [comment]
谢谢

**Comment by MaikoTan** [comment]
> 有的其实，首先
> 
> ```js
> import '@koishijs/plugin-adapter-telegram'
> ```

Well, it should be `import {} from '@koishijs/plugin-adapter-telegram'` when you need the type only, which could be stripped out by the code bundler.
