### ISSUE TITLE
Bug: i18n 的一个小问题

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1057]
### Describe the bug

koishi en 的本地化不是很全，其他指令的本地化可以缺失，但设置语言部分我认为应该补上，通过修改本地 locale 文件倒是可以解决，不如试试把缺失的翻译全丢到 ChatGPT（

![image](https://user-images.githubusercontent.com/25239977/229193920-a43b3d7b-bee1-4c21-a9ae-fc536658344f.png)

![image](https://user-images.githubusercontent.com/25239977/229193140-b73a8683-613d-4e3e-b42b-7ca8eb1e1bc3.png)

### Steps to reproduce

rt

### Expected behavior

rt

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by Ice-Hazymoon** [comment]
session.text 如何指定翻译语言

```
// user.locale zh

await ctx.database.setUser(platform, userId, {
    locale: 'en',
});

session.text('hello') // 你好
```

我期望在设置用户语言后 session.text 能够获取最新的用户语言，或者 session.text 能够提供一个指定语言的选项

**Comment by Ice-Hazymoon** [comment]
> session.text 如何指定翻译语言
> 
> ```
> // user.locale zh
> 
> await ctx.database.setUser(platform, userId, {
>     locale: 'en',
> });
> 
> session.text('hello') // 你好
> ```
> 
> 我期望在设置用户语言后 session.text 能够获取最新的用户语言，或者 session.text 能够提供一个指定语言的选项


看起来不是 setUser 的问题，在 on telegram/callback-query 中 session.text 无法读取用户语言

**Comment by Ice-Hazymoon** [comment]
期待能够修复 adapter 或给 session.text 提供一个语言选项

**Comment by shigma** [comment]
这是同一个问题，telegram/callback-query 不是用户 session，没有绑定到任何用户

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
