### ISSUE TITLE
Feature: 如何获取 session.send 后的 messageId

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1058]
### Describe the problem related to the feature request

```js
const waitMsg = await session.send(session.text('wait_answer'));

session.bot.deleteMessage(session.channelId, waitMsg[0]);
```

我哪里做错了吗

### Describe the solution you'd like

rt

**Comment by Ice-Hazymoon** [comment]
waitMsg: ['123']

```
Error: Telegram API error 400. Bad Request: chat not found
```

**Comment by Ice-Hazymoon** [comment]
![image](https://user-images.githubusercontent.com/25239977/229424041-1ed5ca10-e0b2-4dd8-86be-f10f4cf14228.png)

koishi 把未转换的 chat_id 直接传给 tg 导致报错

![image](https://user-images.githubusercontent.com/25239977/229424066-45e1ad6e-7165-46bb-9a33-a013e58d6baf.png)

**Comment by shigma** [comment]
最新版已修复。
