### ISSUE TITLE
Feature: 迁移至 TypeScript 5.0

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1062]
### Describe the problem related to the feature request

TypeScript 5.0 在近期发布了。

### Describe the solution you'd like

TypeScript 5.0 的破坏性更改：https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#breaking-changes-and-deprecations

**Comment by shigma** [comment]
ts 5.0 没有引入任何需要适配的变化。
