### ISSUE TITLE
Bug: Discord 无法引用消息

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1063]
### Describe the bug

Discord 平台的 `h.quote` 不起作用

### Steps to reproduce

```ts
ctx.middleware((session, next) => {
    session.send(h(null, h.quote(session.messageId), h.text('114514')))
    return next()
})
```

1. 对机器人发送任意消息
2. 机器人进行回复, 回复的消息中没有引用上个步骤的消息

### Expected behavior

能对消息进行引用

### Versions

- OS: Windows 11
- Platform: Discord
- Node version: 19.8.1
- Koishi version: 4.12.2

**Comment by shigma** [comment]
复现了，我去看看。

**Comment by shigma** [comment]
已修复。

**Comment by idanran** [comment]
> 已修复。

好耶
