### ISSUE TITLE
Bug: huanlin-welcome插件问题

### ISSUE THREAD

**Issue by sheep2007** [koishijs/koishi#1071]
### Describe the bug

”设定欢迎词“指令起作用，但 ”查看欢迎词“ 提示 ”发生未知错误。“ 数据库也有显示，但并没有内容（只有群信息，没有内容
手动修改数据库内容后 “查看欢迎词” 指令才正常
![VZVO081 SW4LIXF)MY{T%E5](https://user-images.githubusercontent.com/122354009/231820322-162de020-33ba-41d9-abc3-cbbe0fc4564d.png)
![$ST3BWNN0@C2LMF1@Z7N1CW](https://user-images.githubusercontent.com/122354009/231820363-8e2d6490-11dc-401d-a66a-c477fc3ffac4.png)

### Steps to reproduce

使用“设定欢迎词”指令并输入内容，提示 ”已设定欢迎词“ 。使用 “查看欢迎词” 查看内容，提示 “发生未知错误。” 并且查看数据库没有内容存入。

### Expected behavior

用指令设置时，正确并完整的保存设置的欢迎词

### Screenshots

使用指令设置时：

![U~4${{Y4@)QEVD4P GNF9DF](https://user-images.githubusercontent.com/122354009/231819431-e14b0b9a-8041-4d15-97ec-f6a01c210396.png)
![U15J8ZQ{$4 F0D(KK7$1 BK](https://user-images.githubusercontent.com/122354009/231819446-48647a1a-b437-4337-990e-df7131639700.png)
![Y M`4@4PN3EP8}OVT X09HI](https://user-images.githubusercontent.com/122354009/231819454-aef298e5-d90a-4ee2-a6a8-f017b0b2624f.png)

手动修改数据库后：

![VZVO081 SW4LIXF)MY{T%E5](https://user-images.githubusercontent.com/122354009/231820709-c1f6885a-a8c3-4af5-92d4-bc5d6b260c99.png)

![$ST3BWNN0@C2LMF1@Z7N1CW](https://user-images.githubusercontent.com/122354009/231820720-819df4df-546b-4fd9-a550-46005232782f.png)

### Versions

- OS: Windows 10 
- Platform: Discord
- Node version: 16.17.0
- Koishi version: 4.12.4
- Plugin Version: 1.0.8

**Comment by shigma** [comment]
🤣 这不是官方插件，请去插件的仓库或者论坛反馈。

**Comment by HuanLinOTO** [comment]
我的锅 代码里面有这段

```
for (const word of words[0].words.split("\\r\\n")) {
      result.push(<p>{word}</p>)
    }
```

来防止类似

```
111
222
```

这样的情况变成

```
111\r\n222
```

的

没想到还有一句话的欢迎词
