### ISSUE TITLE
Feature: 希望指令组能够自己创建而非仅由插件创建

### ISSUE THREAD

**Issue by zhuhansan666** [koishijs/koishi#1072]
### Describe the problem related to the feature request

很多插件不会创建自己的指令组，会导致根很杂乱
![image](https://user-images.githubusercontent.com/93586645/232194350-1bb054ba-0d23-4daf-87aa-28d50b325763.png)

### Describe the solution you'd like

支持自定义指令组，想插件组一样

### Describe alternatives you've considered

在插件注册指令时自动将其指令归于与插件同名指令组内

### Additional context

望官方审视，你我一同构建开源、和谐、美好的koishijs开源社区！

**Comment by HuanLinOTO** [comment]
这里的分类是命令的从属关系，与插件无关

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by shigma** [comment]
支持的，建议重看文档。

**Comment by shigma** [comment]
https://koishi.chat/zh-CN/manual/usage/command.html#%E6%B7%BB%E5%8A%A0%E5%AD%90%E6%8C%87%E4%BB%A4
