### ISSUE TITLE
Bug: returning tsx elements does not prevent command.check as expected

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi#1076]
### Describe the bug

RT

### Steps to reproduce

Minimal reproducible code:

```tsx
ctx
  .command('foo')
  .check(() => <>check</>)
  .action(() => <>action</>)
```

> YOU: `foo`

> BOT: `action`

### Expected behavior

> YOU: `foo`

> BOT: `check`

### Versions

- OS: Windows Server 2016
- Platform: all
- Node version: 16.x
- Koishi version: 4.12.5

**Comment by shigma** [comment]
已修，更新到最新版可解决。
