### ISSUE TITLE
Bug: sqlite频繁读写时内存泄漏

### ISSUE THREAD

**Issue by Haku530** [koishijs/koishi#1080]
### Describe the bug

如题

### Steps to reproduce

使用sqlite，文件越大、读写越频繁，内存吃得越快

### Expected behavior

解决内存泄漏的问题

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
已确认此问题存在，会尽快修复，感谢反馈。

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).
