### ISSUE TITLE
Bug?: 当 Config 只写了 Schema.intersect([]) 会导致整个插件无法加载

### ISSUE THREAD

**Issue by Seidko** [koishijs/koishi#1081]
### Describe the bug

当 Config 只写了 Schema.intersect([]) 会导致整个插件无法加载。我认为这并不是一个预期行为。

### Steps to reproduce

复现代码：
```ts
import { Context, Schema } from 'koishi'

export function apply(ctx: Context) {
  console.log('applied')
}

export const Config = Schema.intersect([]) 
```

### Expected behavior

按照上述写法时，控制台按照预期输出`applied`。

### Versions

- OS: Linux 6.2.12-arch1-1
- Platform: Sandbox
- Node version: 18.15.0
- Koishi version: 4.12.5

**Comment by shigma** [comment]
无法加载具体是指什么？

**Comment by Seidko** [comment]
![image](https://user-images.githubusercontent.com/64234553/235827196-7840cbc7-60e8-4681-ab42-f744eba7641f.png)
如图，插件加载以后并没有按照预期打印`test plugin applied`

**Comment by Seidko** [comment]
如果`Schema.intersect([])`的写法是错误的话，应该是提示类型错误而不是毫无反应，我认为在这里有问题。

**Comment by shigma** [comment]
在里面填写东西（比如一个空 object）会使得插件能正常加载吗？

**Comment by Seidko** [comment]
![image](https://user-images.githubusercontent.com/64234553/235878752-b29285b7-f172-4aeb-87d1-91177dd1230e.png)
这样子写会正常报错（x
![image](https://user-images.githubusercontent.com/64234553/235878870-9a5d1348-24a9-4399-9e73-5a9225c12de9.png)
这么写就正常了，说明`Schema.intersect([])`这种写法应该本来就是错误的

**Comment by shigma** [comment]
问题已修复，请等待下一个版本。
