### ISSUE TITLE
Feature: 让 `config` 插件支持热重载

### ISSUE THREAD

**Issue by SaarChaffee** [koishijs/koishi#1088]
### Describe the problem related to the feature request

当 `@koishijs/plugin-market` 升级到 `2.0.0-alpha.0` 后需要安装 `@koishijs/plugin-config@2.0.0-alpha.0` 插件以使用插件配置页面。但是插件配置不吃热重载，导致修改代码后 `hmr` 有反应但是配置页面没有变化。

### Describe the solution you'd like

让 `@koishijs/plugin-config` 支持热重载以恢复需要安装config插件之前的特性

**Comment by shigma** [comment]
虽然已经修了但仍需等待下一个 Koishi 版本发布后，将 config 和 hmr 插件均更新后此功能才可用。
