### ISSUE TITLE
Bug: 将 koishi 作为其他项目的依赖，添加 plugin-config 插件，无法显示插件配置

### ISSUE THREAD

**Issue by Pluckypan** [koishijs/koishi#1089]
### Describe the bug

import * as config from '@koishijs/plugin-config'
ctx.plugin(config);

控制台无报错，无法加载插件配置，后台不显示插件配置选项

### Steps to reproduce

```
import { Context } from 'koishi'

// 创建一个 Koishi 应用
const ctx = new Context({
    nickname: "PUTO",
    prefix: "/",
    port: 1994,
})

// 启用插件
import console from '@koishijs/plugin-console'
import * as sandbox from '@koishijs/plugin-sandbox'
import logger from '@koishijs/plugin-logger'
import explorer from '@koishijs/plugin-explorer'
import * as status from '@koishijs/plugin-status';

ctx.plugin(console);
ctx.plugin(sandbox);
ctx.plugin(explorer);
ctx.plugin(logger);
ctx.plugin(status);

import * as config from '@koishijs/plugin-config'
ctx.plugin(config);

// 自定义插件
import * as example from './example'
ctx.plugin(example);

// 启动应用
ctx.start()
```

### Expected behavior

需要正常显示

### Versions

System:

OS: macOS 13.3.1

CPU: (8) arm64 Apple M1

Binaries:

Node: 18.12.1

Yarn: 1.22.17

Koishi:

Core: 4.12.9

Console: 5.8.3

**Comment by Pluckypan** [comment]
import console from '@koishijs/plugin-console'
import * as sandbox from '@koishijs/plugin-sandbox'
import logger from '@koishijs/plugin-logger'
import explorer from '@koishijs/plugin-explorer'
import * as status from '@koishijs/plugin-status';

这几个插件都能正常展示并运行

**Comment by shigma** [comment]
这是预期的。config 和 market 这两个插件涉及修改配置，只能在 CLI 中运行。

**Comment by Pluckypan** [comment]
> 这是预期的。config 和 market 这两个插件涉及修改配置，只能在 CLI 中运行。

作为其他项目的依赖，我也会启用一些插件，有的插件是需要进行配置的，如果 config 这个插件不显示的话，
我要怎么才能配置这些三方插件呢，其实我的预期就是跟 koishi app 一样，能有个地方配置三方插件的参数。

**Comment by Pluckypan** [comment]
> 这是预期的。config 和 market 这两个插件涉及修改配置，只能在 CLI 中运行。

我就是想要一个可以配置其他插件配置的地方

**Comment by shigma** [comment]
你可以使用 CLI。将 Koishi 作为其他项目的依赖就意味着你是进阶用户，需要自己管理所有配置，并且自己提供动态能力。

**Comment by Pluckypan** [comment]
那先关闭了  Not Support
