### ISSUE TITLE
Bug: 当插件没有 `preinstall` 的时候在 `yarn clone` 时会报错 `unknown command preinstall`

### ISSUE THREAD

**Issue by Seidko** [koishijs/koishi#1098]
### Describe the bug

当插件没有 `preinstall` script 的时候在使用 `yarn clone` 拉取此插件仓库的时后会报错 `unknown command preinstall` 错误。

### Steps to reproduce

1. 创建最新的 boilerplate
2. 使用 `yarn clone` 拉取一个没有 `preinstall` script 的插件的仓库

### Expected behavior

正常运行，不再报错 `unknown command preinstall`

### Screenshots

![image](https://github.com/koishijs/koishi/assets/64234553/f15388e4-b030-4984-8a24-367abf4f5526)

### Versions

- OS: Linux ArchLinux 6.3.3-arch1-1
- Platform: *any*
- Node version: 20.2.0
- Koishi version: 4.13.0

**Comment by Seidko** [comment]
![image](https://github.com/koishijs/koishi/assets/64234553/e94d8ae2-4ecd-4099-9f02-0baf12ef5619)

我在这里调试的时候发现这里的 `exit code` 是恒为 1 的，我需要 catch `unknown command preinstall` 错误然后抛出其他报错吗？还是说对所有报错都进行 catch？

**Comment by shigma** [comment]
这是插件的问题吧？能在官方仓库复现吗？
