### ISSUE TITLE
消息能发不能收

### ISSUE THREAD

**Issue by slgluo** [koishijs/koishi#11]
**Describe the bug**
消息能发不能收

**To Reproduce**
私聊，讨论组，群都不回调，不知道是什么原因，还是我用错了

app.middleware((meta, next) => {
  console.log(meta.message)
  return next()
})
app.receiver.on('message', (meta) => {
  console.log(meta.message)
})

**Expected behavior**

**Screenshots**

**Versions**

- Node Version: [e.g. 12.10.0]
- CoolQ Version: [e.g. 5.15.5]
- CQHTTP Version: [e.g. 4.13.0]
- Koishi Version: [e.g. 1.1.1]

**Additional context**
实在分析不出问题在哪，能不能帮忙分析一下？

**Comment by Shigma** [comment]
如果你在编写插件，确保你调用了 app.plugin()；同时如果你不是用 koishi start 命令执行的，确保你调用了 app.start()。如果是其他情况的话，能看一下你的目录结构和完整代码吗？

**Comment by Shigma** [comment]
刚刚试验了一下，你的代码在我这里确认是可以运行的 😕 因此怀疑是你 CQHTTP 的配置问题。你可以检查一下你的 CQHTTP 配置文件，确认你的 use_http 为 true，post_url 对应的端口为 8080。以及，如果 CQHTTP 插件正常运行，会弹出一个日志窗口，你可以在这个窗口查看消息上报的情况。

**Comment by slgluo** [comment]
> 刚刚试验了一下，你的代码在我这里确认是可以运行的 😕 因此怀疑是你 CQHTTP 的配置问题。你可以检查一下你的 CQHTTP 配置文件，确认你的 use_http 为 true，post_url 对应的端口为 8080。以及，如果 CQHTTP 插件正常运行，会弹出一个日志窗口，你可以在这个窗口查看消息上报的情况。

我是用docker在linux上挂着的，不知道会不会有问题？
**CQHTTP配置文件：**
![CQHTTP配置文件](https://user-images.githubusercontent.com/15703542/72045041-315deb80-32f0-11ea-99c0-42d358d9adb2.png)
**酷Q日志**
你说的日志窗口不知道是不是这个
![酷Q日志](https://user-images.githubusercontent.com/15703542/72045115-52264100-32f0-11ea-8b52-b96082d30f6c.png)

**Comment by Shigma** [comment]
你可以查看一下 CoolQ 目录下 `data/app/io.github.richardchien.coolqhttpapi/log/[qq].log` 这个文件，上面会显示 HTTP API 的日志信息，例如这样：
```
[2020-01-09 14:34:36.573] [I] [HTTP] 已成功处理一个 API 请求：/get_version_info
[2020-01-09 14:34:47.489] [I] [HTTP] 通过 HTTP 上报数据到 http://127.0.0.1:8080 成功，状态码：200
[2020-01-09 14:34:47.496] [I] [HTTP] 已成功处理一个 API 请求：/send_private_msg_async
```
如果上面这条上报信息是失败的话，那很可能就跟 Koishi 本身没啥关系了……

**Comment by slgluo** [comment]
> 你可以查看一下 CoolQ 目录下 `data/app/io.github.richardchien.coolqhttpapi/log/[qq].log` 这个文件，上面会显示 HTTP API 的日志信息，例如这样：
> 
> ```
> [2020-01-09 14:34:36.573] [I] [HTTP] 已成功处理一个 API 请求：/get_version_info
> [2020-01-09 14:34:47.489] [I] [HTTP] 通过 HTTP 上报数据到 http://127.0.0.1:8080 成功，状态码：200
> [2020-01-09 14:34:47.496] [I] [HTTP] 已成功处理一个 API 请求：/send_private_msg_async
> ```
> 
> 如果上面这条上报信息是失败的话，那很可能就跟 Koishi 本身没啥关系了……

我查看了日志，发现是 http://127.0.0.1:8080无法访问，不知道是什么原因
```
[2020-01-09 08:24:21.956] [I] [日志] 日志控制台开启成功
[2020-01-09 08:24:21.968] [I] [HTTP] 开启 HTTP 服务器成功，开始监听 http://[::]:5700
[2020-01-09 08:24:21.989] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080 无法访问
[2020-01-09 08:27:27.423] [I] [HTTP] 已成功处理一个 API 请求：/get_version_info
[2020-01-09 08:27:32.532] [I] [HTTP] 已成功处理一个 API 请求：/send_private_msg
[2020-01-09 08:27:43.551] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080 无法访问
[2020-01-09 08:27:43.594] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080 无法访问
[2020-01-09 08:27:43.598] [W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080 无法访问
```

**Comment by slgluo** [comment]
> 你可以查看一下 CoolQ 目录下 `data/app/io.github.richardchien.coolqhttpapi/log/[qq].log` 这个文件，上面会显示 HTTP API 的日志信息，例如这样：
> 
> ```
> [2020-01-09 14:34:36.573] [I] [HTTP] 已成功处理一个 API 请求：/get_version_info
> [2020-01-09 14:34:47.489] [I] [HTTP] 通过 HTTP 上报数据到 http://127.0.0.1:8080 成功，状态码：200
> [2020-01-09 14:34:47.496] [I] [HTTP] 已成功处理一个 API 请求：/send_private_msg_async
> ```
> 
> 如果上面这条上报信息是失败的话，那很可能就跟 Koishi 本身没啥关系了……

这么看来，不是Koishi的原因

**Comment by Shigma** [comment]
@slgluo 你那日志显示的是什么

**Comment by slgluo** [comment]
> @slgluo 你那日志显示的是什么

日志都在上一条回复里了，机器人收到消息后，就报

`[W] [HTTP] HTTP 上报地址 http://127.0.0.1:8080 无法访问`

虽然我知道这个不应该问你，但还是后脸皮请教一下了，这个post_url到底是个什么东西，post_url所指向的地址，是CQHTTP开的http server，还是Koishi开的，还是说需要要搭一个http服务，让它指向我写的http server？

**Comment by Shigma** [comment]
@slgluo 是这样的。HTTP 模式相当于 Koishi 和 CQHTTP 各开一个 HTTP Server，前者向后者的服务器调用接口（例如发送信息），后者向前者的服务器上报事件（例如收到信息）。前者对应 Koishi 的 `port` 和 CQHTTP 的 `post_url`，后者对应 Koishi 的 `server` 和 CQHTTP 的 `port`。你的情况可能是 Koishi 与 CQHTTP 没有处于同一机器，所以应该把 `post_url` 的 host 部分改成 Koishi 所在的 IP。

**Comment by slgluo** [comment]
> @slgluo 是这样的。HTTP 模式相当于 Koishi 和 CQHTTP 各开一个 HTTP Server，前者向后者的服务器调用接口（例如发送信息），后者向前者的服务器上报事件（例如收到信息）。前者对应 Koishi 的 `port` 和 CQHTTP 的 `post_url`，后者对应 Koishi 的 `server` 和 CQHTTP 的 `port`。你的情况可能是 Koishi 与 CQHTTP 没有处于同一机器，所以应该把 `post_url` 的 host 部分改成 Koishi 所在的 IP。

那我大概明白了，现在两者确实不在同一台机子，Koishi在我自己的电脑运行，CQHTTP在服务器运行，而我填的是127.0.0.1，所以它收到消息时候，不能上报到Koishi的http server。是这样子吧？
[post_url无法访问](https://github.com/richardchien/coolq-http-api/issues/210)
这个问题正好印证这一点

**Comment by Shigma** [comment]
@slgluo 是的。如果你的电脑没有公网 IP 的话，可以选择改成 WebSocket 模式。

**Comment by slgluo** [comment]
> @slgluo 是的。如果你的电脑没有公网 IP 的话，可以选择改成 WebSocket 模式。

已经成功了，谢谢大佬

**Comment by Shigma** [comment]
@slgluo 顺便提醒你代码的一些问题：
```js
const app = new App({
  type: 'http',
  port: 8080,
  server: 'http://****:5700',
  // plugins 这个选项只能用于配置文件，传入构造函数是无效的
  // 正确的做法应该是 app.plugin(require('koishi-plugin-common'))
  plugins: [
    ["common"],
   ],
})

app.middleware((meta, next) => {
  meta.$send('工具人')
  return next()
})
app.receiver.on('message', (meta) => {
  meta.$send('工具人')
})

app.start()

// 这里如果想确保已经上线，可以有两种写法：
// 第一种，利用 start 返回的 Promise 对象
// app.start().then(() => app.sender.sendPrivateMsg(975394636, '你的工具人上线了'))
// 第二种，利用 connect 事件
// app.receiver.on('connect', () => app.sender.sendPrivateMsg(975394636, '你的工具人上线了'))
setTimeout(() => {
  // sendPrivateMsg 的第三个参数表示默认转义输入的文本
  // 对你这种情况没有影响，通常情况下不写才是最好的选择
  app.sender.sendPrivateMsg(975394636, '你的工具人上线了', true)
}, 5000)

console.log('app start...')
```

**Comment by slgluo** [comment]
> @slgluo 顺便提醒你代码的一些问题：
> 
> ```js
> const app = new App({
>   type: 'http',
>   port: 8080,
>   server: 'http://****:5700',
>   // plugins 这个选项只能用于配置文件，传入构造函数是无效的
>   // 正确的做法应该是 app.plugin(require('koishi-plugin-common'))
>   plugins: [
>     ["common"],
>    ],
> })
> 
> app.middleware((meta, next) => {
>   meta.$send('工具人')
>   return next()
> })
> app.receiver.on('message', (meta) => {
>   meta.$send('工具人')
> })
> 
> app.start()
> 
> // 这里如果想确保已经上线，可以有两种写法：
> // 第一种，利用 start 返回的 Promise 对象
> // app.start().then(() => app.sender.sendPrivateMsg(975394636, '你的工具人上线了'))
> // 第二种，利用 connect 事件
> // app.receiver.on('connect', () => app.sender.sendPrivateMsg(975394636, '你的工具人上线了'))
> setTimeout(() => {
>   // sendPrivateMsg 的第三个参数表示默认转义输入的文本
>   // 对你这种情况没有影响，通常情况下不写才是最好的选择
>   app.sender.sendPrivateMsg(975394636, '你的工具人上线了', true)
> }, 5000)
> 
> console.log('app start...')
> ```

好的，谢谢提醒！
