### ISSUE TITLE
Bug: 最新版 plugin-console 右上角所有按钮class包含disabled

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [koishijs/koishi#1100]
### Describe the bug

Toolbar 右上角按钮 属性全部包含 disabled 而无法点击
<span class="menu-item disabled el-tooltip__trigger el-tooltip__trigger"><svg class="k-icon menu-icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M408 143.1C408 166.1 390.1 183.1 368 183.1C345.9 183.1 328 166.1 328 143.1C328 121.9 345.9 103.1 368 103.1C390.1 103.1 408 121.9 408 143.1zM23.1 288C15.38 288 7.414 283.4 3.145 275.9C-1.123 268.4-1.043 259.2 3.356 251.8L55.83 163.3C68.79 141.4 92.33 127.1 117.8 127.1H199.9C202.4 124 204.8 120.3 207.2 116.7C289.1-4.07 411.1-8.142 483.9 5.275C495.6 7.414 504.6 16.43 506.7 28.06C520.1 100.9 516.1 222.9 395.3 304.8C391.7 307.2 387.1 309.6 384 312.1V394.2C384 419.7 370.6 443.2 348.7 456.2L260.2 508.6C252.8 513 243.6 513.1 236.1 508.9C228.6 504.6 223.1 496.6 223.1 488V391.8C215.2 395.6 207.4 398.9 200.1 401.7C189.1 406.6 175.5 403.9 166.5 394.8L115.8 344.1C106.6 334.9 103.9 321.1 109.1 309.2C111.7 303.2 114.9 296 118.5 288L23.1 288zM461.7 50.32C398.4 41.85 309.1 51.1 246.1 143.7C216.8 188.1 178.1 271.9 157.6 318.1L192.6 353.1C239.1 333.2 323.9 295.2 368.3 265C460 202.9 470.2 113.6 461.7 50.32V50.32z"></path></svg></span>

### Steps to reproduce

使用最新版 plugin-console

### Expected behavior

不会全部 disabled 而可以点击

### Screenshots

![image](https://github.com/koishijs/koishi/assets/68551684/03dc0998-1cbe-4f77-bf31-db3ace44c582)

### Versions

- OS: Linux CyanArch 6.2.13-zen-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 26 Apr 2023 20:49:44 +0000 x86_64 GNU/Linux
- Platform: every-platform
- Node version: v19.9.0
- Koishi version: 4.13.1
- plugin-console: 5.10.2

**Comment by Chinese-Cyq20100313** [comment]
https://github.com/koishijs/webui/pull/181

**Comment by shigma** [comment]
已修复：8eb330903e797f2b52c29804c5204a846c779979
