### ISSUE TITLE
Feature: 如何对外暴露一个 server 实现通过 api 来对用户或群组发消息

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1103]
### Describe the problem related to the feature request

举个例子，我想要在 web 端向所有 telegram 中已经聊过天的用户发送一条公告消息，我应该怎么实现。

我希望对外暴露一个 express 之类的 server 服务来和中间件进行通信。

我看到了 https://github.com/koishijs/koishi/issues/1096 这个 issue 可能和我是类似的请求，但我不需要模拟 user，我可以使用 `session.bot.internal` 相关的接口来实现对数据库中的用户推送消息。

我目前没有很好的思路来解决这个问题，所以想请教一个最小化的demo

### Describe the solution you'd like

如题

**Comment by shigma** [comment]
我没理解你表述的需求和你提出的解决方案之间的关系。

你表述出的需求是「向已经聊过天的用户群发消息」，那么你可以请求数据库的 binding 表后群发。

你的标题是「对外暴露一个 server 实现」，这个目前插件市场中有不少 API 相关插件应该都可以完成。不过我都没试过，你可以试试。官方未来也会出相关的插件，不过可能在 4.15 以后。

**Comment by Ice-Hazymoon** [comment]
这个只是简单的例子，实际情况可能会需要对api来进行更一步的操作

"请求数据库的 binding 表后群发" 这方面我不明白前提是如何收到 “需要群发” 的请求。

我会去尝试市场中的其他插件，感谢回复。

**Comment by shigma** [comment]
只是需要 demo 的话可以这样：

```ts
ctx.router.post('/send-to-all', async (_ctx) => {
  const bindings = await ctx.database.get()
  bindings.forEach(binding => getBotSomehow(binding).sendPrivateMessage(binding.userId, ctx.body.content))
})
```

当然需要细化的部分还挺多的，比如多 bot 负载均衡、鉴权等等。

**Comment by purerosefallen** [comment]
koishi-plugin-apisend

**Comment by shigma** [comment]
发布了官方插件 @koishijs/plugin-server-satori。
