### ISSUE TITLE
Bug: 重载 puppeteer 插件时出现报错 `Error: service component:html has been registered`

### ISSUE THREAD

**Issue by Seidko** [koishijs/koishi#1105]
### Describe the bug

在重新加载 puppeteer 插件时出现报错 `Error: service component:html has been registered`

### Steps to reproduce

修改 puppeteer 插件的插件配置并且重载配置。

### Expected behavior

不再出现该报错，插件正常运行。

### Screenshots

![image](https://github.com/koishijs/koishi/assets/64234553/18a95fbd-812b-4169-8280-7e1e812f4749)

### Versions

System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (64) x64 Genuine Intel(R) CPU $0000%@

Binaries:
    Node: 20.1.0
    Yarn: 1.22.19

Koishi:
    Core: 4.13.1
    Console: 5.10.0

**Comment by shigma** [comment]
可能 hmr 对异步插件的支持还不够好。

**Comment by Seidko** [comment]
> 可能 hmr 对异步插件的支持还不够好。

这和 hmr 没有关系，在没有安装 hmr 的生产环境下同样也有这个 bug，推测是 ctx.component 没有成功 dispose。

**Comment by shigma** [comment]
dispose 的代码是有的，你试试看自己写一个定义 component 的插件，看看能不能正常用？

**Comment by Seidko** [comment]
复现了：
![image](https://github.com/koishijs/koishi/assets/64234553/cc029201-a3e5-4e3f-87ff-9ae2848e754a)
