### ISSUE TITLE
Bug: Telegram 适配器，无法获取 web_app_data 的数据

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1107]
### Describe the bug

举个例子，在 Telegraf 中可以这样实现接收 web_app_data 数据

```js
const { Telegraf, Markup } = require("telegraf");

const bot = new Telegraf("bot token");

bot.command("register", (ctx) => {
  return ctx.reply(
    "open webapp",
    Markup.keyboard([
      Markup.button.webApp(
        "Open",
        "https://uture-tg-web.imiku.me/"
      ),
    ])
  );
});
bot.on("message", async (ctx) => {
  console.log(ctx.message.web_app_data)
  return ctx.reply(ctx.message.web_app_data.data)
});

bot.launch();
```

但是在 koishi 中不知道该怎样获取这些数据，session 是否有某个字段可以获取收到的原始数据

![image](https://github.com/koishijs/koishi/assets/25239977/f8d338bb-d3a5-44f2-95e3-1d0bd53ecb0e)

telegram 文档：https://core.telegram.org/bots/webapps#initializing-web-apps

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

"koishi": "^4.12.9",

**Comment by Anillc** [comment]
`session.telegram` 上有你想要的属性，需要你先导入一下适配器的类型

```typescript
import {} from 'koishi-plugin-adapter-telegram'
```

**Comment by Ice-Hazymoon** [comment]
> `session.telegram` 上有你想要的属性，需要你先导入一下适配器的类型
> 
> ```ts
> import {} from 'koishi-plugin-adapter-telegram'
> ```

谢谢
