### ISSUE TITLE
Bug: 指令的带value的重载选项错误地消耗了下一个参数

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi#1109]
### Describe the bug

指令的带value的重载选项错误地消耗了下一个参数

### Steps to reproduce

``` 
 ctx.command('test <msg>')
  .option('writer', '-w <id>')
  .option('writer', '--anonymous', { value: 0 })
  .action(({ options }, msg) => JSON.stringify({options, msg}))
```
输入`test --anonymous foo`

### Expected behavior

foo应当被识别为msg

### Screenshots

![cb57749f1da097a03606b85b8f0431d5](https://github.com/koishijs/koishi/assets/16983883/9015b4cd-ce9d-4761-92c0-677c61413ad3)

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
感谢反馈，已定位问题。

**Comment by shigma** [comment]
已修复此问题，将在下个版本实装修复。
