### ISSUE TITLE
Bug: 为指令定义特定类型的变长参数有非预期的行为

### ISSUE THREAD

**Issue by ENDsoft233** [koishijs/koishi#1111]
### Describe the bug

注册一个指令，使用变长参数时，定义预期的类型，koishi只会转换第一个元素的类型，而保持剩下的不变（仍为 string），这会导致非预期的行为。

### Steps to reproduce

 - 定义含有特定类型变长参数的指令

```ts
ctx
    .command('test [...rest:number]')
    .action(({ session }, ...rest) => {
      console.log(rest);
    });
```

 - 执行这个指令
 - 复现。

### Expected behavior

变长参数禁止定义预期的类型，或者转换所有元素的类型。

### Screenshots

![d87f88689ac485ddcad71c585a5ac656.png](https://s2.loli.net/2023/06/10/ZKLwQu1DP5hEBfT.png)

### Versions

- OS: Windows 11 (10.0.22621.1702)
- Platform: onebot
- Node version: 18.13.0
- Koishi version: 4.13.2

**Comment by shigma** [comment]
感谢反馈。我们尽快修复。

**Comment by shigma** [comment]
已修复此问题，将在下个版本实装修复。
