### ISSUE TITLE
Bug: 子指令继承父指令配置的相关问题

### ISSUE THREAD

**Issue by ENDsoft233** [koishijs/koishi#1112]
### Describe the bug

不太清楚子指令继承父指令配置的规则是什么，实测中是发现 `authority` 配置会被继承，而 `checkArgCount` 则不会；翻阅文档未发现相关内容。

### Steps to reproduce

- 注册子指令

```ts
  ctx
    .command("test", { authority: 2, checkArgCount: true, showWarning: true })
  ctx
    .command("test.test <text>")
    .action(({ }, text) => text);
```

- 测试指令 `test.test` 和 `test.test -h`
- 复现

### Expected behavior

我期望所有父指令的配置都可以被继承到子指令上，包括 `authority` 和 `checkArgCount` 。

### Screenshots

![image.png](https://s2.loli.net/2023/06/11/An9MgvVrITB1K8E.png)

### Versions

- OS: Windows 11 (10.0.22621.1702)
- Platform: onebot
- Node version: 18.13.0
- Koishi version: 4.13.2

**Comment by shigma** [comment]
emmmmm

设计上我不希望子指令继承任何配置。很可能父指令本身也是实际有用的，那样如果搞继承就会有点奇怪？

目前 authority 继承是因为即便是上面的情况继承也是合理的。未来版本可能会做更细粒度的权限管理，那样这里的行为也将不是继承了。

**Comment by Seidko** [comment]
可以加入一些可能的接口或者在 WebUI 中加入继承父指令相关设置的功能吗？有的时候大批量设置指令权限有点点麻烦。

**Comment by shigma** [comment]
> 可以加入一些可能的接口或者在 WebUI 中加入继承父指令相关设置的功能吗？有的时候大批量设置指令权限有点点麻烦。

4.14 会做一套新的权限系统，有什么需求可以等新系统上了以后再讨论。

**Comment by ENDsoft233** [comment]
但其实我感觉 `checkArgCount` 还是应该默认为 `true` :sad:

**Comment by shigma** [comment]
> 但其实我感觉 `checkArgCount` 还是应该默认为 `true` :sad:

你说的有道理，没准会在未来的版本修改此行为。目前我们需要认真评估此改动的影响，并解决由此引起的 breaking change。
