### ISSUE TITLE
Bug: koishi UI 的插件的启用按钮 可能存在问题

### ISSUE THREAD

**Issue by Yamamoto-2** [koishijs/koishi#1113]
### Describe the bug

我近期完成了koishi-plugin-tsugu-bangdream-bot的开发，但是发布之后，安装后无法启动，至少按了启动的按钮之后没有任何报错信息。无论是开发环境，还是windows服务端，都可以复现这个问题。但是插件本身经过我的检查似乎没有明显的问题，而且无论哪种客户端，通过修改koishi.yml 删除插件名前面的" ~ "来强行启用插件，都可以正常开启并运行，且在通过修改配置文件强行开启后，可以正常的开启与关闭插件。

### Steps to reproduce

通过插件市场安装tsugu-bangdream-bot，或在开发环境中直接在external中加载 "https://github.com/Yamamoto-2/tsugu-bangdream-bot" 的代码，均会产生这种问题。

### Expected behavior

希望可以解决这个问题，如果是插件的问题的话，至少能够在控制台显示报错信息，以便于调试

### Screenshots

![2023-06-13 00-30-58](https://github.com/koishijs/koishi/assets/77522610/a4b7604c-8fe1-4e8f-9fb3-eea0f5e13f96)
![2023-06-13 00-48-05](https://github.com/koishijs/koishi/assets/77522610/132acaf1-ad40-4ee3-925d-b2c955cc7f91)

### Versions

- OS: <Windows Server 2016>
- Platform: <onebot>
- Node version: <18.12.0>
- Koishi version: <Desktop v0.10.5 Koishi 4.13.2>

**Comment by shigma** [comment]
感谢您的反馈。你的插件的某个依赖加载失败了。

没有显示日志的问题已经追踪了：https://github.com/koishijs/webui/issues/185
