### ISSUE TITLE
Bug: koishi尝试多种安装方式出错

### ISSUE THREAD

**Issue by whhh233** [koishijs/koishi#1117]
### Describe the bug

服务器信息22.04.1-Ubuntu SMP  2023 x86_64 x86_64 x86_64 GNU/Linux
使用linux方式安装报错:
root@ip-172-31-12-22:~/koishi# ./linux.AppImage 
0000|2023-06-14 15:01:55 [I] launcher Koishi Desktop v0.10.5
0000|2023-06-14 15:01:55 [W] launcher failed to chmod data folder bin: chmod /tmp/.mount_linux.Kn4wXr/usr/bin/bin: read-only file system
2023/06/14 15:01:55 systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files

使用docker安装报错：
/entrypoint.sh: exec: line 10: illegal option -v
使用docker ps检查后发现容器并未启动

### Steps to reproduce

-

### Expected behavior

-

### Screenshots

以下为appimage日志
root@ip:~/koishi# ./linux.AppImage 
0000|2023-06-14 15:01:55 [I] launcher Koishi Desktop v0.10.5
0000|2023-06-14 15:01:55 [W] launcher failed to chmod data folder bin: chmod /tmp/.mount_linux.Kn4wXr/usr/bin/bin: read-only file system
2023/06/14 15:01:55 systray error: failed to register our icon with the notifier watcher (maybe no tray is running?): The name org.kde.StatusNotifierWatcher was not provided by any .service files

以下为docker日志
root@ip:~/koishi# docker run -p 5140:5140 koishijs/koishi -v /root/koishi:/koishi -e TZ=Asia/Shanghai
Archive:  /boilerplate.zip
  inflating: .env
   creating: .yarn/
   creating: .yarn/cache/
  inflating: .yarn/cache/.gitignore
  inflating: .yarnrc.yml
  inflating: README.md
  inflating: koishi.yml
   creating: node_modules/
   creating: node_modules/setprototypeof/
  inflating: node_modules/setprototypeof/README.md
---------------------------------中间部分过长，略去-------------------------
  inflating: node_modules/mkdirp-classic/package.json
  inflating: node_modules/mkdirp-classic/index.js
  inflating: node_modules/mkdirp-classic/LICENSE
  inflating: package.json
  inflating: yarn.lock
/entrypoint.sh: exec: line 10: illegal option -v

### Versions

- OS: 22.04.1-Ubuntu
- Platform: x86
- Node version: v18.16.0
- Koishi version:

**Comment by whhh233** [comment]
> 你使用 Linux 安装方式正常启动了，直接访问 Koishi 控制台即可。

但是使用IP:5140访问页面提示
当前无法使用此页面43.XXX.XXX.XXX 当前无法处理此请求。
HTTP ERROR 502

**Comment by ilharp** [comment]
首先，你应当确定 Koishi 所使用的端口。使用

```sh
./linux.AppImage ps
```

确定 Koishi 实例的端口。

然后，如果无法访问对应的端口，则需要检查 Koishi 是否开放了公网访问，以及防火墙是否放行。

**Comment by whhh233** [comment]
> 首先，你应当确定 Koishi 所使用的端口。使用
> 
> ```shell
> ./linux.AppImage ps
> ```
> 
> 确定 Koishi 实例的端口。
> 
> 然后，如果无法访问对应的端口，则需要检查 Koishi 是否开放了公网访问，以及防火墙是否放行。

在只有命令行的情况下如何修改koishi全局配置，使其监听0.0.0.0

**Comment by ilharp** [comment]
> 在只有命令行的情况下如何修改koishi全局配置，使其监听0.0.0.0

修改 `~/.koishi/data/instances/default/koishi.yml` 文件并添加内容为 `host: 0.0.0.0` 的一行，之后运行

```sh
./linux.AppImage restart default
```

即可。
