### ISSUE TITLE
Bug: 指令推测错误响应了「句号」以外的回复

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi#1119]
### Describe the bug

回复一个 QQ 大表情而不是「。」或「.」时也会响应指令推测。

### Steps to reproduce

发送例如 `hlep` 可能会进行推测的指令，回复一个 QQ 大表情

### Expected behavior

仅响应句号

### Screenshots

![d57e2c32fe448c3](https://github.com/koishijs/koishi/assets/18106422/19c353e2-3b36-4d02-8b49-c1c76b2149c8)

### Versions

- OS: 
- Platform: QQNT?
- Node version: 
- Koishi version: 

### Additional context

[舔舔]

**Comment by shigma** [comment]
能不能抓个 session 看看 content 是什么？

**Comment by Lipraty** [comment]
> 能不能抓个 session 看看 content 是什么？

好的喵

**Comment by Lipraty** [comment]
<img src="https://github.com/koishijs/koishi/assets/18106422/1776f2f5-3db4-490d-9851-d57a3e3ed296" width="20%"/> 我自己更新 QQNT 客户端版本之后无法复现这个问题了，会不会之前某个版本的大表情有奇怪的东西（x

**Comment by shigma** [comment]
那看看有没有其他人能复现吧。

**Comment by shigma** [comment]
由于一个月内无人复现，这个 issue 就此关闭。之后遇到再说。
