### ISSUE TITLE
Feature:  Schema.const 等不支持.disabled

### ISSUE THREAD

**Issue by zhuhansan666** [koishijs/koishi#1122]
### Describe the problem related to the feature request

目前, 我在做i18n的中文变种配置项时, 想要做一个 敬请期待 的选项, 但发现 Schema.const 不支持disabled, 无法禁用交互
(如图中的 中国澳门 一项)
![image](https://github.com/koishijs/koishi/assets/93586645/baaa2a50-3333-47bd-b5ca-2f99fef95ae5)

### Describe the solution you'd like

新增该方法并且可以自定义鼠标点击或悬浮的文本, 如 敬请期待 或 当前模式下不可用 等

### Describe alternatives you've considered

~~直接支持<script>~~

### Additional context

-

**Comment by CyanChanges** [comment]
const 你想怎么 disable

**Comment by shigma** [comment]
是可以做的。

**Comment by CyanChanges** [comment]
> 是可以做的。

常量不是不变吗

**Comment by MaikoTan** [comment]
> 常量不是不变吗

I think the `disable` flag here would mark the such option as unchoocable rather than unchangable.

**Comment by shigma** [comment]
已支持此特性，请等待版本更新。
