### ISSUE TITLE
Feature: Telegram 适配器对外暴露 $getFileFromPath 函数

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1127]
### Describe the problem related to the feature request

如题，建议在 session.bot 中暴露 $getFileFromPath 这个函数，否则获取到的文件或者音频只能得到文件 ID，而不能获取文件地址。

目前 TS 中无法直接使用该函数，只能通过扩展类型来曲线救国。

https://github.com/satorijs/satori/blob/3d6c6b445e6e2ed168d09638f861f7399a267916/adapters/telegram/src/bot.ts#L268-L275

### Describe the solution you'd like

如题

**Comment by shigma** [comment]
现在没暴露吗？你链接里的代码就是暴露的类型啊？

你要在 session.bot 中使用当然要做类型转换，如果你觉得 `as TelegramBot` 很费事的话，可以来给其他所有 adapter 都 PR 一个此方法的实现。

**Comment by Ice-Hazymoon** [comment]
但是像 `bot.getFile` 就不用转换类型，这些常用的 API 默认我认为没问题啊。

**Comment by Ice-Hazymoon** [comment]
或者文件类型默认返回 file url 而不是 file id，这样能更好的同步适配其他平台。

**Comment by Ice-Hazymoon** [comment]
telegram 中收到的文件没有 url，都是 file id，如果不用 $getFileFromPath 则无法获取 file url

**Comment by shigma** [comment]
额你是怎么接收文件的……

**Comment by Ice-Hazymoon** [comment]
用 $getFileFromPath 从 file id 获取 file url

**Comment by MaikoTan** [comment]
> 用 $getFileFromPath 从 file id 获取 file url

How do you get the file id, that's what shigma concerned about.

**Comment by shigma** [comment]
我的意思是，你理论上无法拿到 file id，除非你使用 internal API。

但如果你使用 internal API，那多使用一个 `$getFileFromPath` 也没有变得更麻烦。

**Comment by Ice-Hazymoon** [comment]
但是我收到的文件确实包含 file id 啊，Telegram API 是这样设计的，如果要拿到文件，需要再请求一遍

![image](https://github.com/koishijs/koishi/assets/25239977/e4f3b46c-5a14-41a0-bc0a-f7b5541c6435)

**Comment by shigma** [comment]
咦，这可能确实是 telegram 适配器实现的有点问题，没有返回标准元素。
