### ISSUE TITLE
Bug: 使用 <audio> 标签发送数据时报错

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1129]
### Describe the bug

文件地址是：`data:audio/mpeg;base64,//xxxx` 开头的，但是 koishi 是根据 `base64://` 进行检测的，当然这可能是我的写法问题。

但是使用 segment.audio(`data:audio/mpeg;base64,xxxx`) 得到的地址就能正常发送。

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

"koishi": "^4.13.4",

**Comment by shigma** [comment]
`data:audio/mpeg;base64,//xxxx` 不应该有 `//` 吧，你是不是拼错字符串了……

**Comment by Ice-Hazymoon** [comment]
那应该是我提 issue 的时候多打了，`data:audio/mpeg;base64,` 后面是一个 buffer 转的 base64 string

**Comment by shigma** [comment]
能提供一下复现代码吗？不太理解遇到的问题。`h.audio()` 与 `<audio>` 的作用是完全等价的。

**Comment by Ice-Hazymoon** [comment]
我傻了，audio 的链接 attr 是 url，我写成了 src，所以发不出去

**Comment by shigma** [comment]
这个确实有点怪（

能解决就好。
