### ISSUE TITLE
Feature: 监听 KOOK “用户加入语音频道”和“用户退出语音频道”事件

### ISSUE THREAD

**Issue by maxoyed** [koishijs/koishi#1131]
### Describe the problem related to the feature request

想要统计KOOK服务器内不同用户的语音在线时长，需要监听这两个事件来实现

### Describe the solution you'd like

在KOOK适配器里加入 `kook/joined_channel` 和 `kook/exited_channel` 两个事件，导入类型后可以直接通过 `ctx.on('kook/joined_channel')` 和 `ctx.on('kook/exited_channel')` 来使用

### Additional context

KOOK 开发文档：[用户相关事件列表](https://developer.kookapp.cn/doc/event/user)

**Comment by maxoyed** [comment]
临时解决方案
```typescript
declare module 'koishi' {
  interface Events {
    'kook/joined-channel': (session: Session) => void
    'kook/exited-channel': (session: Session) => void
  }
}
```

**Comment by CyanChanges** [comment]
https://github.com/satorijs/satori/pull/125
