### ISSUE TITLE
Bug: config 没有热更新

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1135]
### Describe the bug

修改 schema 后，控制台没有跟着变动。
似乎从 config 独立成插件后就有这个问题了。

### Steps to reproduce

1. `yarn dev`
2. 修改插件的 schema

### Expected behavior

控制台的配置项跟着变动。

### Versions

- OS: Windows 11
- Node version: 20.2.0
- Koishi version: 4.13.6

**Comment by shigma** [comment]
duplicate of #1088

**Comment by idanran** [comment]
> 虽然已经修了但仍需等待下一个 Koishi 版本发布后，将 config 和 hmr 插件均更新后此功能才可用。

嗯嗯
