### ISSUE TITLE
Feature: 关于扩展数据库

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1137]
### Describe the problem related to the feature request

```js
ctx.model.extend("user", {
  "setting.foo": {
    type: "boolean",
    initial: true,
  },
});
```

```js
session.user['setting.foo'] 无法获取
session.user.setting.foo 可以获取，但是 TS 报错
```

猜测可以通过 TS 的类型推断来解决这个问题

### Describe the solution you'd like

如题

**Comment by Seidko** [comment]
你的代码有两处问题：
1. 要访问深层的属性，你需要 `session.user['setting']['foo']` 而不是 `session.user['setting.foo']`。
2. 要扩充属性同时获得类型提示，你需要 declare module，详细请看[文档](https://koishi.chat/zh-CN/guide/database/model.html)
