### ISSUE TITLE
Bug: 在arm64平台上执行`yarn create koishi`后无法正确构建go-cqhttp

### ISSUE THREAD

**Issue by ymy139** [koishijs/koishi#1138]
### Describe the bug

执行`yarn create koishi`后在构建go-cqhttp时报错，koishi可以正常运行，但无法正常使用go-cqhttp

### Steps to reproduce

在arm64平台上执行`yarn create koishi`

### Expected behavior

正确构建koishi，并且可以正常使用

### Screenshots

*太长了放不下，扔网盘里了*
链接：https://pan.baidu.com/s/1Qllucf7psplSk5DMK3_ntg?pwd=5xpr 
提取码：5xpr

### Versions

- OS: 
![微信图片_20230707093035](https://github.com/koishijs/koishi/assets/117415378/d2cddf01-fec2-4acf-b448-312c28d4fa7d)
- Platform: Onebot
- Node version: v18.16.1
- Koishi version: 4.13.6

### Additional context

平台：树莓派4B，arm v8+
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64

**Comment by shigma** [comment]
为什么关闭了？问题解决了吗?
