### ISSUE TITLE
Bug: QQ频道发送图片错误。

### ISSUE THREAD

**Issue by MRDHR** [koishijs/koishi#1144]
### Describe the bug

Error: Error with request send_guild_channel_msg, args: {"guild_id":"xxxxx","channel_id":"xxxx","message":{"type":"image","attrs":{"url":"https://res.mrdvh.com/vi/UiQxUwp6jGA/maxresdefault.jpg"},"children":[]}}, retcode: 100
                            at _Internal._get (D:\WebstormProjects\MrdBot3\node_modules\@satorijs\adapter-onebot\src\types.ts:558:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at _Internal._Internal.<computed> (D:\WebstormProjects\MrdBot3\node_modules\@satorijs\adapter-onebot\src\types.ts:595:20)

### Steps to reproduce

```
myBot.internal.sendGuildChannelMsg(xxxxx, xxxxx, h('image', {
                                                            url: "https://xxsakldajsd"
                                                        }))
```

### Expected behavior

图片发送成功

### Screenshots

![image](https://github.com/koishijs/koishi/assets/5576916/73e0b272-0ff4-4cf5-ac0b-6580ebf6febc)

### Versions

- OS: windows 11
- Platform: qq guild
- Node version: 18.13.0
- Koishi version: 4.13.7

**Comment by MRDHR** [comment]
![image](https://github.com/koishijs/koishi/assets/5576916/0165d48a-7c4f-46f0-a72f-e489a06bde12)
从日志看到是上传错误了

**Comment by shigma** [comment]
网络图片发送失败系 go-cqhttp 实现问题，与 Koishi 无关。你可以考虑转存本地或者向 go-cqhttp 仓库提交 issue。

**Comment by MRDHR** [comment]
好的，我试试转存本地。

**Comment by shigma** [comment]
哦还有一种办法就是发送前直接下载到 buffer。然后 `h.image(buffer, mimetype)` 发送。

总之这个问题应该算解决了。
