### ISSUE TITLE
Bug: 无指令前缀时的相关问题

### ISSUE THREAD

**Issue by ENDsoft233** [koishijs/koishi#1148]
### Describe the bug

当定义了一个带有权限的指令，在使用时若用户权限不足，会返回 `权限不足。`；而当这个指令是父指令时，则会返回 `指令未找到。`。
我认为在无指令前缀的前提下，返回 `指令未找到。` 是非预期的行为。

### Steps to reproduce

1. 定义如下指令

```tsx
ctx.command('foo', { authority: 2 })
ctx.command('foo.bar <string>').action(async ({ }, str) => str);
ctx.command('bar <string>', { authority: 2 }).action(async ({ }, str) => str);
```

2. 测试如下指令

 - 以 `authority = 1` 的身份

```
foo // 指令未找到。
foo.bar 1 // 权限不足。
bar 1 // 权限不足。
```

 - 以 `authority = 2` 的身份

```
foo // 指令：foo\n可用的子指令有：\nfoo.bar
foo.bar 1 // 1
bar 1 // 1
```

### Expected behavior

以 `authority = 1` 的身份测试时

```
foo // 不返回
foo.bar 1 // 权限不足 或 不返回
bar 1 // 权限不足 或 不返回
```

### Screenshots

![image.png](https://s2.loli.net/2023/07/18/43lsEerdJb8mjtM.png)

### Versions

 - OS: Windows 11 (10.0.22621.1702)
 - Platform: onebot
 - Node version: 18.13.0
 - Koishi version: 4.13.2

**Comment by shigma** [comment]
研究了一下，发现「指令未找到」是因为直接走了 help，没有考虑权限等级。我看看怎么修复。
