### ISSUE TITLE
Bug: missing type for Schema.disabled()

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1149]
### Describe the bug
Recently, Schema support disabled
[![image](https://github.com/koishijs/koishi/assets/68551684/7e773207-ab91-4735-9f1c-29e0e167276a)](https://koishi.chat/zh-CN/schema/meta/disabled.html)
```ts
foo = Schema.string().disabled() // TS2339: Property 'disabled' does not exist on type 'Schema '.
```

disabled is missing in Schema

![image](https://github.com/koishijs/koishi/assets/68551684/2f1dffe7-5d08-4aa6-aa1d-437e705734b6)

### Steps to reproduce

```ts
foo = Schema.string().disabled() // TS2339: Property 'disabled' does not exist on type 'Schema '.
```

### Expected behavior

```ts
foo = Schema.string().disabled() // No TS Error here
```

### Screenshots

![image](https://github.com/koishijs/koishi/assets/68551684/c7998d7e-c6c3-4ec4-9047-29587b25d5a6)
![image](https://github.com/koishijs/koishi/assets/68551684/2f1dffe7-5d08-4aa6-aa1d-437e705734b6)
![image](https://github.com/koishijs/koishi/assets/68551684/9dbd61cc-c0d9-4204-89fb-79fefd9fdec3)

### Versions

- OS: Linux  x86_64 GNU/Linux
- Platform: Linux CyanArch 6.4.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 11 Jul 2023 05:13:16 +0000 x86_64 GNU/Linux
- Node version: v20.4.0
- Koishi version: 4.13.8
- Schemastery version: 3.11.0

**Comment by shigma** [comment]
感谢贡献。
