### ISSUE TITLE
Feature: 指令名支持大写字母

### ISSUE THREAD

**Issue by idranme** [koishijs/koishi#1150]
### Describe the problem related to the feature request

需求

### Describe the solution you'd like

ctx.command('ABC <message>')

**Comment by shigma** [comment]
现在是可以注册大写指令（不报错）但是无法调用吗？

**Comment by idanran** [comment]
> 现在是可以注册大写指令（不报错）但是无法调用吗？

对的

**Comment by idanran** [comment]
> 感谢反馈。已修复，将于下个版本实装。

好耶
