### ISSUE TITLE
Bug: 最新版 yarn build 概率无法完整构建

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1151]
### Describe the bug

在更新最新版本的依赖后 (执行 `yarn dep`)
使用 `yarn build` 有概率无法完整构建
![image](https://github.com/koishijs/koishi/assets/68551684/7bc9faa8-4e29-4ab1-969d-877c5b6e963b)

### Steps to reproduce

1. 更新所有依赖
```sh
yarn dep
```
2. 创建(选择)一个插件
```sh
yarn setup test
```
3. 构建
```sh
yarn build
```
4. 查看插件 `lib` 目录
```sh
ls external/test/lib
```
发现构建不完整
如果无法复现，请删除 `external/test/lib`
重复第 3 步

### Expected behavior

正常构建

### Screenshots

![image](https://github.com/koishijs/koishi/assets/68551684/c665bb49-9dcb-44a6-8db6-0185909fd4ad)
![image](https://github.com/koishijs/koishi/assets/68551684/601b9f4b-2a6a-4d94-a358-9a6ee93077f3)
![image](https://github.com/koishijs/koishi/assets/68551684/929fb440-dde3-4c00-9efe-0bf5e29fb0ab)
![image](https://github.com/koishijs/koishi/assets/68551684/b673c72b-0f57-438c-8d4b-8ed6854a418f)

### Versions

- OS: Linux CyanArch 6.4.3-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Tue, 11 Jul 2023 05:13:16 +0000 x86_64 GNU/Linux
- Platform: Linux
- Node version: v20.4.0
- Koishi version: 4.13.8
- koishi-scripts version: 4.1.7
- Yakumo version: 0.3.13
- yakumo-esbuild version: 0.3.25
- esbuild version: 0.18.15
- esbuild-register version: npm:@shigma/esbuild-register@^1.1.1

### Additional context

package.json https://pastebin.com/ECREvyhf
tsconfig.json https://pastebin.com/01tyYXAM
tsconfig.base.json https://pastebin.com/XhibUWmg
external/test/package.json https://pastebin.com/5r42gMwz
external/test/tsconfig.json https://pastebin.com/YcPANsY0

**Comment by Seidko** [comment]
删除 `tsconfig.tsbuildinfo` 等文件再尝试构建一下试试

**Comment by shigma** [comment]
这是预期的，你没有删除 `tsconfig.tsbuildinfo`。可以执行 `yarn build --clean` 删除。

**Comment by CyanChanges** [comment]
az

**Comment by CyanChanges** [comment]
我修改了代码他也不会 build 出来
那我每次 build 都得先 clean？还是有什么别的操作会？

**Comment by ilharp** [comment]
> 还是有什么别的操作会？

上文已给出了回答：

> 这是预期的，你没有删除 `tsconfig.tsbuildinfo`。

`tsconfig.tsbuildinfo` 文件会记录构建状态。修改代码后，构建时会发现当前代码状态与文件记录的不一致性，从而重新构建不一致的部分。
