### ISSUE TITLE
Feature: 支持停用某项指令

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1155]
### Describe the problem related to the feature request

单独停用某个指令，而不是停用整个插件。

### Describe the solution you'd like

在控制台的“指令管理”的右上角增加“停用指令”。

**Comment by CyanChanges** [comment]
*koishijs/webui
*shigma transfer this issue from koishijs/koishi 
(雾

**Comment by shigma** [comment]
你可以选择：

1. 通过过滤器实现指令的不可访问
2. 向插件作者提议增加一个「停用指令」的配置项

指令是插件的一部分。停用指令会不可避免导致插件功能不可用。

**Comment by idanran** [comment]
> 你可以选择：
> 
> 1. 通过过滤器实现指令的不可访问
> 2. 向插件作者提议增加一个「停用指令」的配置项
> 
> 指令是插件的一部分。停用指令会不可避免导致插件功能不可用。

好哒
