### ISSUE TITLE
Bug: about room types in matrix

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/koishi#1158]
### Describe the bug

In the matrix adapter, the room type is recognized as a private chat in koishi, which makes some plug-ins unusable (such as rss)

### Steps to reproduce

Install rss,and talk in room.

### Expected behavior

Make the room type can be correctly identified

### Screenshots

non-essential

### Versions

- OS: Docker
- Platform: Matrix
- Node version: 18.16.1
- Koishi version: 4.13.9

**Comment by Anillc** [comment]
All sessions from matrix adapter are seen as channels (not pm). Please provide more information.

The problem to get a real type of room is that room types are handled at client, not home server. We can't know Which type a room is in adapter.

**Comment by yunkuangao** [comment]
Whether the room type can be determined by the number of people in the room. For example, if the number of people in the room is 2, it will be regarded as a private chat, otherwise it will be a channel.

Such as this issue: https://github.com/matrix-org/matrix-js-sdk/issues/720#issue-357320750

**Comment by Anillc** [comment]
我还是直接发中文吧。

你的问题是 matrix adapter 把所有消息当成了私聊，但是事实上 matrix adapter 的行为上把所有的消息都作为了群聊，不知道你使用的时候遇到了什么问题。

根据人数来决定房间类型这个事情我不是很想做，我觉得所有房间都是群聊很合理，如果你确实有什么需要私聊的情况可以说一下场景，我好考虑一下。

**Comment by Anillc** [comment]
看了一下，确实有这个问题，原因是有些地方使用了 guildId 来判断当前 session 是否是群聊（例如使用了 `ctx.guild()`）

这个地方还需要再考虑一下 guildId 应该填什么比较好。目前是在 room 在 space 里的时候会填入 space 的 room id。但是当 room 不在任何 space 里的时候会导致 guildId 为空。

我现在打算把 guildId 设置为跟 channelId 同样的值，space 和 guild 的概念不应该划等号。一个原因是在 matrix 里 room 可能不在任何 space 里，另一个原因是一个 room 可能在多个 space 里。

**Comment by yunkuangao** [comment]
关于space，个人认为是一种对现有room的一种特殊管理room，这一点在matrix上也有说明[Spaces: The next frontier](https://element.io/blog/spaces-the-next-frontier/)，而且与现有的逻辑不接洽（public space | private space | personal spaces），可以暂时将space放置。
