### ISSUE TITLE
Bug: Docker启动报错

### ISSUE THREAD

**Issue by skret028** [koishijs/koishi#1163]
### Describe the bug

docker安装启动后，只有欢迎和用户设置，没有其他按钮。

### Steps to reproduce

docker run -d \
--name=koishi \
--net=ipvlan_net \
--ip=192.168.20.22 \
--restart=always \
-p 5140:5140 \
-e TZ=Asia/Shanghai \
-v /mnt/user/container_config/koishi:/koishi \
koishijs/koishi:latest

docker run -d \
--name=koishi \
--net=ipvlan_net \
--ip=192.168.20.22 \
--restart=always \
-p 5140:5140 \
-e TZ=Asia/Shanghai \
koishijs/koishi:latest

持久化和非持久化安装都是这个问题

### Expected behavior

正常显示

### Screenshots

<img width="1212" alt="image" src="https://github.com/koishijs/koishi/assets/107525301/6e24e578-68eb-4d63-b441-7cee65f38524">

> 2023-08-04 11:23:48 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:48 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:48 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:52 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
> 2023-08-04 11:23:53 [W] market timeout of 5000ms exceeded
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/index.js'
>   Error: ENOENT: no such file or directory, open '[object Object]/style.css'
> 2023-08-04 11:24:19 [W] market AxiosError: timeout of 30000ms exceeded
>                             at RedirectableRequest.handleRequestTimeout (/koishi/node_modules/axios/dist/node/axios.cjs:3047:16)
>                             at RedirectableRequest.emit (node:events:514:28)
>                             at Timeout.<anonymous> (/koishi/node_modules/follow-redirects/index.js:169:12)
>                             at listOnTimeout (node:internal/timers:569:17)
>                             at process.processTimers (node:internal/timers:512:7)
> 2023-08-04 11:24:19 [W] market AxiosError: timeout of 30000ms exceeded
>                             at RedirectableRequest.handleRequestTimeout (/koishi/node_modules/axios/dist/node/axios.cjs:3047:16)
>                             at RedirectableRequest.emit (node:events:514:28)
>                             at Timeout.<anonymous> (/koishi/node_modules/follow-redirects/index.js:169:12)
>                             at listOnTimeout (node:internal/timers:569:17)
>                             at process.processTimers (node:internal/timers:512:7)

### Versions

- OS: <unraid6.15.0>
- Platform: <-docker->
- Node version: <18.17.0>
- Koishi version: <1.8.1>

**Comment by yunkuangao** [comment]
Yes, the test is not available on 1.8.0, 1.8.1 of the docker image, it is available on 1.7.4.

This is a piece of error code from the browser console

```
vue.js:1 TypeError: t.map is not a function
    at Ve.deep (client.js:77:64640)
    at Jt (vue.js:1:13817)
    at Xt (vue.js:1:13895)
    at _ (vue.js:1:23354)
    at dn (vue.js:1:14927)
    at D (vue.js:1:54419)
    at he.fn (vue.js:1:52669)
    at he.run (vue.js:1:4592)
    at U.e.update (vue.js:1:53453)
    at j (vue.js:1:52499)
```

**Comment by shigma** [comment]
请使用 1.8.1 版本。

**Comment by shigma** [comment]
此问题已于 1.8.1 版本修复。
