### ISSUE TITLE
koishi-plugin-mongo in npm has title "koishi-database-mongo"

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#117]
**Describe the bug**

npm中koishi-plugin-mongo的package标题是 koishi-database-mongo
**To Reproduce**

不需要
**Expected behavior**

改一下名字
**Screenshots**

**Versions**

- OS: [e.g. iOS] macOS
- Node Version: [e.g. 10.16.0] 15.0
- CoolQ Version: [e.g. 5.15.4] cq-http
- CQHTTP Version: [e.g. 4.13.2]  cq-http latest
- Koishi Version: [e.g. 1.0.0] 2.3.2

**Additional context**

**Comment by Shigma** [comment]
Thanks. Fixed in 9b616ffafa9f1e9606f241fa6d1a8fb7e1117bfa.
