### ISSUE TITLE
Feature: `ctx.http` 使用 fetch 重构

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1181]
### Describe the problem related to the feature request

node16 将于 9 月 11 日停止支持。参见 https://endoflife.date/nodejs

### Describe the solution you'd like

`ctx.http(method, url, config)`
我们可以选择向后兼容 axios 的配置项，或直接使用 fetch 的配置项。

**Comment by idanran** [comment]
如果选择向后兼容的话，有一个相关的库或许可以参考 https://github.com/dragon-fish/fexios

**Comment by shigma** [comment]
目前 fetch 应该还不支持代理，这会导致超过 50% Koishi 用户无法使用。

**Comment by idanran** [comment]
> Node 16 停止支持不代表 axios 停止支持。
> 
> 目前 fetch 应该还不支持代理，这会导致超过 50% Koishi 用户无法使用。

那是否可以提供一个 http.fetch

**Comment by idanran** [comment]
> Node 16 停止支持不代表 axios 停止支持。
> 
> 目前 fetch 应该还不支持代理，这会导致超过 50% Koishi 用户无法使用。

https://stackoverflow.com/questions/72534539/node-js-18-3-native-fetch-request-with-a-proxy

似乎是可以的

**Comment by idanran** [comment]
> > Node 16 停止支持不代表 axios 停止支持。
> > 目前 fetch 应该还不支持代理，这会导致超过 50% Koishi 用户无法使用。
> 
> https://stackoverflow.com/questions/72534539/node-js-18-3-native-fetch-request-with-a-proxy
> 
> 似乎是可以的

等等，好像不行。

**Comment by idanran** [comment]
相关 issue nodejs/node#42814

**Comment by idanran** [comment]
https://github.com/nodejs/node/tree/main/deps/undici/src#undicifetchinput-init-promise

使用代理应该是可以做到的。

**Comment by idanran** [comment]
```
import { fetch, ProxyAgent } from 'undici'

const client = new ProxyAgent('http://127.0.0.1:7890/')

const res = await fetch('https://google.com', {
  dispatcher: client
})
const text = await res.text()
console.log(text)
```

**Comment by simon300000** [comment]
这有什么优点吗？

**Comment by shigma** [comment]
> 这有什么优点吗？

优点是原生了，可以减少不超过 1M 的 bundle size。

**Comment by simon300000** [comment]
> > 这有什么优点吗？
> 
> 优点是原生了，可以减少不超过 1M 的 bundle size。
> 
> 同时 axios 不支持 http proxy over https，目前只能使用 socks proxy。如果 fetch 支持的话有望解决这个问题（目前 fetch 到底能不能支持各种协议的 proxy 尚不明确）。

按照他说的办法，看起来要再带一个1m的undici

**Comment by shigma** [comment]
undici 看起来比 axios 还大 :rofl:

**Comment by idanran** [comment]
不带也可以的

**Comment by idanran** [comment]
> > 这有什么优点吗？
> 
> 优点是原生了，可以减少不超过 1M 的 bundle size。
> 
> 同时 axios 不支持 http proxy over https，目前只能使用 socks proxy。如果 fetch 支持的话有望解决这个问题（目前 fetch 到底能不能支持各种协议的 proxy 尚不明确）。

目前只支持 http 和 https 协议的 proxy

**Comment by idanran** [comment]
单纯使用 undici 的 ProxyAgent，打包器应该会自动摇树。

**Comment by idanran** [comment]
undici:
![image](https://github.com/koishijs/koishi/assets/96647698/e90ac62d-083a-41a0-8a7b-f2ff6dc5babf)

axios:
![image](https://github.com/koishijs/koishi/assets/96647698/76c9480b-8a1b-423b-9b06-8fe2c97b0f7f)

**Comment by shigma** [comment]
> 目前只支持 http 和 https 协议的 proxy

那还是不太行，至少等 socks 支持出来吧。我说的 50% 依赖代理的用户基本上全是 socks，你这一改第二天一半机器人全死完了。

**Comment by shigma** [comment]
<img width="1309" alt="image" src="https://github.com/koishijs/koishi/assets/33423008/6d9018a1-10ad-4265-8af4-d146d2e78377">

<img width="1271" alt="image" src="https://github.com/koishijs/koishi/assets/33423008/1dff2486-897a-4771-b7f9-b7ac6b96c29f">

<img width="792" alt="image" src="https://github.com/koishijs/koishi/assets/33423008/957dfd15-761f-4c57-90e8-e581e1059a18">

**Comment by idanran** [comment]
> <img alt="image" width="1309" src="https://user-images.githubusercontent.com/33423008/263040955-6d9018a1-10ad-4265-8af4-d146d2e78377.png"> <img alt="image" width="1271" src="https://user-images.githubusercontent.com/33423008/263041018-1dff2486-897a-4771-b7f9-b7ac6b96c29f.png"> <img alt="image" width="792" src="https://user-images.githubusercontent.com/33423008/263041129-957dfd15-761f-4c57-90e8-e581e1059a18.png">

啊这

**Comment by shigma** [comment]
> 封装一下 undici，利用打包器摇树应该能解决体积问题。

说话好歹得有基本常识吧。摇树仅仅在库层面对打包有意义，Koishi 作为一个框架，选用什么依赖肯定是完全打进去，用户根本没有 bundle 这一个环节，哪来的摇树？

**Comment by shigma** [comment]
> 啊这

这俩体积都能接受的。只是放个图对比一下而已。其实没有太大可比性。

主要还是看功能。我还是看好 fetch 的未来的。

**Comment by idanran** [comment]
> > 目前只支持 http 和 https 协议的 proxy
> 
> 那还是不太行，至少等 socks 支持出来吧。我说的 50% 依赖代理的用户基本上全是 socks，你这一改第二天一半机器人全死完了。

https://github.com/Kaciras/fetch-socks
目前有个可用的

**Comment by idanran** [comment]
或者等 nodejs/undici#2224 或 TooTallNate/proxy-agents#239

**Comment by idanran** [comment]
> > 封装一下 undici，利用打包器摇树应该能解决体积问题。
> 
> 说话好歹得有基本常识吧。摇树仅仅在库层面对打包有意义，Koishi 作为一个框架，选用什么依赖肯定是完全打进去，用户根本没有 bundle 这一个环节，哪来的摇树？

soga

**Comment by idanran** [comment]
还有一种选项，参照 https://github.com/Kaciras/fetch-socks 自己写一个 socks 的 agent。

**Comment by MaikoTan** [comment]
This can be implemented by a hacky way since node.js's `fetch` API is based on `undici` itself comme ici : https://github.com/nodejs/node/issues/43187#issuecomment-1134634174
But it is too hacky to be supported.

**Comment by simon300000** [comment]
可以让用户选☝️🤓

**Comment by shigma** [comment]
支持不好就老老实实等着，别到时候体积增加了功能减少了一堆插件还 breaking，这不完全是为了一己私欲瞎搞吗？

每次有点小道消息就催着 breaking，axios 又不是没法用了。Koishi 又不是你一个人的软件。

**Comment by shigma** [comment]
可以不用关，有什么进展持续关注一下。等到能用了就可以做。

**Comment by idanran** [comment]
> 可以不用关，有什么进展持续关注一下。等到能用了就可以做。

嗯嗯

**Comment by shigma** [comment]
https://github.com/cordiverse/undios
