### ISSUE TITLE
Bug: telegram 适配器经常出现请求次数过多的错误

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1189]
### Describe the bug

Error: Telegram API error 429. Too Many Requests: retry after 1221

如下图，刚启动没有发送过任何消息，过一段时间就循环出现这个错误

![image](https://github.com/koishijs/koishi/assets/25239977/8a8ee9ab-b00c-4768-8cc6-98cbe083c61d)

猜测可能是以下原因造成

https://github.com/koishijs/koishi/blob/7c47f23e0de360c522da3c3dfe0f97aa08997cfe/packages/core/src/command/index.ts#L131C31-L141

这里在 bot 更新消息时就会调用 updateCommands，而 updateCommands 又会去调用 telegram 的 api，导致 api 调用次数过多

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

koishi: 4.14.3
"@koishijs/plugin-adapter-telegram": "^3.8.1",

**Comment by Lipraty** [comment]
该问题来自一个已存在的 issue。详见： #1180

**Comment by shigma** [comment]
我会尽快修复。之前可以先降版本。

**Comment by shigma** [comment]
https://github.com/koishijs/koishi/issues/1180#issuecomment-1711123507

可以锁 satori 到 2.7.4 版本。
