### ISSUE TITLE
Bug: telegram 无法隐藏用户的 commands 列表

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1192]
### Describe the bug

![image](https://github.com/koishijs/koishi/assets/25239977/f36af4dc-c62e-4b16-909e-9b9a331f318a)

slash: false 也没用

也无法自己手动设置 commands，因为 koishi 会疯狂调用 updateCommands，会把手动设置的内容覆盖

### Steps to reproduce

如题

### Expected behavior

如题

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
支持了 `slash` 配置项，可用于关闭某一个机器人的 slash command 功能。
