### ISSUE TITLE
Bug: 用户首次触发“在 middleware 中调用 session.execute 执行指令”时，必定导致“权限不足”异常

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi#1194]
### Describe the bug

RT

### Steps to reproduce

![image](https://github.com/koishijs/koishi/assets/44761872/e24f5a62-299e-4295-a18b-d370006138f8)
![image](https://github.com/koishijs/koishi/assets/44761872/e2b2716d-b509-47a3-a516-c99208865249)

### Expected behavior

正确触发指令

### Versions

![77038b3ace039fc55ea9319236f9027b](https://github.com/koishijs/koishi/assets/44761872/1bb0ec60-cc4e-4684-8206-35710dfbe7f1)

**Comment by shigma** [comment]
暂时无法复现。

**Comment by CyanChanges** [comment]
看看指令注册的代码？（

**Comment by dragon-fish** [comment]
无法复现。
