### ISSUE TITLE
Bug: `hmr`无法正常重载不导入`@koishijs/koishi`的文件

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi#1199]
### Describe the bug

~~呜呜呜呜呜我复现不出来梦梦你没有心~~

~~目前已知的信息： 触发此问题需要重载的文件中不能require任何koishi的内容~~

自用的workaround：`pending.push(require.resolve('@koishijs/koishi'))`

**更新：**

已复现

此问题的原因是，任何koishi插件及衍生代码均依赖@koishijs/koishi

当重载的源文件中不require 任何直接或间接依赖@koishijs/koishi的模块时，在展开pending的过程中将无法将其标为declined

而一旦进入后续流程，当第一个reload被接受后，@koishijs/koishi就会进入accepted，导致这之后的所有文件全部被reload

### Steps to reproduce

external/foo/utils.ts
```
export default x = 1
```

external/foo/src.ts
```
from { x } from './utils'
x
/* original code */
```

external/bar
```
/* unmodifed */
```

koishi.yml
```
	foo: {}
	bar: {}
```

### Expected behavior

/

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
哪来的 @koishijs/koishi（
