### ISSUE TITLE
Feature: whatsApp 增加按钮点击事件

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#1206]
### Describe the problem related to the feature request

类似 Telegram 的按钮点击时会触发 `telegram/callback-query`

在 WhatsApp 里，应该对 message.type === interactive 进行兼容

![550173381908f3100f6d419c2d634376](https://github.com/koishijs/koishi/assets/25239977/afb083de-0e5d-42c1-ab19-8b37dc89c337)

```js
{
  context: {
    from: '19492127547',
    id: 'wamid.HBgNODYxNzY4NzE5Mzc3MhUCABEYEjI4QTNDMjQ0MjA5REUwQThBQwA='
  },
  from: '86176xxxxxxxx',
  id: 'wamid.HBgNODYxNzY4NzE5JKLTYIhUCABIYIDg5REI4NjTYUIODRjNCNDlCRjRDNDgwRENERkJGNkRBAA==',
  timestamp: '1695953400',
  type: 'interactive',
  interactive: {
    type: 'button_reply',
    button_reply: { id: 'unique-postback-id-first', title: 'First Button' }
  }
}
```

### Describe the solution you'd like

如题

**Comment by shigma** [comment]
已实现
