### ISSUE TITLE
Feature: subcommand 默认继承 command 的权限

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#1214]
### Describe the problem related to the feature request

admin 只能给每个 subcommand 单独赋权，而不能通过给 command 赋权使得全部子指令赋权。

### Describe the solution you'd like

不知道

**Comment by shigma** [comment]
目前的子指令默认依赖父指令权限。

你的需求应该是将多个指令放入指令组中实现。

建议阅读文档并搜索之前的 issue。
