### ISSUE TITLE
使用kook机器人，能发送图片和文件，不能发视频和语音文件

### ISSUE THREAD

**Issue by shumyun** [koishijs/koishi#1219]
### Describe the bug

如题，因没有任何错误提示，想请教如何调试，或者说是其他问题

### Steps to reproduce

使用的是h('message',h.image())和h.file都可以。确定照片、文件、视频、音频都在同一个文件内，并且视频和音频都是ffmpeg生成的标准文件，然后在kook聊天中使用过上传。

### Expected behavior

如上

### Versions

- kook 插件 version: 4.0.4
- Koishi version: 4.15.0

**Comment by shigma** [comment]
已经复现问题。KOOK 最近关闭了之前使用的音视频发送接口，现在必须使用卡片消息发送。

我们将尽快适配。

**Comment by shigma** [comment]
最新版已修复。
