### ISSUE TITLE
Feature: IPV6支持

### ISSUE THREAD

**Issue by linwei5d** [koishijs/koishi#1221]
### Describe the problem related to the feature request

校内ipv4有时无法访问设备，只有ipv6处处能访问得到，于是域名只设置了ipv6

### Describe the solution you'd like

默认监听地址下能通过纯ipv6访问

**Comment by shigma** [comment]
这跟 Koishi 没有关系。你可以设置监听地址为 `::`。

默认监听地址只能被内网访问，这是为了安全性考虑。
