### ISSUE TITLE
Bug: Context 配置 host 无效

### ISSUE THREAD

**Issue by bsdayo** [koishijs/koishi#1222]
### Describe the bug

传入 Context 构造函数的 `config.host` 无效，启动仍绑定为 127.0.0.1

### Steps to reproduce

```ts
import { Context } from 'koishi'

const ctx = new Context({ host: '0.0.0.0', port: 5555 })

ctx.start()
```

控制台输出：
```
[I] app server listening at http://127.0.0.1:5555
```

此时确实无法在其他设备访问服务。

### Expected behavior

`config.host` 配置项能被正常读取

### Versions

- OS: Windows 11
- Platform: _not related_
- Node version: v20.8.0
- Koishi version: v4.15.0

**Comment by shigma** [comment]
https://github.com/satorijs/satori/blob/17b57880f4a76f22ce9efce18641dd157dc025bf/packages/satori/src/router.ts#L84-L88

这里只是显示为 127.0.0.1（方便从命令行点开），实际上监听的是正确的。

我的机器人配置了 `host` 为 `::`，可以在公网正常访问。

**Comment by bsdayo** [comment]
> https://github.com/satorijs/satori/blob/17b57880f4a76f22ce9efce18641dd157dc025bf/packages/satori/src/router.ts#L84-L88
> 
> 这里只是显示为 127.0.0.1（方便从命令行点开），实际上监听的是正确的。
> 
> 我的机器人配置了 `host` 为 `::`，可以在公网正常访问。

感谢解答，了解了
这边重新尝试发现其他设备是可以正常访问的，先前测试的时候可能是网络方面出现问题，抱歉
