### ISSUE TITLE
Bug: 更新后左边导航栏的 设置+依赖管理 图标消失，插件市场永远加载中

### ISSUE THREAD

**Issue by eric2788** [koishijs/koishi#1223]
![image](https://github.com/koishijs/webui/assets/6276840/07e5844a-9a73-4036-a893-36fb819ca4b1)
![image](https://github.com/koishijs/webui/assets/6276840/5e7488ca-444a-4082-a59f-b3bbb1a8594b)

console 没有显示错误，只有如上的 warnings
尝试过重启koishi依然不行

配置如下:

System:
    OS: Linux 5.10 Alpine Linux
    CPU: (4) arm64 Cortex-A72

Binaries:
    Node: 18.17.1
    Yarn: 3.6.2

Koishi:
    Core: 4.15.0
    Console: 5.16.1

我现在除了没法使用插件市场外，因为插件配置以及依赖管理消失的原因也没办法删除/新增插件

**Comment by ilharp** [comment]
推荐使用问题前往 Discussions 版或 Koishi 论坛讨论。已将此 Issue 转换为 Discussion。

这个问题并非 Koishi 的 bug，而是你遇到了名为「多例」的问题。该问题在 Koishi 论坛上已有多个讨论贴及解决方案，可以参考。

<https://k.ilharp.cc/5473>
