### ISSUE TITLE
Bug: KOOK 解析 kmarkdown 的特殊字符有误

### ISSUE THREAD

**Issue by 9cats** [koishijs/koishi#1227]
### Describe the bug

解析 `[` `]`  ``` ` ``` `-` 这四个字符有误

其中 `-` 只有在连续的时候才会解析错误，例如 `test -adb text` 这条指令正常解析，但是 `test --gamma=1` 这条指令解析就有问题

### Steps to reproduce

在 KOOK 输入指令
```
echo 1:[ 2:] 3:` 4:--
```
从 bot 得到响应是：
```
1:\[ 2:\] 3:\` 4:\-\-
```

### Expected behavior

从 bot 得到的响应应该为：
```
1:[ 2:] 3:` 4:--
```

### Versions

- OS: Windows 10
- Platform: KOOK
- Node version: 18.17.1
- Koishi version: 4.15.1
- koishi-plugin-kook version: 4.0.5

**Comment by 9cats** [comment]
#1050

**Comment by 9cats** [comment]
https://github.com/satorijs/satori/blob/4cab923c895f28cf8fcfa421393ac9497d9f913d/adapters/kook/src/utils.ts#L86-L90
参考这里，再添加几行，替换掉以上四个字符应该就能解决解析不正常的问题

**Comment by shigma** [comment]
已修复。
