### ISSUE TITLE
Bug: `using` is a keyword in Typescript 5.2 now!???

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1228]
### Describe the bug

插件可以使用 using 属性标注服务依赖 (https://koishi.chat/zh-CN/guide/plugin/service.html#using-属性)
但是在 TS 5.2 中是关键字
(https://www.google.com.hk/search?q=typescript+using)

以后 JS 估计也有
https://github.com/tc39/proposal-explicit-resource-management

### Steps to reproduce

创建一个 Koishi 插件
使用 using 声明服务依赖

```typescript
// src/index.ts
import { Context } from 'koishi'

export const using = ['keine'] // some Syntax Error here

export function apply(ctx: Context) {
/* do something... */
}
```

### Expected behavior

有一个方法可以声明服务依赖，不使用类插件

### Screenshots

![image](https://github.com/koishijs/koishi/assets/68551684/7a4899ff-f49a-45eb-b94c-30b216356339)

![image](https://github.com/koishijs/koishi/assets/68551684/9e55ee83-531a-4a96-a507-cbfb551b084d)

### Versions

- OS: Windows 11
- Platform: 不适用
- Node version: v20.8.1
- Koishi version: 4.15.1
- Typescript version: 5.2.2

**Comment by shigma** [comment]
Temporary workaround:

```ts
const _using = []

export { _using as using }
```

**Comment by CyanChanges** [comment]
cordis 更了可以 close 了吧（

**Comment by shigma** [comment]
也行
