### ISSUE TITLE
Feature: monorepo template

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1229]
### Describe the problem related to the feature request

提供 monorepo 的 koishi 插件 template
如 koishijs/webui koishijs/koishi-plugin-booru koishijs/koishi-plugin-wordle 那种 packages 和 plugins 下面可以写包和插件的

### Describe the solution you'd like

添加模板repo

**Comment by ilharp** [comment]
`yarn create koishi` 生成的 Koishi 模板项目不正是非常优秀的 Monorepo 范例吗？

**Comment by CyanChanges** [comment]
> `yarn create koishi` 生成的 Koishi 模板项目不正是非常优秀的 Monorepo 范例吗？

但是我要插件，我在 koishi 里 create koishi 不能满足需求啊（

**Comment by ilharp** [comment]
在模板项目里使用 `yarn setup` 可以直接创建插件；如果你不想直接创建，也可以在任意你希望的位置手动创建 `package.json` 文件。

**Comment by CyanChanges** [comment]
> 在模板项目里使用 `yarn setup` 可以直接创建插件；如果你不想直接创建，也可以在任意你希望的位置手动创建 `package.json` 文件。

不是单个插件啊，就是类似于你把 webui clone 到 external 里那个 webui 的效果啊

**Comment by ilharp** [comment]
[koishi](https://github.com/koishijs/koishi) 和 [webui](https://github.com/koishijs/webui) 两人都是 Koishi 模板项目。这是否更能说明你正在寻找的就是 Koishi 模板项目？

**Comment by ilharp** [comment]
[wordle](https://github.com/koishijs/wordle) 似乎不是一个模板项目。我们来询问一下其作者这个 repo 的创建历史。 @MaikoTan 

不过我仍然认为从模板项目创建 monorepo 是最佳的选择，因为你无需自己进行任何配置。

**Comment by CyanChanges** [comment]
> [wordle](https://github.com/koishijs/wordle) 似乎不是一个模板项目。我们来询问一下其作者这个 repo 的创建历史。 @MaikoTan
> 
> 不过我仍然认为从模板项目创建 monorepo 是最佳的选择，因为你无需自己进行任何配置。

不是，我插件我创建啊，但是那种一个external里文件夹多个插件怎么创建？我怎么配置

**Comment by ilharp** [comment]
> 但是那种一个external里文件夹多个插件怎么创建？（如webui，上面说的那个例子）我怎么配置自己的那种

> 可以在任意你希望的位置手动创建 `package.json` 文件。

怎么创建是自己的自由啊，我个人比较喜欢右键「新建-文本文件」然后改名为 `package.json`；其余所有文件比如 `tsconfig.json` 和 `index.ts` 内容都一样，直接复制粘贴过来就行

**Comment by MaikoTan** [comment]
The repository of wordle is a hand-made monorepo, since I am familiar with yarn workspaces as well as git commands, I can create a monorepo in several minutes without the Koishi boilerplate scripts.

wordle的存储库是一个手工制作的monorepo，因为我熟悉yarn工作空间和git命令，所以我可以在几分钟内创建一个monorepo，而无需Koishi样板脚本。

**Comment by shigma** [comment]
实现了 `-m` 参数。。

**Comment by CyanChanges** [comment]
> > 但是那种一个external里文件夹多个插件怎么创建？（如webui，上面说的那个例子）我怎么配置自己的那种
> 
> > 可以在任意你希望的位置手动创建 `package.json` 文件。
> 
> 怎么创建是自己的自由啊，我个人比较喜欢右键「新建-文本文件」然后改名为 `package.json`；其余所有文件比如 `tsconfig.json` 和 `index.ts` 内容都一样，直接复制粘贴过来就行

nsdd，但是需求是 monorepo 的 template, 或者 cli command

——您说的东西都解决不了我的需求，我在标题已经写清楚了，如果您说一些解决不了需求的话，不光浪费您的时间，还有我的时间也浪费了。我只是提个 issue 而已（

您一直带偏到 koishi 官方模板使用 monorepo 还有普通插件的创建，您给这些是没什么用的，文档里写的很清楚创建一个普通的插件的方法，这点文档大家都会看的吧？at 别人询问如何创建插件，但是所提的插件的 repo 结构和您说的模板完全不一致，您提供的的方法完全不能创建类似结构，直至我多次描述最后才您才说一点有用的信息。

同样，用户群对于很多问题发一串论坛的数字，然后自己去阅读一大堆于解决问题并无用处的内容才能找到真正的解决方案，并不清晰。对于普通用户来说，对电脑可能也没有非常熟悉，不一定熟知 Ctrl+F 等查找方法。并不是所有人都能这样随便研究俩小时都不累的，然而原本是能直接给出文本的。。。
此外，用户群里每天都有与 Koishi 和编程无关的擦边等内容，还有同样需要大量阅读和思考才能找到哪里不能说的 ‘308’。管理等发完 “308”, ".ban xxx" 之后就继续——。以至于用户群现在已然有：”Koishi 相关内容不一定能发，但是发电是能发“ 的现象，甚至您自己也推崇这个观点，已经脱离用户群的本质，只有 ”Koishi 用户群“ 这个头衔了。。。但是，对于此类现象却没有制止，反而愈演愈烈。。。

综上所述，如果我多次回复您，“对于您说提得内容了解，会用” 请您不要再重复相同内容，这回对你我都产生困扰。

最后感谢您对 Koishi 的贡献

**Comment by CyanChanges** [comment]
> 实现了 `-m` 选项。

有发版吗？

**Comment by CyanChanges** [comment]
> 实现了 `-m` 选项。

![image](https://github.com/koishijs/koishi/assets/68551684/3a2cbd6a-ff1b-49fa-b548-afe7c87cd723)
啊？Linux 也能炸？

**Comment by shigma** [comment]
你没有配置 user name 和 user email 罢

**Comment by CyanChanges** [comment]
> 你没有配置 user name 和 user email 罢

新装的 Arch， 没注意（

**Comment by CyanChanges** [comment]
> 你没有配置 user name 和 user email 罢

这次我可配置了哦
![image](https://github.com/koishijs/koishi/assets/68551684/a9850331-6996-4336-bbee-2a7a54a6fc7b)
![image](https://github.com/koishijs/koishi/assets/68551684/6b0089bc-c51e-4f8c-ba83-99fa10f6b174)

**Comment by shigma** [comment]
你能不能测试一下，去 @koishijs/scripts 这个包里，把报错的那个指令改成 -m initialize。再看看创建报不报错？

**Comment by CyanChanges** [comment]
> 你能不能测试一下，去 @koishijs/scripts 这个包里，把报错的那个指令改成 -m initialize。再看看创建报不报错？

之前手机去修没收到gmail推送，我现在没时间明天看看

**Comment by CyanChanges** [comment]
> 你能不能测试一下，去 @koishijs/scripts 这个包里，把报错的那个指令改成 -m initialize。再看看创建报不报错？

![image](https://github.com/koishijs/koishi/assets/68551684/083b1f08-e693-4d56-9a0c-6186ea31d9fc)
![image](https://github.com/koishijs/koishi/assets/68551684/5b6e4ae0-8c2c-4437-aa73-6906186eb594)

**Comment by CyanChanges** [comment]
发现问题了, 估计 GPG 没拿到 TTY, 没问我密码开不了 keyring
![image](https://github.com/koishijs/koishi/assets/68551684/1a20a0a2-1c2f-4424-b1cc-9eea6db531a0)

**Comment by CyanChanges** [comment]
> 那我感觉不好解决了……

我觉得最好还是把会炸的地方的log输出出来

**Comment by shigma** [comment]
现在的情况就是没有 log 吧。

顺便你可以试试 spawn 能不能解决，目前是 execSync 的。

**Comment by shigma** [comment]
我本地无论如何也没法复现你的情况，只能麻烦你去试试了。

**Comment by CyanChanges** [comment]
> 我本地无论如何也没法复现你的情况，只能麻烦你去试试了。

好像是没设置要签哪个 key，设置上就好了，因为 ide 有这项设置，所以用 ide commit 不炸，手动 commit 就炸了

如果短时间输入过密码，他就不会再提示输密码，没试过如果这个时候 setup 会怎么样
