### ISSUE TITLE
adapter-cqhttp: 服务器无法连接导致阻塞应用加载

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi#123]
当需要连接 A B 两个账号，但 A 账号无法连接时，应当跳过 A 账号，触发 connect 事件并继续尝试连接。  
当前逻辑下则不会触发 connect 事件导致 bot 无法正常加载。

**Comment by Shigma** [comment]
我不觉得你说的就是期望行为。你连不上任何一个不就代表连接失败吗。

**Comment by undefined-moe** [comment]
A连不上 B能连上的时候应当继续载入

**Comment by Shigma** [comment]
你这样说的话，连接失败这个概念就全无意义了

Promise.all 就是应该用来处理这种情况的，你连不上的自己删配置才更合理

或者可以加一个配置项，但是我说的应该是默认情况

**Comment by undefined-moe** [comment]
全部连不上即为连接失败，有时候某个bot因为某些特殊原因无法连接，而koishi-app又因某些需求自动重启了

**Comment by Shigma** [comment]
【全部连不上即为连接失败】这个说法本身不合理，因为你已经写好配置说明你的插件需要符合一个全连上的预期才能正常使用。

【koishi-app 又因某些需求自动重启了】这种情况不会发生，因为在 koishi 中连接阶段报错只会导致程序终止。你会这么说很可能是因为你对 koishi 有了错误的理解，又用了错误的理解写出了错误的代码，才导致达不成预期的效果。如果你需要自动重启又不希望担心连接失败问题，请使用 koishi start。

**Comment by undefined-moe** [comment]
自动重启应用场景： 检测到远端repo更新，自动拉取，build，再重启以应用
或者应当允许载入时不初始化用户，并使用 app.connect(target) 添加服务器

**Comment by Shigma** [comment]
自动重启是合理的，但是也应该按照需要全部连上为条件

app.connect() 这个会导致 breaking change，目前不考虑
