### ISSUE TITLE
Bug: `before-send` 事件回调中的 `session` 变量缺少 `user`  与 `channel`

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi#1235]
### Describe the bug

监听 `before-send` 事件时，回调函数 session 变量的 `user` 与 `channel` 未传入数据。

### Steps to reproduce

```typescript
  ctx.before('attach-channel', (_, f) => {
    f.add('id')
  })
  ctx.before('attach-user', (_, f) => {
    f.add('id')
  })
  ctx.before('send', (session) => {
    console.log('send:', session.channel, session.user)
  })
```
将返回：
```bash
## 私聊
send: null null
## 群聊
send: null null
```

### Expected behavior

应当返回：
```javascript
{
  flag: 0,
  assignee: 'koishi',
  guildId: '#',
  permissions: [],
  locales: [ 'zh' ],
  foo: 'bar',
  platform: 'sandbox:114514',
  id: '#'
}
{
  flag: 0,
  assignee: 'koishi',
  guildId: '#',
  locales: [],
  permissions: [],
  name: '',
  activity: {},
  platform: 'sandbox:114514',
  id: '#'
}
```
（user 略）

### Versions

System: Windows 11 23H2
Node: 16.17.0
Yarn: 1.22.10
Koishi:
    Core: 4.15.2
    Console: 5.17.0

**Comment by shigma** [comment]
请尝试最新版本看是否已经修复。

**Comment by Lipraty** [comment]
好，我今天测测

**Comment by Lipraty** [comment]
依旧是 null

![image](https://github.com/koishijs/koishi/assets/18106422/4de7313f-b502-4b3e-a4cd-140f0f5a9404)
![image](https://github.com/koishijs/koishi/assets/18106422/479e5de0-fb9f-4cfd-b7a9-82e005744db4)

OS: Windows 11 23H2
Node: 16.17.0
Yarn: 1.22.10
Koishi:
    Core: 4.15.2
    Console: 5.17.0

**Comment by Lipraty** [comment]
issue 已更新
