### ISSUE TITLE
Bug: 邮箱适配器无法登录邮箱

### ISSUE THREAD

**Issue by imAkisa** [koishijs/koishi#1244]
### Describe the bug

我在10月30日新yarn create koishi的4.15.3版本模板项目，只安装了2.1.1版本官方邮箱适配器
我旧的4.16.4版本模板项目&2.0.0版本官方邮箱适配器可以登录qq邮箱，但是新模板项目和旧模板项目用同样的插件配置设置，却无法登录，是同一个服务器

### Steps to reproduce

同上

### Expected behavior

邮箱适配器可以登录邮箱

### Screenshots

<img width="1266" alt="Midgard_10-30_17-35-45" src="https://github.com/koishijs/koishi/assets/108515435/172768a1-575b-4c77-8d11-2638f8329d15">
这是旧的模板项目，可以登录

<img width="1266" alt="Midgard_10-30_17-36-14" src="https://github.com/koishijs/koishi/assets/108515435/3bd3f9ff-6d52-46b8-8b7f-03808103e504">
这是新的模板项目，无法登录

插件配置都是一样的，是同一个服务器，不同端口的两个koishi实例
并且我在新模板项目尝试登录，登录失败后，旧模板项目点启用邮箱适配器也是正常登录的
不存在两个模板项目同时登录同一个mail帐号的情况

### Versions

新的模板项目（不能登录）
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
Binaries:
    Node: 18.18.0
    Yarn: 1.22.19
Koishi:
    Core: 4.15.3
    Console: 5.17.1
2.1.1版本官方邮箱适配器

旧的模板项目（可以登录）
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz
Binaries:
    Node: 18.18.0
    Yarn: 1.22.19
Koishi:
    Core: 4.14.6
    Console: 5.14.4
2.0.0版本官方邮箱适配器

**Comment by CyanChanges** [comment]
配置页面截个图？

**Comment by CyanChanges** [comment]
疑似换 ctx.plugin 后没传配置进去


![Screenshot_20231030-180310](https://github.com/koishijs/koishi/assets/68551684/33cdc9fd-747b-4661-9e6b-496b4e3ae2dd)
此处读取 bot.config.username

![Uploading Screenshot_20231030-180202.png…]()
使用 ctx.plugin (未传 config

**Comment by shigma** [comment]
感谢反馈，请尝试最新版本。
