### ISSUE TITLE
Feature: 添加「连接现有 Koishi Console 后端」功能

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1245]
### Describe the problem related to the feature request

1.可以让某些纯前端插件跨 Koishi 实例使用
2.同步主题&部分配置
3.可以随时更新 Koishi 前端 API （@koishijs/client 随着网站中的版本更新而更新）（可以快速修复一些bug啊？提反馈的时候也可以直接使用这个页面测试最新版有没有修复..?
4.不会重启时刷新页面，正好连不上服务器导致无法自动重连

（也许能解决有的时候访问 Koishi WebUI 页面会 Not Found 的问题？

副作用：可能会出现 API BRAKING CHANGE 导致不兼容的问题（

### Describe the solution you'd like
允许连接其他 Koishi 实例的 API (/status)

(在 Koishi Online) 添加一个 「连接现有 Koishi 实例」(的按钮)，可以输入 Koishi Console 的 API Path (/status)，连接到一个 Koishi 实例

类似于 Clash yacd 等

**Comment by shigma** [comment]
我没有理解你要做什么，控制台是为了管理后端的，如果后端都没有了光看到一个控制台是做什么？

**Comment by CyanChanges** [comment]
> 我没有理解你要做什么，控制台是为了管理后端的，如果后端都没有了光看到一个控制台是做什么？

就是让 k-on 能连 k-on 外的 Koishi Console（/status
（就是可以连别的后端

**Comment by MaikoTan** [comment]
> 就是让 k-on 能连 k-on 外的 Koishi Console（/status
> 
> （就是可以连别的后端，除了 k-on 的跑的浏览器实现后端，还可以连 Node 上跑的 Koishi，类似于 Clash yacd 什么的那种

The Koishi Console was shipped with the web / browser side code. You could just access the Console that you're willing to connect with by typing the url of it. And what on the earth that k-on comes in the conversations?

Koishi控制台随网络/浏览器端代码一起发货。您只需键入其网址即可访问您愿意连接的控制台。K-on到底在对话中出现了什么？

**Comment by CyanChanges** [comment]
> > 就是让 k-on 能连 k-on 外的 Koishi Console（/status
> > （就是可以连别的后端，除了 k-on 的跑的浏览器实现后端，还可以连 Node 上跑的 Koishi，类似于 Clash yacd 什么的那种
> 
> The Koishi Console was shipped with the web / browser side code. You could just access the Console that you're willing to connect with by typing the url of it. And what on the earth that k-on comes in the conversations?
> 
> Koishi控制台随网络/浏览器端代码一起发货。您只需键入其网址即可访问您愿意连接的控制台。K-on到底在对话中出现了什么？

不加在 k-on 上其实也可以（

**Comment by CyanChanges** [comment]
理论上来讲不难写，我看看自己好写就 pr，写完再 open 吧（
