### ISSUE TITLE
Bug: 手机聊天短气泡提前换行

### ISSUE THREAD

**Issue by CyanChanges** [koishijs/koishi#1248]
### Describe the bug

![Screenshot_20231030-211107](https://github.com/koishijs/koishi/assets/68551684/24ce1fbb-72fa-46a3-9f30-132d7bcc68ab)
```
11451
4
11451
4
```

![Screenshot_20231030-211338](https://github.com/koishijs/koishi/assets/68551684/5d6e34f7-57aa-46be-928f-da7dad6c80d0)

```
hel
p
```

### Steps to reproduce

打开有对话示例的文档
或
打开 sandbox 发送一些消息

### Expected behavior

不要换行，空间够

### Screenshots

![Screenshot_20231030-211107](https://github.com/koishijs/koishi/assets/68551684/2c2a3924-4e33-47b3-8534-de02ee1a72de)
![Screenshot_20231030-211338](https://github.com/koishijs/koishi/assets/68551684/b454e4df-dbd7-4c79-b8ad-7f17ca5f31d6)

### Versions

- OS: Android 14; Pixel 7 Pro Build/UP1A.231005.007
- Platform: Sandbox (on koishi.online) & Koishi docs (on koishi.chat)
- Node version: Not applicable
- Browser version: Chrome 118.0.5993.111
- Koishi version: 4.15.3 (Latest deployed Koishi Online / Koishi Docs)

**Comment by shigma** [comment]
![c58d5298b5e6e6ccd0cfbc5e4f85bc31_720](https://github.com/koishijs/koishi/assets/33423008/60e8156b-1d58-4e63-92db-dc46aa68f817)

真不是手机问题？

**Comment by shigma** [comment]
应该真的是手机系统问题。

**Comment by CyanChanges** [comment]
要么是 Chrome 的问题，要么是 Android 14？

**Comment by shigma** [comment]
我有看到其他人在其他手机应用上遇到了类似的问题，也是最后一个字符被换行。但是他并未在 Koishi 中成功复现。因此我认为这个问题很与可能是手机渲染程序的问题。

**Comment by CyanChanges** [comment]
我 Android Studio 开个 P7p 的模拟器试一下

**Comment by CyanChanges** [comment]
复现了，由于未知原因，我手机开gh网页貌似不可以传图，马上发

**Comment by CyanChanges** [comment]
如图，在设置中将系统字体大小调大一格
![Screenshot_20231113-182441](https://github.com/koishijs/koishi/assets/68551684/18a3dbca-2c12-4029-a880-041356e2eb34)

打开文档，出现提前换行
![Screenshot_20231113-182444](https://github.com/koishijs/koishi/assets/68551684/812e9b8e-a559-4fbd-a89c-fcc0e33a75fd)

**Comment by shigma** [comment]
所以这个问题还是系统的问题吧，理论上能在 Koishi 侧修复吗？

如果可以的话，你可以把手机上浏览器的 inspect 打开，看看能不能调 CSS 解决（不影响正常显示的前提下）。

**Comment by CyanChanges** [comment]
> 所以这个问题还是系统的问题吧，理论上能在 Koishi 侧修复吗？
> 
> 如果可以的话，你可以把手机上浏览器的 inspect 打开，看看能不能调 CSS 解决（不影响正常显示的前提下）。

那我也许得先
<details><summary>查看详细步骤</summary>
<p>


1. 解锁 OEM （清除所有数据）
2. 刷 Magisk
3. 启动 Zygisk
4. 安装 LSPosed 模块
5. 安装 ChromeXt，勾选 Chrome 浏览器
6. 打开浏览器，加载 Developer Tools
7. 然后发现改不了（

</p>
</details> 

才能在 Chrome 中使用开发者工具进行调试
但是修改 CSS 可能会有点麻烦，由于我没有进行过移动端开发过，所以不是很好进行调试（只能查看无法编辑，而且查看的体验也有点炸裂（

**Comment by CyanChanges** [comment]
有时间看看开个有 HMR 热修补的 Koishi WebUI (或 Document) 在电脑上修改，手机上查看，这可能方便些

**Comment by MaikoTan** [comment]
> 那我也许得先
> <details><summary>查看详细步骤</summary>
> <p>
> 
> 
> 1. 解锁 OEM （清除所有数据）
> 2. 刷 Magisk
> 3. 启动 Zygisk
> 4. 安装 LSPosed 模块
> 5. 安装 ChromeXt，勾选 Chrome 浏览器
> 6. 打开浏览器，加载 Developer Tools
> 7. 然后发现改不了（
> 
> </p>
> </details> 
> 
> 才能在 Chrome 中使用开发者工具进行调试

You don't need to install XPosed, since you could just debug the webpage on your phone from any PC as long as you connect your phone to the PC via USB and activate the USB debugging mode. Then open Chrome and navigate to `chrome://inspect`, you eould see your phone in the remote devices section.

**Comment by CyanChanges** [comment]
> > 那我也许得先
> > 查看详细步骤
> > 
> > 
> > 1. 解锁 OEM （清除所有数据）
> > 2. 刷 Magisk
> > 3. 启动 Zygisk
> > 4. 安装 LSPosed 模块
> > 5. 安装 ChromeXt，勾选 Chrome 浏览器
> > 6. 打开浏览器，加载 Developer Tools
> > 7. 然后发现改不了（
> > 
> > 
> >  
> > 才能在 Chrome 中使用开发者工具进行调试
> 
> You don't need to install XPosed, since you could just debug the webpage on your phone from any PC as long as you connect your phone to the PC via USB and activate the USB debugging mode. Then open Chrome and navigate to `chrome://inspect`, you would see your phone in the remote devices section.

hmmmm
![image](https://github.com/koishijs/koishi/assets/68551684/c0d6fc3e-fe48-45e3-a7a3-38eb565a174a)
![image](https://github.com/koishijs/koishi/assets/68551684/dc130516-9379-44ca-8c21-d47335e615cb)

**Comment by CyanChanges** [comment]
![image](https://github.com/koishijs/koishi/assets/68551684/b3fb085e-9ded-40fb-81c8-7dec1cb66c43)
dev... failed

**Comment by CyanChanges** [comment]
shigma 能试试改字体大小后，你的手机可以复现吗？我这边 docs 跑不起来，远程 DevTools 也不能正常使用

**Comment by shigma** [comment]
![Screenshot_2023-11-13-22-58-14-817_com.android.chrome.jpg](https://github.com/koishijs/koishi/assets/33423008/e4a1f0d6-7c2c-4989-9e5e-58556d77f8ba)

![Screenshot_2023-11-13-22-58-03-417_com.android.chrome.jpg](https://github.com/koishijs/koishi/assets/33423008/b66ae114-6dc2-47a6-8d17-7891b9677d98)

![Screenshot_2023-11-13-22-57-42-578_com.android.chrome.jpg](https://github.com/koishijs/koishi/assets/33423008/07ed6573-5aa6-48b1-8de7-b01e4589edc6)

![Screenshot_2023-11-13-22-57-32-848_com.android.chrome.jpg](https://github.com/koishijs/koishi/assets/33423008/d839fa59-36d6-44fa-a8a3-9e7a66371de9)

我的任何字体均无法复现。
