### ISSUE TITLE
Feature: mock 插件的 receive 方法的自定义 Timeout

### ISSUE THREAD

**Issue by initialencounter** [koishijs/koishi#1249]
### Describe the problem related to the feature request

 `receive` 方法的 `Timeout` 似乎默认为2000ms, 当插件中包含某些耗时的任务， 2000ms 的超时时间可能无法完成测试
```test
1) tile:
     Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (C:\Users\29115\dev\ks\Plugins\News\gh-tile\test\index.spec.ts)
      at listOnTimeout (node:internal/timers:573:17)
      at process.processTimers (node:internal/timers:514:7)
```

### Describe the solution you'd like

希望 `receive` 方法可以传入一个可选的 Timeout 参数, 希望 `shouldReply` 和 `shouldNotReply` 也能传入 Timeout

**Comment by shigma** [comment]
这个 2000 不是 koishi-plugin-mock 的限制，而是 mocha 的限制，可以使用 --timeout 修改。
