### ISSUE TITLE
Bug: 编写适配器时koishi的Context和satori的Context不兼容

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#1251]
### Describe the bug

在创建新的Adapter和Bot时，如果按照官方文档给出的方式进行定义，会出现"类型Context与C无法兼容“这一TS报错。  
我高度怀疑这是因为Koishi和Satori的Context定义不同，而且存在不兼容部分。

### Steps to reproduce

1. 创建新项目
2. 书写以下示例代码：
```typescript
import { Context, Bot } from 'koishi';

class CustomBot<C extends Context> extends Bot<C> {}
```
3. TypeScript报错，提示Context与C不兼容

### Expected behavior

由于是直接参考官方文档和官方适配器实现书写的相关代码，所以不应该有报错。

### Screenshots

<img width="962" alt="3b0bcb3ba0597f5c3596f8d5ab447e76" src="https://github.com/koishijs/koishi/assets/61967203/38f21455-7c9b-4d67-b37b-5b52bd6c2422">

### Versions

- Koishi version:4.15.3

### Additional context

就如我在上面提到的那样，koishi的Context和Satori的Context很可能存在兼容性问题。希望各位collaborator能够及早排查出相关的问题并予以解决。
我个人作为Koishi的一名三方开发者，对于Koishi本身并不是那么熟悉，所以恕难以直接参与这项工作。不过，我也会尽全力去协助各位collaborator去修复这一问题。

**Comment by CyanChanges** [comment]
satori 继承了 cordis 的 Cobtext 添加了一些内容所以与 cordis 不大兼容，但是 koishi 的 Context 好像（上次看的时候）就是 satori 的 Context 的说，部分类型为指定了 C 模板参数的 cordis 类型，具体原因也许来自类型合并？对于不懂 ts 模板，不懂类型合并，不懂 js 魔法，不懂 tsc。。。（此处省略一万字免责声明）的我来说可能不好解释，具体可以等 shigma 的详细解释

**Comment by shigma** [comment]
fixed by satorijs/satori@c9146652f99f6aaf847287b2e8d98cc7f2cfda2e.
