### ISSUE TITLE
Feature:  数据库操作能否返回成功or失败以及影响的条数？

### ISSUE THREAD

**Issue by SyraTi** [koishijs/koishi#1252]
### Describe the problem related to the feature request

目前的`ctx.databset.set`/`ctx.database.remove`等数据库操作返回值均为`Promise<void>`， 无法得知是否成功or操作影响的条数。
![image](https://github.com/koishijs/koishi/assets/20638533/ea5855e7-34f8-46c5-ac20-ccbadf3499a0)

### Describe the solution you'd like

能否在返回值中返回相关的影响结果？例如“删除了多少条数据”“更新了多少条数据”等

**Comment by shigma** [comment]
有价值的提议，之后会增加相关返回值。

**Comment by shigma** [comment]
已经支持相关的特性，文档稍后更新。更新完毕后我会关闭此 issue。

**Comment by shigma** [comment]
https://koishi.chat/zh-CN/guide/database/#%E8%8E%B7%E5%8F%96%E6%94%B9%E5%8A%A8%E8%A1%8C%E6%95%B0

https://koishi.chat/zh-CN/api/database/database.html#writeresult
