### ISSUE TITLE
Feature: 为每个插件的日志加上折叠按钮

### ISSUE THREAD

**Issue by SaarChaffee** [koishijs/koishi#1253]
### Describe the problem related to the feature request

如果插件的报错日志太长会导致需要滑动很久才看到配置项。

### Describe the solution you'd like

为每个插件的日志加上折叠按钮。

**Comment by CyanChanges** [comment]
目前的日志是一个一个 json，一次调用 reggol 一个 json 从存储调用的输出信息

**Comment by maxoyed** [comment]
> 目前的日志是一个一个 json，一次调用 reggol 一个 json 从存储调用的输出信息

可以在每个插件的页面单独查看插件的日志

**Comment by CyanChanges** [comment]
> > 目前的日志是一个一个 json，一次调用 reggol 一个 json 从存储调用的输出信息
> 
> 可以在每个插件的页面单独查看插件的日志

不不不，是这样的，日志的 name 不是由 koishi，satori 或者 reggol 决定的，是开发者自己选择合适的 name（可能是插件的 name（指 export 的那个）
现有 logger 的数据也没有与插件上下文关联，不好确定那个 name 是哪个插件的 log

logger 实例与上下文关联我觉得还是有意义的，方便用户阅读日志，也方便开发者提取自己插件错误的日志阅读

目前 `ctx.logger` 好像（上次看的时候）好像在 satori 里面，具体和 Koishi 联动可能需要考虑一下，具体我不到，看 shigma 想怎么写

**Comment by CyanChanges** [comment]
plugin-logger 前端可以做个过滤 name 和等级的功能，比较简单，也能实现类似于折叠的不显示的功能

**Comment by ilharp** [comment]
> plugin-logger 前端可以做个过滤 name 和等级的功能，比较简单，也能实现类似于折叠的不显示的功能，不需要改 reggol 和 satori，只对应 name

由于已实现根据 `ctx.logger` 过滤，实现此功能已无意义。

与此 Issue 无关的功能请求请在相关的 Issue 讨论，不要在本 Issue 内讨论与本 Issue 无关的问题。

**Comment by maxoyed** [comment]
> > > 目前的日志是一个一个 json，一次调用 reggol 一个 json 从存储调用的输出信息
> > 
> > 可以在每个插件的页面单独查看插件的日志
> 
> 不不不，是这样的，日志的 name 不是由 koishi，satori 或者 reggol 决定的，是开发者自己选择合适的 name（可能是插件的 name（指 export 的那个）
> 现有 logger 的数据也没有与插件上下文关联，不好确定那个 name 是哪个插件的 log
> 
> logger 实例与上下文关联我觉得还是有意义的，方便用户阅读日志，也方便开发者提取自己插件错误的日志阅读
> 
> 目前 `ctx.logger` 好像（上次看的时候）好像在 satori 里面，具体和 Koishi 联动可能需要考虑一下，具体我不到，看 shigma 想怎么写

不是，直接在插件里实例化 Logger 类，可以自己起名字啊，你看看文档

**Comment by CyanChanges** [comment]
> > > > 目前的日志是一个一个 json，一次调用 reggol 一个 json 从存储调用的输出信息
> > > 
> > > 
> > > 可以在每个插件的页面单独查看插件的日志
> > 
> > 
> > 不不不，是这样的，日志的 name 不是由 koishi，satori 或者 reggol 决定的，是开发者自己选择合适的 name（可能是插件的 name（指 export 的那个）
> > 现有 logger 的数据也没有与插件上下文关联，不好确定那个 name 是哪个插件的 log
> > logger 实例与上下文关联我觉得还是有意义的，方便用户阅读日志，也方便开发者提取自己插件错误的日志阅读
> > 目前 `ctx.logger` 好像（上次看的时候）好像在 satori 里面，具体和 Koishi 联动可能需要考虑一下，具体我不到，看 shigma 想怎么写
> 
> 不是，直接在插件里实例化 Logger 类，可以自己起名字啊，你看看文档

对啊，名字不是 reggol，koishi 或 satori 决定的啊，开发者自己写的啊

**Comment by CyanChanges** [comment]
> > plugin-logger 前端可以做个过滤 name 和等级的功能，比较简单，也能实现类似于折叠的不显示的功能，不需要改 reggol 和 satori，只对应 name
> 
> 由于已实现根据 `ctx.logger` 过滤，实现此功能已无意义。
> 
> 与此 Issue 无关的功能请求请在相关的 Issue 讨论，不要在本 Issue 内讨论与本 Issue 无关的问题。

没看到，问下哪里调谢谢

**Comment by CyanChanges** [comment]
bs，原本的 feature 就是要过滤插件啊，怎么就都 OT 了啊

**Comment by ilharp** [comment]
![image](https://github.com/koishijs/koishi/assets/20179549/3ea78ffa-16ca-45ee-8803-f6f8319016e6)

从昨天到今天 18:40 为止，本 Issue 主楼的功能请求未进行变更，此功能请求是希望为插件的日志视窗添加折叠功能。

在最近的 1 小时内，有 GitHub 用户创建了 6 条评论，试图将此功能请求曲解为「Koishi 应当实现按插件过滤日志」。而实际上 Koishi 已在 [4.15.3 版本](https://github.com/koishijs/koishi/releases/tag/4.15.3) 实现了此功能并实装。同时，有其他用户向他指出了这一点。

在其评论被设置为 Off-Topic 后，他在一分钟内发布了 2 条新的评论，试图继续曲解 Issue 的原意。

![image](https://github.com/koishijs/koishi/assets/20179549/c192504d-185f-44d3-87e7-62102be6a7cc)

我们认为这已经构成了 Spam 行为，并已经将此行为反馈至 GitHub。此 Issue 将被锁定，但此功能实现与否不会受到此影响。如果有其他问题，请创建新的 Issue。

**Comment by shigma** [comment]
加了滚动条（最高 10 行，超过就会显示）。
