### ISSUE TITLE
Feature: IDE Support

### ISSUE THREAD

**Issue by maxoyed** [koishijs/koishi#1260]
### Describe the problem related to the feature request

得益于 typescript 强大的类型系统和 Koishi 丰富的 cli 工具，目前的插件开发效率已非常可观，但在与 IDE 的集成方面还处于非常早期的阶段，以下特性尚未有 IDE 插件支持：

- Code Snippet: 为指令、中间件等常用结构添加代码块，支持快速创建代码结构
- JSX Code Completion & Hovers: 为 JSX 编写的消息元素提供标签、属性的代码补全、提示，并附带文档链接，支持快速编写消息结构而无需翻看文档

以下特性已有插件支持：
- `package.json` Koishi 特有字段提示：[vscode-koishi-dev](https://github.com/MaikoTan/vscode-koishi-dev)

### Describe the solution you'd like

# Visual Studio Code

VS Code 提供了一整套 API 来实现这些插件，参考官方文档：[Extension API | Visual Studio Code Extension API](https://code.visualstudio.com/api).

- Code Snippet 的实现较为简单，不再赘述
- JSX 消息元素补全、提示或许可以通过 [Programmatic Language Features](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) 或者 [Language Server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) 来实现

# IntelliJ Platform
IntelliJ 体系不是很熟，贴出官方文档：[IntelliJ Platform SDK | IntelliJ Platform Plugin SDK](https://plugins.jetbrains.com/docs/intellij/welcome.html)

# Others
期待讨论补充

### Additional context

以上仅为个人开发过程中产生的需求，欢迎大家讨论补充

**Comment by ilharp** [comment]
支持。

---

> * JSX 消息元素补全、提示或许可以通过 [Programmatic Language Features](https://code.visualstudio.com/api/language-extensions/programmatic-language-features) 或者 [Language Server](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) 来实现

JSX 类型提示可以直接由 TypeScript 类型实现，只是现在还没有做而已。这个不需要 IDE 支持。

**Comment by maxoyed** [comment]
> JSX 类型提示可以直接由 TypeScript 类型实现，只是现在还没有做而已。这个不需要 IDE 支持。

抱歉，JSX 不是很熟，刚刚看了一下文档，确实可以，这样最好了。

**Comment by MaikoTan** [comment]
> 以下特性曾有插件支持，但年久失修了：
> 
> * `package.json` Koishi 特有字段提示：[vscode-koishi-dev](https://github.com/MaikoTan/vscode-koishi-dev)

It is far from "年久失修" but just weren't planning what to be added or not. Since it is still working in progress, clainming it as "年久失修" would make the author uncomfortable.
If you have any thoughts or suggestions, feel free to [open an issue](https://github.com/MaikoTan/vscode-koishi-dev/issues/new) to talk about it.

**Comment by maxoyed** [comment]
> It is far from "年久失修" but just weren't planning what to be added or not. Since it is still working in progress, clainming it as "年久失修" would make the author uncomfortable.
> If you have any thoughts or suggestions, feel free to [open an issue](https://github.com/MaikoTan/vscode-koishi-dev/issues/new) to talk about it.

sorry，是我没有搞清楚状况

**Comment by shigma** [comment]
新版本将支持 JSX 元素补全，你可以尝试一下，并欢迎交流使用体验。

**Comment by MaikoTan** [comment]
The code snippets were added in the extension [Koishi Dev](https://marketplace.visualstudio.com/items?itemName=MaikoTan.koishi-dev) for a while, but there are negatives feedbacks. I am still thinking about how to make it convenient and smooth, if you have any idea, feel free to comment here, or in the [Koishi Forum](https://forum.koishi.xyz/t/topic/6458).

Also the extension has support for `koishi.yml` file validation, which depends on the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension, so you should install it first.
