### ISSUE TITLE
Feature: 指令代为执行

### ISSUE THREAD

**Issue by asasdsaweasd** [koishijs/koishi#1274]
### Describe the problem related to the feature request

当某用户权限不足时，可让有权限的代为执行

### Describe the solution you'd like

增加一个内置组件？
比如：`foo<execute>echo 123</execute>bar`
echo指令需要权限2，但用户权限为1。

**Comment by shigma** [comment]
> 当某用户权限不足时，可让有权限的代为执行

那权限的意义是什么？

**Comment by asasdsaweasd** [comment]
> > 当某用户权限不足时，可让有权限的代为执行
> 
> 那权限的意义是什么？

autoAuthorize设置为0时，指令无法执行

**Comment by shigma** [comment]
那你为啥要设置为 0 呢？设置为 0 就是希望无法指令的啊

**Comment by asasdsaweasd** [comment]
> 那你为啥要设置为 0 呢？设置为 0 就是希望无法执行的啊

不想用户加到数据库中，但希望自写的插件能在可控的范围内执行某些指令。

**Comment by ilharp** [comment]
> autoAuthorize设置为0时，指令无法执行

`authorize` 为 0 的目的是「让指令无法执行」，不是「让用户不被添加到数据库中」。

Koishi 默认会在数据库中添加所有可识别的用户。如果你希望某些用户不被添加到数据库中，可以提出一个「判断指定用户不添加数据库」的功能请求。将用户权限设置为 0 只会让 Koishi 拒绝服务，并不能解决你的问题。

**Comment by asasdsaweasd** [comment]
> > autoAuthorize设置为0时，指令无法执行
> 
> `authorize` 为 0 的目的是「让指令无法执行」，不是「让用户不被添加到数据库中」。
> 
> Koishi 默认会在数据库中添加所有可识别的用户。如果你希望某些用户不被添加到数据库中，可以提出一个「判断指定用户不添加数据库」的功能请求。将用户权限设置为 0 只会让 Koishi 拒绝服务，并不能解决你的问题。

感谢，也是一种解决思路
