### ISSUE TITLE
Feature: 创建项目时根据当前 registry 设置确定市场所使用的 registry

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1287]
### Describe the problem related to the feature request

创建项目时市场默认使用了镜像源，但某些国外网络环境下镜像源比官方源慢。

### Describe the solution you'd like

创建项目时市场 register 设置跟随本地设置

**Comment by ilharp** [comment]
创建项目后，可以直接在控制台中点击「恢复默认配置」恢复到官方镜像，也可直接删除 `koishi.yml` 中配置项。

**Comment by shigma** [comment]
<img width="504" alt="image" src="https://github.com/koishijs/koishi/assets/33423008/4c969e10-25f5-4a96-a9d5-97adc2011976">

模板项目中的 registry 配置不符合同源下载原则，应该删掉。

PS：我们的模板项目中的 [`.yarnrc.yml`](https://github.com/koishijs/boilerplate/blob/master/.yarnrc.yml) 已经声明了 npmmirror 镜像。删掉 market 插件的 registry 配置不会造成任何影响。

**Comment by ilharp** [comment]
1. [`.yarnrc.yml`](https://github.com/koishijs/boilerplate/blob/master/.yarnrc.yml) 中的配置在现时点仅对命令行的 `yarn add` 等操作生效，对「依赖管理」页面无效；
1. 删掉 market 配置的话，yarnrc 配置会对「依赖管理」页面和 `yarn add` 命令行操作均生效；

现在是这样的情况吧。

基于这样的情况，删掉 market 插件的 registry 配置，应当不会发生体验降级，是安全的吧

**Comment by shigma** [comment]
![image](https://github.com/koishijs/koishi/assets/33423008/d2e400d4-ef95-48b1-bcfa-7549ff591276)

删掉配置将会自动从环境获取。对于使用 `yarn start` 启动的 Koishi 内的依赖管理是有效的；其他情况下 Koishi 我没有测试过。

我不知道 Koishi Desktop 是否属于使用 `yarn start` 的范畴。如果属于就是安全的。如果不属于，那依赖管理将无法读取 `.yarnrc.yml`。

**Comment by ilharp** [comment]
属于，是安全的。

**Comment by shigma** [comment]
Fixed in the latest boilerplate.
