### ISSUE TITLE
Feature: command可选禁用option

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1288]
### Describe the problem related to the feature request

有指令 weapon <name> [type]
一个用户的 name 是 -xxxx-, 这个名字因为以 - 开头被识别成了 option, 需要加上引号才能正常识别
如果使用变长参数就无法在 help 中展示后面的参数

### Describe the solution you'd like

希望增加禁用 option 检测的参数, 或添加其他在无 option 情况下直接识别带 - 的 arg 的功能

**Comment by bili-22** [comment]
> 这个我感觉有点 edge 了，加引号确实就可以解决。
> 
> 不过可以做。

主要是用户不知道, 直接写help里就很怪, 更希望能在代码里解决

**Comment by shigma** [comment]
最新版本支持了 `strictOptions`，开启后，任何未被注册为 option 的字符串都视为 argument。
