### ISSUE TITLE
Bug(Schema): `Schema.array()` 中的 `Schema.union()` 只有一项时无法选择

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi#1290]
### Describe the bug

当 Schema.union 只有一项时，无法选择该项。

* 仅在表格模式下的 `Schema.array` 测试得出

### Steps to reproduce

```ts
foo: Schema.array(Schema.object({
	bar: Schema.union(['baz'])
})).role('table')
```

### Expected behavior

能够选中 `baz`

### Screenshots

多个选项，能够选择：

![f7c95aacf2b841c6799904e9d587ee5a](https://github.com/koishijs/koishi/assets/18106422/b84aeba1-ec51-4463-ba09-5cf4973b2f3b)
![c116ad7a4c3d6d0cf1ed2b7e07bb9d31](https://github.com/koishijs/koishi/assets/18106422/a24ad972-5b05-4ba0-8126-70354010ddfb)

单个选项，不能选择：

![image](https://github.com/koishijs/koishi/assets/18106422/669f5488-7915-453f-a8c9-78c25ed50d5d)
![fd90852d480b51a0b3d27fac06f1b743](https://github.com/koishijs/koishi/assets/18106422/74152446-6cdf-4332-aa60-80b1641b1b0c)

### Versions

System:
    OS: Linux 5.10 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) x64 Common KVM processor

Binaries:
    Node: 19.3.0
    Yarn: 1.22.19

Koishi:
    Core: 4.15.4
    Console: 5.18.4

**Comment by shigma** [comment]
最新版本未复现此问题。

![460a93ef1985b2ac724a4c82243b0cae](https://github.com/koishijs/koishi/assets/33423008/537c3118-dfdc-4463-b434-0b49bd710f02)

![09557726c7ef335779decfa157c54ed3](https://github.com/koishijs/koishi/assets/33423008/8231a0e4-4388-4790-ae0d-0f893d695097)

**Comment by Lipraty** [comment]
有可能是本地环境问题，先 close 了
