### ISSUE TITLE
Bug: koishi指令重复输出信息

### ISSUE THREAD

**Issue by Coin0804** [koishijs/koishi#1291]
### Describe the bug

koishi -h指令重复输出信息

### Steps to reproduce

在包含koishi本体的项目运行“yarn koishi -h”

### Expected behavior

输出帮助信息

### Screenshots

![image](https://github.com/koishijs/koishi/assets/45031391/8b05e08c-42e9-446a-985a-d9ca2b7238da)

### Versions

- OS: any
- Platform: any
- Node version: any
- Koishi version: ^4.15.6（更早版本应该也有）

**Comment by shigma** [comment]
感谢反馈，现已修复，下个版本实装。
