### ISSUE TITLE
Feature: bind 插件验证码进数据库存储

### ISSUE THREAD

**Issue by Simplifer** [koishijs/koishi#1296]
### Describe the problem related to the feature request

多实例情况下希望可以用 bind 插件绑定用户，但是发现 bind 插件源码里的验证码 tokens 是临时存于内存中的，故而一个实例的验证码在另一个实例那边不生效。

### Describe the solution you'd like

新建一张验证码表或者 binding 表新增 token 列用于存储验证码信息。

### Additional context

可能是我使用方式不对，但是目前我的需求确实需要多实例且共用一个库。

**Comment by ilharp** [comment]
大多数情况下，多实例共用数据库都是由于规划不当而发生的。请问你现在遇到了什么情况，需要用到多实例共用数据库呢？

相比 bind 插件，我觉得更应该解决多实例的问题。如果你持续使用多实例共用数据库，那么之后你将需要给每个未将状态存放于数据库中的插件提出一个 Feature Request，这将给你和开发者双方都造成很大的负担。

**Comment by Simplifer** [comment]
感谢回复。因为平台之间有差异，例如转发消息和 md 消息等，我暂时是分实例开发有对应平台特殊功能的插件，但是也有共有插件需要依赖用户信息，虽然区分了不同平台，但是我的用户始终是同一群人，所以在 bind 插件这我需要跨实例绑定。

所以其实我更应该考虑如何根据不同平台加载不同插件是吗？

**Comment by ilharp** [comment]
是的，这件事可以使用 [过滤器](https://koishi.chat/zh-CN/manual/usage/customize.html#%E8%BF%87%E6%BB%A4%E5%99%A8) 功能轻松完成配置。修改此项配置时甚至无需重启 Koishi。

![image](https://github.com/koishijs/koishi/assets/20179549/e550edb5-6275-412f-8091-ffb3a4f946d4)

**目前理论上没有任何功能需要用到多实例。** 多实例功能主要用于方便完全不同场景下的 Koishi 部署，而非解决单个实例内的问题。

**Comment by shigma** [comment]
标题「bind 插件验证码进数据库存储」跟多实例无关，我认为本身是有意义的。

不过如果作者的原始需求得到解决并关闭了 issue，那就暂时不考虑了。
