### ISSUE TITLE
Bug: 使用server-satori转发adapter-qq的数据时，message缺少content。

### ISSUE THREAD

**Issue by kumoSleeping** [koishijs/koishi#1298]
### Describe the bug

使用server-satori转发adapter-qq的数据时，message缺少content，多出elements。

### Steps to reproduce

使用server-satori转发adapter-qq的数据，观察data。

### Expected behavior

使用server-satori转发adapter-qq的数据时，message存在预期的content。

### Versions

- OS: Windows 10 10.0.20348
- Platform: qq
- Node version: 18.16.0
- Koishi version: 4.15.5

**Comment by CyanChanges** [comment]
其他适配器会出现这种情况吗

**Comment by kumoSleeping** [comment]
目前我使用的 kook onebot red 均没有此情况

**Comment by shigma** [comment]
这个是不是现在好了？

**Comment by kumoSleeping** [comment]
> 这个是不是现在好了？

问题依然存在

Core: 4.17.3
Console: 5.28.2
Server-satori: 2.4.2
Adapter-qq: 4.6.0

收到的包的消息部分：
```
 'message': {'id': 'ROBOT1.0_ek4KIlrI1QE7hstyiOu3OeNcjBmOQc8gA-8gko0IEY-oA1bN7jVk7XX9l3S5PK3.zuFcrWkjMtCSN4LL3qqA6A!!', 'timestamp': None, 'elements': [{'type': 'at', 'attrs': {'id': '31558246850018011'}, 'children': []}, {'type': 'text', 'attrs': {'content': ' /查曲 '}, 'children': []}], 
 ```

**Comment by shigma** [comment]
已修复。
