### ISSUE TITLE
Feature: `schemastery` 添加 color 支持

### ISSUE THREAD

**Issue by Hieuzest** [koishijs/koishi#1299]
### Describe the problem related to the feature request

用于在控制台设置中允许用户自定义与颜色相关的内容，比如可定制的主题

### Describe the solution you'd like

Schema.string().role('color')
显示一个Color Picker

**Comment by Seidko** [comment]
https://koishi.chat/zh-CN/schema/basic/string.html
不是有吗？

**Comment by Hieuzest** [comment]
怎会如此！
