### ISSUE TITLE
Bug: adapter-lark的飞书适配器，在群组中时接收消息报错

### ISSUE THREAD

**Issue by silvermooooon** [koishijs/koishi#1305]
### Describe the bug

![image](https://github.com/koishijs/koishi/assets/119033606/733f99a2-64c7-4818-8481-d203ba91b10f)
飞书中创建群组并邀请机器人进入，在群组中发送消息会收到如下报错：
![image](https://github.com/koishijs/koishi/assets/119033606/3432cd78-ff75-48a7-9f95-10eea45128f9)
bot的权限以及事件订阅如下：
![image](https://github.com/koishijs/koishi/assets/119033606/62abfea6-3c57-4029-bc92-9b97e4a2bfac)
![image](https://github.com/koishijs/koishi/assets/119033606/08f622e9-0533-4a32-b2fd-fb43151129e8)

### Steps to reproduce

创建群组并触发指令

### Expected behavior

正常回复

### Versions

- OS: window11
- Platform: feishu
- Node version: v20.9.0
- Koishi version: 4.16.0
- adapter-lark version:3.2.0

**Comment by MaikoTan** [comment]
It looks like the problem about sqlite (or sqlite driver) rather than the lark adapter, will investigate it later.

**Comment by shigma** [comment]
感谢反馈。

更新 sqlite 插件或 analytics 插件到最新版都可以解决此问题。
