### ISSUE TITLE
Feature: Schema的table列添加对hidden和disabled的支持

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1306]
### Describe the problem related to the feature request

希望使用其它列数据生成某一列的数据, 但目前table模式使用hidden和disabled无效
![image](https://github.com/koishijs/koishi/assets/81406789/55915217-711b-424c-9a48-8e0609653b57)

### Describe the solution you'd like

为table添加hidden或disabled支持

**Comment by shigma** [comment]
合理。会做。
