### ISSUE TITLE
Feature: Schema.number()添加显示成正常文本框的role

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1307]
### Describe the problem related to the feature request

需要输入数字uid, uid不需要加减号选择, 也不需要滑条, 但需要限制仅能输入数字而不允许其他字符

### Describe the solution you'd like

为Schema.number()添加一个显示成正常文本框的role

### Describe alternatives you've considered

为Schema.string()添加只能输入数字的role

**Comment by shigma** [comment]
合理。考虑加个 `.role('string')` 或者 `.role('input')`。有没有其他建议？

**Comment by shigma** [comment]
刚刚又考虑了一下，感觉直接用 `Schema.string()` 更合理。

相比直接使用 number，用 string 具备更多额外的好处，例如可以通过 max / min / pattern 来限制数据的长度，但是用 number 你如果要限制长度只能 min 10000000 max 99999999，感觉很奇怪不是吗？

**Comment by bili-22** [comment]
> 刚刚又考虑了一下，感觉直接用 `Schema.string()` 更合理。
> 
> 相比直接使用 number，用 string 具备更多额外的好处，例如可以通过 max / min / pattern 来限制数据的长度，但是用 number 你如果要限制长度只能 min 10000000 max 99999999，感觉很奇怪不是吗？

同意
