### ISSUE TITLE
Feature: session.quote提供的信息不足，无法判断回复的消息的发送人是谁，

### ISSUE THREAD

**Issue by HunterShenSmzh** [koishijs/koishi#1330]
### Describe the problem related to the feature request

在尝试使用中间件写回复触发机器人功能的时候，发现无论回复的人是谁，都会直接触发机器人。

例如：
```
        // 引用回复
        if (session.quote) {
            let msg = String(session.content);
            console.log(session.quote)
            await session.send(`test`);
            return;
        }
```
![80b89ecc872445f5452a3e6e89055bfd](https://github.com/koishijs/koishi/assets/129963508/bb2f94b5-7e4f-4134-b4b0-b4106cd27426)

即使在回复自己的情况下也会触发机器人的回复。
所以要判断一下 quote 的是谁。
session.quote只提供了：
`content:'' id: ''`
所以无法判断。

### Describe the solution you'd like

给quote添加一些关键信息来帮助判断

### Describe alternatives you've considered

因为提供了一个消息id，我考虑过通过插件写一个匹配库，记录所有插件发送的消息id，然后匹配。但太臃肿了，所以不想这么做。

**Comment by shigma** [comment]
先检查是否存在 session.quote.user.id，如果没有可以使用 bot.getMessage(session.quote.id) 获取。

我没理解错的话应该总是存在的。

**Comment by HunterShenSmzh** [comment]
> 先检查是否存在 session.quote.user.id，如果没有可以使用 bot.getMessage(session.quote.id) 获取。
> 
> 我没理解错的话应该总是存在的。

感谢大佬提示，我已经实现了检测。
session.quote.user.id是不存在的，但是可以用过bot.getMessage来获取用户id，这里是我的具体代码：
```
        if (session.quote) {
            let msg = String(session.content);
            let reverse = session.bot.getMessage(session.channelId, session.quote.id);
            let quoteID = (await reverse).user.userId;
            if (session.selfId === quoteID) {
                await session.send(`test`);
                return;
            }
        }
```
再次感谢。
