### ISSUE TITLE
Bug: 消息元素 `quote` 失效

### ISSUE THREAD

**Issue by ArgonarioD** [koishijs/koishi#1331]
### Describe the bug

我尝试了以下几种写法：

1. 
```tsx
await session.send(
  <>
    <quote id={session.messageId} />
    {content}
  </>
)
```
2.
```ts
await session.send(h('message', 
  h('quote', {id: session.messageId}),
  content
))
```
3.
```ts
await session.send((
  String(h('quote', { id: session.messageId })) +
  content
))
```
其中 `content` 是 string 类型的对象。
无论是在沙盒中还是对接 koishi-adapter-onebot 时发送出来的消息都只有 content，没有 quote。

### Steps to reproduce

1. 创建 koishi 项目
2. 用中间件在 `apply` 函数中编写上述任意一种写法
3. 在沙盒中触发

### Expected behavior

`quote` 类型消息元素应该能够正常显示在沙盒和其它适配器的客户端中。

### Versions

- OS: Windows 11 专业版 10.0.22621
- Platform: 沙盒 和 Onebot
- Node version: 18.16.0
- Koishi version: 4.16.4
- @koishijs/plugin-sandbox version: 3.2.4
- koishi-plugin-adapter-onebot version: 6.4.0

**Comment by idanran** [comment]
该问题在 Lagrange (OneBot 实现端) 上**已复现**。在查阅 Lagrange 的 README 后发现，**Lagrange 尚未支持发送该类型的消息元素**。如果你在使用 Lagrange 的话，可以尝试请求 Lagrange 支持发送 OneBot 11 的 Reply 元素。

**Comment by ArgonarioD** [comment]
> 该问题在 Lagrange (OneBot 实现端) 上**已复现**。 在查阅 Lagrange 的 README 后发现，**Lagrange 尚未支持发送该类型的消息段**。 **如果你在使用 Lagrange 的话，那么可以确认该问题与 Koishi 无关**，你可以尝试请求 Lagrange 支持发送 OneBot 11 的 Reply 消息段。

好的，我确实是在使用 Lagrange。抱歉没有贴出对接的 Onebot 实现端（）
