### ISSUE TITLE
Feature: Database Model 添加更多数据类型支持

### ISSUE THREAD

**Issue by modcrafts** [koishijs/koishi#1333]
### Describe the problem related to the feature request

想要在数据库中存储BIGINT类型的数字
原有的 integer length 无法超过11, 导致现有数据类型无法存储更大的数字

### Describe the solution you'd like

在database.extend方法中增加更多的数据类型支持,例如 bigint 等
```typescript
ctx.database.extend('a', {
  long_number: 'bigint',
})
```

**Comment by shigma** [comment]
现已支持。
