### ISSUE TITLE
Feature: 请求muteGuildMember增加返回值

### ISSUE THREAD

**Issue by asasdsaweasd** [koishijs/koishi#1341]
### Describe the problem related to the feature request

现阶段无法知道是否禁言成功或者失败
会出现禁言失败但send()了成功的文本给用户

### Describe the solution you'd like

返回值: Promise<void>改成返回状态

**Comment by shigma** [comment]
通常情况下，如果禁言失败，此 API 调用应该会抛出错误，因此不需要返回值。

如果你使用的适配器没有抛出错误，你需要

- 如果是官方适配器：指出哪一个适配器与预期行为不符；
- 如果是社区适配器：前往对应的适配器仓库提交 issue。
