### ISSUE TITLE
Bug: 文档搜索失效

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#1343]
### Describe the bug

文档搜索失效

### Steps to reproduce

- 打开koishi.chat

### Expected behavior

可以搜索文档

### Screenshots

<img width="905" alt="image" src="https://github.com/koishijs/koishi/assets/10007589/72dc3304-9831-42aa-b100-8b25035a9111">
<img width="1019" alt="image" src="https://github.com/koishijs/koishi/assets/10007589/1e2badc4-d236-463d-937a-646623ee81ad">

### Versions

- OS:  macOS
- Platform:  not relevant 
- Node version:  not relevant 
- Koishi version:  not relevant

**Comment by shigma** [comment]
已修复。
