### ISSUE TITLE
Feature: 更改server启动后的logger

### ISSUE THREAD

**Issue by Twiyin0** [koishijs/koishi#1344]
### Describe the problem related to the feature request

修改okishi.yml中server项目的host为0.0.0.0后logger依旧提示启用在http://127.0.0.1:5140
![image](https://github.com/koishijs/koishi/assets/87588281/aebd667a-446e-4109-ac21-354c47a89949)
![image](https://github.com/koishijs/koishi/assets/87588281/caead144-e65e-4cea-b3f5-fdab4880465f)

### Describe the solution you'd like

将logger的提示修正即可

**Comment by shigma** [comment]
虽然跟这个问题无关但是我好奇为啥 127.0.0.1 颜色不一样。

**Comment by CyanChanges** [comment]
我也遇到这个问题，Koishi 开不出去（x

**Comment by CyanChanges** [comment]
> 虽然跟这个问题无关但是我好奇为啥 127.0.0.1 颜色不一样。

可能是终端特性？（

**Comment by Twiyin0** [comment]
> 虽然跟这个问题无关但是我好奇为啥 127.0.0.1 颜色不一样。

Termius特有的（
