### ISSUE TITLE
Bug: 小火煎后控制台空白

### ISSUE THREAD

**Issue by jackz0722** [koishijs/koishi#1356]
### Describe the bug

拉取新的项目模板 yarn dev 启动项目 控制台空白   yarn start启动项目 控制台正常

### Steps to reproduce

拉取新的项目模板 yarn dev 启动项目

### Expected behavior

希望 yarn dev 开发环境正常使用控制面板

### Screenshots

![46e5758c72c8403f80811a5523afc950](https://github.com/koishijs/koishi/assets/84524966/948a7c6f-5186-4443-8f6f-9c301663baa7)
yarn dev 启动
![image](https://github.com/koishijs/koishi/assets/84524966/0ba3568b-9d54-4040-8329-516495cfc04d)
yarn start 启动
![image](https://github.com/koishijs/koishi/assets/84524966/c1762ef8-b783-4c42-95c6-0f822881b171)

### Versions

System:
    OS: Linux 5.14 CentOS Stream 9
    CPU: (2) x64 Intel(R) Celeron(R) N5105 @ 2.00GHz

Binaries:
    Node: 20.11.0
    Yarn: 4.0.1

Koishi:
    Core: 4.16.7
    Console: 5.27.2

**Comment by ilharp** [comment]
Duplicate of https://github.com/koishijs/webui/issues/305

请尝试使用最新版本的 bp 创建项目

**Comment by shigma** [comment]
已修复。
