### ISSUE TITLE
Bug: QQ适配器指令前缀不生效

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1364]
### Describe the bug

QQ机器人所有消息都带at，at的优先级高于prefix，造成prefix不生效

### Steps to reproduce

使用QQ适配器并添加prefix，不使用prefix依然可以调用指令

### Expected behavior

希望提供一种使用为QQ适配器套用prefix的方式

### Versions

- Platform: QQ
- Node version: 20
- Koishi version: 4.16

**Comment by Hieuzest** [comment]
增加一个禁用appel的全局配置项？

**Comment by ilharp** [comment]
> 使用QQ适配器并添加prefix，不使用prefix依然可以调用指令

什么情况下希望不使用 prefix 就不响应指令？做 QQ 机器人肯定是希望能响应指令的场景越多越好吧。

**Comment by shigma** [comment]
> 增加一个禁用appel的全局配置项？

它这个场景不仅需要禁用 appel，还得禁用私聊的无前缀。
