### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by jingming295** [koishijs/koishi#1365]
### Describe the bug

插件名字带有@xxx的情况下，不能热加载

例子：@aaa/koishi-plugin-test

如果去掉 @xxx 的话，然后yarn一下，然后yarn dev，去插件设置加载的话，又能热加载了

### Steps to reproduce

yarn setup @aaa/koishi-plugin-test
然后yarn dev
然后加载这个插件，然后去index.ts ctrl + c

### Expected behavior

希望能够热加载，因为我这里有一些插件的名字是带有@xxx这种格式的

### Screenshots

![image](https://github.com/koishijs/koishi/assets/48265334/90a854f0-e424-40d8-9a10-2fa3d8df7c2d)
然后在index.ts 按 ctrl + s，并没有热加载
![image](https://github.com/koishijs/koishi/assets/48265334/d2671eec-3af1-4deb-a3e2-17b85e458a66)

### Versions

- OS: Windows 11
- Platform: 沙盒
- Node version: v20.11.0
- Koishi version: 4.17.0-beta.2

**Comment by ilharp** [comment]
你阅读 [官方文档](https://koishi.chat/zh-CN/guide/develop/workspace.html#scoped) 配置 scoped 了吗

**Comment by jingming295** [comment]
原来如此，现在没问题了

**Comment by shigma** [comment]
原来是这个原因，我还没反应过来
