### ISSUE TITLE
Bug: yarn pub 无法填写otp

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1372]
### Describe the bug

yarn pub直接成功, 需要--debug才能填写otp
![image](https://github.com/koishijs/koishi/assets/81406789/ea16e675-d804-488b-9913-b67905527343)

### Steps to reproduce

使用开启二部验证的npm账号执行yarn pub

### Expected behavior

正确请求otp

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by Lipraty** [comment]
你可以：

```sh
yarn pub your-pkg --otp=******
```

**Comment by CyanChanges** [comment]
> 你可以：
> 
> ```shell
> yarn pub your-pkg --otp=******
> ```

这个 your-pkg 可以是 workspace 的名字，甚至可以稍微简写一下

**Comment by CyanChanges** [comment]
emm, 应该可以 close 了吧, 
https://github.com/cordiverse/yakumo/blob/dc2c94f5359f7f2d9abd3dc68fbecf852941281a/packages/core/src/plugins/publish.ts#L45
这个提示应该是 Yarn 的 prompt, 不大好整?
如果加 silent 参数会不会就不用把 stdio 忽略了?
但是只有你开 debug 他才会一个一个运行, 而不是一起运行,
如果不加 debug 会不会出现 N 个要你 otp 的 prompt? (
