### ISSUE TITLE
Bug: Schema相同的属性未正确合并

### ISSUE THREAD

**Issue by bili-22** [koishijs/koishi#1373]
### Describe the bug

相同类型组合
![image](https://github.com/koishijs/koishi/assets/81406789/de414f6c-e1f8-4cce-9265-d8401ee5e8bb)
![image](https://github.com/koishijs/koishi/assets/81406789/f33b0c8f-f78a-41b4-be17-87b07831138a)

不同的类型组合
![image](https://github.com/koishijs/koishi/assets/81406789/93d8a7c2-1b6f-42fa-bdee-ce7dc82d5083)
![image](https://github.com/koishijs/koishi/assets/81406789/e6d20822-3f48-4c45-8d72-449b2013c53f)

### Steps to reproduce

代码同上

### Expected behavior

相同类型组合时只保留一个输入框, 冲突的类型组合时报错

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
这个行为是预期的。

1. 在一些情况下我们是需要用到「intersect 中多个对象存在相同属性」这一特性的，可以参考文档中关于配置联动的示例。
2. 更一般的情况下，我们也无法直接判断两个相同属性之间的包含关系，不应该做贸然合并（尽管对于显而易见的冲突情况我们可以报错，但这就是另一个问题了，并且实际场景中也不会有人这么用）。

对于你的需求，可以这样实现：

```ts
interface SharedConfig {
  foo: string
}

const SharedConfig = Schema.object({
  foo: Schema.string(),
})

interface Config1 extends SharedConfig {
  bar: boolean
}

const Config1 = Schema.object({
  bar: Schema.boolean(),
}) // 不写 SharedConfig 相关属性，或者 hidden

interface Config2 extends SharedConfig {
  baz: number
}

const Config2 = Schema.object({
  baz: Schema.number(),
}) // 不写 SharedConfig 相关属性，或者 hidden

interface FinalConfig extends Config1, Config2 {}

const FinalConfig = Schema.intersect([
  SharedConfig,
  Config1,
  Config2,
])
```
