### ISSUE TITLE
Bug: 无法在局域网访问网页面板

### ISSUE THREAD

**Issue by Zhou-Shilin** [koishijs/koishi#1375]
### Describe the bug

本机使用`127.0.0.1:5140`可正常访问koishi网页面板，但是在局域网内使用`192.168.0.135:5140`无法访问。
局域网内可ping通5140，但是telnet显示connect refused
防火墙已放行端口

### Steps to reproduce

1. 使用“创建模版项目”的方法安装koishi到一台ubuntu server服务器上；
2. 使用`ufw allow 5140`放行端口；
3. 尝试在局域网内其他机器上访问，无法访问；
4. 在ubuntu server上通过`apt install ubuntu-desktop`加装图形化界面，再安装xrdp，控端安装rdp client连接服务器，使用图形化界面中的浏览器访问，可以访问到。（总之通过本机访问确实可用，但是过程非常麻烦，在局域网内其他机器上访问还是很必要的需求）

### Expected behavior

在局域网内其他机器上也应该能够访问koishi网页面板。

### Versions

- OS: Ubuntu Server
- Platform: /
- Node version: v14.19.1
- Koishi version: 4.17.1

**Comment by BakaFT** [comment]
🤔
提供的信息不足以证明你把服务的监听地址更改为了0.0.0.0/::

检查server插件的host配置项

**Comment by shigma** [comment]
请看文档：

https://koishi.chat/zh-CN/manual/recipe/server.html

**Comment by Zhou-Shilin** [comment]
感谢回复，已解决
