### ISSUE TITLE
Bug: 在使用指令管理 改变一些层级后，指令管理选项消失

### ISSUE THREAD

**Issue by 502milk** [koishijs/koishi#1385]
### Describe the bug

新建了一个命令，并把一些子命令放在层级下，重载了koishi后，指令管理选项消失

### Steps to reproduce

(我无复现现第二次

### Expected behavior

无

### Screenshots

![image](https://github.com/koishijs/koishi/assets/49502047/8f00cd72-f28a-4b06-bed1-c44ad1fb4c82)
![image](https://github.com/koishijs/koishi/assets/49502047/f9b2ebd9-e46f-4e83-bb10-be5a6ab431b6)

### Versions

- OS: Win11
- Node version: 
- Koishi version: 4.17.3

**Comment by shigma** [comment]
应该是旧版 bug，升级就好了。

**Comment by 502milk** [comment]
> 应该是旧版 bug，升级就好了。

试过升级和降级重启后无效
直接卸载了，重装插件解决（已经没事再备份了）
