### ISSUE TITLE
云服务器如何公网连接控制台

### ISSUE THREAD

**Issue by NFS688** [koishijs/koishi#1391]
服务器无桌面环境，无法使用localhost连接到控制台再开启公网访问，配置文件找不到相关设置
![image](https://github.com/koishijs/koishi/assets/140144693/8577c89e-527b-4721-9715-cafb232eeb2e)
![image](https://github.com/koishijs/koishi/assets/140144693/a05f81bf-bfb3-40ca-b7b5-b73e80a17a25)

**Comment by NFS688** [comment]
查看docker的配置文件之后解决了，不过奇怪的是docker部署无法公网访问，使用项目模板部署能正常访问
服务器是nat挂机宝
![image](https://github.com/koishijs/koishi/assets/140144693/bd7c3738-e6ab-44ca-98c9-1c12a88a5c52)
以上是端口转发规则
![image](https://github.com/koishijs/koishi/assets/140144693/8d83d931-1ac8-4002-93b5-e52c6971aefc)
![image](https://github.com/koishijs/koishi/assets/140144693/ec687a85-976b-4775-a5d1-485f24e6c941)
docker部署无法正常访问
![image](https://github.com/koishijs/koishi/assets/140144693/a8bc1f33-10c5-46cc-ac3a-0cc6e1af44fa)
![image](https://github.com/koishijs/koishi/assets/140144693/222b6488-779e-4777-872e-96a621ecc6c6)
项目模板可以正常访问

**Comment by shigma** [comment]
文档稍微有一点过时，现在的 host 和 port 要写在 plugins 下面的 server 里。你可以检查一下自己的配置文件。

**Comment by HYLZ-2019** [comment]
> 文档稍微有一点过时，现在的 host 和 port 要写在 plugins 下面的 server 里。你可以检查一下自己的配置文件。

您好，请问是应该这样写吗？
```
start:
  - default
plugins:
  server:
    host: 0.0.0.0
    port: 5140
```
我这样改完还是不能公网暴露（服务器已经设置了全部端口公网放行）。我安装的是Linux .zip版本，版本是Koishi Desktop v1.1.3，本地能访问控制台。

**Comment by ilharp** [comment]
> > 文档稍微有一点过时，现在的 host 和 port 要写在 plugins 下面的 server 里。你可以检查一下自己的配置文件。
> 
> 您好，请问是应该这样写吗？
> 
> ```
> start:
>   - default
> plugins:
>   server:
>     host: 0.0.0.0
>     port: 5140
> ```
> 
> 我这样改完还是不能公网暴露（服务器已经设置了全部端口公网放行）。我安装的是Linux .zip版本，版本是Koishi Desktop v1.1.3，本地能访问控制台。

你重启 Koishi 了吗？使用 `./koi restart default` 重启。

**Comment by HYLZ-2019** [comment]
> > > 文档稍微有一点过时，现在的 host 和 port 要写在 plugins 下面的 server 里。你可以检查一下自己的配置文件。
> > 
> > 
> > 您好，请问是应该这样写吗？
> > ```
> > start:
> >   - default
> > plugins:
> >   server:
> >     host: 0.0.0.0
> >     port: 5140
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我这样改完还是不能公网暴露（服务器已经设置了全部端口公网放行）。我安装的是Linux .zip版本，版本是Koishi Desktop v1.1.3，本地能访问控制台。
> 
> 你重启 Koishi 了吗？使用 `./koi restart default` 重启。

我重启之后还是不行。

**Comment by SPFA-newbie** [comment]
> > > > 文档稍微有一点过时，现在的 host 和 port 要写在 plugins 下面的 server 里。你可以检查一下自己的配置文件。
> > > 
> > > 
> > > 您好，请问是应该这样写吗？
> > > ```
> > > start:
> > >   - default
> > > plugins:
> > >   server:
> > >     host: 0.0.0.0
> > >     port: 5140
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我这样改完还是不能公网暴露（服务器已经设置了全部端口公网放行）。我安装的是Linux .zip版本，版本是Koishi Desktop v1.1.3，本地能访问控制台。
> > 
> > 
> > 你重启 Koishi 了吗？使用 `./koi restart default` 重启。
> 
> 我重启之后还是不行。

目前似乎不支持直接访问，用nginx映射一下端口就行了
