### ISSUE TITLE
Feature: 指令参数类型增加非负整数

### ISSUE THREAD

**Issue by idranme** [koishijs/koishi#1398]
### Describe the problem related to the feature request

仅允许参数的值为非负整数

### Describe the solution you'd like

指令参数类型增加非负整数

**Comment by DGCK81LNN** [comment]
`natural`

https://github.com/koishijs/koishi/blob/d985a519741f3a46fbd0919f32dffcc3a75e74ae/packages/core/src/command/index.ts#L187-L191

**Comment by idranme** [comment]
> `natural`
> 
> https://github.com/koishijs/koishi/blob/d985a519741f3a46fbd0919f32dffcc3a75e74ae/packages/core/src/command/index.ts#L187-L191

https://koishi.chat/zh-CN/guide/basic/command.html#argument-type
文档没有提及
