### ISSUE TITLE
关于指令系统代码的一个建议和疑问

### ISSUE THREAD

**Issue by slgluo** [koishijs/koishi#14]
**Is your feature request related to a problem? Please describe.**
我发现，command是通过context进行构造，也就是说我需要获得context之后再声明这个command。比如我的入口是index.js，这样的话是不是所有command的逻辑和index.js的逻辑都写在一起了？

**Describe the solution you'd like**
能不能给context增加addCommand()类似的方法，把command的声明和执行的逻辑从index.js中拆分出去。这样我就可以创建一个command的文件夹，然后再把这些command导入index.js，再addCommand()。

或者在当前版本，我如何实现这样的目的？或者有没有更好的方法？

**Comment by Shigma** [comment]
插件系统可以解决你的问题。

```js
// pluginA.js
module.exports = (ctx) => {
  ctx.command('cmd1')
}

// pluginB.js
module.exports = (ctx) => {
  ctx.command('cmd2')
}

// index.js
const { App } = require('koishi')
const pluginA = require('./pluginA')
const pluginB = require('./pluginB')

const app = new App(config)
app.plugin(pluginA) // 在所有上下文注册指令 1
app.group(123).plugin(pluginB) // 在群 123 中注册指令 2
```

**Comment by slgluo** [comment]
> 插件系统可以解决你的问题。
> 
> ```js
> // command/a.js
> module.exports = (ctx) => {
>   ctx.command('cmd1')
> }
> 
> // command/b.js
> module.exports = (ctx) => {
>   ctx.command('cmd2')
> }
> 
> // index.js
> const { App } = require('koishi')
> const pluginA = require('./command/a')
> const pluginB = require('./command/b')
> 
> const app = new App(config)
> app.plugin(pluginA) // 在所有上下文注册指令 1
> app.group(123).plugin(pluginB) // 在群 123 中注册指令 2
> ```
> 
> 顺便，现在已经有 `ctx.command()` 了啊，为啥你还要一个 `ctx.addCommand()`……

第一，你的例子我理解了，我需要使用插件作为桥梁是吧。
第二，最后的问题，因为`ctx.command()`之后还跟着`option()`，`action()`。其实我就是想在`context`外面先构造好`command`，而不是`context`的一个一个方法的进行构造，说白了就是复用`command`。我的理解是，command是比plugin更小颗粒度的东西，context可由若干plugin组合，plugin也可由若干command组合，plugin可组合复用，那command是不是也可复用更好呢。
也许我理解有误，可能我还需要再认真读你的文档

**Comment by Shigma** [comment]
@slgluo 我这样写不能复用吗……

**Comment by slgluo** [comment]
> @slgluo 我这样写不能复用吗……

额，我的表达有问题，可以复用。我只是更喜欢类似plugin这样的方式进行定义，你已经解决我的问题了，感谢大佬！

**Comment by Shigma** [comment]
好吧 (╯▽╰)

其实我到现在也不清楚你要什么样的接口……

**Comment by slgluo** [comment]
> 好吧 (╯▽╰)
> 
> 其实我到现在也不清楚你要什么样的接口……

可能我描述的也有点乱。举个例子：
比如我pluginA和pluginB同时都使用了一个command，我是不是得在pluginA和pluginB写相同的代码，command的name，option，action都一样
```js
// pluginA.js
module.exports = (ctx) => {
    ctx.command('my-command')
        .option('-a, --alpha')
        .option('-b, --beta [beta]')
        .option('-c, --gamma <gamma>')
        .action(...)
}

// pluginB.js
module.exports = (ctx) => {
    ctx.command('my-command')
        .option('-a, --alpha')
        .option('-b, --beta [beta]')
        .option('-c, --gamma <gamma>')
        .action(...)
}
```

那我就在想，是不是可以有那么一种方式，先将command定义好，包括name，option，action等等，然后再使用一个API就可以将它配置到plugin里，或者context里，如下：
```js
// pluginA.js
const myCommand = require('./command/MyCommand')
module.exports = (ctx) => {
    ctx.command(myCommand )
    // 或者其他的方式，将myCommand 使用起来
   ...
}

// pluginB.js
const myCommand = require('./command/MyCommand')
module.exports = (ctx) => {
    ctx.command(myCommand )
    // 或者其他的api，将myCommand 使用起来
   ...
}

// index.js
const myCommand = require('./command/MyCommand')
const app = new App(config)
app.command(myCommand )
// 或者其他的api，将myCommand 使用起来
```

**Comment by Shigma** [comment]
@slgluo 这样你可以定义一个 pluginC：

```js
// pluginC.js
module.exports = (ctx) => {
    ctx.command('my-command')
        .option('-a, --alpha')
        .option('-b, --beta [beta]')
        .option('-c, --gamma <gamma>')
        .action(...)
}

// pluginA.js
module.exports = (ctx) => {
    ctx.plugin(pluginC)
    // do other things
}

// pluginB.js
module.exports = (ctx) => {
    ctx.plugin(pluginC)
    // do other things
}
```

**Comment by slgluo** [comment]
> @slgluo 这样你可以定义一个 pluginC：
> 
> ```js
> // pluginC.js
> module.exports = (ctx) => {
>     ctx.command('my-command')
>         .option('-a, --alpha')
>         .option('-b, --beta [beta]')
>         .option('-c, --gamma <gamma>')
>         .action(...)
> }
> 
> // pluginA.js
> module.exports = (ctx) => {
>     ctx.plugin(pluginC)
>     // do other things
> }
> 
> // pluginB.js
> module.exports = (ctx) => {
>     ctx.plugin(pluginC)
>     // do other things
> }
> ```

OK，明白了，感谢大佬解答，再给你一颗星(￣▽￣)~*
