### ISSUE TITLE
Bug: middleware处理时不应武断selfId === userId时返回

### ISSUE THREAD

**Issue by garveen** [koishijs/koishi#1403]
### Describe the bug

在别的客户端发送消息时，该消息无法被koishi插件处理，这是不应该的

### Steps to reproduce

https://github.com/koishijs/koishi/blob/e496ddb884fddd3d7194ac28fc28b1fdc375b6e3/packages/core/src/middleware.ts#L238

### Expected behavior

这个判断删了，或者加个开关

### Versions

平台无关

**Comment by ilharp** [comment]
人机一体会造成严重的递归问题，Koishi v3 时代有不少使用者因为此问题导致机器人无限发送消息并最终被平台限流。Koishi 目前暂不支持人机一体。

**Comment by garveen** [comment]
问题不是人机一体，而是同一个账号在别的客户端发送的信息无法被koishi处理。即使会产生递归问题，加一个可选择开关也比直接return强，现在的实现导致一些功能从根本上无法实现。

**Comment by shigma** [comment]
> 现在的实现导致一些功能从根本上无法实现

可以说说你的需求。如果合理的话可以加开关。

**Comment by garveen** [comment]
> 可以说说你的需求。如果合理的话可以加开关。

需要做消息日志，包括机器人发送的消息也需要存起来，并且日志和实际业务不在同一台机器，不使用同一套代码

**Comment by shigma** [comment]
那你应当使用 message 事件而非 middleware。

middleware 会被截断，就算不考虑是否是自身消息也不应该使用。
