### ISSUE TITLE
Bug: 插件市场新添加的插件没有在插件配置中显示

### ISSUE THREAD

**Issue by TszcWhut** [koishijs/koishi#1406]
### Describe the bug

插件市场新添加的插件没有在插件配置中显示

### Steps to reproduce

【插件市场】->添加 一个新插件例(image) ->查看 【插件配置】菜单->搜索框检索(image) 
新增的插件并没有出现在插件配置菜单中 刷新页面也无法出现 但是可以在 插件市场 对刚才添加的插件点击 修改 然后点击 配置 就会自动跳转会 插件配置 并正常显示

### Expected behavior

添加成功的插件都在插件配置菜单下正常显示

### Versions

- OS: Docker: koishijs/koishi:latest
- Platform: Docker: koishijs/koishi:latest
- Node version: Docker: koishijs/koishi:latest
- Koishi version: Docker: koishijs/koishi:latest

**Comment by TszcWhut** [comment]
大概理解了 是为了兼容多账号吧，但是插件添加以后会重载页面回到首页，需要重新去插件市场搜索此插件（虽然目前保留了搜索记录）但是多次点击的体验还是有点割裂感的，要是可以的话 能不能在增加一个按钮【添加插件并配置】， 热重载后再自动读取SessionStorage里的待更新插件列表到插件配置菜单页面 可能会好一点

**Comment by shigma** [comment]
Koishi 的插件市场有两种安装模式：普通安装和批量安装。

普通安装后，会立即创建插件配置并跳转；批量安装时可以批量选择，且安装后也不会创建配置。

按理说是会显示的，你是什么操作流程？

**Comment by ilharp** [comment]
> 是为了兼容多账号吧

多账号是插件重用实现的其中一类功能；还有很多其他不同的功能。

例如，我需要管理两个不同艺人的粉丝群，每个群都需要有如下功能：

- 入群欢迎，两个群需要有不同的欢迎语；
- 社交平台推送，每个群需要实时推送各自艺人的社交动态；

此时，我可以开发「入群欢迎」和「社交平台推送」两个插件，之后对每个群创建、配置并启动一个插件的实例，最后将两组插件按群移入两个不同的分组内。我可以对每个分组调整其所属的上下文（对哪个群生效），或是临时停用/启用某一个群分组下的所有插件。换句话说， **插件重用使用户可以按照自己需要的切面来组织插件。**

---

> 要是可以的话 能不能在增加一个按钮【添加插件并配置】， 热重载后再自动读取SessionStorage里的待更新插件列表到插件配置菜单页面 可能会好一点

SessionStorage 确实是一个不错的方法；但就目前的情况来讲，插件安装后控制台刷新这件事本身可以被解决。解决此问题以后可以再看后续行为。

---

> 按理说是会显示的，你是什么操作流程？

目前有部分插件安装后会导致 Koishi 重启或是控制台刷新，之后可以看看原因。

**Comment by TszcWhut** [comment]
> Koishi 的插件市场有两种安装模式：普通安装和批量安装。
> 
> 普通安装后，会立即创建插件配置并跳转；批量安装时可以批量选择，且安装后也不会创建配置。
> 
> 按理说是会显示的，你是什么操作流程？

安装的分别是 adp-onebot 和 image-search，就正常的在插件市场搜索插件并点击添加按钮进行安装，点击安装后就会自动重启刷新页面；可能和我提到的另一个bug有关系，因为只使用了Docker版不知道其他版本的情况，刚才也尝试更新了容器的版本到4.17.7，依然无法解决
[app Error: EMFILE: too many open files, watch '/koishi'](https://github.com/koishijs/koishi/issues/1405)
