### ISSUE TITLE
Bug: onebot适配器炸了

### ISSUE THREAD

**Issue by TszcWhut** [koishijs/koishi#1407]
### Describe the bug

https://github.com/koishijs/koishi-plugin-adapter-onebot/issues/29
onebot无法使用了

### Steps to reproduce

部署koishi---插件市场搜索onebot-安装适配器onebot

### Expected behavior

正常运行

### Screenshots

![image](https://github.com/koishijs/koishi/assets/147678482/86abfdbe-e55f-464e-9df0-c287b2085d78)

### Versions

Docker: koishijs/koishi:latest

**Comment by shigma** [comment]
duplicate: https://github.com/koishijs/koishi-plugin-adapter-onebot/issues/29
