### ISSUE TITLE
Bug: 无法上传包

### ISSUE THREAD

**Issue by Night-GUA** [koishijs/koishi#1420]
### Describe the bug

根据教程 已npm login
然后 输入npm run pub koishi-plugin-setu
提示
npm run pub koishi-plugin-setu

> setu@0.0.0 pub
> yakumo publish koishi-plugin-setu

× Published 0 packages, 1 failed.

### Steps to reproduce

上述

### Expected behavior

正常提交

### Versions

- OS:  Windows 11
- Node version: e.g. v20.4.0
- Koishi version:  最新本地开发应用程序

**Comment by ilharp** [comment]
1. 「setu」是一个 Koishi 插件市场内的现有插件。项目仓库： <https://github.com/Lipraty/koishi-plugin-setu>
2. 大部分情况下你想发布的插件版本不应当是 `0.0.0`。发布插件前，请 bump 到想要发布的版本。

**Comment by Night-GUA** [comment]
`{
  "name": "@yuqianzhi/koishi-plugin-setu",
  "description": "呃,一个setu插件",
  "version": "1.0.0",
  "main": "lib/index.js",
  "typings": "lib/index.d.ts",
  "files": [
    "lib",
    "dist"
  ],
  "license": "MIT",
  "scripts": {},
  "keywords": [
    "chatbot",
    "koishi",
    "plugin"
  ],
  "devDependencies": {},
  "peerDependencies": {
    "koishi": "^4.17.9"
  }
}
`
这是我的package.json
我不是基于[setu](https://github.com/Lipraty/koishi-plugin-setu)而写

**Comment by ilharp** [comment]
那么请根据 [发布插件](https://koishi.chat/zh-CN/guide/develop/publish.html#%E5%8F%91%E5%B8%83%E6%8F%92%E4%BB%B6-1) 教程，在 `name` 处填写工作区目录名。目录名为 `external` 文件夹下的文件夹名称。

**Comment by Night-GUA** [comment]
`D:\zhuomian\koishi-plugin-open-setu\setu>npm run bump setu -3

> setu@0.0.0 bump
> yakumo version setu

- @yuqianzhi/koishi-plugin-setu: 1.0.1 => 1.0.2

D:\zhuomian\koishi-plugin-open-setu\setu>npm run build

> setu@0.0.0 build
> yakumo build


D:\zhuomian\koishi-plugin-open-setu\setu>npm run pub setu

> setu@0.0.0 pub
> yakumo publish setu

× Published 0 packages, 1 failed.`

仍然如此

**Comment by Night-GUA** [comment]
路径 `D:\zhuomian\koishi-plugin-open-setu\setu\external\setu`
  "name": "@yuqianzhi/koishi-plugin-setu",

**Comment by ilharp** [comment]
所以你的工作区名称是 `setu`，插件目录是 `setu`，插件包名是 `@yuqianzhi/koishi-plugin-setu`。理论上应该没有问题，确实比较奇怪。等待其他人来看吧。

**Comment by Night-GUA** [comment]
已解决 是使用了国内镜像的原因
