### ISSUE TITLE
Bug: recall 插件引用消息撤回时发生参数无效导致无法正常使用指令

### ISSUE THREAD

**Issue by araea** [koishijs/koishi#1432]
### Describe the bug

`recall` 插件引用消息撤回时发生参数无效导致无法正常使用指令。

### Steps to reproduce

使用 `recall` 插件并进行引用撤回操作。

### Expected behavior

引用撤回时能正常撤回对应的消息。

### Screenshots

![7c411c1f1c1029618304d66132b8011a](https://github.com/user-attachments/assets/a2567ddc-58a9-49f9-81bd-64a78a155ebc)

### Versions

Node: 20.10.0
Koishi: 4.17.10 
Console: 5.28.4
Adapter: onebot
OS: Windows 11 10.0.22621

### Additional context

![image](https://github.com/user-attachments/assets/a14aeef7-4c7d-4a02-8ab9-378309ea5d9a)

**Comment by shigma** [comment]
感觉还是要回到 recall 侧修复。
