### ISSUE TITLE
机器人正常运行时，go-cqhttp后台持续报错

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/koishi#146]
**To Reproduce**

使用koishi和go-cqhttp在本地运行机器人，HTTP协议，端口号默认。

**Describe the bug**

机器人正常运行时，go-cqhttp后台持续报错，大意为上报心跳包失败(EOF)，但并不影响机器人正常工作，日志内容见后。

**Expected behavior**

略

**Screenshots**

<details>
<summary>错误日志，不断重复，仅提供一段</summary>

[2021-03-06 19:49:01] [WARNING]: 上报Event到 HTTP 服务器 localhost:8080 时出现错误: Post "http://localhost:8080": EOF 将重试.
[2021-03-06 19:49:01] [WARNING]: 上报Event数据 
{"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":**********,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"packet_received":1152,"packet_sent":950,"packet_lost":0,"message_received":196,"message_sent":0,"disconnect_times":0,"lost_times":0,"last_message_time":1615031042}},"time":1615031341} 
到 localhost:8080 失败: Post "http://localhost:8080": EOF

![QQ图片20210306194912](https://user-images.githubusercontent.com/21092951/110206288-c0946e00-7eb7-11eb-9d7f-e0035629f774.png)

</details>

<details>
<summary>聊天记录</summary>

![QQ图片20210306194552](https://user-images.githubusercontent.com/21092951/110206284-be321400-7eb7-11eb-9fdc-2a7b27b14e1e.png)

</details>

<details>
<summary>聊天记录2</summary>

![QQ图片20210306194747](https://user-images.githubusercontent.com/21092951/110206286-bffbd780-7eb7-11eb-9dfe-9629613ce2eb.png)

</details>

**Versions**

- OS: [ Windows Server 2019 ]
- Node Version: [ 12.14.1 ]
- Go-CQhttp Version: [ ..... & 0.9.40-fix2 ]
- Koishi Version: [ 1.9.0 & 3.0.1]

**Additional context**

无

**Comment by Shigma** [comment]
这个问题大概早就解决了（
