### ISSUE TITLE
Bug: `strictOptions: true` 的指令中，以 `-` 开头的文本参数未贪婪匹配

### ISSUE THREAD

**Issue by DGCK81LNN** [koishijs/koishi#1473]
### Describe the bug

对于启用 `strictOptions` 的指令，当文本参数以 `-` 开头时，其值于第一个空格处被截断。

### Steps to reproduce

```js
import { inspect } from "node:util"
// ...
ctx
  .command("test <text:text>", { strictOptions: true })
  .action((_, ...args) => h.text(inspect(args)))
```

`test 123 456 789`

    ['123 456 789']

`test -123 456 789`

    ['-123', '456', '789']

### Expected behavior

仍然保持贪婪匹配的行为。

### Versions

- OS: Windows 10
- Platform: sandbox
- Node version: 22.9.0
- Koishi version: 4.18.0

**Comment by DGCK81LNN** [comment]
https://github.com/koishijs/koishi/blob/d06e1e9b2ad1d7ae7e31efc7f11249b1133d9450/packages/core/src/command/parser.ts#L396

**Comment by shigma** [comment]
发现这个 strictOptions 还是有其他边界情况。例如我有两个参数 -a, -b，此时输入 -ab 也会导致无法识别。
