### ISSUE TITLE
Bug: 在近期更新了部分官方插件后，数组配置项出现了在开发模式和生产模式下 不一致 的情况

### ISSUE THREAD

**Issue by shangxueink** [koishijs/koishi#1474]
### Describe the bug

1. emojihub原本的配置项内容是
```
    MoreEmojiHub: Schema.array(Schema.object({
      command: Schema.string().description('注册的指令名称'),
      source_url: Schema.string().description('表情包文件地址'),
    })).role('table').description('表情包指令映射 当前默认`40套`txt文件`点击右方按钮 可以恢复到默认值`<br>`表情包文件地址`可以填入`txt文件绝对路径`或者`文件夹绝对路径`或者`图片直链`或者`图片文件绝对路径`').default(defaultMoreEmojiHub),

```
 
我们在`yarn dev`启动情况下，控制台的对应配置项长这样
![image](https://github.com/user-attachments/assets/8470f046-fe3d-417b-9d02-cbd868e78dd9)

---

2. 在10.29小火箭升级了部分依赖后，发现在 生产模式下的该插件的配置项与开发模式下不一致的情况

我具体更新了这些内容
![4920ce92dff7e43a1605317670a7874e](https://github.com/user-attachments/assets/5c49f4b1-83d0-4399-ac73-3c6d9cce657c)

然后我的插件的配置项变成了这样

![image](https://github.com/user-attachments/assets/22a0a992-49bf-4663-b6bc-7bc6cc3b23e3)

---

但是在这样的情况下，我们使用yarn dev启动，任然可以恢复到预期的配置项

用yarn  start 启动就可以复现（10.29更新后）

### Steps to reproduce

在10.29小火箭升级了部分依赖后，发现在 生产模式下的该插件的配置项与开发模式下不一致的情况

我具体更新了这些内容
![4920ce92dff7e43a1605317670a7874e](https://github.com/user-attachments/assets/5c49f4b1-83d0-4399-ac73-3c6d9cce657c)

然后我的插件的配置项变成了这样

![image](https://github.com/user-attachments/assets/22a0a992-49bf-4663-b6bc-7bc6cc3b23e3)

---

但是在这样的情况下，我们使用yarn dev启动，任然可以恢复到预期的配置项

用yarn  start 启动就可以复现

### Expected behavior

1. emojihub原本的配置项内容是
```
    MoreEmojiHub: Schema.array(Schema.object({
      command: Schema.string().description('注册的指令名称'),
      source_url: Schema.string().description('表情包文件地址'),
    })).role('table').description('表情包指令映射 当前默认`40套`txt文件`点击右方按钮 可以恢复到默认值`<br>`表情包文件地址`可以填入`txt文件绝对路径`或者`文件夹绝对路径`或者`图片直链`或者`图片文件绝对路径`').default(defaultMoreEmojiHub),

```
 
我们在`yarn dev`启动情况下，控制台的对应配置项长这样
![image](https://github.com/user-attachments/assets/8470f046-fe3d-417b-9d02-cbd868e78dd9)

### Screenshots

日志无报错

### Versions

![4920ce92dff7e43a1605317670a7874e](https://github.com/user-attachments/assets/5c49f4b1-83d0-4399-ac73-3c6d9cce657c)

### Additional context

System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i5-12500H

Binaries:
    Node: 22.9.0
    Yarn: 4.1.1

Koishi:
    Core: 4.18.0
    Console: 5.30.0

**Comment by shangxueink** [comment]
在目前（10.26）重新开一个项目模板后
yarn start 启动后，

安装一些使用了「表格」样式的数组配置项的插件

发现都不正常了哦……

---

比如jrys-prpr，deer-pipe，……好多哦（）

**Comment by CatKoishi** [comment]
我也有同样的情况，使用dev模式启动，数组可以呈现表格形式，start启动则失效
日志无报错

**Comment by shangxueink** [comment]
生产环境 小火箭之后 似乎不会直接变成这样

而是要 小火箭+重启一下koishi 才能复现这样的情况

---

看了一下 似乎生产环境可以这样回退版本修复

**在小火箭更新之后** 可以这样回退


---


![image](https://github.com/user-attachments/assets/249a1cd0-e26e-452c-aced-849ba1ac59b0)


@koishijs/plugin-console | 5.30.0 | ->  | 5.29.4
-- | -- | -- | --
@koishijs/plugin-config | 2.8.6 | ->  | 2.8.5
koishi-plugin-theme-vanilla | 1.1.0 | ->  | 1.0.6

---

然后可以执行 
```
// 项目模板

yarn add @koishijs/console@5.29.4
```

```
// koishi desktop

koi yarn -n default add @koishijs/console@5.29.4  
```

然后重启 koishi ，

应该就恢复到之前的配置项样子

**Comment by shangxueink** [comment]
生产环境 小火箭之后 似乎不会直接变成这样

而是要 小火箭+重启一下koishi 才能复现这样的情况

---

看了一下 似乎可以这样回退版本修复

**在小火箭更新之后** 可以这样回退


---


![image](https://github.com/user-attachments/assets/249a1cd0-e26e-452c-aced-849ba1ac59b0)


@koishijs/plugin-console | 5.30.0 | ->  | 5.29.4
-- | -- | -- | --
@koishijs/plugin-config | 2.8.6 | ->  | 2.8.5
koishi-plugin-theme-vanilla | 1.1.0 | ->  | 1.0.6

---

然后重启 koishi ，

应该就恢复到之前的配置项样子

---

**Comment by shigma** [comment]
看起来是构建出了问题，会尽快修复。

**Comment by shigma** [comment]
已修复：https://github.com/shigma/schemastery/commit/308a8a857d0b811b7888261d4d79544f629a0a80

请尝试 5.30.1 版本。
