### ISSUE TITLE
Feature: Linux无桌面环境无法进入控制台

### ISSUE THREAD

**Issue by NorLorikein** [koishijs/koishi#1477]
### Describe the problem related to the feature request

Linux搭建koishi后，想要公网访问控制台必须先使用内网进入控制台通过server插件部署公网，但无桌面环境下无法访问控制台

### Describe the solution you'd like

增加可以在本地文件修改插件配置参数的功能

### Describe alternatives you've considered

无

### Additional context

无

**Comment by MaikoTan** [comment]
You could modify the `koishi.yml` file in the root of Koishi instance folder to achieve this.

> (翻译自 Google 翻译)
>
> 您可以修改 Koishi 实例文件夹根目录中的“koishi.yml”文件来实现这一点。
