### ISSUE TITLE
Bug: 在 Koishi 4.18.1 版本下，`Schema` 中的条件求值不可用

### ISSUE THREAD

**Issue by dingyi222666** [koishijs/koishi#1482]
### Describe the bug

![65eba070728d8245fbb98975bd8147fc](https://github.com/user-attachments/assets/f9bcaff2-7776-48e8-ae19-68eb968cc65a)

如上图，条件求值中无法添加条件分支。

### Steps to reproduce

升级到 Koishi 4.18.1，并确保 `@koishijs/client` 为 5.30.1 版本。

### Expected behavior

在 Koishi 4.18.0 中无此问题：

![image](https://github.com/user-attachments/assets/1c83fbad-5e3b-4053-ac8e-1e0740b99e1a)

对应的 `@koishijs/client` 为 5.29.4 版本。

### Versions

- OS: Windows 11
- Platform: Sandbox
- Node version: 20.16.0
- Koishi version: 4.18.1

**Comment by shigma** [comment]
这个应该修了。

https://github.com/shigma/schemastery/pull/61
