### ISSUE TITLE
使用koishi-plugin-common的bind指令时抛出异常

### ISSUE THREAD

**Issue by Anillc** [koishijs/koishi#152]
**Describe the bug**

在onebot平台上使用bind指令后到telegram平台发送token后报错  

**To Reproduce**

使用`koishi-plugin-mysql`、`koishi-plugin-common`以及参数`autoAuthorize: 1`  

**Expected behavior**

user表中telegram字段更新

**Screenshots**

![Screenshot_20210314_161431](https://user-images.githubusercontent.com/23411248/111062922-f0122e80-84e6-11eb-9a5a-ed8f9f58396f.jpg)

**Versions**

- OS: CentOS 8  
- Node Version: 14.15.3  
- Koishi Version: 3.1.0  
- koishi-plugin-mysql Version: 3.0.0  
- koishi-plugin-common Version: 4.1.0

**Additional context**

推测原因：  
- user表中onebot和telegram有UNIQUE修饰  
- 使用`autoAuthorize: 1`参数后会自动在表中分别插入onebot和telegram的user  
- bind指令不会自动删除已有的user，导致字段内容重复，抛出异常  

另外如果不使用`autoAuthorize: 1`，会导致在telegram端返回`权限不足`的提示

**Comment by Shigma** [comment]
> 另外如果不使用 autoAuthorize: 1，会导致在 telegram 端返回权限不足的提示

这是因为账户只能绑定已经存在的账户，onebot 不能与不存在的 telegram 账户绑定。

**Comment by Anillc** [comment]
> @Anillc 感谢你的反馈！问题已于 [de3baaa](https://github.com/koishijs/koishi/commit/de3baaac5ba8156ba771d7ae437f48e554da85ea) 解决，但你对这个指令的行为理解有误。
> 
> > 另外如果不使用 autoAuthorize: 1，会导致在 telegram 端返回权限不足的提示
> 
> 这是因为账户只能绑定已经存在的账户，onebot 不能与不存在的 telegram 账户绑定。
> 
> 因此，如果你已有 onebot 账户，而没有 telegram 账户的话，应该在 telegram 而不是 onebot 中使用 bind 指令，不然 onebot 会被销号。

明白了，感谢回复
