### ISSUE TITLE
plugin-status SIGINT handle

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi#158]
![image](https://user-images.githubusercontent.com/29992205/111636266-46f36d00-8833-11eb-9c8a-4ab1056d9f88.png)

建议core提供app.parallel('exit')事件统一处理退出行为而非由插件自行注册process.on('SIGINT')。这可能会导致其他SIGINT钩子异常（上传完数据后直接触发process.exit）

**Comment by Shigma** [comment]
不太确定要什么，比如这样吗：

```ts
// core
process.on('SIGINT', () => {
  app.logger('app').info('terminated by SIGINT')
  app.parallel('exit').finally(() => process.exit())
})

// plugin
ctx.on('exit', () => {
  return upload(sync, true)
})
```

**Comment by Shigma** [comment]
上面的写法可能引起 breaking change，我不太确定会不会让其他人的逻辑炸掉。虽然应该是有 workaround 的，问题不太大。

有需求的话我选个 minor version 做这个。

**Comment by undefined-moe** [comment]
如果上面的写法让其他人的逻辑炸掉，那么现在的写法一定也会炸掉（）
毕竟SIGINT事件是同时触发并行运行的

**Comment by Shigma** [comment]
> 如果上面的写法让其他人的逻辑炸掉，那么现在的写法一定也会炸掉（）
> 毕竟SIGINT事件是同时触发并行运行的

上面的写法让所有用 koishi 且同时处理 SIGINT 的人炸掉，而现在的写法只让用 koishi-plugin-status 且同时处理 SIGINT 的人炸掉。这还是有挺大区别的。

当然如果只有你一个人处理 SIGINT 那当我没说。

**Comment by undefined-moe** [comment]
那等minor吧

**Comment by Shigma** [comment]
或者还有一种办法，就是让 status 自己提供一个接口 handleSigInt，这样不用担心影响 core，我觉得更好

**Comment by Shigma** [comment]
虽然是可以统一处理，但是这样写有一些额外的坏处：

1. 与 node 耦合了，未来版本如果要做 node 无关的话，那么这个特性也无法保留
2. 测试会崩，大量测试得重写

为了解决 2 的问题，我还是得在 app 中提供一个接口让用户阻止这个行为。那既然要开接口，显然是开在 status 影响更小，因为目前只有 status 一个插件用到它，没必要冒着崩一堆东西的风险在 app 开这个后门。

**Comment by undefined-moe** [comment]
> 显然是开在 status 影响更小

**Comment by undefined-moe** [comment]
> 显然是开在 status 影响更小

我建议core只在有插件尝试注册exit事件是挂SIGINT钩子，但是我反对接口开在status的逻辑，这个功能应当是和status无关的
很难想象如何做node无关 目前很多地方依赖http/https/net/os/fs/path库，全部做polyfill可能很难实现

**Comment by Shigma** [comment]
> 这个功能应当是和 status 无关的

正好相反，这个功能目前**只与 status 有关**。不开这个接口如果会导致一部分人不用 status 的话，那么开在 core 只会导致更多人不用 koishi。如果你不认为应该开在 status，那我觉得不开接口或者移除 SIGINT handler 更好（具体哪一个倒是可以商量），因为开在 core 确实是严重的 breaking change，而且我完全不认同 core 给插件开后门的行为。

> 很难想象如何做 node 无关

你觉得难而已，v4 会怎么样真的不一定。

**Comment by undefined-moe** [comment]
开在core不代表需要默认启用。可以仅当该接口被调用时添加SIGINT handler

**Comment by Shigma** [comment]
一个开在 core，并不默认启用，并且所有功能只为了你一个人的代码，显然由你自己提供更好吧。

**Comment by undefined-moe** [comment]
userCache在进程退出时强制同步也该做了（确信

**Comment by undefined-moe** [comment]
我觉得这玩意比status更重要

**Comment by Shigma** [comment]
> 开在 core 不代表需要默认启用

凭什么要让这么多人的系统空间和性能为你买单呢？

> userCache 在进程退出时强制同步也该做了（确信

userCache 会在每一个会话结束后自动同步，通常情况下不会丢失信息

**Comment by Shigma** [comment]
我觉得你的问题是 status 的问题，应当由 status 解决。解决方案有二：

1. 删掉 status 的这个特性
2. 给 status 提供额外的配置项

如果你都不满意的话，那么 status 单纯不是你的选择而已。
