### ISSUE TITLE
Cannot destructure property 'terminator' of 'argv.tokens[(argv.tokens.length - 1)]' as it is undefined

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi#162]
![image](https://user-images.githubusercontent.com/29992205/111794476-3a3d4a80-8901-11eb-9bb2-879b779bc42f.png)

**Comment by Shigma** [comment]
怎么复现

**Comment by Shigma** [comment]
看起来是由教学问答产生的，能给一下具体的问答内容吗？

**Comment by Shigma** [comment]
由于新版本（3.6.1）中相关的代码已经被改动，请确认是否仍有此问题出现。如果有的话欢迎开一个新的 issue。
