### ISSUE TITLE
command可无视group选择器激活

### ISSUE THREAD

**Issue by XxLittleCxX** [koishijs/koishi#168]
在help中没有, 但可以直接调用执行

**To Reproduce**
```js

function apply(ctx){
  ctx.command("test")
}

app.group("112233").plugin(apply)
```

**Expected behavior**
`test`不可用

**Comment by idlist** [comment]
提供一个范例
![test2](https://user-images.githubusercontent.com/29368226/111909750-7d322600-8a99-11eb-9e16-e3968682fce6.png)
![test](https://user-images.githubusercontent.com/29368226/111909736-6f7ca080-8a99-11eb-81e6-c7f0b2cce003.png)
