### ISSUE TITLE
plugin-status 使用 webui 注册密码时报错

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#171]
**Describe the bug**

RT

**To Reproduce**

见截图

**Expected behavior**

可以注册密码

**Screenshots**

![2B049532-971C-4EB9-BE09-D18738EFA1FA](https://user-images.githubusercontent.com/44761872/111939590-a5586e00-8b07-11eb-840f-c488075ee21a.png)
![FA9EECB6-95E4-448E-A6E4-45F50F0AD67C](https://user-images.githubusercontent.com/44761872/111939618-b0ab9980-8b07-11eb-96e0-a7930f9d93e2.png)

**Versions**

plugin-status 4.0.0-rc.1

- OS: [e.g. iOS] （客户端）Windows 10 FireFox最新/Edge最新
- Node Version: [e.g. 10.16.0] 14.x
- CoolQ Version: [e.g. 5.15.4] -
- CQHTTP Version: [e.g. 4.13.2] -
- Koishi Version: [e.g. 1.0.0] 3.3.0

**Additional context**

**Comment by Shigma** [comment]
It seems that `Crypto.subtile` is only available in secure contexts, in other words, HTTPS.

**Comment by Shigma** [comment]
因此应该在非安全上下文中禁止密码登录的功能。

**Comment by Dragon-Fish** [comment]
确认在切换为 https 后可以注册密码以及使用控制台密码登录
