### ISSUE TITLE
mongo 中 db.setChannel 似乎出现问题

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#189]
**Describe the bug**

RT

**To Reproduce**

假定一个最简单的指令：

```js
App.command('setchannel <data>', '设置频道数据').action(({ session }, data) => {
  session.database.setChannel(session.platform, session.groupId, { foo: data })
})
```

在群聊内向机器人发送：`setchannel bar`

数据库内实际未出现值为`bar`的字段`foo`

**Expected behavior**

略。

**Screenshots**

**Versions**

- OS: [e.g. iOS] Windows Server 2019
- Node Version: [e.g. 10.16.0] 15.4.0
- CoolQ Version: [e.g. 5.15.4] -
- CQHTTP Version: [e.g. 4.13.2] -
- koishi: ^3.5.1
- plugin-mongo: ^2.2.0
- koishi-utils: ^4.1.1

**Additional context**

老板，来一个双层牛肉巨无霸

**Comment by Shigma** [comment]
所以 #188 是由这个导致的吗……

**Comment by Dragon-Fish** [comment]
> 所以 #188 是由这个导致的吗……

@Shigma 目前未知， #188 与本问题均无报错。

**Comment by Dragon-Fish** [comment]
本问题似乎得到解决，希望继续完善 #179 更新中的变更。

问题原因：在 collection channel 中出现疑似测试版 status 插件意料外插入的 documents，这些 docs 的 type 字段值为 null，可能导致 setChannel 查数据库时找到多个 docs

解决方法：`db.channel.remove({ type: null })`
