### ISSUE TITLE
[RFC] 关于 adapter-discord 发送图片时兼容 onebot 协议的讨论

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#201]
目前 adapter-discord 发送本地图片时，需要在消息段的 url 中提供文件的绝对路径。

作为上游开发者，我更希望各个 adapter 的接口统一一些，因此提议在 adapter-discord 发送本地图片时兼容 onebot 中的使用**本地文件传输协议**进行传参（`file:///` + 绝对路径，例如`file:////path/to/image.jpg`或`file:///C:\path\to\image.jpg`）。

**Comment by Shigma** [comment]
这只是 adapter-discord 的 bug 并且很好修复。
