### ISSUE TITLE
plugin-chat 中聊天图片无法显示

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#219]
**Describe the bug**

RT，见图

**To Reproduce**

**Expected behavior**

图片正常显示

**Screenshots**

![图片](https://user-images.githubusercontent.com/44761872/114273537-fbf10200-9a4c-11eb-8c22-2795810d9eb4.png)

**Versions**

- Node Version: 15.4
- CoolQ Version: 1.0.0-beta2
- Koishi Version: 3.7.2
- plugin-webui 4.1.1
- plugin-chat 0.2.1

**Additional context**

未安装 plugin-asset

**Comment by Shigma** [comment]
这个功能跟 koishi-plugin-assets 没有关系。你检查一下控制台有没有报错。

**Comment by Dragon-Fish** [comment]
![image](https://shiki.shigma.xyz:8443/assets/62e11ab1cb8545da9f3f6726cba650d9.image)

**Comment by Shigma** [comment]
我是说你的 koishi 的控制台。 

顺便这个可能是另一个问题，请另开 issue。

**Comment by Dragon-Fish** [comment]
koishi 控制台无报错，打开 chat 标签后浏览器报错如上，有一大堆

**Comment by Shigma** [comment]
Observer 问题已经成功复现并且将在 v3.8 中修复。图片加载问题无法复现。

**Comment by Dragon-Fish** [comment]
chat 0.3.0 中图片依旧无法加载，正在核查是否为我这边的问题

**Comment by Dragon-Fish** [comment]
该问题似乎依旧存在。

目前情况：webui 的 path 设定为 `/dash`，图片路径为`/dash/status/assets/${encodeURIComponent(源地址)}`，服务器返回 404 错误。

例如：https://sili.wjghj.cn/dash/status/assets/http%3A%2F%2Fgchat.qpic.cn%2Fgchatpic_new%2F1%2F0-0-1F3052BF56F8D71B3F12A38F8EBE2FEA%2F0%3Fterm%3D2

**Comment by Shigma** [comment]
问题在于 apiPath 不能以 uiPath 为前缀。
