### ISSUE TITLE
plugin-chat 中聊天列表的样式似乎不正确

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#222]
**Describe the bug**

文字描述不清，请大哥看录屏（

大概意思是消息列表超出了 container

**To Reproduce**

**Expected behavior**

**Screenshots**

https://user-images.githubusercontent.com/44761872/114274319-6b1c2580-9a50-11eb-9930-b0e1b552199f.mp4

**Versions**

- Node Version: 15.4
- CoolQ Version: 1.0.0-beta2
- Koishi Version: 3.7.2
- plugin-webui 4.1.1
- plugin-chat 0.2.1

**Additional context**

应该不是缓存问题，遇到这个情况时已关闭 CDN 缓存

**Comment by Shigma** [comment]
目前 dev 和 prod 均无法复现。等新版本再看看有没有这个问题吧。

**Comment by Shigma** [comment]
新版本已发布，麻烦检查一下这个问题是否依然存在。

**Comment by Dragon-Fish** [comment]
0.3.0 中似乎已修复

**Comment by Dragon-Fish** [comment]
重新打开此 issue，原因：

目前在 Safari for iOS 上可以正常显示

在 Windows Firefox 87.0 (64位) 浏览器上，最新发行版和当下 dev 分支下均显示异常复现了此问题，确定使用无痕模式并关闭了 CDN 缓存。

![图片](https://user-images.githubusercontent.com/44761872/114891536-8f0bac80-9e3e-11eb-93a9-79eab363195b.png)

**Comment by Shigma** [comment]
我这里使用了 -webkit-fill-available 属性解决布局问题，所以只能在 chrome, edge 和 safari 上正常显示。暂时我也不知道该怎么改。有熟悉 CSS 的可以给点建议吗？

**Comment by Dragon-Fish** [comment]
是否可以使用`height: 80vh;`这种兼容性较好一些的写法，如此修改以后界面看起来似乎符合预期。

**Comment by Shigma** [comment]
你调一下高度就挂了，这里肯定不能写死的
