### ISSUE TITLE
adapter-onebot 大量报 app Error: response timeout

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#227]
**Describe the bug**

使用cli启动， **消息已经成功发送出去了** ，但还是在日志中大量报 app Error: response timeout
还没测index启动会不会有同样的问题

go-cqhttp版本0.9.40-fix2，当前版本为koishi 3.8.0，koishi-adapter-onebot 3.0.7
同时之前在使用同一个go-cqhttp，koishi 3.4.0，koishi-adapter-onebot 3.0.1时没有这个问题。

![image](https://user-images.githubusercontent.com/29368226/114653548-ddc02600-9d1a-11eb-93fa-1d4b0a8c00f4.png)

**Comment by Dragon-Fish** [comment]
![F0372DF4-4673-474B-A472-1D39A9B52262](https://user-images.githubusercontent.com/44761872/114654887-ac952500-9d1d-11eb-9ca2-c9fded990f65.jpeg)

Same issue
