### ISSUE TITLE
plugin-webui 的 k-card-body 样式缺少 padding

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#228]
**Describe the bug**

暂无数据 变成了这样

![image](https://user-images.githubusercontent.com/29368226/114653903-9ab28280-9d1b-11eb-815b-33127a858c72.png)

路径为

![image](https://user-images.githubusercontent.com/29368226/114654069-f2e98480-9d1b-11eb-88b9-166f9ad55ced.png)

版本为koishi-plugin-webui@4.2.0

**Comment by Shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/114760878-675f0a80-9d92-11eb-8550-3f1065463edb.png)

不知道为什么我这里是有的（k-card-body 确实没有 padding 但是 p 有 margin）

**Comment by idlist** [comment]
我用Edge Chronium和iOS Safari看，p都没有margin
电脑里没装Firefox和Chrome 🤔 

实例在这个地址 http://bot.idl.ist:21919/console/
