### ISSUE TITLE
plugin-chat 中消息列表无法正确的滚动到最底部

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#229]
**Describe the bug**

当滚动到消息最底部后收到新消息时，会自动滚动到最底部，但是似乎高度计算有误，每次都差一点点，最后导致底部的消息逐渐变成 padding 消失掉。见截图中打蓝框的地方。

**To Reproduce**

**Expected behavior**

**Screenshots**

![1E7A8BA2-84BE-46B7-9F88-8A1A28417F4F](https://user-images.githubusercontent.com/44761872/114655253-6d1b0880-9d1e-11eb-9f83-3b66a509c983.jpeg)

**Versions**

- Node Version: [e.g. 10.16.0]
- CoolQ Version: [e.g. 5.15.4]
- CQHTTP Version: [e.g. 4.13.2]
- Koishi Version: [e.g. 1.0.0] 3.8.0
- plugin-chat 0.3.0

**Additional context**

**Comment by Shigma** [comment]
我想应该在 v4 中修复了，如果可以的话可以帮忙确认一下。
