### ISSUE TITLE
koishi 启动时报错

### ISSUE THREAD

**Issue by LF112** [koishijs/koishi#23]
**Describe the bug**
启动使用 koishi 编写的项目后，打印出了下面这些报错：
`(node:3361) UnhandledPromiseRejectionWarning: Error: authorization failed
    at HttpServer._listen (/LF/Robot/FenBin/Main/node_modules/koishi-core/dist/server.js:269:19)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:3361) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:3361) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

下面是我的配置：
`const app = new App({
    type: 'http',
    port: 41007,
    server: 'http://localhost:41006',
    secret: '***_2020',
    token: '************',
})`

**Screenshots**
![Snipaste_2020-02-08_18-21-44.png](https://i.loli.net/2020/02/08/hyPNzjbA6OKUJDd.png)

**Comment by aFishTail** [comment]
同报错，解决了吗

**Comment by LF112** [comment]
> 同报错，解决了吗

koishi 与 httpcq 连接失败（鉴权失败或链接失败），尝试启动酷Q并确保cqhttp为启用状态，且连接地址及密钥等正确再尝试启动项目。

简单点说就说 koishi 与 cqhttp 连接失败，必须先让 cqhttp 服务启动了才行
