### ISSUE TITLE
plugin-mongo 丢失了用户数据 (userFileds)

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#233]
**Describe the bug**

近期，有三名使用 MongoDB 的 bot 持有者反馈他们丢失了数据库中自己的用户数据，具体表现为集合 user 中自己的 document 整个没有了。

**To Reproduce**

目前未知，将在 comment 中持续跟进。

**Expected behavior**

**Screenshots**

**Versions**

- Node Version: 14.x 15.x
- Koishi Version: 3.8.0 3.9.0
- plugin-mongo: 2.2.1
- plugin-webui: 4.2.0
- plugin-chat: 0.3.0

**Additional context**

**Comment by Dragon-Fish** [comment]
~~受害者召唤术~~

@undefined-moe @NWYLZW

**Comment by Dragon-Fish** [comment]
目前已知我们均打开过 webui，并且其中 @NWYLZW 与我在使用账号密码登录时遇到了以下提示：

![](https://user-images.githubusercontent.com/44761872/114890305-78188a80-9e3d-11eb-9b8f-149d37d8838e.jpg)

**Comment by NWYLZW** [comment]
**补充**
可能会在更新依赖后触发

**Comment by Shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/115153647-b619e680-a0a9-11eb-91ef-26e3c04cd639.png)

应该是这里实现出了问题。不应该直接覆写，而是修改对应的字段。

**Comment by undefined-moe** [comment]
是你传进来的不对好吧（

**Comment by Shigma** [comment]
传进来的对象不含有 id 等关键信息，因此不会影响数据的存在性。目前不清楚具体成因，希望有关人员能够提供更进一步的信息。

**Comment by Shigma** [comment]
目前还是没有办法稳定复现此 bug。

**Comment by Dragon-Fish** [comment]
在较长时间里无法复现
