### ISSUE TITLE
plugin-mysql 在启动时报出语法错误

### ISSUE THREAD

**Issue by kecrily** [koishijs/koishi#238]
**Describe the bug**

在执行 `npx koishi start` 命令时，`koishi-plugin-mysql` 创建尝试初始化数据库，报出 mysql 语句语法错误。

**To Reproduce**

在我的环境中执行
```
npx koishi start
```

**Expected behavior**

正常启动

**Screenshots**

``` 
...
[I] mysql auto creating table subscribe
[W] mysql CREATE TABLE `subscribe` (`id` `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,`names` TEXT,primary key (`id`)) COLLATE = 'utf8mb4_general_ci'
[E] app ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,`names` TEXT,primary key (`id`)) COL...' at line 1   at MysqlDatabase.query (/home/bot/node_modules/koishi-plugin-mysql/lib/index.js:155:19)
        at MysqlDatabase.start (/home/bot/node_modules/koishi-plugin-mysql/lib/index.js:133:20)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Promise.all (index 0)
        at async _App.start (/home/bot/node_modules/koishi-core/lib/index.js:1941:5)
```

**Versions**

- OS: Debian 10.0(core: 4.19.132-1 gcc: 8.3.0 )
- Node Version: 14.16.1
- Npm Version: 6.14.12
- go-cqhttp Version: 1.0.0-beta3
- Koishi Version: 3.9.1
- Koishi-plugin-mysql: 3.3.1
- MariaDB: 10.4

**Additional context**

插件列表：

- onebot
- chat
- common
- github
- monitor
- rss
- schedule
- teach
- tools
- webui

**Comment by KoishiStudio** [comment]
请问你这边解决了吗，我这边也是这样

**Comment by NWYLZW** [comment]
解决应该解决了吧
你的版本信息是？

**Comment by KoishiStudio** [comment]
> 解决应该解决了吧
> 你的版本信息是？

- OS:Archlinux (内核5.12.14-arch1-1)
- Node Version:12.22.4 14.74.4 16.6.2 这三者都试过
- npm Vsersion:7.20.5
- go-cqhttp Version: v1.0.0-beta5
- koishi Version: 3.13.1
- Koishi-plugin-mysql: 3.5.0
- MariaDB: 10.6.4 (也试过mysql 8.0.25 和mysql 5.6.51)

插件列表：

- onebot
- chat
- common
- github
- image-search
- puppeteer
- schedule
- teach
- tools
- webui

**Comment by NWYLZW** [comment]
离谱，你的报错也是和他的一样吗

**Comment by KoishiStudio** [comment]
> 离谱，你的报错也是和他的一样吗

我的是这样的
```
[I] mysql auto creating table user
[W] mysql CREATE TABLE `user` (`lastCall` timestamp,`password` varchar(64),`token` varchar(64),`expire` bigint unsigned default 0,`onebot` varchar(50) null default null,primary key (`id`),unique index (`onebot`),bigint(20) unsigned not null auto_increment,varchar(50) null,int(20) unsigned not null,int(4) unsigned not null,varchar(65536) not null default ,varchar(65536) not null default ,varchar(50) null,varchar(50) null) COLLATE = 'utf8mb4_general_ci'
[E] app ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bigint(20) unsigned not null auto_increment,varchar(50) null,int(20) unsigned no' at line 1   at MysqlDatabase.query (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:216:19)
        at MysqlDatabase.start (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:194:20)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 0)
        at async _App.start (/home/koishibot/koishi/node_modules/koishi-core/lib/index.js:2030:5)
error Command failed with exit code 1.

```

**Comment by KoishiStudio** [comment]
> > 离谱，你的报错也是和他的一样吗
> 
> 我的是这样的
> 
> ```
> [I] mysql auto creating table user
> [W] mysql CREATE TABLE `user` (`lastCall` timestamp,`password` varchar(64),`token` varchar(64),`expire` bigint unsigned default 0,`onebot` varchar(50) null default null,primary key (`id`),unique index (`onebot`),bigint(20) unsigned not null auto_increment,varchar(50) null,int(20) unsigned not null,int(4) unsigned not null,varchar(65536) not null default ,varchar(65536) not null default ,varchar(50) null,varchar(50) null) COLLATE = 'utf8mb4_general_ci'
> [E] app ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bigint(20) unsigned not null auto_increment,varchar(50) null,int(20) unsigned no' at line 1   at MysqlDatabase.query (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:216:19)
>         at MysqlDatabase.start (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:194:20)
>         at processTicksAndRejections (internal/process/task_queues.js:97:5)
>         at async Promise.all (index 0)
>         at async _App.start (/home/koishibot/koishi/node_modules/koishi-core/lib/index.js:2030:5)
> error Command failed with exit code 1.
> ```

另外手动创建user表之后会继续报错如下
```
[W] mysql CREATE TABLE `channel` (`name` varchar(50),`activity` text,primary key (`id`),bigint(20) unsigned not null auto_increment,int(20) unsigned not null,varchar(50) null,varchar(65536) not null default ,varchar(65536) not null default ) COLLATE = 'utf8mb4_general_ci'
[E] app ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'bigint(20) unsigned not null auto_increment,int(20) unsigned not null,varchar(50' at line 1   at MysqlDatabase.query (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:216:19)
        at MysqlDatabase.start (/home/koishibot/koishi/node_modules/koishi-plugin-mysql/lib/index.js:194:20)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 0)
        at async _App.start (/home/koishibot/koishi/node_modules/koishi-core/lib/index.js:2030:5)
```

**Comment by NWYLZW** [comment]
这段代码你能直接在你的数据库执行吗？
```
CREATE TABLE `user` (`lastCall` timestamp,`password` varchar(64),`token` varchar(64),`expire` bigint unsigned default 0,`onebot` varchar(50) null default null,primary key (`id`),unique index (`onebot`),bigint(20) unsigned not null auto_increment,varchar(50) null,int(20) unsigned not null,int(4) unsigned not null,varchar(65536) not null default ,varchar(65536) not null default ,varchar(50) null,varchar(50) null) COLLATE = 'utf8mb4_general_ci'
```

**Comment by NWYLZW** [comment]
我看着像某个插件的导致的问题（猜的
可以试试移除某些插件直到数据库能够建表为止

**Comment by KoishiStudio** [comment]
> 这段代码你能直接在你的数据库执行吗？
> 
> ```
> CREATE TABLE `user` (
>   `lastCall` timestamp,
>   `password` varchar(64),
>   `token` varchar(64),
>   `expire` bigint unsigned default 0,
>   `onebot` varchar(50) null default null,
>   primary key (`id`),
>   unique index (`onebot`),
>   bigint(20) unsigned not null auto_increment,
>   varchar(50) null,
>   int(20) unsigned not null,
>   int(4) unsigned not null,
>   varchar(65536) not null default ,
>   varchar(65536) not null default ,
>   varchar(50) null,
>   varchar(50) null
> ) COLLATE = 'utf8mb4_general_ci'
> ```

用这段得到的报错如下（版本 10.6.3-MariaDB 和5.6.51 MySQL均如此）
```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'bigint(20) unsigned not null auto_increment,
  varchar(50) null,
  int(20) un...' at line 9

```

**Comment by KoishiStudio** [comment]
> 我看着像某个插件的导致的问题（猜的
> 可以试试移除某些插件直到数据库能够建表为止

只保留mysql插件和onebot也这样，我一会用windows试试吧

**Comment by NWYLZW** [comment]
具体还是要看 shigma 来看到底是啥问题了
我在 koishi 里面还没有试过 mysql
你也许可以换个数据库，换成 mongo 看看问题是否还会继续出现

**Comment by NWYLZW** [comment]
> > 我看着像某个插件的导致的问题（猜的
> > 可以试试移除某些插件直到数据库能够建表为止
> 
> 只保留mysql插件和onebot也这样，我一会用windows试试吧

还有一件事，你就算没安装，引入了也是会奏效的
最好是把 import / require 都删了

**Comment by KoishiStudio** [comment]
> 这是 koishi 3.13.1 新引入的问题，回退版本到 3.13.0 可以解决

好的，感谢

**Comment by MindXL** [comment]
我今天在扩展自己的数据表时也出现了这个问题。
使用新式的`Table.extend('user',{})`，也就是传入 Meta 类型参数时，plugin-mysql在将 Meta 接口中的 fileds 转换为 sql 语句时出了问题。

[Meta:](https://github.com/koishijs/koishi/blob/cb23788d650cb296a8ff8f7b749cbde45b415621/packages/koishi-core/src/database.ts#L36)
https://github.com/koishijs/koishi/blob/cb23788d650cb296a8ff8f7b749cbde45b415621/packages/koishi-core/src/database.ts#L36

plugin-mysql中这一行定义了每个小段sql，它的成品就是`varchar(50) null`这种字符串。它的开头少加了相应的key。
https://github.com/koishijs/koishi/blob/cb23788d650cb296a8ff8f7b749cbde45b415621/packages/plugin-mysql/src/database.ts#L145

**Comment by NWYLZW** [comment]
你这个应该是 dup 了，继续在那个 issue 下面评论最好

**Comment by Shigma** [comment]
> 你这个应该是 dup 了，继续在那个 issue 下面评论最好

理论上这都应该单独再开一个 issue 的（

**Comment by NWYLZW** [comment]
好吧，我感觉还是那个建表的问题，所以觉得 dup 了

**Comment by Monkeysama** [comment]
同一个问题，我猜测是某些原因导致建表语句里缺少了字段名

**Comment by NWYLZW** [comment]
> 同一个问题，我猜测是某些原因导致建表语句里缺少了字段名

不说我都忘记关了，这个 bug 已经修复了，暂时还没有发版
