### ISSUE TITLE
[Bug?]: session.bot is undefined 

### ISSUE THREAD

**Issue by beetcb** [koishijs/koishi#240]
**Describe the bug**
https://github.com/koishijs/koishi/blob/1f4f187613ff1af443486c0e9a621da8ba777fd5/packages/koishi-core/src/session.ts#L165-L171

go-cqhttp 配置好后，此处代码中 `this.bot` 是 `undefined`，导致出现消息事件时报错：
```js
Cannot read property 'Symbol(koishi.session.send)' of undefined
```
**To Reproduce**
- 事件上报方式：websocket
- 源码：[beetcb/qbot](https://github.com/beetcb/qbot)
- 源码 DEV 方式：
    1. 下载 `go-cqhttp` binary 到 `qbot/build`，在 `config.yml` 里配置好账号
    2. `npm i & npm run build`
    3. `npm run bot`

**Expected behavior**
我记得前几次成功过，现在突然报错，从这个 Commit 开始 https://github.com/beetcb/qbot/commit/99defbeb3e3d5d0a68402ac9f3b841a37d9e1b8e （这个时候还用的是 HTTP 上报）

**Screenshots**

koishi:

![image](https://user-images.githubusercontent.com/63141491/115240040-f16ff000-a151-11eb-96d6-e739a0d4e109.png)

cqhttp:

![image](https://user-images.githubusercontent.com/63141491/115240144-0ba9ce00-a152-11eb-814b-3b2c76685b0f.png)

**Versions**

- OS: Windows 10
- Node Version: v15.8.0
- CQHTTP Version: go-cqhttp@v1.0.0-beta2
- Koishi Version: 3.9.1

**Additional context**

`go-cqhttp` API 一切正常（测试过），koishi 前几天也正常运行，今天无论是 linux 上和本地 windows 都报此错误

希望作者帮忙看看，感谢 @Shigma

**Comment by beetcb** [comment]
`config` 缺失 `selfId`，已解决 😂

建议把文档中的 [构造函数选项](https://koishi.js.org/api/app.html#%E6%9E%84%E9%80%A0%E5%87%BD%E6%95%B0%E9%80%89%E9%A1%B9) 在 `指南#通过脚本调用 Koishi` 中也引用一下，不然和我一样使用 Node 的同学容易迷路 @Shigma

**Comment by Shigma** [comment]
了解了。
