### ISSUE TITLE
不需要权限校验使用command的api

### ISSUE THREAD

**Issue by NWYLZW** [koishijs/koishi#242]
**Is your feature request related to a problem? Please describe.**
假设shot命令权限是4
我现在对shot命令进行了封装
例如用户执行

> 谷歌 koishi是什么

我会调用shot命令返回一个图片给用户

> `session.excute('shot https://google.com/search?q=什么是koishi')`

但是普通用户的权限是1
会触发无权限错误

**Describe the solution you'd like**
以某个用户的身份执行excute
`suExcute('onebot:123456', 'shot https://google.com/search?q=什么是koishi')`
以最高权限执行excute
`superExcute('shot https://google.com/search?q=什么是koishi')`

**Describe alternatives you've considered**
null

**Additional context**
null

**Comment by Shigma** [comment]
我觉得这个需求可以通过让 puppeteer 暴露接口来解决。不应该试图绕过 command 的检测。

**Comment by NWYLZW** [comment]
是可以通过让`puppeteer`暴露一个api出来解决

我主要是觉得用我的解决办法，可以解决其他情况下的问题

* 管理员想以某个用户的身份去执行命令
  假设`todos.add -u @body 解决#233issue`
  内部逻辑就可以`suExcute(user, 'todos.add 解决#233issue')`
  用于解决这个问题的话就是`suExcute(admin, 'shot https://google.com/search?q=什么是koishi')`

* 在沙盒环境执行代码(套娃)
  假设有一段脚本我想
  普通用户也能在沙盒环境下执行`excute('> send(${msg})')`
  eval指令我不想暴露给任何用户
  这个时候我就能用`superExcute('> send(${msg})')`
  同样也能解决issue提出的这个问题

**Comment by Shigma** [comment]
1. 绕过 authority 检测不具备一般性。你的做法不如直接改 user.authority，无需大费周章定义新的方法。
2. 同理沙盒有暴露的方法，请参考 eval 插件文档。

**Comment by NWYLZW** [comment]
1. user.authority的修改可能造成权限问题（升权可能导致并发多个指令时，越权情况出现）
  第一个想法的目的是为了方便切换用户执行脚本
2. 我不清楚eval有暴露出来的api，所以举的例子有点问题
  我的目的是以最高权限临时执行某个指令

**Comment by Shigma** [comment]
如果要官方实现，也只会采用我说的办法。如果你觉得这个办法不安全，那么说明这个功能本身不安全。

**Comment by NWYLZW** [comment]
好的

**Comment by NWYLZW** [comment]
其实我的设想是这样子的
```ts
const auth = option.user.auth ?? option.auth ?? session.user.auth
if (auth < cmd.auth) throw new Error()
```
不过你觉得没必要也行，我用ppt的api吧。

**Comment by NWYLZW** [comment]
直接修改user.auth具有多线程下的不安全性
但是如果以某个用户执行，或者以最高权限执行就不会有这个问题了
* 以某个用户执行，或最高权限执行 是相对要执行的某个指令
* 若是直接修改用户auth则影响的是，处理阶段所有指令执行

就这样子

**Comment by Shigma** [comment]
> 不过你觉得没必要也行，我用ppt的api吧。

不是『没必要』而是『没法做』，权限检测是指令执行的一部分，用户没有办法只绕过一项检测而不绕过指令的执行。

如果你想修改用户对某个指令的权限，可以从指令本身入手：

```js
const shot = ctx.command('shot')
shot.config.authority = 1 // 先设置一个很低的权限
shot.check(({ session }) => {
  if (session._sudo) return
  return session.user.authority < 2 ? '权限不足' : undefined
})

// 然后当你要 sudo 的时候
session._sudo = true
session.execute('shot https://target-url')
```

**Comment by NWYLZW** [comment]
我尝试一下
