### ISSUE TITLE
文档点击过快导致侧栏异常

### ISSUE THREAD

**Issue by undefined-moe** [koishijs/koishi#247]
![image](https://user-images.githubusercontent.com/29992205/115997349-5d040280-a615-11eb-8bbc-cda86344847b.png)

**Comment by Shigma** [comment]
怎么个异常法啊 23333

**Comment by undefined-moe** [comment]
点一个侧栏，没加载完就点另一个，然后就会错乱（如图schedule的list放到ppt下面了

**Comment by Shigma** [comment]
哦哦！原谅我没看出来

**Comment by Shigma** [comment]
@undefined-moe 可能是网速问题，导致 AB 两次请求按照 BA 回来了

**Comment by Shigma** [comment]
文档已支持 SW，应该能够有效解决此问题。@undefined-moe 你看看现在还有吗？

**Comment by undefined-moe** [comment]
还有的 
![image](https://user-images.githubusercontent.com/29992205/117099022-aafdd080-ada2-11eb-846b-227072f9a0f4.png)

**Comment by Shigma** [comment]
是 vuepress-next 的问题，与这个仓库没有关系。如果有需求的话可以去那边提（我其实私下里反馈过）。
