### ISSUE TITLE
plugin-webui 的数据统计更新的 SQL 语句报错

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#248]
**Describe the bug**

这个是中途报错
![image](https://user-images.githubusercontent.com/29368226/116062693-ba03c500-a6b6-11eb-9004-0f76de08ebd7.png)

这个是手动终止程序后报错
![image](https://user-images.githubusercontent.com/29368226/116063102-24b50080-a6b7-11eb-90e5-9bd4f8e92e18.png)

估计问题就是出在这个最后一项（undefined 和 NaN），不知道这一项是什么
另外，我的 webui 过了一周也还是没有数据，估计也和这个东西有关

可能是 3.9.1（含）之后引入的 bug，因为这之前一直没报 Warning 或者已经有了只是没报
删库（删掉所有 stats 开头的表）不能解决这个问题

**Versions**

koishi@3.9.2
koishi-plugin-mysql@3.3.1
koishi-plugin-webui@4.4.0

**Comment by Shigma** [comment]
研究了一下，直接原因应该是某个 session 没有 subtype。这很好修，但是目前尚不清楚是什么样的 session 会没有 subtype。
