### ISSUE TITLE
plugin-teach 中标点符号和空格在正则问题中仍然会被处理掉

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#249]
**Describe the bug**

举个例子，如果想让问题是一个问号，下面的方法是触发不了的
![wut](https://user-images.githubusercontent.com/29368226/116066114-495ea780-a6ba-11eb-96ca-279d86c07477.png)

另外，使用空格 + 捕获组的问题会因为空格失效而导致捕获组的捕获出问题
这些原因可能是因为在正则问题里，空格和标点符号会仍然被处理掉（就像在一般问题里一样），但是这很可能是不被期望的。因为使用正则通常表明使用者自身很清楚想要实现一个怎样的问题匹配。

其实这是 plugin-teach 的一个陈年老 unexpected behavior 了，只是现在提一下

**Comment by idlist** [comment]
补充一下，这个示例问题在数据库里长这样 

![image](https://user-images.githubusercontent.com/29368226/116067243-8f683b00-a6bb-11eb-8078-7a637193169e.png)

**Comment by idlist** [comment]
转发，同源问题

【活跃】undefined 12:25:07
# roll(\d+) ${Math.floor((Math.random()$1+1)}

【活跃】 int main(){ return -1; } 12:25:08
问答已添加，编号为 2358。

【活跃】undefined 12:25:12
#2358 -x

【活跃】 int main(){ return -1; } 12:25:13
问题含有错误的或不支持的正则表达式语法。

【活跃】undefined 12:25:30
# roll([0-9]+) ${Math.floor((Math.random()$1+1)} -x

【活跃】 int main(){ return -1; } 12:25:31
问答已添加，编号为 2359。

【活跃】undefined 12:25:37
#2358 -r

【活跃】 int main(){ return -1; } 12:25:39
问答 2358 已成功删除。

【活跃】undefined 12:25:39
roll 6

【活跃】undefined 12:25:46
roll6

【活跃】undefined 12:25:50
?

【活跃】undefined 12:25:57
#2359

【活跃】 int main(){ return -1; } 12:25:58
编号为 2359 的问答信息：
正则：roll([0-9]+)
回答：${Math.floor((Math.random()$1+1)} -x}
生效环境：本群
来源：undefined (3402182471)

【活跃】undefined 12:26:16
#2359 ~ ${Math.floor((Math.random()$1+1)}

【活跃】 int main(){ return -1; } 12:26:17
问答 2359 已成功修改。

【活跃】undefined 12:26:34
#2359 roll(.+)

【活跃】 int main(){ return -1; } 12:26:34
问题含有错误的或不支持的正则表达式语法。

**Comment by undefined-moe** [comment]
这大概不是同一个问题
我那个是

```
【活跃】 int main(){ return -1; } 12:25:58
编号为 2359 的问答信息：
正则：roll([0-9]+)
回答：${Math.floor((Math.random()$1+1)} -x}
生效环境：本群
来源：undefined (3402182471)
```
 
它参数识别有点锅

**Comment by undefined-moe** [comment]
*符号是被discord吃了 不是koishi的问题

**Comment by undefined-moe** [comment]
~~虽然这也是个问题~~

**Comment by idlist** [comment]
> 这大概不是同一个问题
> 我那个是
> 
> ```
> 【活跃】 int main(){ return -1; } 12:25:58
> 编号为 2359 的问答信息：
> 正则：roll([0-9]+)
> 回答：${Math.floor((Math.random()$1+1)} -x}
> 生效环境：本群
> 来源：undefined (3402182471)
> ```
> 
> 它参数识别有点锅

没看源码，但我盲猜 Shigma 是先手动解析了一道正则，然后保留了有效正则，去掉了“无效”正则，然而去掉的过程有点问题
所以我觉得是同源

**Comment by undefined-moe** [comment]
那也不该在-x后面补}吧

**Comment by idlist** [comment]
> 那也不该在-x后面补}吧

意思回答的 AST 解析也有问题
那的确是另一个问题，所以你这段里有两个问题 🤔
