### ISSUE TITLE
Question: how to listen on the event being kicked from a group?

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#255]
I'm trying to make a dice bot with Koishi.js, in which the event bot itself being kicked from a group should be listened on because of the community.
However, the below code doesn't work..
```ts
    groupCtx.on('group-member-deleted/passive', async (session) => {
      if (
        session.userId !== this.botConfig.selfId ||
        session.operatorId === this.botConfig.selfId
      ) {
        return;
      }
      this.botService.log.error(
        `Got kicked by ${session.operatorId} in group ${session.groupId}`,
      );
      // do something
    });
```

Asking for help.. Thanks for reply in advance.

**Comment by Shigma** [comment]
Can your provide your platform? It seems that some platforms do not support the `group-member-deleted` event.

**Comment by purerosefallen** [comment]
On mirai Docker image made by myself.
https://github.com/purerosefallen/docker-mirai-cqhttp

**Comment by Shigma** [comment]
Sorry, I mean your adapter 😆

**Comment by NWYLZW** [comment]
I guess it is `onebot-adapter`.
Because he said `cqhttp`.

**Comment by Shigma** [comment]
Well that's weird, I will see later if it can be reproduced.

**Comment by purerosefallen** [comment]
May I ask if the above code is correct to handle the bot being kicked?

**Comment by Shigma** [comment]
You got the point. Maybe you should try `group-deleted/passive` instead.

| koishi | cqhttp |
| :-: | :-: |
| group-added | group_increase (user_id == self_id) |
| group-member-added | group_increase (user_id != self_id) |
| group-deleted | group_decrease (user_id == self_id) |
| group-member-deleted | group_decrease (user_id != self_id) |

**Comment by purerosefallen** [comment]
This one works, but... the operatorId stays 0.
