### ISSUE TITLE
Suggestion: use decorators to make a plugin

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#259]
**Is your feature request related to a problem? Please describe.**
Nope, but develop a plugin more convenient.

**Describe the solution you'd like**
I wish we could develop a plugin in the below way, to use decorators in class.

The following is an example.

`some-plugin.ts`
```ts
import * as koishiPluginCommon from 'koishi-plugin-common';

@Plugin('my-plugin') // plugin name goes here
export class MyPlugin extends AbstractPlugin {
	@Context()
	context: Context; // if context needs to be here..

	@Config({default: {}}) // the 2nd param of installing a plugin
	config: MyPluginConfig;

	@Group('1111111111')
	@Middleware({ prepend: false }) // ctx.group('1111111111').middleware(...)
	async myMiddleware(session: Session, next: NextFunction) {

	}

	@OnEvent('group-request') // //ctx.on('group-request')
	async onGroupRequest(session: Session) {

	}

	@Comamnd('echo <message:string>') // a way of writing command
	@Usage('Usage text of echo command')
	@AddOption('some_option', '--some-option') // add an option going to argv
	async onEchoCommand(
		@Argv() argv: ArgvObject,
		@Args(0) args: string, // the nth arg
		@Option('another_option', '--another-option <param:string>') param: string, // add another option in this way
	) {
		return message;
	}

	@ImportPlugin() // ctx.plugin(koishiPluginCommon, {})
	async importKoishiPluginCommon() {
		return [koishiPluginCommon, {}]; // the 2nd param is config
	}
}
```

**Describe alternatives you've considered**
In fact I hope for a bot framework in Nest.js.. Because every chatbot development is somehow something under MVC development.

**Additional context**

**Comment by NWYLZW** [comment]
Good idea.
The type support of decorators in TypeScript is not very good, it will be very troublesome to implement, of course it is also possible.

**Comment by NWYLZW** [comment]
There will be more redundant code like this.

**Comment by Shigma** [comment]
I'm not so familiar with decorators, can you provide a supposed transpiled result for the code above? I just don't know how can I turn class methods into context calls.

**Comment by NWYLZW** [comment]
Decorator has to be matched with Reflect

**Comment by purerosefallen** [comment]
@Shigma I'm planning to make an implement of the above `AbstractPlugin`..
~~When I'm not so busy~~

*I mainly develop bots with Koishi.js for my company use.. The boss of it is very evil.*

**Comment by Shigma** [comment]
Supported by koishi-dev-utils.
