### ISSUE TITLE
adapter-discord 分段发送失败时继续发送后面的部分

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#267]
**Is your feature request related to a problem? Please describe.**

有时候消息夹杂图片，adapter-discord 的行为是将消息分段发送，一旦图片发送失败，后面的内容就不会发送。

例如有这样一个信息：

```
前面的文字
[图片]
后面的文字
```

如果图片发送失败，后面的文字就无了。

**Describe the solution you'd like**

希望在某段信息发送失败后，继续发送后面的片段。

**Describe alternatives you've considered**

**Additional context**

**Comment by Shigma** [comment]
我觉得可以。不过这样一来，如果中间某些片段发不出去，就应该抛出一个 AggregateError，这是 Node 15 的特性。需要考虑一下是引入 polyfill 还是强制用户升级（

**Comment by Dragon-Fish** [comment]
目前主流的 Node 版本应该依然是 12 和 14，强迫用户升级可能不太现实

**Comment by Shigma** [comment]
那就等到用户都升到 16 以后实装这个特性好了（

**Comment by Dragon-Fish** [comment]
那怕是要等 114514 年

**Comment by Shigma** [comment]
这个 polyfill 我觉得可以接受：https://github.com/es-shims/AggregateError

然后可能需要 utils 里面开个后门处理 AggregateError 的错误信息。
