### ISSUE TITLE
发送群消息时返回错误

### ISSUE THREAD

**Issue by muyuqingqiu** [koishijs/koishi#271]
koishi版本是v3
后端是cqhttp-mirai-0.2.1
调用bot.sendMessage发送群消息时报错
![B7923992-1185-4443-95EE-A5F8B0E03481](https://user-images.githubusercontent.com/17589155/117809075-45bd4a00-b290-11eb-8901-ed4cf33e719e.png)

**Comment by idlist** [comment]
请附上导致这一原因的代码片段和可能相关的 App 配置，就这一张图看不出是什么原因。

**Comment by muyuqingqiu** [comment]
![5F5378E7-F503-45EE-8531-6F90B7C17D88](https://user-images.githubusercontent.com/17589155/117917327-6b436580-b31b-11eb-8c8a-7640ec17a191.png)
![C4BA1C0E-2E91-47FC-84A1-634CA5826F25](https://user-images.githubusercontent.com/17589155/117917365-7f876280-b31b-11eb-86ff-ce09d02d1de6.png)


![11AB0571-CDED-4114-BCDF-2767F87EE33D](https://user-images.githubusercontent.com/17589155/117917408-9463f600-b31b-11eb-989e-fcfc2b8c8d43.png)


app配置和发送消息的代码，很简单。
查看了下mirai的输出，没有报错。。

**Comment by NWYLZW** [comment]
你的插件写法似乎有点不对
你的目的是不是插件绑定时，给指定用户发送消息？

**Comment by NWYLZW** [comment]
另外，或许可以尝试一下 ws（万一见鬼了呢

**Comment by muyuqingqiu** [comment]
> 你的插件写法似乎有点不对
> 你的目的是不是插件绑定时，给指定用户发送消息？

这个只是在测试。实际上我直接用curl发送http请求一样返回这个错误。
目前条件就是只能用http。。。我也没办法orz

**Comment by NWYLZW** [comment]
> > 你的插件写法似乎有点不对
> > 你的目的是不是插件绑定时，给指定用户发送消息？
> 
> 这个只是在测试。实际上我直接用curl发送http请求一样返回这个错误。
> 目前条件就是只能用http。。。我也没办法orz

你如果使用 curl 发 http 请求报错，那就不是 koishi 的问题了
你或许可以试试我写的这篇[教程](https://juejin.cn/post/6960919929109348366)

**Comment by NWYLZW** [comment]
另外我觉得你想要的写法应该通过[connect 事件](https://koishi.js.org/api/events.html#%E4%BA%8B%E4%BB%B6-before-connect)去触发

**Comment by NWYLZW** [comment]
（以下是我的猜测
插件加载的时候，bot 可能并没有连接，你不应该直接在插件中直接发送消息给用户
这个时候 bot 是很有可能没有连接的

**Comment by muyuqingqiu** [comment]
> > > 你的插件写法似乎有点不对
> > > 你的目的是不是插件绑定时，给指定用户发送消息？
> > 
> > 
> > 这个只是在测试。实际上我直接用curl发送http请求一样返回这个错误。
> > 目前条件就是只能用http。。。我也没办法orz
> 
> 你如果使用 curl 发 http 请求报错，那就不是 koishi 的问题了
> 你或许可以试试我写的这篇[教程](https://juejin.cn/post/6960919929109348366)

好的，我看一下，非常感谢。

**Comment by idlist** [comment]
是写法的问题，发消息必须在 `ctx.on('connect')` 之后发，直接这么写是不行的。

以及我翻了一下文档，现在的教程实在没有 `ctx.bot[0].sendMessage()` 的写法了……除非你有必须这么做的理由（比如 `dcqq-relay`），否则直接调用`ctx.bot[id].method()` 的写法是不推荐的。

**Comment by NWYLZW** [comment]
我也觉得
