### ISSUE TITLE
有关 koa router 构建的一个未考虑情况

### ISSUE THREAD

**Issue by NWYLZW** [koishijs/koishi#272]
**Is your feature request related to a problem? Please describe.**

当我想创建一个挂载到 ctx.router 下的子路由的时候
必须描述下面的代码
`router[Context.current] = ctx`
使用起来有一些奇怪

**Describe the solution you'd like**

暂时没有好的想法，如果可以补一份文档或许不错（我准备 pr

**Describe alternatives you've considered**

暂无

**Additional context**

**Comment by Shigma** [comment]
Fixed by c215069c005e7253b5ca42352fa74133174505fa
