### ISSUE TITLE
无法开启反向ws模式

### ISSUE THREAD

**Issue by muyuqingqiu** [koishijs/koishi#273]
**Describe the bug**

无法开启反向ws模式
**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**

- OS: [e.g. iOS] linux
- Node Version: [e.g. 10.16.0] 12
- go-cqhttp Version: [e.g. 5.15.4] 1.0beta3
- Koishi Version: [e.g. 1.0.0] 最新

**Additional context**

搞不清楚反向ws的配置应该如何写。目标是后端ws连接到koishi开启的8181端口。目前试了很多种如
port: '8180',
type: 'onebot:ws-reverse',
path:'/ws',
server: 'ws://0.0.0.0:8181',
或
port: '8181',
type: 'onebot:ws-reverse',
server: '0.0.0.0',
或
port: '8181',
type: 'onebot:ws-reverse',
server: 'ws://0.0.0.0:8181',
或
port: '8180',
type: 'onebot:ws-reverse',
server: 'ws://0.0.0.0:8181/ws/'
后端均无法连接。

使用的后端 go-cqhttp

后端配置

![1441279A-3AB3-4A88-80AD-1DBFB12E73C1](https://user-images.githubusercontent.com/17589155/118244183-d9ca2400-b4d1-11eb-98ce-b6fbe0aecb70.png)

后端报错

![2B588A5D-B9B9-4859-BC66-7DA7C3F90EAA](https://user-images.githubusercontent.com/17589155/118244257-ed758a80-b4d1-11eb-83f0-f6d02c519053.png)

**Comment by muyuqingqiu** [comment]
当配置为
port: '8180',
type: 'onebot:ws-reverse',
path:'/ws',
server: 'ws://0.0.0.0:8181',

koishi这边的输出只有

![F50450FF-A822-41E7-892E-22AA4ED18F44](https://user-images.githubusercontent.com/17589155/118245075-e7cc7480-b4d2-11eb-87fc-0c9d9e17047b.png)

**Comment by idlist** [comment]
没用过 `ws-reverse`，参考 [文档](https://koishi.js.org/api/adapter/onebot.html#options-bots-server) 和 [更新日志](https://koishi.js.org/api/changelog.html#koishi-3-8-0) 盲猜可能是

```js
// koishi.config.js
type: 'onebot:ws-reverse',
server: 'ws://localhost:8180'
```

```yaml
# config.yml
disable: false
universal: 'ws://localhost:8180/onebot'
```

`koishi.config.js` 中 `path` [只在 `http` 模式中有用](https://koishi.js.org/api/adapter/onebot.html#options-onebot-path)，而 `port` 是指 `koishi` 自身服务使用的 `port`，和 bot 与 go-cqhttp 之间的连接无关，所以这两个项不会是问题的原因。

以及 大家基本上都用 `ws` （跑）

**Comment by Shigma** [comment]
反向的话，先启动 koishi 再启动 gocq 试试？

**Comment by Shigma** [comment]
已确定此问题存在，正在修复。

**Comment by Shigma** [comment]
@muyuqingqiu bad handshake 是因为 `path` 配置项应该写在 `options.onebot` 中：

```js
// koishi.config.js
module.exports = {
  onebot: {
    path: 'ws',
  },
  port: '8181',
  type: 'onebot:ws-reverse',
  server: 'ws://0.0.0.0:8181',
}
```

**Comment by muyuqingqiu** [comment]
> @muyuqingqiu bad handshake 是因为 `path` 配置项应该写在 `options.onebot` 中：
> 
> ```js
> // koishi.config.js
> module.exports = {
>   onebot: {
>     path: 'ws',
>   },
>   port: '8181',
>   type: 'onebot:ws-reverse',
> }
> ```
> 
> 此外，ws-reverse 协议不需要提供 server。

尝试了这个写法。。。还是提示bad handshake
![1695FDEB-9D79-403B-BDAE-C6B28537A206](https://user-images.githubusercontent.com/17589155/118429204-b8e91500-b703-11eb-957a-a328a8ac84df.png)

**Comment by Shigma** [comment]
@muyuqingqiu 你这里还有一个 slash 问题。得把 gocq 的配置改成 `ws://0.0.0.0:8081/ws`。

**Comment by muyuqingqiu** [comment]
> 你这里还有一个

可以了，十分感谢！
顺便提个建议，希望能把启动app的配置再写详细一些，或者干脆针对每种模式写个实例。上面给出的写法如path写在onebot下面和反向ws不需要server等我在文档中找了很多次也没找到。花了不少时间在这个问题上。

**Comment by Shigma** [comment]
草，这就可以了，我这明明还有报错的来着（惊

**Comment by Shigma** [comment]
@muyuqingqiu 更新了文档：https://koishi.js.org/api/adapter/onebot.html#%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83
