### ISSUE TITLE
使用 koishi init 之后生成的 koishi.config.js 没给含有短横线的 key 值自动加引号导致语法错误

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#275]
**Describe the bug**

如题
以防万一又又又又忘了，想起来先记一下

**Screenshots**

现在的情况是
![image](https://user-images.githubusercontent.com/29368226/118598938-641bcc00-b7e1-11eb-84f5-3a6620072c55.png)

应该是
![image](https://user-images.githubusercontent.com/29368226/118599022-831a5e00-b7e1-11eb-823c-17046c9da250.png)

或者为了（迫真）一致性，给plugin底下的key全加上单引号也不错:thinking:

- Koishi Version: [e.g. 1.0.0] 从DC群抓的，我也不知道.jpg

**Comment by Shigma** [comment]
我觉得可以自动把 camelCase 转成 param-case。
