### ISSUE TITLE
无法发送带图片的私聊消息

### ISSUE THREAD

**Issue by NWYLZW** [koishijs/koishi#276]
**Describe the bug**
无法发送带图片的私聊消息

**To Reproduce**
当我尝试使用 `session.bot.sendPrivateMessage` 这个 api 发送带图片消息的时候，我无法成功发送消息
已经尝试了多种方式发送，base64、url、file，均不可以

**Expected behavior**
成功在私聊中发送图片给指定的用户

**Screenshots**
![image](https://user-images.githubusercontent.com/51358815/119105368-d42f8980-ba4f-11eb-8c1a-349cbce81c07.png)
![image](https://user-images.githubusercontent.com/51358815/119105397-dabe0100-ba4f-11eb-826e-b5488fa05549.png)
![image](https://user-images.githubusercontent.com/51358815/119105418-e01b4b80-ba4f-11eb-81e4-7a923cd5537d.png)
![image](https://user-images.githubusercontent.com/51358815/119105443-e7425980-ba4f-11eb-8954-c7b56a7ba0c5.png)
当我使用 session.send 时可以正常发送
![image](https://user-images.githubusercontent.com/51358815/119105500-f75a3900-ba4f-11eb-8c16-db03d17f6ecc.png)

**Versions**
3.11.0

- OS: win
- Node Version: 14.16.0
- CQHTTP Version: v1.0.0-beta3
- Koishi Version: 3.11.0
- koishi-adapter-onebot Version: 3.0.8

**Additional context**
none

**Comment by Shigma** [comment]
Mrs4s/go-cqhttp#914

**Comment by Shigma** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/914#issuecomment-955187759
