### ISSUE TITLE
考虑对Discord的一图一文消息进行拼接发送

### ISSUE THREAD

**Issue by wfjsw** [koishijs/koishi#279]
**Is your feature request related to a problem? Please describe.**
目前Discord发送带图消息使用图文分离发送方法，会导致完整的一条消息被从中间割裂，影响阅读体验。

**Describe the solution you'd like**
Discord原生支持图片前附带文字消息，可以用这种方式将文字与图片相应结合作为一条消息发送。可选的，将图片后的文字同样合并到一条消息中发送。对于多图消息不做处理。

**Comment by Shigma** [comment]
说的有道理。我之后做一下。
