### ISSUE TITLE
MongoDB数据库支持

### ISSUE THREAD

**Issue by fzxiao233** [koishijs/koishi#28]
话不多说，总之我有时间就来写

没时间...咕咕咕

**Comment by simon300000** [comment]
level数据库用起来是有点问题对吧？

**Comment by fzxiao233** [comment]
> level数据库用起来是有点问题对吧？

sdy

**Comment by simon300000** [comment]
> > level数据库用起来是有点问题对吧？
> 
> sdy

有没有可能描述一下，或者需要的话，新开一个issue？

**Comment by Shigma** [comment]
level 是有什么问题（捂脸

**Comment by simon300000** [comment]
_这锅我大概要背一半_

**Comment by Shigma** [comment]
稍微提一下，Koishi v2 中将没有 koishi-database-mysql 这种包，改为 koishi-plugin-mysql。也就是说数据库也会以插件的形式实现。如果这里想直接为 v2 提供支持的话就参考一下 next 分支的 mysql 实现好了。
