### ISSUE TITLE
如何进行错误处理

### ISSUE THREAD

**Issue by Ice-Hazymoon** [koishijs/koishi#285]
**Describe the bug**
cqhttp返回错误时程序直接退出，应该如何进行错误处理

比如一个检测关键词禁言功能，如果禁言的用户为管理员，cqhttp就会返回错误

```
koishi-adapter-onebot\lib\index.js:334
      throw new SenderError(params, action, retcode, this.selfId);
            ^

SenderError: Error when trying to send to set_group_ban, args: {"group_id":"xxx","user_id":"xxx","duration":60}, retcode: 100
    at CQBot.get (Desktop\Project\bot\node_modules\koishi-adapter-onebot\lib\index.js:334:13)
    at async CQBot.<computed> [as $setGroupBan] (Desktop\Project\bot\node_modules\koishi-adapter-onebot\lib\index.js:437:18)
```

- OS: windows 10
- Node Version: v16.2.0
- CQHTTP Version: v1.0.0-beta4
- Koishi Version: 3.11.2

**Comment by Shigma** [comment]
这个其实是 node 16 导致的。可以使用下面的方法解决：

1. https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode
2. 自己在调用 `bot.setGroupBan()` 的时候就 catch 一下
3. 试试社区插件 koishi-plugin-blame（我不确定能用，但是好像不少人用过）

**Comment by Ice-Hazymoon** [comment]
谢谢
