### ISSUE TITLE
fileUrl

### ISSUE THREAD

**Issue by Thefangyi** [koishijs/koishi#286]
telegram: {
    selfUrl: '',
    path: '',
  },

app Error: missing configuration "selfUrl"
请问selfUrl应该如何配置，原谅我看文档实在是看不明白，，
然后discord的群是交流群吗，好像点github的链接进不去诶

**Comment by idlist** [comment]
selfUrl是能解析到你自己的服务器的网址或者ip地址：端口
比如我的bot的selfUrl就是 http://bot.idl.ist:21919/

以及discord需要科学上网

**Comment by Shigma** [comment]
selfUrl 的意思是，tg **需要你的 koishi 能够在公网被访问**。koishi 会开放一个端口（比如 port: 8080），然后假如你的 ip 是 1.2.3.4 那 selfUrl 就应该是 https://1.2.3.4:8080。当然如果是 SSL 你还需要处理证书。

**Comment by Shigma** [comment]
@Thefangyi 啊顺便 discord 要翻墙。如果不具备条件也欢迎在 [discussions](https://github.com/koishijs/koishi/discussions) 提问。
