### ISSUE TITLE
统一的前置信息处理、传递，与统一的错误处理

### ISSUE THREAD

**Issue by ReiKohaku** [koishijs/koishi#287]
**特性描述**
1. 在**命令解析完毕**，所有**check**方法**执行完毕**，首个**action**方法**执行之前**（亦或是在**check**之中），允许开发者进行一些统一的处理（例如从某个API获取数据），然后**将需要的值放入某处**（如**Argv**），方便在**action**中调用。
2. 在**action**函数执行时，若抛出异常，将进入一个**统一的处理函数**。该函数的首个参数为抛出的错误，其余参数与**action**的参数完全一致：即统一的错误回调处理，方便开发者统一地处理运行中错误，并通过诸如`argv.session.send()`之类的函数告知用户。

----

**理想中的调用方案**
这两个需求，希望可以在整个应用（App）、整个插件（`app.plugin`）以及整个命令（不含子命令，`context.command`）中设置。

如果为整个应用设置，则应用中加载的所有插件都会应用这些处理：
```typescript
import {App} from "koishi-core";
const app: App = new App({ /* Something */ });
app.prepend(async (argv, ...args): unknown => {
    // 统一前置处理
    // 此处的argv和args[]参数，均与action中的相同
    // 同时，应当允许使用异步参数
    const apiData = await myApi(argv.session?.platform, argv.session?.userId);
    return apiData;
    // 此处返回的返回值，将会置入所有命令的argv参数之中，例如argv.prepend.app
})
app.on("command-error", async (error, argv, ...args): string | undefined => {
    // 统一错误回调处理
    const errorMsg = await myErrorApi(error.toString());
    if (errorMsg) argv.session?.send(errorMsg);
    // 或使用 return errorMsg，但其实无论返回 string 还是 undefined，这个会话都到此为止了
})
app.start().catch(console.error);
```

如果为整个插件设置，则插件中声明的所有命令都会应用这些处理：
```typescript
app.plugin((context, options) => {
    /* Something */
    context.prepend(/* 和上面前置处理相同种类的函数，返回值置入argv参数中，如argv.prepend.plugin */)
    context.on("command-error", /* 和上面错误回调相同种类的函数 */)
})
```

如果为单个命令设置，则它和它的子命令都会应用这些处理：
```typescript
const cmd = context.command("my-command")
    .prepend(/* 和上面前置处理相同种类的函数，返回值置入argv参数中，如argv.prepend.command */)
    .error(/* 和上面错误回调相同种类的函数 */)
cmd.subcommand("my-subcommand") // 这个子命令将会应用上面它的父命令的prepend和error函数
```

----

**备注**
也许已经有了这个问题的解决方案，但我觉得提供一种方便的解决方案是很有必要的。
*如果是我眼瞎就直接把这个issue关了吧（瘫）*

**Comment by Shigma** [comment]
@ReiKohaku 感谢您的建议！

1. 事实上我现在已经觉得 check+action+before-command+command 的拆分方式过于细碎了，如果未来还有 koishi v4 的话我甚至可能取消 check 机制（当然短期内不可能）。钩子它是这样一回事，你无论设置多少个，总会有人需要在中间的某个地方插入新的。你提出的需求是有意义的，我会尝试解决，但是大概不会通过这种方案。
2. command-error 事件可以做。

**Comment by Shigma** [comment]
很抱歉过去这么久才进一步回复……你提出的所有需求都将会在 koishi v4 的正式版得到解决，下面是一份简单的介绍，未来我们会在文档中具体说明这些特性：

![image](https://user-images.githubusercontent.com/33423008/147568900-e53788bf-0da8-42ae-8382-01aae72d57e9.png)

**Comment by Shigma** [comment]
已经在 v4 解决，之后可查看相关文档。
