### ISSUE TITLE
[Bug?] Windows 下私聊发送 Base64 图片发不出去

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#288]
**Describe the bug**

Windows 下私聊发送 Base64 图发不出去，go-cqhttp 提示这个：
![1](https://user-images.githubusercontent.com/29368226/121810265-bd690500-cc92-11eb-9b32-2065d4fea31f.png)

Koishi 报这个
![2](https://user-images.githubusercontent.com/29368226/121810321-f5704800-cc92-11eb-912e-2f22ada9e9d1.png)
中略
![3](https://user-images.githubusercontent.com/29368226/121810341-0ae57200-cc93-11eb-910d-91fcb843e029.png)

同样的写法在 Linux 下能够发出图片，以及在 Windows 下发本地图片 (`file:///`) 是能发出去的。
和 #276 应该有一定关联，区别在于我使用了 `session.send()` 但也还是发不出去。
现在也尚不清楚是 go-cqhttp 的锅还是风控的锅还是 Koishi 的锅，但我用 go-cq 100b3 和 b4 测了一下发现都不行，所以 Koishi 的锅的可能性更高一点。

**To Reproduce**

在私聊下
```js
session.send(s('image', { url: `base64://${img.toString('base64')}` }))
```
尝试了修改成
```js
session.send(s('image', { file: `base64://${img.toString('base64')}` }))
```
但并不能解决问题。

**Versions**

- OS: Windows 10
- Koishi Version: 3.11.2
- go-cqhttp Version: 1.0.0-beta.3 & 1.0.0-beta.4 （两个版本都测了一下，都不行）

**Comment by Shigma** [comment]
你的 img 是 Buffer 吗？尝试直接打印这个 base64 看看浏览器能不能显示？

**Comment by idlist** [comment]
> 你的 img 是 Buffer 吗？尝试直接打印这个 base64 看看浏览器能不能显示？

不能，图会裂 🤔 

另外在群里发是没问题的，应该是 #276 相同问题了

**Comment by Shigma** [comment]
Mrs4s/go-cqhttp#914

**Comment by idlist** [comment]
万一有人遇到了同样的问题然后还点进来了：

试试 [这个](https://github.com/koishijs/koishi/discussions/270#discussioncomment-977496) ，虽然不一定有用。

**Comment by Shigma** [comment]
https://github.com/Mrs4s/go-cqhttp/issues/914#issuecomment-955187759
