### ISSUE TITLE
koishi 在 puppeteer 的 docker 镜像中无法运行

### ISSUE THREAD

**Issue by LF112** [koishijs/koishi#289]
**Describe the bug**
Docker buildkite/puppeteer:latest 容器内运行报错 Unexpected token
```bash
at Object.<anonymous> (/app/node_modules/koishi/index.js:1:80)
node_modules/koishi-core/lib/index.js:1259
  } catch {
          ^
```

**Screenshots**
![image](https://user-images.githubusercontent.com/35809783/121837044-4457c500-cd07-11eb-80de-5497faac84ac.png)
![image](https://user-images.githubusercontent.com/35809783/121837392-0d35e380-cd08-11eb-95c8-6a8b3b7c87bd.png)

**Versions**

- OS: Debian
- Node Version: 14.16.0
- CoolQ Version: v1.0.0-beta4
- CQHTTP Version: v1.0.0-beta4
- Koishi Version: ^3.11.2

**Comment by undefined-moe** [comment]
根据截图判断 这绝对不是 v14 的 node

**Comment by LF112** [comment]
解决了，NODE 版本过低
重新看了日志
![image](https://user-images.githubusercontent.com/35809783/121860293-4b90ca00-cd2b-11eb-92d0-8da3258dee44.png)

在 Dockerfile 文件内增加以下字段以解决:
```bash
RUN npm i n -g && n $(n --latest)
```
