### ISSUE TITLE
Discord 无法加入

### ISSUE THREAD

**Issue by SettingDust** [koishijs/koishi#290]
**Describe the bug**

README 中的 Discord 无法加入，显示无权限

**Comment by Shigma** [comment]
![image](https://user-images.githubusercontent.com/33423008/122210020-be3ea880-ced7-11eb-83f0-1f7be2a38fad.png)

是因为没有绑定电子邮件吗？

**Comment by SettingDust** [comment]
> ![image](https://user-images.githubusercontent.com/33423008/122210020-be3ea880-ced7-11eb-83f0-1f7be2a38fad.png)
> 
> 是因为没有绑定电子邮件吗？

我已经加入很多频道了

**Comment by Shigma** [comment]
那先试试这个链接：gg/8w5XZf6pxc

**Comment by SettingDust** [comment]
> 那先试试这个链接：gg/8w5XZf6pxc

ok, 进去了

**Comment by Shigma** [comment]
感谢反馈，已经修改 readme 中的链接。
