### ISSUE TITLE
auth 指令行为异常

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#292]
**Describe the bug**

指令：`auth -u <user> <authority>`

指令效果总是会作用于调用者本人，且未处理authority未定义的情况。

- 即使设置了`user`，也会作用到调用者头上
- 如果未设置`authority`会直接把调用者的权限设置为`null`

**To Reproduce**

- `auth -u xxx 2` → 调用者本人的权限变成了2
- `auth` → 调用者本人的权限变成了`null`
- `auth -u xxx` → 调用者本人的权限变成了`null`

**Expected behavior**

**Screenshots**

**Versions**

- OS: [e.g. iOS] Windows server 2016
- Node Version: [e.g. 10.16.0] 14.x
- OneBot: v1.0.0-beta4
- koishi: ^3.12.0
- plugin-common: ^4.2.7
- plugin-mongo: ^2.2.3

**Additional context**

**Comment by Shigma** [comment]
Fixed by 0d12bf.
