### ISSUE TITLE
检测频道删除相关事件

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi#294]
在 discord 中，如果频道被删除，将会导致 github 等主动推送的功能产生大批量报错。因此应该在频道被删除或更改权限时自动更新数据库。

**Comment by Shigma** [comment]
或者当检测到频道删除时，自动将该频道对应的 flag 自动修改为 silent

**Comment by Dragon-Fish** [comment]
需要检测 onebot 频道删除，不仅 GitHub，schedule 等一众插件也会疯狂报错

**Comment by H4M5TER** [comment]
bump
我觉得这是硬需求，当然优先级还需要调研一下

**Comment by shigma** [comment]
此功能交给插件侧做更合适。
