### ISSUE TITLE
[RFC] 移除 teach 插件中对于正则表达式的兼容性检测

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#299]
这个问题同样会影响使用 mongo 的用户，因此亟待解决。

好消息是 mariadb 支持 PCRE，经过我个人实测，现版本 NodeJS 所支持，而 MySQL 5.7 不支持的正则表达式语法都可以在 mariadb 10.5 中正常使用，包括：

- escape character set (`\d`)
- non-greedy quantifier (`+?`)
- word boundary assertion (`\b`)
- lookaround assertion (`(?=)`)
- non-capturing group (`(?:)`)

因此我觉得可以考虑移除 teach 插件中对于正则表达式的兼容性检测，并在文档中建议用户使用 mariadb。

参考：https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by Afanyiyu** [comment]
这是想移除一个已经存在的功能吗？另外，个人认为 5 年之后 MySQL 5.7 的用户也不会少多少

**Comment by idlist** [comment]
> 这是想移除一个已经存在的功能吗？另外，个人认为 5 年之后 MySQL 5.7 的用户也不会少多少

可以继续在文档中提醒 MySQL 5.7 用户不要使用不支持的正则表达式，即像现在这样列出 MySQL 5.7 支持的表达式。这样的话在实际表现上是没有区别的，只是不再强制检测了而已。

**Comment by Shigma** [comment]
文档已经修改。

**Comment by Shigma** [comment]
> 这是想移除一个已经存在的功能吗？另外，个人认为 5 年之后 MySQL 5.7 的用户也不会少多少

主要问题是插件之间应该是解耦的，强迫用户不使用许多关键的 PCRE 特性会导致 mongo 用户也受到影响。
