### ISSUE TITLE
Docs: is it a typo in adapter.md?

### ISSUE THREAD

**Issue by MaikoTan** [koishijs/koishi#313]
https://github.com/koishijs/koishi/blob/edb6d5cd785fba364839e5531ead070e8e8fc5bd/docs/guide/adapter.md#L29-L33

As you can see, the code below set `path` to `/event`, but the comment said that the `pathname` would be `/onebot` instead.
So is it a typo? Or does the `pathname` just ignore the `path` value and refer to the protocol name `onebot`?

Merci.

**Comment by undefined-moe** [comment]
I think it's a typo.

**Comment by Shigma** [comment]
thanks for report. will fix.
