### ISSUE TITLE
Feature request: Mirai support

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#32]

**Comment by Shigma** [comment]
我会持续关注 mirai 的开发，不过就目前而言它的 http api 还没有完善到 cqhttp 的程度（要知道 coolq 本身的 api 已经是较少的了），所以短时间内可能并不会做 mirai 的支持。

**Comment by masnn** [comment]
[Mirai-Go-cqhttp](https://github.com/Mrs4s/go-cqhttp) 已经有了较为完善的api。可考虑进行支持
除版本号相关操作异常外暂未发现其他问题。

**Comment by Shigma** [comment]
@masnn 谢谢你的提醒！next 分支已经补充了 go-cqhttp 的相关接口，将在下个大版本实装对其的支持。

https://github.com/koishijs/koishi/blob/7d485ecd7c97cab29ef9b6ee690fde045ed25ac5/packages/koishi-core/src/sender.ts#L402-L439

**Comment by Shigma** [comment]
由于 mirai 官方已经删库跑路，加上 go-cqhttp 已经能够较好地契合现在的 koishi，现在决定短期内不考虑适配 mirai-http-api 或类似的接口。

**Comment by UlyssesZh** [comment]
Mirai 以及 mirai-http-api 现在正在积极维护. 是否可以考虑适配?

**Comment by ilharp** [comment]
> Mirai 以及 mirai-http-api 现在正在积极维护. 是否可以考虑适配?

上面已经有写：

> go-cqhttp 已经能够较好地契合现在的 koishi。

你是遇到了某些场景下 mirai-http-api 比 go-cqhttp 更可用的情况吗？能否列举一下？

**Comment by shigma** [comment]
这个 issue 距离现在已经有两年多的时间了。如果你确实有此需求，我觉得可以新开一个 issue。

**Comment by UlyssesZh** [comment]
> 你是遇到了某些场景下 mirai-http-api 比 go-cqhttp 更可用的情况吗？能否列举一下？

我的 QQ 账号能用 mirai 登录而不能用 go-cqhttp 登录 (会提示密码错误或账号被冻结). 目前我的 workaround 是用 [yyuueexxiinngg/onebot-kotlin](/yyuueexxiinngg/onebot-kotlin).

虽然或许我再研究研究就能登录成功了, 但是 "go-cqhttp 能较好地契合 Koishi" 并不完全构成拒绝适配 Mirai 的理由, 文档中也指出 "在未来也可能出现其他面向 QQ 的适配器".

**Comment by shigma** [comment]
遵循开源的宗旨，我们永远欢迎任何人开发 Koishi 的适配器，例如 koishi-plugin-mirai 或 koishi-plugin-oicq。

**Comment by H4M5TER** [comment]
目前没有 mirai http api 和 oicq 的适配的主要原因是：
1. go-cqhttp 能用
2. 没有多余的人力
3. 看不到额外的好处
密码错误或账号被冻结的问题目前确实有遇到，workaround就是从其他地方挪token过去
