### ISSUE TITLE
koishi.config.js方式 "注入表" 需要哪些配置才会生效

### ISSUE THREAD

**Issue by nsioo** [koishijs/koishi#33]

**Comment by Shigma** [comment]
如果你要实现自己的表的话，只需要做这两件事：

1. 在数据库中添加你的表
2. 用 `injectMethods` 函数实现你所需要的方法

如果你使用 TypeScript，你还需要注入对应的类型。

**Comment by Shigma** [comment]
这个 issue 因长时间无人回复而关闭。如果问题未解决请重开一个新的 issue。
