### ISSUE TITLE
[BUG] 模拟数据库使用 `in`, `eq` 运算的时候无法合适的处理 Date 类型

### ISSUE THREAD

**Issue by NWYLZW** [koishijs/koishi#338]
**Describe the bug**
使用 test-util 的 mock database 的时候 `in`, `eq` 运算并不能很好的处理 Date 类型

**To Reproduce**
```ts
await app.database.get('XXX', {
  uid: '1', ctime: [new Date('2021-08-13T16:00:00.000Z')]
})
await app.database.get('XXX', {
  uid: '1', ctime: { $eq: new Date('2021-08-13T16:00:00.000Z') }
})
```

**Expected behavior**
能够正确的 include, equal 指定的这个 Date 类型数据

**Versions**

- Koishi Version: 3.13.0

**Comment by Shigma** [comment]
请提供实例代码

**Comment by NWYLZW** [comment]
> 请提供实例代码

刚刚不小心直接打了 ctrl + 回车，然后 issue 就直接发出去了
（不好意思

**Comment by Shigma** [comment]
Date 类型不是原始类型，不应使用 $in。这一点会在新版的 typings 中予以体现：

```ts
declare const expr: Query.FieldExpr<Date>
expr.$in // should be `never`
```

**Comment by NWYLZW** [comment]
数据库 Foo 中有如下数据
| id | ctime |
| ---- | ---- |
| 1 | '2021-08-13T16:00:00.000Z' |

使用如下 db query 的时候的判断会有问题
```ts
await app.database.get('Foo', {
  uid: '1', ctime: [new Date('2021-08-13T16:00:00.000Z')]
})
```

**Comment by Shigma** [comment]
或许这种情况下 memory db 可以报一个错，这部分我来做吧

**Comment by NWYLZW** [comment]
> Date 类型不是原始类型，不应使用 $in。这一点会在新版的 typings 中予以体现：
> 
> ```ts
> declare const expr: Query.FieldExpr<Date>
> expr.$in // should be `never`
> ```

$eq 操作符也出现了类似的问题，有关时间对比

`new Date('2021-08-13T16:00:00.000Z') === new Date('2021-08-13T16:00:00.000Z')`

如上，在 db 里面应该是 true

**Comment by NWYLZW** [comment]
> Date 类型不是原始类型，不应使用 $in。这一点会在新版的 typings 中予以体现：
> 
> ```ts
> declare const expr: Query.FieldExpr<Date>
> expr.$in // should be `never`
> ```

$eq 操作符也出现了类似的问题，有关时间对比

`new Date('2021-08-13T16:00:00.000Z') === new Date('2021-08-13T16:00:00.000Z')`

如上，在 db 里面应该是 true

**Comment by Shigma** [comment]
Fixed by 9a3775.
