### ISSUE TITLE
请问中间件可以处理加群等事件吗？

### ISSUE THREAD

**Issue by backrunner** [koishijs/koishi#34]
看到文档里中间件可以接收到notice或request型的元数据，但是如果我注册中间件并直接console.log(meta)，在实际测试中如果有加群申请或者有新成员入群，打印并不触发，意味着meta没有截获到东西，只有正常的message可以触发。

这是否意味着当前这类事件只能通过receiver处理，不能用中间件？如果可以需要怎么使用？

版本信息：Koishi/1.11.2 CoolQ/Air CQHTTP/4.14.2

**Comment by Shigma** [comment]
文档中没有说中间件可以接受 notice 和 request 型元数据。这两类只能通过 receiver 处理。

**Comment by backrunner** [comment]
> 文档中没有说中间件可以接受 notice 和 request 型元数据。这两类只能通过 receiver 处理。

重新看了两遍文档，应该是我把深入Meta对象的部分连着上面中间件的部分一起理解了，认为下面写到的meta中间件接受到的meta，造成了这个误解...

**Comment by Shigma** [comment]
了解了，我也会继续完善相关文档的。
