### ISSUE TITLE
[BUG] 使用kaihaila Bot实例发送 Card Message 失败

### ISSUE THREAD

**Issue by AiEson** [koishijs/koishi#341]
**BUG 描述**

使用开黑啦 Bot 实例发送消息（sendMessage()）时，加入 segment('card') 前缀，未能成功发送卡片消息，而是后台得到报错。

**期望行为**

正常发送卡片消息

**Logs**

app SyntaxError: Unexpected token u in JSON at position 0
于 bot.ts:184:76

**Comment by Air1996** [comment]
请使用 JSON.stringify 序列化要发送的内容
`
         await session!.send(
                segment('card', {
                    content: JSON.stringify({
                        type: 'card',
                        theme: 'primary',
                        size: 'lg',
                        modules: modules,
                    }),
                })
            )
`

**Comment by AiEson** [comment]
我在代码中使用如下方法进行发送，但什么都没有发生，并且后台并没有报错出现
ctx.middleware((session, next) => {
    if(session.content == 'test') {
      session!.send( segment('card', { content: JSON.stringify({ type: 'card', theme: 'primary', size: 'lg', modules: 'modules', }), }) )
    }
  })

**Comment by AiEson** [comment]
非常感谢
