### ISSUE TITLE
getGroupList() 与 getGroupInfo() 被调用之后不返回值

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#35]
`getGroupList()` 与 `getGroupInfo()` 被调用之后不返回值。

```js
const { App: Koishi } = require('koishi');
class Bot {
    constructor(item) {
        this.config = item.config;
        this.app = new Koishi({
            type: 'ws',
            port: 6700,
            server: `ws://${this.config.host || 'localhost'}:${this.config.port || '6700'}`,
            token: this.config.access_token
        });
        this.run();
    }
    async run() {
        this.app.receiver.on('connect', async () => {
            console.log('Connected');
            let groups = await this.app.sender.getGroupList();
            console.log(`Found ${groups.length} groups`); // -> No output
        });
        await this.app.start();
    }
};
let config = require('./config.json');
global.App = new Bot({ config });
```

CQHTTP 显示 已成功处理一个API请求：get_group_list

Ubuntu 1604
node@13.3.0
CoolQ@5.19.9A
CQHTTP@4.13.0
koishi@1.11.2

**Comment by Shigma** [comment]
程序输出了什么？Connected 输出了吗？

**Comment by masnn** [comment]
![image](https://user-images.githubusercontent.com/29992205/78787572-1bd68b80-79dd-11ea-9284-8f2da3d6658c.png)

加了个Interval，这个速度显然是不正常的

**Comment by Shigma** [comment]
我这测试的结果是这样的：

![image](https://user-images.githubusercontent.com/33423008/78787994-c189fa80-79dd-11ea-8c87-7cfd1a33ef97.png)

![image](https://user-images.githubusercontent.com/33423008/78788021-c9e23580-79dd-11ea-92c4-abdd8aebed81.png)

我没看出有问题的地方？

**Comment by masnn** [comment]
我测试1.11.1可以用，1.11.2就会炸，

**Comment by masnn** [comment]
爆炸的lock长这样 [https://s.qaq.sh/x10iw](https://s.qaq.sh/x10iw)

**Comment by Shigma** [comment]
唔。可能确实是 1.11.2 的问题，我稍后研究一下。

**Comment by Shigma** [comment]
@masnn 1.12.0 已经发布，应该修复了这个问题。

**Comment by masnn** [comment]
已修复。
