### ISSUE TITLE
koishi监听已被占用的端口不会报错，且收不到gohttp的消息

### ISSUE THREAD

**Issue by LolitaOT** [koishijs/koishi#350]
**Describe the bug**
koishi监听已被占用的端口不会报错，且收不到gohttp的消息
**To Reproduce**
1.使用vue cli启动开发环境使用8080端口
2.启动koishi使用8080端口

**Expected behavior**
koishi应该会提示端口被占用

**Screenshots**

![QQ截图20210818180653](https://user-images.githubusercontent.com/32677256/129880552-9fde62ee-3a12-44b6-b2af-96c502ff1670.jpg)

**Versions**
koishi: 3.12.1
vue cli: 4.5.7
gocqhttp: v1.0.0-beta4
node: 14.17.0

**Additional context**
两个都启动成功后，koishi接收不到任何来自gocqhttp的消息

**Comment by Shigma** [comment]
我这里复现成功了，确实存在此问题。奇怪的是用原生 createServer 创建的 Server 实例，调用 .listen() 一个已经被监听的端口，没有任何报错，也收不到 request。

**Comment by Shigma** [comment]
经过研究 vue-cli 只会监听 ipv4 的端口，然后 node 默认监听 ipv6 的端口，所以没有报错。

我甚至觉得是 vue-cli 的问题。

**Comment by Afanyiyu** [comment]
@Shigma 可否来个 `netstat -ntpl` 看看

**Comment by Shigma** [comment]
![`$ 7SDK2IH_CPIX0AA@IYYN](https://user-images.githubusercontent.com/33423008/130474581-8524c633-f9f2-4da4-85b2-cb33256c0b9f.jpg)
