### ISSUE TITLE
数据库User表错误，在插入新用户数据时没有id字段

### ISSUE THREAD

**Issue by Monkeysama** [koishijs/koishi#358]
**Describe the bug**
配置项的autoAuthorize在自动为用户分配权限，插入user表时缺少id字段，导致所有用户共用一条数据，权限错乱，数据覆盖和冲突

**Screenshots**
![HBKV8S07( D0UM7)3 XG4VF](https://user-images.githubusercontent.com/34790617/130341866-136aca50-28ca-4609-9181-e2ddd15f9349.png)
![QQ截图20210822121007](https://user-images.githubusercontent.com/34790617/130341869-6852f187-3e41-4f25-a9f1-3ae2f24259b0.png)

**Versions**
- OS:  win10 x64
- Node Version: 14.15.1
- CQHTTP Version: 1.0.0-beta5
- Koishi Version: 3.14.0
- Koishi Mysql: 3.6.0

**Additional context**

**Comment by Shigma** [comment]
非常抱歉！这个是新版本引入的 bug。

目前可以尝试通过下列方法修复：打开 node_modules/koishi-core/lib/index.js，搜索下面的代码：

```js
const result = Tables.create('user')
```

在下面加如下代码：
```diff
  const result = Tables.create('user')
+ delete result.id
```

重启启动机器人可解决问题。
