### ISSUE TITLE
更新3.14.0后无法发送信息

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#359]
### Discussed in https://github.com/koishijs/koishi/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **GDWGH** August 22, 2021</sup>
![image](https://user-images.githubusercontent.com/57795156/130339269-657f19df-799a-4a12-86b2-48570e9b9367.png)
对应的信息：
Debian Linux 10 aarch64
node 14.17.5 yarn 1.22.5
koishi.config.js:[koishi.config.js.txt](https://github.com/koishijs/koishi/files/7026442/koishi.config.js.txt)
cqhttp的配置：[config.yml.txt](https://github.com/koishijs/koishi/files/7026443/config.yml.txt)
</div>

**Comment by Shigma** [comment]
@GDWGH 我这试了一下是可以发送的，先麻烦你检查一下能否正常接收（比如写一个简单的 on message console log 插件）

**Comment by GDWGH** [comment]
> 比如写一个简单的 on message console log 插件

不过我是小白 不会写。。。。

**Comment by GDWGH** [comment]
> @GDWGH 我这试了一下是可以发送的，先麻烦你检查一下能否正常接收（比如写一个简单的 on message console log 插件）

cqhttp可以接收 但是 koishi端无响应

**Comment by Shigma** [comment]
如果 koishi 不能接收的话就可能不是无法发送，而是无法接收消息的问题了。

**Comment by GDWGH** [comment]
> 如果 koishi 不能接收的话就可能不是无法发送，而是无法接收消息的问题了。

有没有可能是cqhttp的问题？（我按照过那里的讨论区修改过cqhttp的配置文件）

**Comment by GDWGH** [comment]
> > 如果 koishi 不能接收的话就可能不是无法发送，而是无法接收消息的问题了。
> 
> 有没有可能是cqhttp的问题？（我按照过那里的讨论区修改过cqhttp的配置文件）

是cqhttp配置问题
之前被风控 看了这层（ https://github.com/Mrs4s/go-cqhttp/issues/211#issuecomment-894043784 ）才发不了信息的
对不起 浪费了您的时间！

**Comment by Shigma** [comment]
没事，解决就好
