### ISSUE TITLE
收发消息时自动转换换行符为\n

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#36]

**Comment by Shigma** [comment]
能具体描述一下你的问题吗？

**Comment by masnn** [comment]
仅个人建议。 发送\n应该自动转换为\r\n

**Comment by Shigma** [comment]
@masnn 这么做有什么具体的意义吗？

**Comment by masnn** [comment]
不知道，但是觉得可以统一一下，因为用户发\n一定是想发回车的...

**Comment by masnn** [comment]
还有就是建议预处理过程中将消息解析为mirai那种messageChain格式，然后把&lt; &gt;这种转义回去，个人认为比CQ码的设计好

**Comment by Shigma** [comment]
> 不知道，但是觉得可以统一一下，因为用户发\n一定是想发回车的...

我觉得这个不是系统应该实现的工作，可以有很简单的三行插件来实现这个转化。

**Comment by Shigma** [comment]
> 还有就是建议预处理过程中将消息解析为mirai那种messageChain格式，然后把< >这种转义回去，个人认为比CQ码的设计好

在实现一种通用的机制之前一切当然得按照 CQ 来。用着 CQHTTP 的 SDK 却使用 mirai 的语法是很奇怪的。如果要实现 mirai 适配那就是另一件 issue 的事情了。
