### ISSUE TITLE
`plugin-webui` 打不开

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#360]
在 Linux 上的 [实例地址](http://bot.idl.ist:21919/console)
后来我在自己的 Windows 开发机上试了一下，也打不开。

版本信息：
os: Windows 10. Linux Ubuntu Server 20
koishi: **3.14.0**
go-cqhttp: 1.0.0-beta.4

**Comment by Shigma** [comment]
有报错吗？以及上个版本能开吗？

**Comment by idlist** [comment]
> 有报错吗？以及上个版本能开吗？

上个版本没试过，最近一次开应该是 3.13.x （忘了）
没有报错，包括启动和打开网页的时候

**Comment by MindXL** [comment]
我也遇到了这个问题，进入console页面后网页只有渐变的蓝色背景色

![image](https://user-images.githubusercontent.com/57893196/130395575-c55d85b6-9798-44f2-8536-dfc2567d129b.png)

网页的body标签中只有这样的元素，`#app`里面没有东西
```
<body>
    <div id="app"></div>
</body>
```

当初koishi还在v2版本时，我安装plugin-webui后进console页面也是遇到了这个问题。但过了一段时间等更新后再安装就成功了。


不过最近一直没关注，今天看到这个issue后我也去看了眼，又出现了这个问题，但不知道是在哪个版本出的问题（

**Comment by MindXL** [comment]
> 我也遇到了这个问题，进入console页面后网页只有渐变的蓝色背景色
> 
> ![image](https://user-images.githubusercontent.com/57893196/130395575-c55d85b6-9798-44f2-8536-dfc2567d129b.png)
> 
> 网页的body标签中只有这样的元素，`#app`里面没有东西
> 
> ```
> <body>
>     <div id="app"></div>
> </body>
> ```
> 
> 当初koishi还在v2版本时，我安装plugin-webui后进console页面也是遇到了这个问题。但过了一段时间等更新后再安装就成功了。
> 
> 不过最近一直没关注，今天看到这个issue后我也去看了眼，又出现了这个问题，但不知道是在哪个版本出的问题（

我这边之前的能成功运行的时候，`koishi`版本为3.12.3，`plugin-mysql`版本为3.3.2，`plugin-webui`版本为4.6.3

**Comment by jiajiu123** [comment]
出现相同问题，网页只有蓝色背景色
Koishi版本3.14.1，Plugin-mysql版本为3.6.1，Plugin-webui版本为4.7.0
浏览器控制台提示Uncaught SyntaxError: The requested module '../vue.js' does not provide an export named 'defineEmit'

**Comment by vlssu** [comment]
我也出现这个问题，坐等解决

**Comment by Shigma** [comment]
这个好像是 vue 版本的问题，我锁下版本看看

**Comment by vlssu** [comment]
> 这个好像是 vue 版本的问题，我锁下版本看看

降到版本几呢

**Comment by Shigma** [comment]
昨天发了一个新版本，大家能看下 webui 好了吗？

@idlist @MindXL @jiajiu123 @vlssu

**Comment by MindXL** [comment]
我这里已经能正常显示了

**Comment by idlist** [comment]
好了

**Comment by Shigma** [comment]
ok 那我关掉了
