### ISSUE TITLE
 `plugin-mysql` 下，对已经存在的表无法新增字段

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#361]
![image1](https://user-images.githubusercontent.com/29368226/130355731-652f81e7-a354-4b05-bcee-ddcde8091f29.png)

复现手法：删掉 `channel` 表，先不安装 `github` 插件启动，然后停止 app，然后安装 `github` 插件启动，就会导致这个问题。
查询数据库后发现字段中缺少 `githubWebhooks` 这个字段。
如果一开始就安装了 `github` 插件则不会出现这个问题（即这个字段正常被插入了 `channel` 表中）。

版本信息：
os: Windows 10. Linux Ubuntu Server 20
koishi: **3.14.0**
go-cqhttp: 1.0.0-beta.4

**Comment by idlist** [comment]
经测试，是以下的新的数据库扩展写法导致的问题。

举个简单的例子，如果往数据库的 `channel` 表中新增一个 `aircon` 字段，新写法应该是这样写
```js
const { Tables } = require('koishi')

Tables.extend('channel', {
  fields: {
    aircon: {
      type: 'json',
      initial: {}
    }
  }
})
```
但是这么写就会造成这个“建表时能够插入字段，但是先建表后修改时无法插入字段”的情况了。

**Comment by Shigma** [comment]
抱歉新版本问题比较多，我会尽快发版解决 QAQ
