### ISSUE TITLE
事件监听`before-command`中回调函数的返回类型可能有缺失

### ISSUE THREAD

**Issue by MindXL** [koishijs/koishi#363]
**Is your feature request related to a problem? Please describe.**

我目前的想达成的功能是：在特定的群内完全不触发任何指令。

typescript下发现`before-command`事件对应的回调函数的返回类型为`string | void | Promise<void> | Promise<string>`，我认为可能缺少了一个`Promise<string | void>`。因为在需要用到Promise的情况下，我想做到特定条件下可以触发指令，而其他特定条件下不能触发指令。

**Describe the solution you'd like**

在事件`before-command`回调函数的返回类型中添加`Promise<string | void>`

**Describe alternatives you've considered**

给每一个指令添加检查器`.check()`。不过因为指令太多不太好弄，所以还没试过。

**Additional context**

```
ctx.on('before-command', async (_) => {
    if(...) return '';
}
```

像上述结构的代码经过`tsc`强行编译后能够正常运行，达到了想要的效果，所以我猜源码没有问题，可能只需要在类型上作更改。

`ctx.on('before-command', ...)`、`ctx.before('command', ...)`和`ctx.once('before-command', ...)`几种写法均出现了这个问题。

注：可能是此处出现的问题

https://github.com/koishijs/koishi/blob/3cad36fb2ea4192a1a0912f9d8343af74db00512/packages/koishi-core/src/context.ts#L602

**Comment by Shigma** [comment]
这个问题你大概是绕不过去的：

```ts
type Awaitable<T> = T extends Promise<unknown> ? T : T | Promise<T>
type A = Awaitable<void | string> // string | void | Promise<void> | Promise<string>
```
