### ISSUE TITLE
Bug: plugin-github授权跳转后一直显示Forbidden

### ISSUE THREAD

**Issue by wibus-wee** [koishijs/koishi#368]
### Describe the bug

github.authorize 用户名后，打开链接（事先已经添加GitHub oauth app了）点击授权后，跳转回设置的`/github/authorize`时，一直报 forbidden

无论是机器人还是go-http都没有生成错误日志

### Steps to reproduce

如Describe the bug所说

### Expected behavior

提示授权成功？or？反正就不是forbidden

### Screenshots

<img width="418" alt="截屏2021-08-25 上午8 00 21" src="https://user-images.githubusercontent.com/62133302/130705061-a2ba938f-7054-4549-87a5-39c7d3f0a609.png">
<img width="1020" alt="截屏2021-08-25 上午8 06 12" src="https://user-images.githubusercontent.com/62133302/130705502-facf5d5f-8fd3-4ecb-93d6-32c119fbf87e.png">

koishi.config.js plugin github中只填写了appID和appSecret

个人认为与go-http无关，并且go-http没有收到发送请求，日志啥也没有

### Versions

- OS: CentOS 7.6
- Platform: OneBot:http
- Node version: v14.17.5
- Koishi version: 3.14.1

**Comment by Shigma** [comment]
请问你配置了 selfUrl 吗

**Comment by wibus-wee** [comment]
这是我的koishi.config.js文件

```js
// 配置项文档：https://koishi.js.org/api/app.html
module.exports = {
  // Koishi 服务器监听的端口
  port: 8080,
  selfUrl: 'http://***:8080',
  onebot: {
    // 对应 cqhttp 配置项 http_config.post_urls, ws_reverse_servers.reverse_url
    path: '',
    secret: '',
  },
  bots: [{
    type: 'onebot:http',
    // 对应 cqhttp 配置项 http_config.port
    server: 'http://***:5700',
    selfId: ***,
    nickname: 'wibusBot',
    token: '',
  }],
  plugins: {
     mysql: {
      host: '127.0.0.1',
      port: 3306,
      user: '***',
      password: '***',
      database: '***',
    },
    "common": {
        operator: 'onebot:****',
    },
    "webui": {
        title: "Console",
        selfUrl: 'http://IP地址:8080',
        // uiPath: "/console",
        // devMode: true,
    },
    "github": {
        appId: 'xxx（省略了）',
        appSecret: 'xxx（省略了）',
    },
    "image-search": {},
    // "puppeteer": {},
    'tools': {},
    'chess': {},
    'schedule': {},
    teach: {
        prefix: "$#"
    },
    // eval: {
    //     prefix: "#$",
    //     // scriptLoader: "typescript"
    // },
    
  },
//   logLevel: 3,
}

```

刚刚重新看了一下文档，还看到有一个地方有selfUrl：App，莫非要创建一个实例？

**Comment by Shigma** [comment]
selfUrl 应该是你的公网 URL，你能在公网访问到你的 selfUrl 吗？

**Comment by wibus-wee** [comment]
可以的

**Comment by Shigma** [comment]
Fixed by d689e5cb97cfd7c530279cffcefb5e6423242944
