### ISSUE TITLE
Koishi v4 升级指南

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#369]
Koishi 已经发布了 v4.0.0-alpha.0，这意味着你已经可以体验 Koishi 的下一个大版本了。如果你是 v3 的用户，你可能需要一个清单来指引你如何升级到 v4。

**前排提示：Koishi v4 依然处于测试阶段，可能存在 bug 以及 API 调整。目前仅建议在测试环境而不是生产环境使用。**

## 更新计划

- 2021.9 - 2021.10: alpha stage
- 2021.11: beta stage
- 2021.12: release candidates - final release

## 迁移指南

请参见：https://koishi.js.org/api/migration.html

有关升级中遇到的问题可以直接在这里提出。

**Comment by univeous** [comment]
迁移指南网址404（
应该是 https://koishi.js.org/api/migration.html 吧

**Comment by Shigma** [comment]
> 除了discord还有别的群么?discord现在老是莫名封帐号,请问可以建一个TG群,把discord消息转发到TG群中么?

这个发了稳定版以后估计会开一个。

**Comment by Shigma** [comment]
> 迁移指南网址404（ 应该是 https://koishi.js.org/api/migration.html 吧

感谢，已经修改了。
