### ISSUE TITLE
Feature request: 中间件前置的功能

### ISSUE THREAD

**Issue by shumyun** [koishijs/koishi#374]
### Describe the problem related to the feature request

本人通过中间件前置到队列前面是想在指令执行之前做些总判断，但是内置中间件内除了指令执行，承担了自动添加用户的功能，是否有其他的方法，先自动注册，然后拦截指令执行。

### Describe the solution you'd like

无

**Comment by idlist** [comment]
有没有试过 [前置中间件](https://koishi.js.org/guide/lifecycle.html#内置监听器) ？

**Comment by shumyun** [comment]
我就是用了前置中间件，但是和我预期的效果不一致，前置中间件应该会排列到内置中间件之前，内置中间件完成了自动注册用户和指令执行的功能，我是想问有没办法在自动注册用户和指令执行的中间插入我的判断，以达到我的需求。

**Comment by Shigma** [comment]
具体需求是什么呢？应该有其他实现方式的

**Comment by shumyun** [comment]
> 具体需求是什么呢？应该有其他实现方式的

我的需求就是在自动注册用户之后，指令执行之前插入一些判断。
看了文档，是用 attach-user 这个事件吗？
自动注册用户这个功能是在哪个事件前后发生，是否可以告知下

**Comment by Shigma** [comment]
1. emit before-attach(session)
2. bail before-parse(content, session) 将 content 解析为 argv
3. emit before-attach-channel(session, fields) 收集需要的 channel fields
4. serial attach-channel(session) 此时 session.channel 已经可以访问，返回 true 则不进行后续操作
    - 内置逻辑：session.channel.flag & Channel.Flag.ignore 则不进行后续操作
    - 内置逻辑：session.channel.assignee !== session.selfId && !atSelf 则不进行后续操作
5. emit before-attach-user(session, fields) 收集需要的 user fields
6. serial attach-user(session) 此时 session.user 已经可以访问，返回 true 则不进行后续操作
    - 内置逻辑：session.user.flag & User.Flag.ignore 则不进行后续操作
7. emit attach(session)
8. session.execute(argv)

如果你希望在 session.user 可访问的情况下不触发指令和全部后续中间件，请使用 attach-user 并返回一个 true。

**Comment by shumyun** [comment]
我先关了，有问题再来，谢谢
