### ISSUE TITLE
Bug: `plugin-github` 在删除仓库订阅时，无法删除已经在 GitHub 上被删除的仓库

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#375]
### Describe the bug

如题

### Steps to reproduce

1. 在 GitHub 上新建一个仓库 A
2. 用 plugin-github 订阅这个仓库 A
3. 在 GitHub 把这个仓库 A 删掉
4. 用 plugin-github 取消订阅这个仓库 A

就会造成这个错误

### Expected behavior

当然是可以删除啦！

### Screenshots

比如下面这个例子， 仓库 A 即为 idlist/wut

![image](https://user-images.githubusercontent.com/29368226/131297590-54cd90e3-92b2-43f3-97a0-f5545314178d.png)

### Versions

- OS:  Linux
- Platform:  all
- Node version:  16.1.0
- Koishi version:  3.14.1

**Comment by Dragon-Fish** [comment]
另：无法删除已移交控制权或更名的仓库
