### ISSUE TITLE
Bug: QQ图片无法正常跨频道转发至其他平台

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#377]
### Describe the bug

使用官方common插件提供的跨频道转发消息功能转发QQ图片时只会留下空白

### Steps to reproduce

通过common插件的跨频道转发功能设置QQ转发到其他平台时就会出现此问题

### Expected behavior

应当正常转发并显示图片

### Screenshots

以QQ->开黑啦为例：
![9~YV1@O6VI30YGTZ0S7L7U6](https://user-images.githubusercontent.com/61967203/132214360-d030f76e-c94e-404e-91a0-f37ab73f8639.png)

### Versions

- OS: Ubuntu 18.04
- Backend service: go-cqhttp 1.0.0-beta6
- Node version: 14.17.5
- Koishi version: 3.14.0

**Comment by Shigma** [comment]
经实测，QQ 到 discord 转发图片正常，应该是开黑啦实现问题或开黑啦发图功能异常。

**Comment by Shigma** [comment]
目前测试的结果是 QQ 到开黑啦转发也正常，暂时无法复现……
