### ISSUE TITLE
请问可以用pm2跑koishi吗，或者别的解决Unexpected end of JSON input的法子

### ISSUE THREAD

**Issue by yctjb1** [koishijs/koishi#38]
**Describe the bug**

`C:\Program Files\workspace\acghomebuild\koishi_demo>koishi run
info apply plugin common
port=8080
info Koishi/1.11.2 CoolQ/Pro CQHTTP/4.15.0
info server listening at 8080
info connected to http://localhost:5701
success bot started successfully in 445 ms.
error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at IncomingMessage.req.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\koishi\node_modules\koishi-core\dist\server.js:232:35)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`
**To Reproduce**

未知，程序均可以正常运行（可以联系并提供源码），本地win10跑正常无报错。
仅腾讯云的windows server环境下，过一段时间，会出现此问题
**Expected behavior**

解决这个问题，或者问题出现后依然可以运行项目(比如pm2之类的手段)，
或者有排查错误原因的良方
**Screenshots**

无

**Versions**

- OS: windows server 2016 数据中心版 64位中文版
- Node Version: v10.16.0
- CoolQ Version: 1.11.2
- CQHTTP Version: 4.15.0
- Koishi Version: 
koishi/1.11.2 win32-x64 node-v10.16.0
koishi v1.11.2

**Additional context**

感觉不是我的锅就是腾讯云的锅

**Comment by Shigma** [comment]
过一段时间是指什么？是收到某些消息后导致的还是总是会导致，只不过得等一段时间？

**Comment by yctjb1** [comment]
> 过收到是指什么？是收到某些消息后导致的还是总是会导致，只不过得等取代？

是的得等一段时间，腾讯云上总是会导致但是触发条件无法得知,一段时间不收到消息也会触发

**Comment by yctjb1** [comment]
![image](https://user-images.githubusercontent.com/30720171/80553595-03b2c480-89fd-11ea-88ae-5c7a2caef31f.png)
error SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.req.on (C:\Users\Administrator\AppData\Roaming\npm\node_modules\koishi\node_modules\koishi-core\dist\server.js:232:35)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

这是今天发现的新报错，对话里熊爷牛逼是被过滤器过滤掉的评论
module.exports.name = 'plugin_function'

module.exports.apply = (app) => {

    app.middleware((meta, next) => {//中间件，只对过滤后的数据进行处理
        if (meta.message.includes(`[CQ:at,qq=2757730019]`) || /^八六\s/.test(meta.message) || /^八六[,|，]/.test(meta.message)) {
          // 仅当接收到的消息包含 at 机器人时才继续处理或 八六+空格
          return next()
        }

        // else{
        //     console.log(meta)
        //     return next()
        // }
    })
}

**Comment by yctjb1** [comment]
去了koishi-core>dist>server.js里
用
function parse_json (str, val) {
                    if (typeof val != 'object') val = {};
                  
                    try{
                      val = JSON.parse(str) || val;
                    } catch(e){};
                  
                    return val;
                  }

const data = parse_json(body);

替换掉了232行的JSON.parse，临时解决了运行被打断的问题

**Comment by Shigma** [comment]
@yctjb1 你能通过 catch block 输出原 str 来查看到底是出现了什么问题吗？

**Comment by yctjb1** [comment]
> @yctjb1 你能通过 catch block 输出原 str 来查看到底是出现了什么问题吗？

![Uploading image.png…]()
是一个空字符串

**Comment by yctjb1** [comment]
> @yctjb1 你能通过 catch block 输出原 str 来查看到底是出现了什么问题吗？

![image](https://user-images.githubusercontent.com/30720171/80565929-4cca3f00-8a24-11ea-908f-e9814292addd.png)
是一个空字符串

**Comment by Shigma** [comment]
好的，我了解了，之后的一个版本我会修一下这个问题。谢谢你的反馈！

**Comment by Shigma** [comment]
现在应该没有这个问题了，回头看似乎也不像是 koishi 的问题。

顺便 pm2 跑 koishi 也挺常见的，我看不少人都这么用的。
