### ISSUE TITLE
文档“插件与上下文”部分的“具名插件”中的样例过期

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#380]
### Describe the bug

https://koishi.js.org/guide/context.html#%E5%85%B7%E5%90%8D%E6%8F%92%E4%BB%B6

还是 v1 时代的写法

稍微看了一眼，这个页面的其他的地方好像都没问题

开个 issue 当备忘

### Steps to reproduce

略

### Expected behavior

什么时候顺手改一下就好

或者等 v4（

### Versions

和版本无关，摸了

**Comment by Shigma** [comment]
改成 content 就行是吧

**Comment by idlist** [comment]
> 改成 content 就行是吧

其实主要是把 `meta` 改掉吧（
