### ISSUE TITLE
Feature request: QQ群文件转发功能

### ISSUE THREAD

**Issue by gpzlx1** [koishijs/koishi#407]
### Describe the problem related to the feature request

QQ群消息的文件转发功能。
我目前实现了qq群信息转发，可以从一个群转发到另一个群。但是在测试的时候，没法转发上传的文件。在文档里也没有找到相关的APi。
想请教下，对应的api。如果没有，希望在未来支持 群文件的转发。

### Describe the solution you'd like

提供群文件操作的相关接口或者文档。

**Comment by Shigma** [comment]
只有当 onebot 或者 go-cqhttp 实现了此功能，我们才能实现。请说明你需要的是 onebot 或者 go-cqhttp 的具体哪一个接口。

**Comment by DDEle** [comment]
我猜是 https://docs.go-cqhttp.org/event/#群文件上传 和 https://docs.go-cqhttp.org/api/#上传群文件 😂

**Comment by DDEle** [comment]
@gpzlx1 请参考 https://koishi.js.org/plugins/adapter/onebot.html#go-cqhttp-%E6%89%A9%E5%B1%95-api

**Comment by gpzlx1** [comment]
> 

Thx
