### ISSUE TITLE
Bug: koishi v4 使用discord遇到 Disallowed intent(s)的问题

### ISSUE THREAD

**Issue by yunkuangao** [koishijs/koishi#408]
### Describe the bug

在使用koishi v4后，使用discord适配器后无限重试，返回的内容为
```
[I] adapter connect to server: wss://gateway.discord.gg/
[W] adapter Disallowed intent(s)., will retry in 5s...
[I] adapter connect to server: wss://gateway.discord.gg/
[W] adapter Disallowed intent(s)., will retry in 5s...
```

### Steps to reproduce

根据教程https://koishi.js.org/v4/guide/introduction/coding.html

首先
```shell
yarn init
yarn add koishi@next @koishijs/plugin-common@next @koishijs/plugin-adapter-discord@next
```

然后创建index.js
```js
const { App } = require('koishi')

// 创建一个 Koishi 应用
const app = new App()

// 安装 onebot 适配器插件，并配置机器人
app.plugin('adapter-discord', {
  token: 'tokenstr',
})

// 安装 common 插件，你可以不传任何配置项
app.plugin('common')

// 启动应用
app.start()
```

最后
```shell
node .
```

### Expected behavior

能够让我开心的发涩图

### Screenshots

这是出问题的截图
![image](https://user-images.githubusercontent.com/40163747/141507303-bbcd9969-0e40-491d-84f3-70763b7b5705.png)
这是出问题的bot权限
![image](https://user-images.githubusercontent.com/40163747/141507385-f89054ec-28d4-4ae8-add6-6c3eee9a841a.png)
这是正常的bot权限
![image](https://user-images.githubusercontent.com/40163747/141507391-15f29552-62ca-4eba-8385-a20909b25206.png)

### Versions

- OS: Windows 10 
- Platform: Discord 
- Node version: v17.0.1
- Koishi version: 4.0.0-beta.0

### Additional context

请让我快点看涩图

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/141606007-47012308-debf-4c64-adfb-3e6a22af22fc.png)

bot设置选一个这个

**Comment by yunkuangao** [comment]
@XxLittleCxX 大佬牛逼
