### ISSUE TITLE
指令系统和中间件之间是否有冲突？链接数据库后为何指令系统失效？

### ISSUE THREAD

**Issue by muyuqingqiu** [koishijs/koishi#41]
**Describe the bug**

两个问题
1.   在不连接数据库的情况下，先注册中间件，再注册指令，此时如果走了指令，在它之前注册的中间件不会触发。如果注册的是前置中间件，则只有中间件会触发，指令完全失效。

2.   在连接数据库后，指令和中间件都不生效。。。已经在数据库中建了相应的表和字段。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**

最新的
- Node Version: [e.g. 10.16.0]
- CoolQ Version: [e.g. 5.15.4]
- CQHTTP Version: [e.g. 4.13.2]
- Koishi Version: [e.g. 1.0.0]

**Additional context**

**Comment by Shigma** [comment]
1. 这是期望的行为。
2. 能提供最小的可复现代码吗？

**Comment by muyuqingqiu** [comment]
> 1. 这是期望的行为。
> 2. 能提供最小的可复现代码吗？

1. 那如果想在指令触发前执行一些逻辑的话，应该如何实现呢？
2.
这是启动配置
`module.exports = {
    type: 'http',
    port: 9080,
    server: 'http://0.0.0.0:5700',
    logLevel: 3,
    database: {
        mysql: {
            host: 'localhost',
            port: 3306,
            user: 'root',
            password: 'xxxxx',
            database: 'QQBOTDB',
        },
    }
}
`

这是测试用的指令

`
app.command('echo <message>')
    .action(({
        meta
    }, message) => meta.$send(message));
`

把配置里的数据库相关字段注释掉，指令有反应。反之则没有。


另外还有几个问题：
1. logger模块无法使用，我引入了looger后，调用logger.info('foo');
但是没有输出任何信息

2.  关于数据库部分，相关的文档我看了几遍，但是还是不太理解。内置的两张表是需要自己手动创建并注入相关字段么？新的群的信息和用户的信息记录是框架自动创建到数据库的么？还是需要自己写个中间件，每次有人发言先判断下数据库有没有群信息，有没有这个用户信息。如果没有的话再自己手动添加相关信息到数据库？

**Comment by Shigma** [comment]
非常感谢你的提问！下面我逐一进行回答。

1. 中间件这个机制的本身是为了建立一套完整的消息控制流，它的核心逻辑是通过 next 传递控制权。通常来说，我们希望大部分消息都只被成功处理一次，因此中间件会被顺序执行。先执行前置中间件，再执行内置中间件（指令的调用在这一步完成），最后执行其他用户注册的中间件。这就是你之前遇到的问题的原因。如果希望在前置中间件中完成一些工作，可以调用 next 函数：

```js
app.prependMiddleware((meta, next) => {
  meta.foo = 'bar'
})

app.command('echo').action(({ meta }) => console.log(meta.foo)) // 输出 bar
```

2. 你使用的是 `app.logger().info('foo')` 吗？这里的引入是什么意思？

3. 数据库部分我承认 Koishi 目前还不是特别完善。是的，user 和 group 两张表都需要自己先建好并事先配置好字段。（这一点有望在未来的版本改善但是可能我要花一些时间。）

4. 用户信息是否默认创建是一个比较复杂的问题。我们有的时候需要拒绝陌生的访问，有的时候却希望能自动插入数据。这里的行为其实是由 getUser 的一个参数 defaultAuthority 控制的，如果传入的 defaultAuthority 不为 0，且该用户不存在，则会在数据库创建一个新的用户。而这里的 defaultAuthority 又可以通过 app 构建时的选项控制（默认为 0）：

```js
const app = new App({
  defaultAuthority: 1, // 所有访问 bot 的账号，只要不存在，就立即以 1 为权限创建
})
```

或者传入一个函数：

```js
const app = new App({
  defaultAuthority (meta) {
    if (meta.groupId === 123) {
      return 1 // 群 123 中的用户访问 bot 时，如果账号不存在，就立即以 1 为权限创建
    }
    return 0 // 其他情况下不创建账号
  },
})
```

群的话目前是没有这个机制的。换言之，群数据需要手动插入行。一直没做的原因主要是我不太清楚不同的 bot 开发者都有怎样的需求。如果你有一些建议，欢迎在这里提出。

**Comment by muyuqingqiu** [comment]
> 一直

非常感谢您的详细回复，因为我也是最近才开始接触bot相关的开发，很多东西还是处于一头雾水的状态。问题比较繁琐还请见谅。

问题1 ：  我已经了解了。
问题2 ： 关于启用了数据库后指令和中间件系统失效的问题是我现在最为困惑的，在您的答复中没有看到相关的回复。

关于logger的问题 ：  意思就是我执行了这样的代码
`const logger = ctx.logger(); logger.info('foo');`
后，无法在控制台看到输出（我使用pm2来管理bot的启动，所以其实就是pm2 log里看不到输出）。
我尝试改了配置中的输出等级，但是没有作用。

问题4 ：我也理解了，不过印象里文档中并没有相关的描述，如果能把这些内容添加进去，相信能解决很多其他开发者的疑惑。

**Comment by muyuqingqiu** [comment]
我之后又进行了一些测试，找到了链接数据库后指令和中间件无法响应的问题原因。
直接原因是group中的assignee字段默认为0，flag字段默认为3。因此框架判断不响应群消息。
因此我尝试在接收到每个消息时，判断他的群信息，然后修改数据库中群的信息，让这些群能够被响应。

但是我又发现这些数据库中的信息并没有被持久化，每次bot重启后，数据库中的group和user信息又清空为默认了。。。这让我很费解。

```
app.group(...RES_GROUPS).prependMiddleware(async (meta, next) => {
    if (!reqedGroups[meta.groupId]) {
        let groupInfo = await app.database.getGroup(meta.groupId);
        let userinfo = await app.database.getUser(meta.userId);
        console.log(userinfo,groupInfo);
        if (groupInfo.assignee === 0) {
            groupInfo = {
                ...groupInfo,
                assignee: SELF_ID,
                flag: 0
            }
            await app.database.setGroup(meta.groupId, groupInfo);
        }
        if (!userinfo.authority) {
            let authority = 1;
            if (meta.userId === superId) {
                authority = 4;
            }
            userinfo = {
                ...userinfo,
                authority
            }
            await app.database.setUser(meta.userId, userinfo);
        }
        reqedGroups[meta.groupId] = groupInfo;
    }
    
    return next();
})

```



这是我的代码

**Comment by Shigma** [comment]
> 直接原因是 group 中的 assignee 字段默认为 0，flag 字段默认为 3。因此框架判断不响应群消息。

是这样的。所以应该先向数据库中插入群数据……我之前不知道为啥没想到这个。

> 每次 bot 重启后，数据库中的 group 和 user 信息又清空为默认了……

你的数据库是用的啥，数据只要被写入不就跟 Koishi 没关系了吗？

**Comment by muyuqingqiu** [comment]
用的就是指南中推荐的mysql。
我也很费解，我上面的代码中也能看到，我调用了db.setGroup,数据按理来说已经被写入了。
但是bot重启后，我打印出db.getGroup得到的返回值，依然是默认的。


```

app.group(...RES_GROUPS).prependMiddleware(async (meta, next) => {
    if (!reqedGroups[meta.groupId]) {
        let groupInfo = await app.database.getGroup(meta.groupId);
        let userinfo = await app.database.getUser(meta.userId);
        console.log(userinfo, groupInfo);//0|start  | { id: 12324535, authority: 0, flag: 0, usage: {} } { id: 12312313, assignee: 0, flag: 3 }
        if (groupInfo.assignee === 0) {
            groupInfo = {
                ...groupInfo,
                assignee: SELF_ID,
                flag: 0
            }
            await app.database.setGroup(meta.groupId, groupInfo);
        }
        if (!userinfo.authority) {
            let authority = 1;
            if (meta.userId === superId) {
                authority = 4;
            }
            userinfo = {
                ...userinfo,
                authority
            }
            await app.database.setUser(meta.userId, userinfo);
        }
        let re_groupinfo = await app.database.getGroup(meta.groupId);
        let re_userinfo = await app.database.getUser(meta.userId);
        console.log(re_userinfo, re_groupinfo);//0|start  | { id: 12312313, authority: 0, flag: 0, usage: {} } { id: 123123123, assignee: 3453564564, flag: 0 }
        reqedGroups[meta.groupId] = groupInfo;
        reqedUsers[meta.userId] = userinfo;
    }

    return next();
})

```

**Comment by muyuqingqiu** [comment]
之前的问题除了logger以外都已经搞清楚了。
现在想问下，如何获取到群的名字呢？目前meta中只有id.
另外文档中说meta对象中添加的私有属性中有个$parsed，我在开发时并没有找到这个对象。不知道是什么原因。

**Comment by muyuqingqiu** [comment]
想问下是否有删除好友的api。文档中没有看到。

**Comment by Shigma** [comment]
> 想问下是否有删除好友的api。文档中没有看到。

木有，这个暂时做不到（捂脸）
