### ISSUE TITLE
Feature request: QQ频道支持

### ISSUE THREAD

**Issue by RealHeart** [koishijs/koishi#410]
### Describe the problem related to the feature request

go-cqhttp已支持QQ频道

### Describe the solution you'd like

https://github.com/Mrs4s/go-cqhttp/blob/master/docs/guild.md

**Comment by Shigma** [comment]
我会尽快在 v4 最新版实现。

**Comment by Shigma** [comment]
Fixed by 2c130dab306b796c90f5d4c022d76f04bb0d8693 and 4043487bb48840df9ab76e45831d96a79666671d.

**Comment by RealHeart** [comment]
@Shigma 在提一嘴 现在官方Bot在内测了 是否考虑支持下？
https://bot.q.qq.com/wiki/

**Comment by Shigma** [comment]
现在已经可以在 v4 的 onebot 插件中使用第三方 bot 实现了，官方 bot 接口仍然不稳定，而且我还没有申请资格，会在之后做。如果有兴趣的话你来 pr 也可以。

**Comment by NWYLZW** [comment]
> @Shigma 再提一嘴 现在官方Bot在内测了 是否考虑支持下？ https://bot.q.qq.com/wiki/

正在做 adapter ，并及时更新支持

https://github.com/koishijs/koishi/pull/421
https://github.com/koishijs/koishi/pull/431

**Comment by Shigma** [comment]
现在 QQ 频道在插件 adapter-qqguild 和 adapter-onebot 均已完美支持。
