### ISSUE TITLE
Bug: v4 在不配置 `port` 的情况下，`console` 无法启动

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#413]
### Describe the bug

如题

### Steps to reproduce

```js
module.exports = {
  // 不配置 port
  plugins: {
    // 其他插件
    console: {}
  }
}
```

### Expected behavior

其实严格来说这不算是 bug，但是我觉得这个报错行为有改进的空间，因为看到这个报错很难第一反应过来是没 port。

1. 可以给 port 一个默认值 8080，然后在 8080 被占用的情况下用 8081 之类的，然后运行的时候产生一个 info 日志行说没有配置 port，使用默认 port
2. 直接报错，但是报错信息直接提示没有配 port

selfUrl 应该是可选的，就无所谓了。

### Screenshots

![image](https://user-images.githubusercontent.com/29368226/144231876-12bef26b-8da6-462b-85b4-f0452f030f3a.png)

### Versions

- OS:  Windows 10
- Platform:  idk
- Node version:  v16.1.0
- Koishi version:  v4.0.0-beta-2

**Comment by Shigma** [comment]
这个问题在 #418 中已经解决了，现在不会报错（虽然也不会启动服务器，但是我觉得没关系了）。
