### ISSUE TITLE
Bug: 在卸载扩展 Channel/User 表的插件后，数据库新增行时报错

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#414]
### Describe the bug

如题

这个问题会导致数据库半瘫痪

### Steps to reproduce

比如说有一个插件这么扩展了 Channel 表（这里是 v3 写法，换成 v4 写法也生效）

```js

Tables.extend('channel', {
  fields: {
    days_matter: {
      type: 'json',
      initial: {
        notif: 7,
        annual: 'false'
      }
      // 关键在于隐性的 nullable: false
    }
  }
})
```

在安装了这个插件后， channel 表就会被扩展 days_matter 字段。
但是如果接下来 **不安装** 这个插件而运行 bot，那么，在 **新群入表** 的时候就会报下面截图中的错误。

### Expected behavior

当然是能不报错啦！

### Screenshots

![image](https://user-images.githubusercontent.com/29368226/144421815-cb05c21f-b1ab-4336-9370-828942d6c1e4.png)

### Versions

- OS:  Win10
- Platform:  all
- Node version:  v16.1.0
- Koishi version:  v3.14.2, v4.0.0-beta.3

使用的是 mysql 数据库

**Comment by idlist** [comment]
后来测试了一下，这个问题 v3/v4 都有……

**Comment by Shigma** [comment]
从新版本起 nullable 的默认值将会为 true（仍然可以手动设置为 false，后果自负）。

可能需要一些测试。

**Comment by Shigma** [comment]
此外，旧版插件已经修改的数据库可能需要手动设置允许 null。
