### ISSUE TITLE
Bug: 插件往 Channel/User 表新增 `json` 字段时，没有对已存在的行进行初始化，导致报错

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#415]
### Describe the bug

如题，和 #414 比较相近，也有一部分 Nullable 的问题，但似乎不太一样。
这个问题也是 v3/v4 同时有的问题。

这个问题会导致部分字段类型（比如 `json` 类型）无法正常使用。
因为似乎对于 ORM `json` 类型，只有 NULL 和 `{}` 这两个“空内容”能够被正常解析，而真正的“空”（无内容）是没法被解析的，会直接报 `SyntaxError: Unexpected end of JSON input`。
但是不对已存在的行进行初始化，同时不配置 `nullable: true` 的话，新增字段的初始值就不会是 NULL，而是“空”了。

### Steps to reproduce

```js
const { Tables } = require('koishi')

Tables.extend('channel', {
  test: {
    type: 'json',
    initial: {
      ipsum: 'lorem'
    }
    // 重点在此：配置了 initial 但是不配置 nullable: true
  }
})

module.exports = (ctx) => {
  ctx
    .command('test')
    .action(async ({ session }) => {
      const test = await session.observeChannel(['test'])
      console.log(test)
    })
}
```

这里有一个比较小的能够复现这个问题的用于 **v4** 的插件 ，假设叫它 `test.js`：

1. 找个群 （群 A） 发一句话，让这个群入表
1. 安装 `test.js` 插件
2. 在这个群 A 中运行指令 `test`
3. 报错！因为 koishi 没有对已有的行进行初始化，而 ORM 的 `json` 类型无法解析“空”内容，它只能解析 NULL 和 `{}`

报错内容如下面的截图。

### Expected behavior

和 #414 一样，还是想 koishi 自身有没有机制能改良一下这个行为，否则的确有点坑

然后或许可以改进一下 json 字段的解析，在空字符串的情况下也能解析成功

### Screenshots

![image](https://user-images.githubusercontent.com/29368226/144426595-f66024dc-ce36-44af-93cf-4bf962477756.png)

### Versions

- OS:  Win10
- Platform:  all
- Node version:  v16.1.0
- Koishi version:  v3.14.2, v4.0.0-beta-3

使用的是 mysql 数据库

### Additional context

所以说了半天，要不始终默认 nullable: false 吧
默认所有新增字段 primary key 和 foreign key 的 nullable: true，其他的 nullable: false 的就没有这个问题了（迫真）

**Comment by idlist** [comment]
对已有行的初始化这一点，我测试过在字段 = NULL 的情况下做 get/observe 操作的时候是有初始值的，或许可以不做。

要不给 `json` 类型新增一个“如果 JSON 读取出错了就重置到初始值”的机制？我也不懂这样做好不好就是了……

**Comment by idlist** [comment]
先把这个问题限定到 ORM json 字段了，不清楚其他类型有没有类似的问题，有就再说。

**Comment by Shigma** [comment]
JSON 无法解析空串的错误已经修复。

从新版本起 nullable 的默认值将会为 true（仍然可以手动设置为 false，后果自负）。

可能需要一些测试。
