### ISSUE TITLE
Feature request: Docker support

### ISSUE THREAD

**Issue by NN708** [koishijs/koishi#42]
It seems that both CoolQ and CQHTTP have Docker support. Shall we make a Docker image for Koishi to help users deploy Koishi on Linux servers more quickly?

**Comment by NN708** [comment]
Docker support for Koishi is now available on Docker Hub: https://hub.docker.com/r/koishijs/koishi (version 1.12.0). [docker-compose.yml](https://github.com/koishijs/koishi/blob/docker/docker/docker-compose.yml) can be used to deploy CoolQ, CQHTTP, MySQL and Koishi very quickly.

## More Things To-Do
- [ ] Write instructions for Docker on Koishi website
- [ ] Port Docker support to Koishi v2
- [ ] Install plug-ins automatically
- [ ] Use environment variables to initialize MySQL configuration in Koishi

## Discussion
The starting script [start.js](https://github.com/koishijs/koishi/blob/docker/docker/start.js) is basically the same as `koishi init`, but use environment variables. Is it possible to add something like `koishi init -d`, letting it read environment variables to initialize configuration file?

**Comment by Shigma** [comment]
Due to the sunset of CoolQ and CQHTTP, we are now pending https://github.com/Mrs4s/go-cqhttp/issues/7.

**Comment by purerosefallen** [comment]
I don't think building a Docker image for Koishi itself is a good idea. Docker images should be built by upstream developers.
Anyway, is this Docker image a base image for other Docker images of apps depend on Koishi be built? I think building an official image like this may be a good idea. eg.
```Dockerfile
FROM koishi
WORKDIR /usr/src/app
COPY ./package*.json ./
RUN npm ci
COPY . ./
RUN npm run build
CMD npm start
```

**Comment by NN708** [comment]
@purerosefallen Thank you for your suggestions! However, this official Docker image is mainly for users who want to quickly deploy only Koishi and public plugins with one-click. For upstream developers, I think that building your own Docker image based on Node is simpler, and this official image for Koishi could be a reference for you.

**Comment by NN708** [comment]
[Using Docker](https://koishi.js.org/guide/docker.html) page has been released on Koishi website. Closing this issue now.
