### ISSUE TITLE
Bug: Discord 适配器发送图片出错

### ISSUE THREAD

**Issue by DDEle** [koishijs/koishi#427]
### Describe the bug

发送图文混合消息时报错（没测单图片发送有没有问题

把 `handleMixedContent` 改成 separate 和 attach 后也会报错（但separate可以发文字再报错，attach可以发文字+一张图再报错）

### Steps to reproduce

想办法直接调用 `bot.sendMessage(str)`，其中 `bot` 是一个 discord 机器人实例（从`ctx.bots.filter`出来的），`str` 如下
```
DDEle 发布了新动态：
U39-V/U39-S 测试版 488341 更新
文字版更新日志参见 oni.fandom.com/zh/?curid=3305
[CQ:image,url=https://i0.hdslb.com/bfs/album/df0f045d8ae1acf14980cbc97c2d6a5297fa0d9a.png]
[CQ:image,url=https://i0.hdslb.com/bfs/album/3669833d3db3c57091b3b13f48279eae32e717cc.png]
链接：https://t.bilibili.com/599210128921868171
```

### Expected behavior

正常发送图文消息

### Screenshots

![unknown (1)](https://user-images.githubusercontent.com/28386673/145932300-6956eb37-286f-43ad-8b79-fb403c4fab57.png)

### Versions

- OS: Windows 10
- Platform: onebot / telegram
- Node version: v16.13.0
- Koishi version: 4.0.0-beta.5
- @koishijs/plugin-adapter-discord: 2.0.0-beta.6

**Comment by DDEle** [comment]
![image](https://user-images.githubusercontent.com/28386673/146504391-7d6b0410-d70a-40d5-a9d5-9236bd431742.png)
是 Quester 的问题（见上方截图部分）。Discord 适配器使用 head 请求，但是所有 Quester 函数都只返回 `res.data` 而没有 `res.headers`。可以考虑判断 method 为 head/HEAD 的时候单独处理返回 headers（但是这样个人感觉和别的请求的行为不太一致）。

**Comment by Shigma** [comment]
嗯这里设计的不太好，或许 quester 确实要修改.
