### ISSUE TITLE
Bug: telegram 私信无法触发

### ISSUE THREAD

**Issue by DDEle** [koishijs/koishi#428]
### Describe the bug

输入 bind 代码无效（就是类似大概`koishi/${token}`那个）；尝试调用help命令也不行。在群聊中正常。命令行中没有任何报错信息。

### Steps to reproduce

给机器人私聊发送任意命令。

### Expected behavior

显然是要回应私聊时的消息啦。

### Screenshots

![image](https://user-images.githubusercontent.com/28386673/145933392-9b2e3047-0d1e-4052-a206-c289521eff8a.png)
![image](https://user-images.githubusercontent.com/28386673/145933404-c8140a9a-f990-4465-aee7-9280199b5585.png)

### Versions

- OS: Windows 10
- Platform: onebot / telegram
- Node version: v16.13.0
- Koishi version: 4.0.0-beta.5
- @koishijs/plugin-adapter-telegram: 2.0.0-beta.4

### Additional context

适配器有正常生成 session，详见截图

**Comment by Shigma** [comment]
Fixed by #445
