### ISSUE TITLE
有计划实现反向websocket通信么？

### ISSUE THREAD

**Issue by muyuqingqiu** [koishijs/koishi#43]
**Describe the bug**

尝试把前端切换到mirai，使用了cqhttp-mirai插件，但是cqhttp-mirai不支持http api，koishi又不支持反向websocket。。。好难办

话说作者有计划支持mirai么？
**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**

- Node Version: [e.g. 10.16.0]
- CoolQ Version: [e.g. 5.15.4]
- CQHTTP Version: [e.g. 4.13.2]
- Koishi Version: [e.g. 1.0.0]

**Additional context**

**Comment by Shigma** [comment]
有这个想法，但是不知道什么时候实现……

**Comment by muyuqingqiu** [comment]
orz，那我慢慢等好了
现在我被迫用mirai http上报接受消息，然后api端口填的cqhttp的端口，结果就是向A机器人发送的消息是B回应2333

**Comment by Shigma** [comment]
Fixed in 185b5a2d5a5983e56b0f2c56350958ad4491454f.

Will be available in koishi-core v2.0.0.beta.5.
