### ISSUE TITLE
快速启动不支持 node 12

### ISSUE THREAD

**Issue by fireattack** [koishijs/koishi#448]
### Describe the bug

在node 12 环境`yarn create koishi`会报错 `[E] app Error: Cannot find module 'fs/promises' `

fs/promises 14 才有，[12](https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_promise_example)是 `const fs = require('fs').promises;`

### Steps to reproduce

1. 安装 Node 12
2. yarn create koishi
3. 选项全默认然后 Yes

### Expected behavior

能正常安装。[官方文档](https://koishi.js.org/guide/introduction/console.html#%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C) 写道 “Koishi 需要 NodeJS (最低 v12”。

### Versions

- OS: Win10
- Node version: v12.20.0
- Koishi version: Unknown

**Comment by Shigma** [comment]
感谢反馈，问题了解了。单纯改掉这个写法很简单，不过我在考虑把最低要求改成 14。

**Comment by Anillc** [comment]
我记得现在的 koishi 的编译结果里含有 `||=` 运算符，node 12 貌似并不支持这个运算符

![image](https://user-images.githubusercontent.com/23411248/148631432-011a93d8-3405-4fd3-8e67-85fd5bd2a80c.png)

**Comment by Shigma** [comment]
> 我记得现在的 koishi 的编译结果里含有 `||=` 运算符，node 12 貌似并不支持这个运算符

能指个路嘛？因为我之前用 14 好像没出问题的，文档上写了 15。

**Comment by Anillc** [comment]
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment>

**Comment by Shigma** [comment]
我当然知道 mdn 在哪 2333

我是想让你指下我代码里哪里生成了，因为我看到源码里用到 `||=` 的地方，生成的代码都转换过了。

**Comment by Anillc** [comment]
试了下，现在的版本已经没有这个问题了。之前在 beta 还是 alpha 来着某几个版本是没办法启动的，我还特意更新了下 node 才好的
