### ISSUE TITLE
Bug: adapter-onebot-ex无法在数据库正常生成QQ频道的channel信息

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#449]
### Describe the bug

当在QQ频道发送消息时，onebot-ex适配器无法正常在数据库channel表（集合）中生成Channel信息

### Steps to reproduce

1. 安装koishi,database-mysql和adapter-onebot-ex  
2. 配置并启动机器人  
3. 在QQ频道中发送消息（确保机器人账号已在频道中并有收发消息权限）

### Expected behavior

此时在数据库中应该有相应频道的记录（文档）

### Screenshots

![Y`3GXJN8L_CG`)B1C)R6EYJ](https://user-images.githubusercontent.com/61967203/148371320-a8983f16-c373-4bcf-8998-525d85667a23.png)
![SIGMX86SU(MZ5~PFKKP{N~H](https://user-images.githubusercontent.com/61967203/148371366-4438c6a6-23bb-4181-bf77-0e4e832a080c.png)

### Versions

- OS: Ubuntu 20.04.3
- Backend service: go-cqhttp v1.0.0-beta8-fix2
- Node version: 16.13.1
- Koishi version: 4.0.0-rc.1
- MySQL version: 5.7.35
- onebot-ex version: 2.0.0

**Comment by Shigma** [comment]
koishi-adapter-onebot-ex 不是官方插件，请前往相应的仓库进行反馈。

**Comment by purerosefallen** [comment]
Fixed in `2.0.1`.

**Comment by Shigma** [comment]
光速修复好评 👍
