### ISSUE TITLE
Feature request: 新增一个表，用于储存 telegram adapter 的 chatid 和 userid

### ISSUE THREAD

**Issue by Anillc** [koishijs/koishi#453]
### Describe the problem related to the feature request

由于 telegram bot 的 api 限制，发送消息需要使用 chatid，但是却没办法从 userid 获得 chatid

### Describe the solution you'd like

新增一个表，在用户对 bot 点击 start 的时候储存 userid 和 chatid，需要发送私聊消息的时候进行查表。

### Describe alternatives you've considered

扩展 user 表。但是这样做会出现一些问题，比如 bind 指令并不会迁移 chatid 导致丢失数据，使原本可以发送私聊消息的无法发送

### Additional context

另外可以考虑把 username 也储存在这张表里。telegram 同样也没办法通过 username 获取到 userid，大概是防 spam 的机制，导致一些功能比如 at 的解析，无法正常使用。但是有个问题是 username 是可能会发生改变的，储存的 username 并不能保证正确

**Comment by Shigma** [comment]
> 扩展 user 表。但是这样做会出现一些问题，比如 bind 指令并不会迁移 chatid 导致丢失数据，使原本可以发送私聊消息的无法发送

只要收到消息的时候可以拿到 chatid 就可以立即对表写入了吧？

**Comment by Anillc** [comment]
用户 start 之后可能再也不会往私聊发消息了，chat id 就没有了。而且受到消息就更新一下表感觉也不怎么好

**Comment by Shigma** [comment]
那样的话确实可以用一个表来存储 userid 到 chatid。

之前想要在 user 表中实现主要是考虑到性能问题，多一个表就意味着多一次请求。不过感觉这个场景主动覆盖率并没有那么高，被动情况下可以优化掉数据库请求（因为被动是有 chatid 的）。bind 是个问题不过应该有办法。

不过 username 的话，考虑到变动频率确实就不适合放 user 表了。如果要做的话，建一个独立的 tg 表或许更好。

**Comment by Shigma** [comment]
经验证，私聊中的 `message.chat.id` 与 `message.from.id` 是一致的。所以没有这个需求了。
