### ISSUE TITLE
Bug: 任意 QQ 大头贴会随机触发任意问答

### ISSUE THREAD

**Issue by DDEle** [koishijs/koishi#457]
### Describe the bug

在 QQ，任意大头贴（解析出来以后形如“[晚安]”）会随机触发任意问答，甚至包括非本上下文的问答。

本 Issue 搬运自 @Dragon-Fish 与 @Anillc 在 DC 的反馈。

### Steps to reproduce

怎么发 sticker：手机端（个人是安卓）在发表情的那个界面，最左边的那个按钮点进去就能到表情商城；然后随便下个表情包就会在底部出现那个表情包的 tab；直接发送即可。

### Expected behavior

显然（

### Screenshots

![](https://cdn.discordapp.com/attachments/839476759112187954/916148045979222056/IMG_0434.png)

### Versions

- OS: Ubuntu
- Platform: Onebot
- Node version: 14.18.1
- Koishi version: 4.0.0

### Additional context

小鱼君：问答机随机触发的问题好像有点端倪了；空 dialogue 指令可以随机触发任意回答
![](https://media.discordapp.net/attachments/839476759112187954/925359184017506304/unknown.png)

Anillc: v4 也会
![](https://media.discordapp.net/attachments/839476759112187954/925359393829183528/unknown.png)

个人是有直接观测到 v4 在别人发大头贴的时候触发这个问题。

**Comment by idlist** [comment]
有几个细节可以补充一下：

- gocq b7f1 没有这个问题，用 gocq b8f2 就有这个问题了，所以应该是因为 gocq 的升级导致多上报了什么消息段导致触发随机问答。
- 随机问答的范围仅限于普通问答。正则问答不会被表情包随机触发。

**Comment by DDEle** [comment]
在 dc 中的复现。（在 v3 我其实也遇到过，但是当时没多想，直接把那个频道对机器人隐藏了）
![image](https://user-images.githubusercontent.com/28386673/151300916-208a446f-384c-4d7c-8db2-0d1d848d15ec.png)
