### ISSUE TITLE
Bug: `ctx.broadcast` 似乎是坏的

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#462]
### Describe the bug

会产生神秘错误，消息也发不出去

### Steps to reproduce

用它

### Expected behavior

当然是能发出消息了

### Screenshots

![unknown](https://user-images.githubusercontent.com/29368226/149665490-88a6f0d7-5eb9-4044-9e07-90fbe723b7bf.png)
![unknown (1)](https://user-images.githubusercontent.com/29368226/149665492-bbc51e58-8f6a-456d-b875-d7b5d08a30a3.png)

其中 `status.channel` 就是上图 object 中的 channel

### Versions

- OS:  Win10
- Platform: 
- Node version:  v16
- Koishi version:  v4.0.0
这应该是core功能来着

**Comment by Shigma** [comment]
broadcast 一参数应该是 `string[]`

**Comment by idlist** [comment]
> broadcast 一参数应该是 `string[]`

我确认过了，的确是 string[] _(:3

**Comment by idlist** [comment]
这个问题的根源可能在 [这里](https://github.com/koishijs/koishi/blob/919a328ef936e82bcd4b43a27cfa0ebe82bdceda/packages/koishi/src/assets.ts)

**Comment by idlist** [comment]
经测试，在 dist 代码中将 [这一段](https://github.com/koishijs/koishi/blob/919a328ef936e82bcd4b43a27cfa0ebe82bdceda/packages/koishi/src/assets.ts#L66) prototype 修改代码全部删掉之后就能正常工作了，尚不清楚删除这一段会造成怎样的副作用
