### ISSUE TITLE
Bug: `plugin-rate-limit` 的指令缺少描述

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#465]
### Describe the bug

如题

不应该默认安装了这个插件的人一定安装了 `plugin-admin`

### Steps to reproduce

见截图

### Expected behavior

有个说明

### Screenshots

![unknown (2)](https://user-images.githubusercontent.com/29368226/149665736-63ac82aa-279e-479b-afad-a170f5d3ee75.png)
![unknown (3)](https://user-images.githubusercontent.com/29368226/149665742-6b45aee7-3138-4723-80b4-72e35a01e3ae.png)

只配置了这些插件

### Versions

- OS:  Win10
- Platform: 
- Node version:  v16
- Koishi version:  v4.0.0

**Comment by Shigma** [comment]
问题属实。下个版本起将不使用 user 这个父指令。
