### ISSUE TITLE
Bug: `console` + `commands` 会出现“文件不存在”问题

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#466]
### Describe the bug

如题见截图，然后 commands 界面（估计是有的）在 console 中不存在

就算 commands 本身的确没有界面，出这个“文件不存在”的错误还是不应该的

### Steps to reproduce

只安装 console 和 commands 就行

### Expected behavior

不报错

### Screenshots

![unknown (4)](https://user-images.githubusercontent.com/29368226/149665837-ca7cec03-b0a9-4c2f-9de7-73ee2b3c8141.png)

### Versions

- OS:  Win10
- Platform: 
- Node version:  v16
- Koishi version:  v4.0.0

**Comment by Shigma** [comment]
commands 应该是有界面的。之后会修。
