### ISSUE TITLE
Feature Request: @koishijs/plugin-forward 支持通过指令添加

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#473]
### Describe the problem related to the feature request

现有的@koishijs/plugin-forward只能通过配置文件进行转发配置
然而，为了能够让群里的非技术人员也能够配置转发，我希望能够通过命令进行转发配置

### Describe the solution you'd like

1. 在数据库的Channel表中记录转发配置（拓展一个forward字段，记录对应source频道的所有转发target）
2. 通过命令进行配置（命令可参考[koishi-plugin-forward](https://github.com/Anillc/forward)）

### Describe alternatives you've considered

无

**Comment by Shigma** [comment]
草，原来你理解的 CLI 是这个意思！

那样的话我觉得这个提议不错。

**Comment by Anillc** [comment]
要不要将官仓中的 forward 和 koishi-plugin-forward 合并一下
