### ISSUE TITLE
Bug: 指令的帮助功能会触发该指令的Action

### ISSUE THREAD

**Issue by yp05327** [koishijs/koishi#475]
### Describe the bug

使用
```
指令 -h
or
帮助 指令
```
之后会收到帮助消息 以及 原本这条指令的处理结果
也就是执行了一次action内的函数

该指令的定义为
···
command [param:type]
···

### Steps to reproduce

1. 安装koishi
···
npm init koishi
Choose a typescript compiler:
tsc
···
2. 打开后台添加机器人
3. 创建以下插件
···
import {Context} from 'koishi'
import axios from "axios";

export default function feiyan(ctx: Context) {
    ctx.command('feiyan [location:text]', '查询肺炎信息')
        .usage('location为可选')
        .example('肺炎查询')
        .action(async (_, location) => {
            let result: string = ``

            await axios.get("https://ncov.dxy.cn/ncovh5/view/pneumonia")
                .then(function (response) {
                    result = `result`
                })

            return result
        })
}
···

### Expected behavior

查询帮助时不应该会执行action

### Versions

- OS: Windows 10
- Backend service: go-cqhttp v1.0.0-beta8-fix2
- Node version: 12.18.3
- Koishi version: 4.0.1

**Comment by Shigma** [comment]
听说是 gocqhttp 的问题？

**Comment by DDEle** [comment]
现版本应该没这个问题了（go-cqhttp v1.0.0-rc1）

**Comment by Shigma** [comment]
他那个是 QQ 频道问题，你得用 QQ 频道测试

**Comment by yp05327** [comment]
确实是gocqhttp的问题
现在没有这个问题了
