### ISSUE TITLE
Feature request: `@koishijs/plugin-status` 日志自动滚动

### ISSUE THREAD

**Issue by mnixry** [koishijs/koishi#481]
### Describe the problem related to the feature request

在`@koishijs/plugin-status` 中, 它提供了一个面板使用户可以在网页端查看Bot日志
但是对于通常的活动日志查看功能来说, 用户较为关心的应该是最新出现, 也就是最底部的日志
目前, 该插件并不具有该功能

### Describe the solution you'd like

添加一个自动滚动功能, 可以使用户随时跟踪最新出现的日志

最好地解决方案应该是监听用户当前查看日志的位置, 如果是最底部就启用自动滚动, 如果不是就关闭

### Describe alternatives you've considered

如果以上功能较难实现, 也可以添加一个开关手动控制是否启用自动滚动

**Comment by Shigma** [comment]
下个版本叫 @koishijs/plugin-logger 了（
