### ISSUE TITLE
Bug: 在同一个实例上跑不同平台的 bot 产生了无法插入数据库的情况

### ISSUE THREAD

**Issue by Anillc** [koishijs/koishi#484]
### Describe the bug

![image](https://user-images.githubusercontent.com/23411248/150792634-93e25092-e03d-4873-95ef-716f6d5e4a3c.png)

koishi 在往数据库中插入用户时对当前平台以外的平台使用了 `''` 作为填充值，与数据库模型中的 unique 发生冲突

### Steps to reproduce

在同一个实例上跑不同平台的 bot

### Expected behavior

正常插入数据库

### Versions

- OS: ubuntu container (host: NixOS) 
- Backend service: go-cqhttp 1.0.0-beta8-fix2 
- Node version:  17.4.0
- Koishi version: 4.1.0

**Comment by Shigma** [comment]
regression of 706b828d5ced3cd721d969d7b2dedef7175fe844
