### ISSUE TITLE
Bug: 网页面板在插件市场安装插件

### ISSUE THREAD

**Issue by ZerxZ** [koishijs/koishi#490]
### Describe the bug

安装成功却提示 安装失败提示和不刷新

### Steps to reproduce

在网页面板里面插件市场

### Expected behavior

安装成功 刷新页面

### Versions

- OS:Windows 10
- Platform: onebot
- Node version: v16.13.1
- Koishi version: 4.1.1

**Comment by Shigma** [comment]
我们更新了版本，应该已经修复了此问题。麻烦您确认一下。

**Comment by Shigma** [comment]
经过后续 issue 的反馈此问题已经解决。
