### ISSUE TITLE
Bug: cli 启动下 `manager` 无法启动，提示缺少服务 `loader`

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#497]
### Describe the bug

按理来说 cli 启动就有 loader 了

### Steps to reproduce

只安装适配器、数据库、console 和 manager 就行，如下图

### Expected behavior

当然是能打开啦！

### Screenshots

![image](https://user-images.githubusercontent.com/29368226/152734458-9c357ab8-1194-4018-99b6-a94e1f6e780d.png)
![屏幕截图 2022-02-07 141822](https://user-images.githubusercontent.com/29368226/152734754-217fb927-5642-42d7-b130-3691908b8219.png)

### Versions

- OS:  Win10
- Platform: 
- Node version:  v16.13.2
- Koishi version:  v4.1.2

console v2.1.0
manager v1.3.0

**Comment by Shigma** [comment]
这是因为 manager 只对使用 json/yaml 的配置文件有效。
