### ISSUE TITLE
请问一下有关于插件的例子吗

### ISSUE THREAD

**Issue by Illyasviels** [koishijs/koishi#5]
在插件上下文中使用sender无效

error ctx.sender.sendPrivateMessage is not a function

```
module.exports.name = 'base'

module.exports.apply = (ctx) => {
  ctx.receiver.on('message', (meta) => {
    ctx.sender.sendPrivateMessage(*, 'Hello world')
  })
  console.log(ctx.sendPrivateMessage)
}
```

**Comment by Shigma** [comment]
@Illyasviels 感谢你的 issue。

正确的 API 应该是 [`sendPrivateMsg`](https://koishijs.github.io/api/sender.html#sender-sendprivatemsg) 而不是 `sendPrivateMessage`.

**Comment by Shigma** [comment]
貌似文档中一些地方写错了，我得改一下……谢谢反馈。🤣

**Comment by Illyasviels** [comment]
嗯 谢啦~
