### ISSUE TITLE
对指定的上下文安装命令后执行异常

### ISSUE THREAD

**Issue by Clansty** [koishijs/koishi#50]
**Describe the bug**

对指定的上下文安装命令后，执行正确的命令时出现 你要找的是不是...

**To Reproduce**

```js
const { App } = require('koishi')
require('koishi-database-mysql')

global.dev=true
const app = new App({
  type: 'http',
  port: 8080,
  server: 'http://localhost:5700'
})

app.start()
app.group(xxx).command('echo <message>')
  .action(({ meta }, message) => meta.$send(message))
```
在 xxx 这个群发送 `echo a`

**Expected behavior**

机器人回复“a”

**Screenshots**

![C936CCB999261852C947E1BBF8ED63A7](https://user-images.githubusercontent.com/18461360/87393553-edbaa600-c5e0-11ea-832e-e83922e16f4c.jpg)

**Versions**

- OS: Ubuntu 20.04 WSL
- Node Version: 12.18.2
- CoolQ Version: 5.15.10
- CQHTTP Version: 4.15.0
- Koishi Version: 1.12.0

**Comment by Shigma** [comment]
Fixed in fdabf2429887677f0b5e520d67b7bfe06795381f, available in v2 beta.
