### ISSUE TITLE
Feature Request: 从 QQ 转发到 TG 的时候，图片会自己没了

### ISSUE THREAD

**Issue by eyians** [koishijs/koishi#509]
### Describe the problem related to the feature request

跨平台转发图片

### Describe the solution you'd like

有可能使用CQ:image中的url

**Comment by Anillc** [comment]
测试了一下，我这边发送 qpic.cn 的图片没有遇到发送失败的情况。请问发送失败有报错日志吗，具体的情况是怎么样的呢

另外我建议这种跨平台发送图片最好在 koishi 实例中获取图片再以 base64 的形式发送出去，因为 bot 平台并不一定能访问到从另一个平台得到的链接
