### ISSUE TITLE
不转换简体/繁体字符

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#51]
**Is your feature request related to a problem? Please describe.**

[这里会自动把繁体字转换为简体字](https://github.com/koishijs/koishi/blob/c3b0b5094a6776050fcabf4f0d51b7231225f6de/packages/koishi-core/src/app.ts#L279)
$parsed很好用，但希望能不强制转换为简体字

**Describe the solution you'd like**

options中增加参数阻止繁体字被转换为简体字

**Describe alternatives you've considered**

不用$parsed.message

**Additional context**

**Comment by Shigma** [comment]
可以做的，后面我发个版本加个选项吧~

顺便能说下你这个需求的场景吗？

**Comment by arily** [comment]
场景来自 https://github.com/Exsper/SillyResponseBot
bot会根据提问做出回答
小圈子里有些词用到了被认为是繁体字的字
并且偶尔会有些繁体中文使用者，强制转换掉感觉有点不好

**Comment by Shigma** [comment]
dbda27dff38b202e517f2a4bb7c2b34b02188e54 中新增了一个 processMessage 选项，可以手动控制处理消息的方式，将其覆盖即可满足你的需求。已经实装于 koishi-core@2.0.0-beta.4。
