### ISSUE TITLE
Feature Request: 增加对机器人发出的消息的进行处理的API

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#514]
### Describe the problem related to the feature request

转发机器人自身发送的消息

### Describe the solution you'd like

session.send触发

**Comment by DDEle** [comment]
试试这个?
[#事件-before-send](https://koishi.js.org/api/core/events.html#%E4%BA%8B%E4%BB%B6-before-send)

**Comment by idanran** [comment]
> 试试这个?
> [#事件-before-send](https://koishi.js.org/api/core/events.html#%E4%BA%8B%E4%BB%B6-before-send)

好的，谢谢。但我突然想到一个问题，那就是机器人会不会循环发送自己的消息？

**Comment by Shigma** [comment]
> 好的，谢谢。但我突然想到一个问题，那就是机器人会不会循环发送自己的消息？

这个自己判断清楚就可以。

**Comment by idanran** [comment]
> > 好的，谢谢。但我突然想到一个问题，那就是机器人会不会循环发送自己的消息？
> 
> 这个自己判断清楚就可以。

👌谢谢你
