### ISSUE TITLE
Bug: web控制台更新依赖报错

### ISSUE THREAD

**Issue by jiajiu123** [koishijs/koishi#524]
### Describe the bug

在控制台更新依赖时，控制台提示安装超时，终端显示： console unknown message: install { '@koishijs/plugin-database-mysql': '4.1.2' }
更新或移除任何依赖的任何版本都会出现此错误

### Steps to reproduce

在依赖管理选择版本后，点击更新依赖，终端提示console unknown message: install { '@koishijs/plugin-database-mysql': '4.1.2' }

### Expected behavior

可以正常更新依赖

### Screenshots

![image](https://user-images.githubusercontent.com/60831923/154176301-b896e97f-1412-4081-913d-cce6b6cac852.png)
![image](https://user-images.githubusercontent.com/60831923/154177462-fe16d50a-8242-4cbc-bd89-77f3ce86a072.png)

### Versions

- OS: Ubuntu 20.04.3 LTS
- Platform: QQ
- Node version: 16.14.0
- Koishi version: 4.2.1
- console version: 3.0.1

**Comment by Shigma** [comment]
已发布 @koishijs/plugin-manager@1.5.1，麻烦看下能不能解决你的问题。

**Comment by jiajiu123** [comment]
已解决
