### ISSUE TITLE
Bug: `status` + `mysql` 统计每小时发言数会全部统计到 0:00-1:00 区间

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#536]
### Describe the bug

听说隔壁 mongo 没有这个问题

### Steps to reproduce

实例地址 https://bot.idl.ist

### Expected behavior

那当然是每个时间段都有啦

### Screenshots

![image](https://user-images.githubusercontent.com/29368226/154922257-7aa30c4c-5f42-4bf4-b446-ad4081d3e49c.png)

### Versions

- OS:  Win10
- Platform:  all
- Node version:  v16.3.0
- Koishi version:  v4.2.2

**Comment by DDEle** [comment]
![image](https://user-images.githubusercontent.com/28386673/155954436-7ec28dff-6a0b-4d3b-9649-986f58b550f3.png)
👆相关问题

**Comment by idlist** [comment]
现在用的版本是 v4.5.2，我还是有这个问题，是不是得考虑捅库 🤔

**Comment by idlist** [comment]
看了一下控制台又好了，看来是必须删库才能修复这个问题

**Comment by DDEle** [comment]
> 看了一下控制台又好了，看来是必须删表才能修复这个问题。
> 
> 就是不知道是在哪个版本删表之后能修复这个问题，我服务器上的也是 v4.5.2，迁移服务器的时候顺手把 `status` 的几个表全删了，然后就好了。本地的全累计在一起估计是没删表的锅。
> 
> 不过既然问题没了就先关了。

看起来是之前 `status_hourly` 表的 `time` 字段被设置为了 `DATE` 类型...

如果别人出现类似问题的话也许可以先检查下这个点。
