### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#54]
提供选项，让command执行中遇到错误自动发送 e.message 到群或打印到console
或者command return一个string或Promise<string>也可以作为快捷回复使用

**Comment by masnn** [comment]
每次写 return await meta.$send(...) 感觉好蠢 不如直接 return ...

**Comment by simon300000** [comment]
这里应该可以把await去掉

**Comment by masnn** [comment]
确实可以，不过写习惯了（

**Comment by masnn** [comment]
有时候meta.$send发不出去的话应该把错误log一下（刚刚研究了半天发现我在尝试发json

**Comment by Shigma** [comment]
这是两个问题。

1. 指令执行中的报错信息显示将在下个大版本大幅优化。
2. meta.$send 默认情况下使用的是 send_msg_async，此接口无法获得是否发出去。我在考虑增加一个选项决定这个行为，但是还没想好名字（其实 v1 就想到这个问题了，就因为没想到名字一直拖到现在 233）

**Comment by Shigma** [comment]
更新 185e851aa48cf4aa2564f3bd654389a3393e69fe 中已经实装了接口 `appOptions.preferSync`，用于在 `meta.$send` 中禁用快捷操作和强制使用同步 API。

**Comment by Shigma** [comment]
> 每次写 return await meta.$send(...) 感觉好蠢 不如直接 return ...

这个行为还不确定要不要改，因为有些指令要多步发送，不然不好区分？

**Comment by masnn** [comment]
多部发送的话直接内部用meta.$send或者app.sender.sendMsg处理，return Promise<null>即可，Promise<string>和string 则直接回复内容

**Comment by Shigma** [comment]
a1ce1a53804ae53ff8b2e120592bf83dbcd097f5 以实现，代码示例：

```ts
ctx.command('cmd').action(() => return 'foo')
// 输入 cmd
// 输出 foo
```
