### ISSUE TITLE
自动重定向至子指令后选项无法自动赋值

### ISSUE THREAD

**Issue by b1acksoil** [koishijs/koishi#540]
### Describe the bug

首先十分感谢采纳之前在 #476 的建议！

但出现了新的问题，即定义选项后，无法自动根据缩写给选项变量赋值

如[文档中](https://koishi.js.org/guide/command/command.html#%E5%AE%9A%E4%B9%89%E9%80%89%E9%A1%B9)所说，使用 `.option('-a', 'alpha')` 定义选项后，应该在使用 `-a` 选项时，自动为 `options.alpha` 赋值

但在调用指令 `/cmd subcmd -a` 时发现并没有为 `alpha` 赋值，反而是直接赋给了 `a`

> console.log(JSON.stringify(options))
> 
> {"a":true}

而在父子指令中加上 `.` （`/cmd.subcmd -a`）后又恢复正常，为 `options.alpha` 赋上了 `true`

> console.log(JSON.stringify(options))
> 
> {"alpha":true}

### Steps to reproduce

定义父指令 `cmd` 并添加子指令 `subcmd`，然后为 `subcmd` 添加选项 `('alpha', '-a')`

分别使用 `cmd subcmd -a` 和 `cmd.subcmd -a` 进行测试

### Expected behavior

重定向至子指令时自动根据缩写给选项变量赋值

### Versions

- OS: Windows 10
- Platform: Onebot
- Node version: 16.13.2
- Koishi version: 4.2.1

**Comment by b1acksoil** [comment]
发现了另一个问题（

定义alpha和beta两个选项
```
ctx
  .command('cmd')
  .subcommand('subcmd')
  .option('alpha', '-a')
  .option('beta', '-b')
```
这时不使用自动重定向（`cmd.subcmd --alpha --beta`）

> console.log(JSON.stringify(options))
> 
> {"alpha":true,"beta":true}

使用自动重定向（`cmd subcmd --alpha --beta`）会出现

> console.log(JSON.stringify(options))
> 
> {"alpha":"--beta"}

**Comment by Shigma** [comment]
嗯确实是需要解决的 Bug。
