### ISSUE TITLE
Bug: 控制台聊天（plugin-chat）中的 QQ 图片无法正常显示

### ISSUE THREAD

**Issue by DDEle** [koishijs/koishi#549]
### Describe the bug

QQ图片会显示为“此图片来自QQ空间 未经允许不可引用”，但是把图片链接复制出来在新窗口中打开是没有问题的。
![image](https://gchat.qpic.cn/gchatpic_new/2502045323/801547821-2738995759-E57DF3089D64CD2E0C9CF6B219B1E628/0?term=3)

=> 

![image](https://user-images.githubusercontent.com/28386673/155674639-8da0dd37-f2e6-4000-a5ed-4fa9e51c4fe0.png)

### Steps to reproduce

显然

### Expected behavior

正常显示图片

### Versions

- OS: Ubuntu（浏览器为 Win10 Edge）
- Platform: Onebot
- Node version: v16.13.1
- Koishi version: v3的时候就开始有了 v4也有 非官仓调试

**Comment by Shigma** [comment]
因为之前与 assets 冲突，临时关掉了代理，之后大概加回去（

**Comment by shigma** [comment]
Fixed by 775989c78741f3821844fa84e3c9741f5f742111
