### ISSUE TITLE
pagination of help

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#55]
help太长了发不出去
应添加分页功能

**Comment by Shigma** [comment]
如果太长的话建议通过子指令的方式组织一下，这样查看的时候也方便一点~

分页的话也可以考虑做~

**Comment by Shigma** [comment]
最新一次更新 1b2877752aac362bd143b2b1bcd6ef61c7689457 中实装了 `CommandConfig.hidden` 选项。
