### ISSUE TITLE
Koishi v2 is coming...... 🎉

### ISSUE THREAD

**Issue by Shigma** [koishijs/koishi#56]
![image](https://user-images.githubusercontent.com/33423008/89108336-2b854e80-d46a-11ea-9f97-4af9cd2da123.png)

经过半年多，上万行代码的开发，Koishi v2 终于要跟大家见面了。目前核心功能已经趋于稳定，预计下周出 beta 版本。

**Comment by masnn** [comment]
koishi 来了  cq走了 😢

**Comment by Shigma** [comment]
没办法……我现在开发环境已经换成 go-cqhttp 了……想想我还买过 8 个授权……（哭）

![image](https://user-images.githubusercontent.com/33423008/89114951-6f9d4100-d4b4-11ea-8509-55df183d8cff.png)

**Comment by masnn** [comment]
有没有考虑过对接其他平台 e.g. t.me ?

**Comment by Shigma** [comment]
有的！不过得慢慢来 233333

**Comment by masnn** [comment]
go-cqhttp目前来看消息长度限制比cqhttp短不少，请注意

**Comment by muyuqingqiu** [comment]
我的pro还没到期，但是也得找后路了emmm

**Comment by dzcpy** [comment]
快三个星期过去了，2.0怎么样了？可以支持go-cqhttp中一些coolq里没有的特殊功能吗？

**Comment by masnn** [comment]
在做了在做了.jpg CQ:reply已经支持了

**Comment by Shigma** [comment]
> 快三个星期过去了，2.0怎么样了？可以支持 go-cqhttp 中一些 coolq 里没有的特殊功能吗？

我这一直在跟进 go-cqhttp 的功能，你只要用 2.0 就是基本全功能支持。
