### ISSUE TITLE
Bug: 控制台插件列表为空

### ISSUE THREAD

**Issue by maxoyed** [koishijs/koishi#562]
### Describe the bug

创建好项目自动启动后，打开插件市场后显示“共搜索到 0 个插件“。

### Steps to reproduce

1. 按照文档”入门-创建模板项目“中的描述创建模板项目（从模板仓库创建或使用包管理器创建均出现此问题）
2. 打开浏览器访问控制台，并点击左侧导航栏的”插件市场“

### Expected behavior

打开”插件市场“出现非空的插件列表

### Screenshots

![image](https://user-images.githubusercontent.com/25519245/156826672-4603dd80-6797-48c0-b50f-7bfedc1a8b43.png)
![image](https://user-images.githubusercontent.com/25519245/156826729-1e45e9c7-4130-425d-9ef5-f10c1b3a2e6f.png)
![image](https://user-images.githubusercontent.com/25519245/156827829-e8dff3f6-8bdf-4947-83bf-6c345b8cc916.png)

### Versions

- OS: Windows 10 专业版 21H2
- Platform: OneBot
- Node version: v16.13.2 and v16.14.0
- Koishi version: 4.4.0

### Additional context

在Windows和Linux主机上均测试有此问题

**Comment by Shigma** [comment]
目前无法复现这个问题。由报错信息猜测是你本机上无法访问 npm registry。等其他用户的复现吧。

**Comment by maxoyed** [comment]
@Shigma 破案了，npm不能设置成淘宝源，否则无法使用 npm search，把淘宝源删除就可以了
