### ISSUE TITLE
Bug: 控制台界面 显示数据库未安装

### ISSUE THREAD

**Issue by mrchenxxx** [koishijs/koishi#568]
### Describe the bug

安装的数据库是MongoDB 成功连接数据库后,控制台界面 显示数据库未安装
![image](https://user-images.githubusercontent.com/44868578/156904080-3f2dfe28-a25a-4b31-b353-83b4d517885b.png)
![Uploading image.png…]()

### Steps to reproduce

yarn 创造的项目 使用的数据库是MongoDB

### Expected behavior

显示正常

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by Shigma** [comment]
@mrchenxxx 这个问题我刚刚没有复现成功，我按照我猜测的一个可能性尝试了修复。

请将 @koishijs/plugin-console 更新到 3.2.5 以上的版本再次测试。如果仍然有问题可以在下面回复我。
