### ISSUE TITLE
刚用koishi开发完我的机器人。。酷Q凉凉了

### ISSUE THREAD

**Issue by SHALEWOXIEXIE** [koishijs/koishi#57]
还有其他的替代方案吗, 唉, 刚研究了一阵子koishi, 写完自己的程序, 酷Q就凉凉了, 可惜了这么好的框架, 谢谢作者了

**Comment by masnn** [comment]
https://github.com/Mrs4s/go-cqhttp 目前测试与koishi兼容性较好。

**Comment by SHALEWOXIEXIE** [comment]
谢谢 我试试  @masnn

**Comment by SHALEWOXIEXIE** [comment]
mirai 作者连夜删掉了github。。在群里表示不再维护

**Comment by plasmatank** [comment]
> mirai 作者连夜删掉了github。。在群里表示不再维护

连夜把库下下来了

**Comment by Shigma** [comment]
@SHALEWOXIEXIE koishi v2 将基于 go-cqhttp 开发和测试，未来也会尝试适配更多的框架。
