### ISSUE TITLE
Bug: Telegram平台中content错位

### ISSUE THREAD

**Issue by univeous** [koishijs/koishi#581]
### Describe the bug

session.content与实际的content中segment的位置不同。

### Steps to reproduce

console.log(session.content)

### Expected behavior

实际content:
`"x @a y"`
期望session.content:
`"x [CQ:at, ...] y"`
实际输出的content:
`"[CQ:at, ...]x  y"`

### Versions

- OS: 
- Platform: Telegram
- Node version: 16.13.2
- Koishi version: 4.4.2

**Comment by Shigma** [comment]
adapter-telegram 2.2.3 版本已解决此问题。
