### ISSUE TITLE
Bug: 控制台new插件命令无法正确获取输入的插件名

### ISSUE THREAD

**Issue by mkZH0740** [koishijs/koishi#588]
### Describe the bug

使用yarn run new并填写name和description后报错

### Steps to reproduce

使用yarn create koishi创建项目后使用yarn new创建插件

### Expected behavior

正确创建插件

### Screenshots

![image](https://user-images.githubusercontent.com/56063116/160522118-2041518c-fd74-4505-9c11-b1390cd220fb.png)

### Versions

- OS: windows 10
- Platform: 
- Node version: 14.18.1
- Koishi version: ^4.5.0

### Additional context

typo位于报错位置，将name修改为this.name后问题解决
修改前：
![image](https://user-images.githubusercontent.com/56063116/160522544-a941d1f8-3824-4eeb-8ae6-196bc11714f4.png)
修改后：
![image](https://user-images.githubusercontent.com/56063116/160522694-782fe148-c5b1-4610-a6d5-e560c67411f2.png)

**Comment by Shigma** [comment]
已发布 @koishijs/scripts@1.2.4，更新到最新版本可修复此问题。
