### ISSUE TITLE
Bug: 发送图片消息，报错上传图片失败

### ISSUE THREAD

**Issue by zfowed** [koishijs/koishi#590]
### Describe the bug

我发了一条图片消息：
```
[CQ:image,file=https://acg.toubiec.cn/random.php?sj=2088659730]
````
但是报错了，想知道怎么才可以发送图片

![image](https://user-images.githubusercontent.com/23629388/160765504-f01e8200-0c13-42bf-b464-ba45e8436a26.png)

### Steps to reproduce

用到了 gocphttp 创建

![image](https://user-images.githubusercontent.com/23629388/160782314-1743612f-ab13-4f27-92ee-759ea7abde98.png)

```
ctx.middleware(async (session: Session, next: Next): Promise<void | string> => {
    return `[CQ:image,file=https://acg.toubiec.cn/random.php?sj=2088659730]`
})
```

### Expected behavior

期望正常发送图片

### Versions

- OS: Windows 11
- Backend service: 
- Node version: 16.14.0
- Koishi version: 4.5.0

**Comment by Shigma** [comment]
file 换成 url

**Comment by zfowed** [comment]
@Shigma 哇塞，可以了，万分感谢！！！

**Comment by zfowed** [comment]
已经解决了
