### ISSUE TITLE
Bug: `@koishijs/plugin-puppeteer` 中关于 `browser.viewPort` 的设置不起作用

### ISSUE THREAD

**Issue by Dup4** [koishijs/koishi#593]
### Describe the bug

<img width="901" alt="image" src="https://user-images.githubusercontent.com/38343778/161717164-beff3b69-6ddd-44a7-805b-a97d110f4292.png">

以上是 `browser.viewPort` 的默认值。

我设置为如下配置：

```yaml
puppeteer:
  browser:
    defaultViewport:
      width: 1920
      height: 1080
```

但是截图仍然是 `800x600` 的。

### Steps to reproduce

根据上述描述可以轻易重现。

### Expected behavior

截图的默认视口大小应为 `1920x1080`。

### Versions

- OS: macOS 12.3
- Platform: OneBot
- Node version: 16.11.0
- Koishi version: 4.5.0
- puppeteer-core version: 13.5.2

### Additional context

https://github.com/koishijs/koishi/blob/1fad834fc03115eb797bd32ffae144536f589275/plugins/puppeteer/src/index.ts#L22-L29

我查看过相关源代码，问题可能出在 23 行的 `viewPort`。

https://github.com/koishijs/koishi/blob/1fad834fc03115eb797bd32ffae144536f589275/plugins/puppeteer/src/index.ts#L47-L49

48 行直接拿 config 传入 `puppeteer.launch` 作为 `options` 参数。

https://github.com/puppeteer/puppeteer/blob/24e1469e15bab88031650dcdd890edf499fb5c25/src/common/BrowserConnector.ts#L31-L50

但是 `puppeteer.launch` 中 `options` 对应的设置 `viewPort` 的参数名应该是 `defaultViewport`。

所以其实简单 fix 的话，用以下的 patch 就能修复。

```patch
diff --git a/plugins/puppeteer/src/index.ts b/plugins/puppeteer/src/index.ts
index cb4cec3..27d189b 100644
--- a/plugins/puppeteer/src/index.ts
+++ b/plugins/puppeteer/src/index.ts
@@ -21,7 +21,7 @@ type LaunchOptions = Parameters<typeof puppeteer.launch>[0]
 
 const LaunchOptions = Schema.object({
   executablePath: Schema.string().description('Chromium 可执行文件的路径。缺省时将自动从系统中寻找。'),
-  viewPort: Schema.object({
+  defaultViewport: Schema.object({
     width: Schema.natural().description('默认的视图宽度。').default(800),
     height: Schema.natural().description('默认的视图高度。').default(600),
     deviceScaleFactor: Schema.number().min(0).description('默认的设备缩放比率。').default(2),
```

如果认可这个 fix，我可以提一个 PR.

**Comment by Shigma** [comment]
非常感谢！似乎是因为 puppeteer 更新导致了 API 变更。
