### ISSUE TITLE
酷Q停运了，这个会受影响嘛

### ISSUE THREAD

**Issue by lxxxv5** [koishijs/koishi#60]
求助，酷Q停运了，这个会受影响嘛

**Comment by plasmatank** [comment]
> 求助，酷Q停运了，这个会受影响嘛

目前可以用别的框架，比如go-cqhttp

**Comment by lxxxv5** [comment]
> > 求助，酷Q停运了，这个会受影响嘛
> 
> 目前可以用别的框架，比如go-cqhttp

感谢！
