### ISSUE TITLE
部分官方插件仍不支持 i18n

### ISSUE THREAD

**Issue by DGCK81LNN** [koishijs/koishi#613]
部分官方插件仍不支持 i18n，希望能尽快添加本地化支持。其中，以下功能目前还在使用 `template`：

* exit ([packages/cli/src/worker/daemon.ts](https://github.com/koishijs/koishi/blob/bd78a603af3442445b6c6417f15d656c41e25cd4/packages/cli/src/worker/daemon.ts))
* callme ([plugins/a11y/callme](https://github.com/koishijs/koishi/blob/bd78a603af3442445b6c6417f15d656c41e25cd4/plugins/a11y/callme/src/index.ts))
* chat ([plugins/frontend/chat](https://github.com/koishijs/koishi/blob/bd78a603af3442445b6c6417f15d656c41e25cd4/plugins/frontend/chat/src/index.ts))
* teach ([plugins/teach](https://github.com/koishijs/koishi/tree/bd78a603af3442445b6c6417f15d656c41e25cd4/plugins/teach/src))

**Comment by Shigma** [comment]
官方插件现已全部支持 i18n。
