### ISSUE TITLE
Bug: The requested module 'xxxx/schemastery/lib/index.js' does not provide an export named 'Schema' at  (at utils.ts:1:1)

### ISSUE THREAD

**Issue by ParadiseWitch** [koishijs/koishi#634]
### Describe the bug

更新依赖后，使用开发模式（`yarn dev`）启动，网页显示空白，控制台报错：
```
The requested module 'xxxx/schemastery/lib/index.js' does not provide an export named 'Schema' at  (at utils.ts:1:1)
```

### Steps to reproduce

1. 创建模板项目并安装好依赖
2. 使用开发模式启动

### Expected behavior

开发模式启动项目后网页能正常显示

### Screenshots

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/37146904/164884049-717624a9-13b4-427c-b7b8-c4f7423bee7e.png">

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/37146904/164884290-b84af42e-9ddd-4b14-86de-8f7dac2af7c8.png">

### Versions

- OS: macOS Monterey 
- Node version: 16.13.1 
- Koishi version: 4.6.0

**Comment by Shigma** [comment]
Fixed by c76a19a4389aecc35585f03145e6251d2f6d19b5.
