### ISSUE TITLE
Bug: adapter-onebot leads to error in manager plugin

### ISSUE THREAD

**Issue by mkZH0740** [koishijs/koishi#649]
### Describe the bug

使用adapter-onebot插件正向websocket连接gocqhttp启动时报错

### Steps to reproduce

如描述

### Expected behavior

无报错

### Screenshots

![image](https://user-images.githubusercontent.com/56063116/166135514-073eca71-6fa8-4cd7-aaff-9cba4ea24763.png)
![image](https://user-images.githubusercontent.com/56063116/166135526-700a699a-07bc-4a5d-abd8-16971fa18a40.png)

### Versions

- OS: Arch Linux
- Backend service: 1.0.0-rc1
- Node version: 17.9.0
- Koishi version: 4.6.1

**Comment by Shigma** [comment]
问一下这个 bot 是启用了 QQ 频道的吗？

**Comment by Shigma** [comment]
已修复，将于下个版本实装。
