### ISSUE TITLE
Bug: koishi-scripts 在 tsc lint 失败时不输出错误信息

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/koishi#650]
### Describe the bug

如题

### Steps to reproduce

- create-koishi
- 新建插件
- 放一点不能通过 lint 的代码
- yarn build 或 yarn run koishi-scripts build 不显示错误信息
- yarn tsc -b 正常显示错误信息

### Expected behavior

略

### Versions

koishi 4.6.1
scripts 1.3.1

**Comment by shigma** [comment]
这是因为 tsc 根本不适用 stderr，它把所有输出全堆到 stdout 了。
