### ISSUE TITLE
Feature Request: Discord adapter: WebSocket 支持代理

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/koishi#653]
### Describe the problem related to the feature request

我的 Discord 机器人反复重连，虽然能连上

### Describe the solution you'd like

Discord 使用 ws 链接官方的 api ，并不共享全局设置的 proxyAgent (是给 ctx.http 用的)
考虑继承全局的 proxyAgent 设置或提供独立的设置

### Describe alternatives you've considered

proxifier / proxychains + 域名黑白名单，成本比较高（比较麻烦）

### Additional context

![image](https://user-images.githubusercontent.com/21092951/166207265-96f732ee-fc6d-4735-9436-ed69cc72da99.png)

**Comment by TimeBather** [comment]
Ok,Is relly

**Comment by Shigma** [comment]
已经做了：https://github.com/koishijs/koishi/commit/a02bf8a9fa0563b388f334782be0e57f1335c686

**Comment by H4M5TER** [comment]
我没设 proxyAgent
