### ISSUE TITLE
Feature Request: Manager: Market: 提供 registry 的配置项

### ISSUE THREAD

**Issue by H4M5TER** [koishijs/koishi#654]
### Describe the problem related to the feature request

pnpm 也会使用 .npmrc，这没什么，但是 pnpm config 会调 npm config，而 corepack 安装 pnpm 时不会携带 npm，然后就会爆
pnpm 能独立运行却依赖 npm config 而没有去判断 npm 存在是坏坏的。

### Describe the solution you'd like

虽然这可以说是 pnpm 的问题，但是我觉得提供一个 registry 的配置项是好的。
用户完全有可能希望在本地使用一个没有提供 search 的 registry 吧。（我确实是）

### Describe alternatives you've considered

去输出 pnpm

**Comment by Shigma** [comment]
没听懂问题？
