### ISSUE TITLE
Is this project allowed for commercial use?

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#66]
We want to make QQ bots based on this project for a text RPG game, making profits. Now I wonder if this project is allowed for commercial use. If not for free, how would I be able to purchase a license?

**Comment by Shigma** [comment]
Koishi v2 将采用 LGPL 3.0 协议。基于此协议，你可以**调用 Koishi 的功能，同时闭源+商用，无需向我支付金额**。在本项目的 README 中有一个赞赏码，它仅代表对我开发开源项目的支持，不是你使用本软件的必需。

但如果你**修改了 Koishi 的功能**，例如复制并修改了本仓库中任何一个组件的代码，你需要把你修改的代码**按照同样的协议开源**。其他部分依旧可以如上使用。
