### ISSUE TITLE
模糊匹配严格度在一些情况下失效

### ISSUE THREAD

**Issue by APicebar** [koishijs/koishi#67]
现在只发现一个情况下失效
在设置 commandPrefix 并执行带有prefix的指令的情况下，严格度会失效
设置 commandPrefix 和 similarityCoefficient 后，对bot发送带prefix的指令即可触发

![a70HqP.png](https://s1.ax1x.com/2020/08/09/a70HqP.png)
![a707rt.png](https://s1.ax1x.com/2020/08/09/a707rt.png)
![a70TKI.png](https://s1.ax1x.com/2020/08/09/a70TKI.png)

- OS: Windows 10
- GO-CQHttp Version: 0.9.14
- Node Version: v12.18.3
- Koishi Version: v1.12.0

如果是我傻逼，请毫不留情的D我（

**Comment by Shigma** [comment]
没看懂你的问题（捂脸）

如果 commandPrefix 为 `!`，只有以 `!` 开头的会被识别为指令。similarityCoefficient 设置为 1 意味着所有无法识别的指令都会给予提示。所以根据这个设置，机器人的行为恰好是期望的行为。

**Comment by APicebar** [comment]
那应该是你doc写错了吧（
我当时看doc的时候是说 similarityCoefficient 为1时禁用模糊啊（（

![](https://cdn.luogu.com.cn/upload/image_hosting/x6efgy2d.png)

**Comment by Shigma** [comment]
啊……是的，我应该是写反了，0 的时候禁用。麻烦你再用程序确认一下可以吗？

**Comment by APicebar** [comment]
啊现在不是很方便（
我早上早点起来测吧（
家长还在（
测完了我就自己关issue吧（趴

**Comment by Shigma** [comment]
当然不急 23333

也感谢你指出错误。
