### ISSUE TITLE
Feature Request: 支持端口递增尝试

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi#675]
新增配置项 `maxPort`。其默认值当 `selfUrl` 非空时等于 `port`，否则为 `65535`。

应用启动时，如果端口已被使用，则自动尝试下一个端口；除非当前端口超过了 `maxPort`。

**Comment by purerosefallen** [comment]
why not getting free ports directly from system API?

**Comment by shigma** [comment]
Spawning a netstat subprocess is slow compared to portfinder.
