### ISSUE TITLE
doc: guide/console/extension

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#678]
https://koishi.js.org/guide/console/extension.html#%E5%88%9B%E5%BB%BA%E6%89%A9%E5%B1%95
位置： src/index.ts
```js
ctx.console.addEntry({
      dev: resolve(__dirname, 'client/index.ts'),
                             //^ not found
```
我按照实际dataview的代码 ```resolve(__dirname, '../client/index.ts'),```才成功添加console页面

**Comment by shigma** [comment]
这两行缺了 `../`，感谢反馈
