### ISSUE TITLE
Bug: 无法显示配置

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi#684]
### Describe the bug

控制台配置页任何选项都显示

![image](https://user-images.githubusercontent.com/20179549/168578062-60513b4f-448c-4b7c-8b13-48b672d8cd32.png)

### Steps to reproduce

安装世界上所有的插件

### Expected behavior

1. 配置正常显示

2. 如果有配置不能正常显示，则应该在控制台报错

### Versions

```
# uname -a
Linux VM-4-12-ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# node -v
v16.13.1
# yarn koishi -v
yarn run v1.22.17
$ koishi -v
koishi/4.7.0 linux-x64 node-v16.13.1
```

### Additional context

该 bug 不影响程序的正常工作，且不是安装世界上所有插件的话很难出现，可以不用修

**Comment by shigma** [comment]
> 安装世界上所有的插件

请依次尝试关闭插件以定位问题。Koishi 不需要也不可能为插件负责。
