### ISSUE TITLE
Bug: QQ频道适配器收到消息时出错

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#687]
### Describe the bug

通过QQ频道适配器（@koishijs/plugin-adapter-qqguild）接收消息时会出现**TypeError: Cannot read properties of undefined**

### Steps to reproduce

1. 配置QQ频道适配器
2. 在QQ频道向机器人发送@消息（或在配置了MESSAGE_CREATE(1<<9)这个Intents的情况下直接发送消息）
3. 机器人日志出现报错

### Expected behavior

应该正常进行反应。

### Versions

- OS: Windows 10
- Platform: QQGuild
- Node version: 18.0.0
- Koishi version: 4.7.0

**Comment by TimeBather** [comment]
这个问题应该是Adapter没有正确响应图片等富文本消息导致的，排查点应该在message的解析函数那里，估计是没传context回来
