### ISSUE TITLE
feature request 本地测试逻辑

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#7]
能否增加在本地测试插件的功能

**Comment by Shigma** [comment]
@arily 可以具体描述一下你需要的功能吗 🤣

**Comment by arily** [comment]
在本地给bot发送信息用来测试.middleware()还有.command()

**Comment by Shigma** [comment]
如果你想要的是用于单元测试的功能的话，建议参考这些单元测试文件：
- https://github.com/koishijs/koishi/blob/master/packages/koishi-core/tests/runtime.spec.ts
- https://github.com/koishijs/koishi/blob/master/packages/plugin-common/tests/help.spec.ts

它们的基本的原理是利用 koishi-test-utils 创造一个假的 CQHTTP 服务器并与 koishi-core 通信。不过 koishi-test-utils 目前只是为了我写单元测试开发的，可能部分功能只对 jest 有用。

**Comment by arily** [comment]
好的 我去看看

**Comment by Shigma** [comment]
@arily koishi-test-utils 1.1.0 已经发布了，我也撰写了相关的文档：

- 使用指南：https://koishijs.github.io/guide/unit-tests.html
- API 文档：https://koishijs.github.io/api/test-utils.html

如果对这个新的模块有什么建议，欢迎另开 feature request 或者 bug report。
