### ISSUE TITLE
Feature: 安装在 devDep 中的插件在控制台中也被列入依赖

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#701]
### 简介

现在的表现是

![QQ图片20220528160411](https://user-images.githubusercontent.com/29368226/170816659-76ca78e9-52e7-46cc-a9ea-3dc0773204a7.png)
![QQ图片20220528160420](https://user-images.githubusercontent.com/29368226/170816672-878dd73b-a0cd-4975-911a-99bd842652df.png)

但是因为将机器人部署在生产环境上一般是直接 git clone 然后 npm i （或者 npm ci），然后不论是哪种安装方式都会将 devDep 安装下来，所以实际上将插件安装在 devDep 是可行的，只是说不一定是最佳实践。

而在控制台中，则必须将插件安装在 dep 里才视作“列入依赖”。虽然实际上并没有什么影响（只是多了一行字而已（没有那样的强迫症）），所以做不做这个还是可以观望一下。

### 可能有用的信息

npm 下除非手动将包同时写入 dep 和 devDep，否则一个包无法共存于 dep 和 devDep，同时 devDep 的优先级比 dep 要高。

#### 情景1

```shell
npm i kleur    // 包被安装在 dep 中
npm i -D kleur // 包被从 dep 中移除，并添加到 devDep 中
npm i kleur    // 包仍在 devDep 中，必须 uninstall 后重新 i 才能让他回到 dep
```

#### 情景 2

在 `npm init -y` 后手动在 `package.json` 中添加如下内容：

```json
  "dependencies": {
    "kleur": "4.0.0"
  },
  "devDependencies": {
    "kleur": "3.0.0"
  }
```

然后执行 `npm i`，结果如下：

![image](https://user-images.githubusercontent.com/29368226/170817156-061900af-a97f-4617-9dc0-5f819ef24a05.png)
![image](https://user-images.githubusercontent.com/29368226/170817176-3d5877a7-e9e3-4a3c-955c-d85e766d7ab1.png)

（npm 甚至不会装两个包）

同时，被安装的包版本是 `3.0.0`。如果将 package.json 中的版本调换，则会安装 `4.0.0` 版本的包。

### 其他

除了 devDep 以外还有 optDep 和 peerDep，但是问题在于真的有人在搓机器人的时候会把插件作为 peerDep 或者 optDep 吗（

**Comment by shigma** [comment]
> 但是问题在于真的有人在搓机器人的时候会把插件作为 peerDep 或者 optDep 吗

但是问题在于真的有人在搓机器人的时候会把插件作为 devDep 吗？你为啥不直接放到 dep 里呢？

**Comment by idlist** [comment]
> > 但是问题在于真的有人在搓机器人的时候会把插件作为 peerDep 或者 optDep 吗
> 
> 但是问题在于真的有人在搓机器人的时候会把插件作为 devDep 吗？你为啥不直接放到 dep 里呢？

一种分类，我把 koishi 和所有 koishi 插件都塞进devdep了 🤔

**Comment by idlist** [comment]
另外顺手搜了一下，也的确有 `npm i --production` 这种在生产环境下只安装 dep 而不安装 devdep 的指令（只是我没用过），所以还是看 shigma 觉得怎么做。

粗略的话可以有这么几种：

1. wontfix
2. 将 devdep 也列入检测范围，但给出与现在不同的提示（如“这个插件被安装在开发环境依赖中，在生产环境中可能会导致意想不到的情况“之类的）
3. 将 devdep 与 dep 视作同义，不报提示

**Comment by shigma** [comment]
> 我把 koishi 和所有 koishi 插件都塞进 devDep 了。

那这是错误的，除非你的项目不需要 koishi 就能运行。

> 我觉得做这个更好。

你没有考虑到连带问题。如果要检测 devDep 就比如在「依赖管理」中显示一个插件是 dep 还是 devDep。那么占用额外一列的空间，能给大部分人额外的好处吗？

**Comment by idlist** [comment]
> 那这是错误的，除非你的项目不需要 koishi 就能运行。

我不觉得这是错误的。我的项目这么做能够运行，而且有两个事实是：

1. 我部署的时候不使用 `--production` flag，这能保证 devdep 在生产中也能被安装。
2. 我的生产环境使用 js 启动，而且不启用 manager，实际上这个提示从源头就不存在了。

我认为这只能算作“不是最佳实践”，只有你在下个版本中修改行为让不被列入 dep 和 workspace 的插件直接没法运行，才能被称作是“错误的”。

**Comment by shigma** [comment]
如果谁都以能运行作为标准，那也不需要包管理器存在了。包管理器就是在大家都能遵守游戏规则的前提下，让发布者和使用者的负担都降低到最小的解决方案。部署的时候你可以不 --prod，但是如果不 --prod 就无法部署，这就是错误的。你的做法只是想方设法绕过了你的错误而已。绕过错误的方式有千万种，难道它们能证明错误本身不存在吗？

**Comment by idlist** [comment]
> 让发布者和使用者的负担都降低到最小

首先我不“发布”我的机器人，也没有其他人会使用我的机器人，如果将发布机器人定义为“其他人能直接部署机器人”的话，那我一直都没有这么做，而且以后大概也不会这么做。既然发布者和使用者**对于我而言从头到尾就不存在**，那么建立在这上面的正误论本身就 **没有意义**。

当然这些都是我的做法，所以我一直在说你觉得不做更好的话就不做。我只是提出来我觉得的一些细节处理，而且也只是我觉得而已。

**Comment by shigma** [comment]
我在意的其实不是做的成本怎么样，我主要是觉得做了会损害大部分人的利益。我相信绝大部分正常使用 Node.js 和他的包管理器的人、以及根本不懂如何使用 Node.js 和他的包管理器的人，都不会做出把生产依赖放入 devDep 的行为。因而如此做法必然会占用大片影响他们的判断。

> 既然发布者和使用者对于我而言从头到尾就不存在，那么建立在这上面的正误论本身就没有意义。

有意义的，一个人的做法不是孤立存在的。作为开源软件开发者，你的每个公开行为都能够让别人看到并影响他们的决策。错误的做法即便不产生恶劣的影响也是能够判断的，因为一旦这种做法被复制和演化，结成的恶果就不是始作俑者所能预测的了。

开源软件最大的意义不是它创造的直接价值：开源这件事本身就是最大的意义。Koishi 是一个开源软件，它会接纳外界的反馈并改善自己。你可以选择不去提这个需求，但是你提了，就说明你有意识地向大家开放并推荐你的实践经历。看到这个 issue 的所有人都将是你的受众。现在你仍然认为上面的正误论没有意义吗？

**Comment by idlist** [comment]
那么这个 issue 的源头就是我觉得装进了 devDep 也算是一种装，不完全等价于提示文字上的“尚未安装”。

不过看现在的讨论我也觉得 issue 题中的“devDep 直接算入依赖”确实不妥（虽然这不会改变我实际的做法），如果要做可以考虑细化提示文字，当然也可以不做。不过这个 issue 就先关了，要做细化提示文字就另外开新 issue 吧。
