### ISSUE TITLE
Feature: `manager` 更加细化的“未列入依赖”提示

### ISSUE THREAD

**Issue by idlist** [koishijs/koishi#706]
### Describe the problem related to the feature request

前情提要 #701

思来想去还是觉得这个语义上的不全等还是有点难受。

不过相对而言属于优先级非常低的内容就是了，毕竟相当的 edge case。

### Describe the solution you'd like

![image](https://user-images.githubusercontent.com/29368226/170836927-a19599f5-d343-4647-ab4d-d8c3fe2def6c.png)

就还是这张图，在插件被装入除了 dep 以外的 dep fields 中时提示比如“插件已安装，但未被列入生产依赖，可能会在部署时造成不符合预期的行为，点击此处添加至依赖”。

### Describe alternatives you've considered

摸了

### Additional context

摸了

**Comment by shigma** [comment]
额，dependency 的翻译就是「依赖」而不是「生产依赖」。如果写英文的话也只能是 dependencies 这个词吧？

**Comment by idlist** [comment]
> 额，dependency 的翻译就是「依赖」而不是「生产依赖」。如果写英文的话也只能是 dependencies 这个词吧？

这不是重点，重点是提示“你装了但装的位置不对”，现在这个句子我觉得体现不出来，你看我的第一反应就是“我装了但控制台说我没装”。

然后由此而来我觉得可以另外request一个manager的disable warnings配置项（或者已经有了但我不知道🤔）

**Comment by shigma** [comment]
事实上，你装进 devDep 也确实是「尚未列入依赖」啊 🤣 

disable warnings 未来可能会做，但是可能不通过统一的配置项，而是每一种 warning 独立配置；并且这部分属于前端逻辑，可能不写在后端，通过 localStorage 存储。

**Comment by idlist** [comment]
> 事实上，你装进 devDep 也确实是「尚未列入依赖」啊

我就是在说现在的说明文字没法让我意识到这一点🤔

**Comment by simon300000** [comment]
> > 事实上，你装进 devDep 也确实是「尚未列入依赖」啊
> 
> 我就是在说现在的说明文字没法让我意识到这一点🤔

👀这算是node生态吧

**Comment by shigma** [comment]
能够正常使用 node 的人不会犯下把依赖安装进 devDeps 的错误；不熟悉 node 的人使用脚手架，也不会有安装进 devDeps 的机会。给这个提示实际上几乎不会有任何人能够看到。

**Comment by idlist** [comment]
> > > 事实上，你装进 devDep 也确实是「尚未列入依赖」啊
> > 
> > 
> > 我就是在说现在的说明文字没法让我意识到这一点🤔
> 
> 👀这算是node生态吧

和生态其实关系不大，更多的是“发布的形式”。

写插件就不会有这种“可以错着来”的情况，因为必定是走 npm 发布，别人 npm i 的时候 npm 也只会安装 dep 而不会安装 devDep。

但机器人不一样，发布机器人大多是 git clone（除了某些真的很大型的机器人集群）然后 npm i，这才有这种操作的空间。

**Comment by idlist** [comment]
> 能够正常使用 node 的人不会犯下把依赖安装进 devDeps 的错误

> 毕竟相当的 edge case

你的面前就有那么一个不正常使用 node 的人。

**Comment by shigma** [comment]
如果你算一个的话，那我还能举出十万甚至九万中不正常使用 node 的方式，难道我需要把每一种错误用法都写进 manager 吗？

**Comment by idlist** [comment]
算了，我不想汴京了，你汴赢了，我累了。

你直接说不做都比这么汴来汴去来得直接。
