### ISSUE TITLE
Bug: `yarn setup` 创建插件时名字带 `koishi-plugin` 将会导致插件无法加载

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi#709]
### Steps to reproduce

`yarn setup koishi-plugin-demo`

`yarn dev`

### Expected behavior

采用以下方案之一：

1. 修复此问题

2. `yarn setup` 拒绝用户创建 `koishi-plugin` 开头的插件

3. 在 2 的基础上，在文档标明此处不能创建 `koishi-plugin` 开头的插件

### Versions

```
# uname -a
Linux VM-4-12-ubuntu 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
# node -v
v18.1.0
# yarn koishi -v
yarn run v1.22.18
$ koishi -v
koishi/4.7.2 linux-x64 node-v18.1.0
```

**Comment by shigma** [comment]
导致此问题的原因是什么，你知道吗

**Comment by ilharp** [comment]
我可能知道  也可能不知道

但对于看着文档入门的新人来说他肯定是不知道的

---

好吧实话实说我不知道

**Comment by MaikoTan** [comment]
> 好吧实话实说我不知道
> 

Although I distribute a PR, but seems the problem is not exist at the first?
Have you open console and enable the plugin you just created?

**Comment by ilharp** [comment]
> > 好吧实话实说我不知道
> 
> Although I distributed a PR, it seems the problem you mentioned is not exist at the first? Have you opened console and enable the plugin you just created?

Manager 完全无法感知到这个插件的存在，重新用短名称创建之后才出现

**Comment by MaikoTan** [comment]
> Manager 完全无法感知到这个插件的存在，重新用短名称创建之后才出现

Okay, then I think my PR should solve the problem.
Can you test #710 on your side?
