### ISSUE TITLE
Bug: QQ频道接收非附件类消息报错

### ISSUE THREAD

**Issue by fatevase** [koishijs/koishi#716]
### Describe the bug

接收到不包含附件的信息会报错

### Steps to reproduce

qq频道 @机器人 发送非附件类信息，机器人接收到后后台`msg.attachments.filter `报错。

### Expected behavior

原版在`plugin-adapter-qqguild` lib/index.js 中 第129行
```
session.content = msg.attachments.filter(({ contentType }) => contentType.startsWith("image")).reduce((content, attachment) => content + import_koishi2.segment.image(attachment.url), session.content);
```
由于发送不包含附件内容的信息，获取到的`msg`中不包含`attachment`，要做下判空。
```
 if(msg.attachment){
      session.content = msg.attachments.filter(({ contentType }) => contentType.startsWith("image")).reduce((content, attachment) => content + import_koishi2.segment.image(attachment.url), session.content);
    }
```

### Versions

- OS: Ubuntu 22.04
- Platform: QQGuild
- Node version: 16.13.1
- Koishi version: 4.7.3

**Comment by fatevase** [comment]
> 说句实话，这位仁兄，既然您都把问题找出来了，为什么不干脆直接提个PR来修……

* 不太确定这么直接加判断好不好，虽然自己是改了就能正常接收信息了。
* QQ频道还有一些其他的小问题，比如隔段时间bot会掉线并且不能重连或是每次登录bot会弹两次登录提示等，还是等正经的维护人员来统一处理比较好。

**Comment by fatevase** [comment]
> 说句实话，这位仁兄，既然您都把问题找出来了，为什么不干脆直接提个PR来修……

@ConstasJ 
不太确定这么直接加判断好不好，虽然自己是改了就能正常接收信息了。
QQ频道还有一些其他的小问题，比如隔段时间bot会掉线并且不能重连或是每次登录bot会弹两次登录提示等，还是等正经的维护人员来统一处理比较好。

**Comment by TimeBather** [comment]
> > 说句实话，这位仁兄，既然您都把问题找出来了，为什么不干脆直接提个PR来修……
> 
> @ConstasJ 不太确定这么直接加判断好不好，虽然自己是改了就能正常接收信息了。 QQ频道还有一些其他的小问题，比如隔段时间bot会掉线并且不能重连或是每次登录bot会弹两次登录提示等，还是等正经的维护人员来统一处理比较好。

掉线不重连问题我已经反馈给开发者了,你试试升级一下版本,我记得他解决了这个问题,不晓得发版咩有

**Comment by fatevase** [comment]
> 掉线不重连问题我已经反馈给开发者了,你试试升级一下版本,我记得他解决了这个问题,不晓得发版咩有

@TimeBather 
4.7.4 还有这个问题，不知道你有没有还遇到这种问题

**Comment by TimeBather** [comment]
> > 掉线不重连问题我已经反馈给开发者了,你试试升级一下版本,我记得他解决了这个问题,不晓得发版咩有
> 
> @TimeBather 
> 4.7.4 还有这个问题，不知道你有没有还遇到这种问题

我是用的自己写的Guild Adapter实现，并使用的官方SDK，没有使用文档中的实现，所以没有出现这个问题。

**Comment by NWYLZW** [comment]
有点无语，官方给的 itf 不标准，字段都不标明哪些是可能 undefiend 的。
我修一下

**Comment by NWYLZW** [comment]
> > 说句实话，这位仁兄，既然您都把问题找出来了，为什么不干脆直接提个PR来修……
> 
> @ConstasJ 不太确定这么直接加判断好不好，虽然自己是改了就能正常接收信息了。 QQ频道还有一些其他的小问题，比如隔段时间bot会掉线并且不能重连或是每次登录bot会弹两次登录提示等，还是等正经的维护人员来统一处理比较好。

重连晚点修一下，得我的 sdk 更新一下
俩次登录提示我先修了

**Comment by NWYLZW** [comment]
对了，duplicate
