### ISSUE TITLE
Feature: 插件配置和插件市场的优化

### ISSUE THREAD

**Issue by takaqiao** [koishijs/koishi#720]
### Describe the problem related to the feature request

因为装multiple插件/安装 调试的时候 真的很裂开

### Describe the solution you'd like

插件配置这里 新增插件最好能加一个过滤掉已安装插件的选项 新增插件最好放在不会变化的地方（所以不用每次去按分组——新增插件），已安装未安装（但是已添加）的插件最好能分开，添加进去的插件最好能够进行一定程度的排序（如A-Z,添加时间,更新时间blabla）,添加的插件最好加一个小分类（例如市场那样的 adapter和adapter放一块）
然后插件市场最好也能附带一个一键卸载，现在如果插件比较冗余的情况下把插件挪走有点点累（如果后面有几百个几千个插件wok直接累垮）

### Describe alternatives you've considered

要不干脆市场和插件管理直接合并？我不寄丢 

### Additional context

没有了
头子牛逼

**Comment by shigma** [comment]
你提出了多个本质不同的需求。

> 插件配置这里 新增插件最好能加一个过滤掉已安装插件的选项

我们有的插件允许被加载多次，因此这个做法是不合理的。不过未来我们可能会优化这个选择，例如可以加入搜索或者已加载提示。

> 新增插件最好放在不会变化的地方（所以不用每次去按分组——新增插件）

感谢你的提议，我们会考虑的。

> 已安装未安装（但是已添加）的插件最好能分开，添加进去的插件最好能够进行一定程度的排序（如 A-Z,添加时间,更新时间blabla）

插件的分组和排序是具有意义的，用户可以自行拖动。

> 添加的插件最好加一个小分类（例如市场那样的 adapter和adapter放一块）

可以使用插件组功能，创建新的 adapter 分组并将你的插件拖进去。

> 然后插件市场最好也能附带一个一键卸载，现在如果插件比较冗余的情况下把插件挪走有点点累

在最新版本（474）中插件列表右侧有一点垃圾桶按钮，你可以点击卸载。

**Comment by takaqiao** [comment]
好的哥
