### ISSUE TITLE
Feature: Schema的Union多类型支持

### ISSUE THREAD

**Issue by TimeBather** [koishijs/koishi#728]
### Describe the problem related to the feature request

由于我的插件使用了registry来支持其他插件对此插件进行扩展,因此需要在配置文件中指定使用自定义算法,所以使用了Schema.union()在给用户提供选择的同时支持输入自定义算法名称.但Koishi的Schema并没有支持union中包含多个非const类型的Schema的可视化编辑

### Describe the solution you'd like

增加一个complexUnion类型(我的修复文件中的complexSelect),然后在类型前加一个选择框进行选择
对const和其他类型复合的情况,const类型选中则不显示后方的类型

### Additional context

简单修复:
https://gist.github.com/TimeBather/f3d49acacc0a9661acc11ae1d2234550
L58-L78
L188-L193
L225-L227
L283-L285

**Comment by TimeBather** [comment]
这个需求(指背景)似乎有更好的替代解决方法,不过这个问题确实存在

**Comment by shigma** [comment]
你说的需求确实存在，不过这个修复还有一些没有考虑的地方，比如 union 还可以是 object 或者其他高级类型。

**Comment by TimeBather** [comment]
我在上文已经标注了“简单修复”，所以并没有对任何情况进行考虑，这也是我为什么没有PR的原因之一

**Comment by shigma** [comment]
Fixed by 5842477f4274e7a7fd65e6d01c1da949dbbbf36c and 59ce98ec5386db5ab7240af4de0b2dcccf43d49d.
