### ISSUE TITLE
Bug: yarn setup name 包含非法字符，校正后依旧报错

### ISSUE THREAD

**Issue by Mahoo12138** [koishijs/koishi#729]
### Describe the bug

当你尝试新建一个名字形如：`plugin#` 的插件时：
```bash
$ yarn setup plugin#
error koishi-plugin-plugin#@1.0.0: Name contains illegal characters
```
你观察到错误，尝试进行校正：
```bash
$ yarn setup pluginOK 
error koishi-plugin-plugin#@1.0.0: Name contains illegal characters
```
还是会报错显示之前的非法插件名

### Steps to reproduce

As shown above 👆

### Expected behavior

Apparently

### Versions

- OS: Ubuntu 20.04 based Android
- Platform: onebot
- Node version: 16.14.0
- Koishi version: 4.7.4

**Comment by shigma** [comment]
新版本已修复此问题。过去创建的目录麻烦手动删除。
