### ISSUE TITLE
Bug: manager 无法修改全局配置

### ISSUE THREAD

**Issue by Anillc** [koishijs/koishi#734]
### Describe the bug

修改全局配置不会生效，点击应用配置后又会回到之前的配置

### Steps to reproduce

使用 yarn create koishi 和官仓均能复现该问题

### Expected behavior

正确地修改配置

### Versions

- OS: NixOS
- Node version: 16.15.0
- Koishi version: 4.7.5 / 16ae7a0dca3defae74754000e430e5b2b500dcdb

**Comment by samnyan** [comment]
https://github.com/koishijs/koishi/blob/bc3b50479e95951e2295664752293e218ef53971/plugins/frontend/manager/client/settings/global.vue#L5

这里传入的`current.config`是initial state，所以保存的值不会更新。
应该传入`config`
