### ISSUE TITLE
Bug: 控制台添加机器人，选择有多个protocol的adapter会报错无法显示设置表单

### ISSUE THREAD

**Issue by samnyan** [koishijs/koishi#738]
### Describe the bug

在控制台添加机器人的页面，选择任意一个有多个protocol的adapter（也就是除了discord和qqguild），都会报错
```
vue.js:1 TypeError: Cannot read properties of undefined (reading 'type')
```
导致页面表单无法显示，无法添加机器人

### Steps to reproduce

在机器人页面添加机器人，并且选择一个有多个protocol选项的adapter（如onebot）

### Expected behavior

应显示对应adapter的配置表单

### Versions

- OS: Windows 11
- Platform: any
- Node version: 16.15.0
- Koishi version: 4.7.6

### Additional context

https://github.com/koishijs/koishi/blob/b4d678c05b3db77f499b42568bdc3de09baea9b8/plugins/frontend/client/client/components/form/schema.vue#L171-L181
这里的174行的 `active.value` ，正常应该是一个object。
加了断点之后，这里选择adapter之后发生了两次调用，第一次调用的时候 `active.value` 是正常的object，第二次调用是数字 0，导致访问它的 `.meta.description` 直接报错。

**Comment by shigma** [comment]
Fixed by 91aad42eca1c15aff4224b05d478d77a35a2f298.
