### ISSUE TITLE
Bug: teach plugin not working with sqlite

### ISSUE THREAD

**Issue by LR146** [koishijs/koishi#740]
### Describe the bug

使用插件teach插件加入了新的问答
可是输入指定的询问，机器人并不会有任何反应，

### Steps to reproduce

在沙盒或者私聊机器人或者在群内输入指令如下
teach foo bar
机器人会回复我，已加入问答列表
输入#4时 也会出现问答列表

可当输入foo时
机器人不做任何反应，已在沙盒qq私聊群聊测试
都没有任何反应

### Expected behavior

尽快修复该问题

### Screenshots

https://user-images.githubusercontent.com/95366265/176924207-488b17c9-0fc1-4abc-944b-aa1de9ab9934.mp4

https://user-images.githubusercontent.com/95366265/176924207-488b17c9-0fc1-4abc-944b-aa1de9ab9934.mp4

Uploading QQ录屏20220701232550.mp4…

Uploading QQ录屏20220701232550.mp4…

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version: 
插件名为：teach
当前版本为：3.2.0

**Comment by shigma** [comment]
疑似 sqlite 数据库的问题，现已修复：

- 如果你的版本号 <4.8.0：手动安装 @minatojs/driver-sqlite@1.2.2，或更新到 4.8.0 以上的版本并采取下一条
- 如果你的版本号 >=4.8.0：将 @koishijs/plugin-database-sqlite 更新到 1.4.2 以上版本（可以在控制台完成）
