### ISSUE TITLE
会话选择器支持选择所有私聊会话 / 所有群组会话

### ISSUE THREAD

**Issue by cigui** [koishijs/koishi#751]
### Describe the problem related to the feature request

我希望限制自己的插件只处理所有私聊信息，但不限制为特定的用户。从现在的 koishi 文档看起来，我可能需要使用 `ctx.intersect` 方法进行条件选择，但我不确定这里的条件需要怎么写（或者我觉得如果能提供类似于 `ctx.allPrivate()` / `ctx.allGuild()` 之类的属性选择器会更方便？）

### Describe the solution you'd like

新增属性选择器
- `ctx.allPrivate()` 用于选择所有来自私聊消息的会话
- `ctx.allGuild()` 用于选择所有来自群组的会话

### Describe alternatives you've considered

我目前是在 onebot 下写插件，粗略看了一下 adapter 代码里会通过 `session.subtype` 区分群组 / 私聊消息，试了一下也是可以用 `session.subtype === 'private'` 进行过滤的，但这个 `subtype` 在 koishi 文档里并没有被提及，我不确定这种做法是不是 ok 的。

**Comment by MaikoTan** [comment]
你可能需要的是 `ctx.guild()` 和 `ctx.private()` (｡･ω･｡)ﾉ♡

**Comment by cigui** [comment]
> 你可能需要的是 `ctx.guild()` 和 `ctx.private()` (｡･ω･｡)ﾉ♡

cool，确实是这样的！

不过看文档示例我还以为 guild 必须传入群组 id 来过滤，另外文档里好像也没提及有 private 方法可以用，是不是可以更新一下文档

**Comment by MaikoTan** [comment]
> > 你可能需要的是 `ctx.guild()` 和 `ctx.private()` (｡･ω･｡)ﾉ♡
> 
> cool，确实是这样的！
> 
> 不过看文档示例我还以为 guild 必须传入群组 id 来过滤，另外文档里好像也没提及有 private 方法可以用，是不是可以更新一下文档
> 

确实最近版本更迭了不少东西，文档没有跟上更新。之后应该会有完善，总之以 TypeScript 类型提示为准。 (・–・;)ゞ
