### ISSUE TITLE
Bug: 指令限制功能里，指令处于冷却状态也会增加调用次数

### ISSUE THREAD

**Issue by emicoto** [koishijs/koishi#752]
### Describe the bug

在指令限制功能启用时，
被用户所调用的指令进入冷却状态后，也会增加调用次数

### Steps to reproduce

[详细看截图](https://gyazo.com/79c4838c9d1c229f50ec72c5552aa4da)

### Expected behavior

希望冷却中不会增加调用的次数。
以及，那个调用过于频繁的自动回执，
如果能改为
“<指令名>调用过于频繁，请<冷却时间>后再试“
或许会更好懂些

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
感谢反馈！问题已修复。请更新 rate-limit 插件到 1.2.8 版本。
