### ISSUE TITLE
Feature: 为网站空缺位置设计了一个图片

### ISSUE THREAD

**Issue by pthmz** [koishijs/koishi#755]
### Describe the problem related to the feature request

网站图片空缺，我设计了一个，拿走吧 > <
![image](https://user-images.githubusercontent.com/97567575/179703669-b4eae0cc-26aa-414c-a5b7-17e4ef6b49af.png)
![未标题-1](https://user-images.githubusercontent.com/97567575/179703703-9e5329eb-4ae4-46a9-81b3-2d19fc6fe98e.png)

### Describe the solution you'd like

无

**Comment by shigma** [comment]
感谢你的贡献，不过我们已经做好了新版主页。
