### ISSUE TITLE
Bug: 某些条件下使用 new Logger() 创建的 logger 不会输出时间

### ISSUE THREAD

**Issue by memset0** [koishijs/koishi#766]
### Describe the bug

1) 使用 `new Logger('xxx')` 方法创建的 logger 不会显示时间
2) 使用 `ctx.logger('xxx')` 方法创建的 logger 会显示时间

### Steps to reproduce

用 `koishi.config.js` 作为入口启动（应该有影响）

```typescript
// ...
export const name = 'test'
export function apply(ctx: Context) {
  const loggerA = new Logger(name)
  const loggerB = ctx.logger(name)
  loggerA.info('testA')
  loggerB.info('testB')
}
```

### Expected behavior

不同方式创建的 logger 都能显示时间

### Versions

- OS: Windows 10
- Node version: 14.19.0
- Koishi version: 4.8.2

**Comment by ENDsoft233** [comment]
复现失败，loggerA 仍然显示时间。

**Comment by ENDsoft233** [comment]
> > 复现失败，loggerA 仍然显示时间。
> 
> 您有用 `koishi.config.js` 作为入口文件吗

抱歉，没关注到这里，没有使用此作为入口，您可以提供下您的入口文件吗？

**Comment by memset0** [comment]
> > > 复现失败，loggerA 仍然显示时间。
> > 
> > 
> > 您有用 `koishi.config.js` 作为入口文件吗
> 
> 抱歉，没关注到这里，没有使用此作为入口，您可以提供下您的入口文件吗？

稍后上传一下

**Comment by shigma** [comment]
所以这个 issue 有进展吗？

**Comment by memset0** [comment]
It now works as expected with the latest version, closed.
