### ISSUE TITLE
Feature: Disable web preview for telegram

### ISSUE THREAD

**Issue by memset0** [koishijs/koishi#767]
### Describe the problem related to the feature request

https://github.com/satorijs/satori/blob/ea0ab178e7c11cf006dc1f4e3b29d1a3aeec5477/adapters/telegram/src/sender.ts#L165-L172

1. 作为一个指令向机器人，发送的链接大部分时候并不需要生成预览。如果默认禁用的话，可以比较方便的使用 https://t.me/botname?start=xxx 之类的功能
2. 现阶段的 API 设计似乎没法同时兼容两种方法，就有点难受（x）

### Describe the solution you'd like

在表单中默认追加 `disable_web_page_preview: true`，或者 ↓

### Describe alternatives you've considered

或者通过别的方式设计接口来把这个选项给塞进去，但是 bot.internal 似乎已经被对应的 web API 填满了，也不知道该放哪里。

或者可以在 bot.internal 中发送请求前加一个 event 之类的可以亡羊补牢一下（x）

**Comment by undefined-moe** [comment]
`segment.link('https://', {text: 'desc', preview: false})`

**Comment by memset0** [comment]
> `segment.link('https://', {text: 'desc', preview: false})`

但这东西是对于整条消息的啊，感觉这样还是有点怪（x）

**Comment by undefined-moe** [comment]
但这确实是 link 含的属性（x

**Comment by memset0** [comment]
合理，您快去写（x）

**Comment by shigma** [comment]
目前并没有 link 这个 segment 吧……

我还挺喜欢 @undefined-moe 的这个设计的，不过可能确实有必要添加相应的发送设置。大致两个方向：

1. `bot.sendMessage()` 增加一个四参数表示额外的发送设置，我们提供一套标准的接口并允许扩展；同时 `session.send()` 也增加同样的二参数（一个典型的应用是回复信息可以直接用这个新参数来写而不是 `[CQ:quote]`）
2. `preview` 确实可以理解为 link 的特征，未来如果有对应的 segment 可以提供

**Comment by memset0** [comment]
选用 1.) 还可避免用 `[CQ:html]` 或 `[CQ:markdown]` 来表示对应类型消息的情况，~~所以什么时候提上日程呢~~

**Comment by undefined-moe** [comment]
个人观点：为何不适用方案一：

- 与 dialogue 不兼容。
- 与 return segments 快速回复不兼容。

额外发送设置更应当用于发送本身的选项：
- 消息是否分拆及分拆逻辑；
- 消息部分发送失败是否返回错误；

**Comment by undefined-moe** [comment]
对于一个跨平台框架，应当尽可能自行维护各组件的行为，避免平台实现不一致。

HTML 和 markdown 目前在平台间仍兼容性非常差，不应作为通用设计。

**Comment by shigma** [comment]
> 选用 1.) 还可避免用 `[CQ:html]` 或 `[CQ:markdown]` 来表示对应类型消息的情况，~所以什么时候提上日程呢~

未来版本中这俩大概本来就会没掉。

> 为何不适用方案一：

说 preview 不适合我能理解，这里的不适合包括 quote 吗？

> 与 return segments 快速回复不兼容。

那只要做了这个方案就会不兼容，我觉得在这个方案的同时仍然可以保留现有的头部 segment 设计（为了可能叫 meta element）。

**Comment by memset0** [comment]
其实我的想法是

* 参考 Onebot 12 标准提供类似 `[CQ:tg.html]` `[CQ:tg.markdown]` `[CQ:tg.disable_preview]` 的 segment 来用于表示启用对应的选项
* sendMessage 等方法提供四参数，并与 segment 中提供的选项合并

这样能做到向前兼容，也可以解决和 dialogue 的兼容问题

**Comment by undefined-moe** [comment]
```js
// Good example
[
  segment.h2('title'),
  segment.image('x.png'),
  'text'
]

// Bad example
segment.markdown(`
## title
![x.png](x.png)
text
`)

上述语法可以由 adapter 提供 h2 -> bold 的 fallback 方案
而使用下述语法，甚至连 telegram 都无法很好的处理，其他平台若要处理，需要引入 markdown 解析库（HTML同理），显然不是 **跨平台** 的首选解决方案。

**Comment by undefined-moe** [comment]
同时请注意：
1. OneBot 协议不是万能的
2. 官方不应推荐任何 platform-specific 的行为，应致力于 一套代码，全平台通用 而不是 提供各式各样的接口让用户自行选择

**Comment by shigma** [comment]
CQ 码很快就会全面停用了，OneBot 的做法与其说是增加表达能力，实际上是在不同平台之间建立壁垒。Koishi 未来的设计会更加考虑跨平台特性而不是平台独占特性。

- 如何发送 markdown？

```ts
// 引入 markdown 解析库（或许可以考虑内置）
import md from '@satorijs/markdown'

return md`
## title
![x.png](x.png)
text`
```

- 如何回复消息？

```ts
import { segment } from 'koishi'

return segment.meta('quote', { id: xxx }) + content
// or
session.send(content, { quote: { id: xxx } })
```

**Comment by memset0** [comment]
https://12.onebot.dev/interface/rules/

> OneBot 实现可以支持扩展的动作（action），称为扩展动作，扩展动作的名称建议包含前缀。扩展动作的请求和响应仍必须包含 [OneBot Connect - 动作请求](https://12.onebot.dev/connect/data-protocol/action-request/) 和 [OneBot Connect - 动作响应](https://12.onebot.dev/connect/data-protocol/action-response/) 中定义的所有字段，但具体的动作参数和动作响应数据字段可以任意命名。
> 
> 例子：
> 
> ```json
> {
>     "action": "qq.get_group_honor_info",
>     "params": {
>         "group_id": "123456"
>     }
> }
> ```

**Comment by undefined-moe** [comment]
我不建议在 core 中引入 markdown。我建议所有开发者均使用 segment 去构建文本段。markdown 语法几乎无法在此场景下进行扩展，无法处理特殊情况（上文preview），同时显著增加 core 体积。

**Comment by memset0** [comment]
个人想法是

* 如果开发者需要发送 markdown / html 类型的消息，应自行处理文本的解析和转义问题，并由 koishi 提供统一的 sendMessage 接口

* 如果开发者需要接受 markdown / html 类型的消息，那么样式表达由 segment 的 data 字段提供

**Comment by undefined-moe** [comment]
所有 markdown/html 都应由 adapter 在接收时拆解为基础消息段。
没有任何理由非得发送 markdown/html 消息。

**Comment by undefined-moe** [comment]
但我认为可以提供一个外置工具库去完成 Segment[] <-> markdown string 的转换。

**Comment by memset0** [comment]
> 所有 markdown/html 都应由 adapter 在接收时拆解为基础消息段。

把样式放到 data 字段不影响支持 -> 不支持的平台间 fallback，且在同平台转发 / 支持相同样式的平台间转发都能实现样式统一。

> 没有任何理由非得发送 markdown/html 消息。

您的某位可爱群友不就非得发送（x）

**Comment by undefined-moe** [comment]
我不认为 adapter 接收时转为 Segment[] 再发送 Segment[] 会导致任何样式不统一。
markdown/html 在不引入对应解析库之前是不可能进行任何 fallback 操作的。

**Comment by shigma** [comment]
@memset0 你没有意识到一个问题，markdown 在不同平台没有统一的实现。tg-favored markdown 和 discord-favored markdown 也是不一样的子集，并且也有各自的扩展。而且 discord 甚至没有 markdown 的概念，你正常发就是 markdown。

为了解决不统一的问题，唯一的解决方案就是先将 md 转化为 element，然后发送时再转换为平台语法的 md。在第二步转化中，我们可以根据平台特性适配语法，并对不支持的语法做 fallback。

**Comment by memset0** [comment]
可能是表达问题，我大概也是这个意思。。。

**Comment by shigma** [comment]
> 您的某位可爱群友不就非得发送（x）

当上面这套 API 成型后我们将不会提供 `[CQ:markdown]` 支持。所有的 markdown 消息都必须通过库 `@satorijs/markdown` 构建。（当然你仍然可以调用 Internal API，但这可能就不存在区别了，也不关我们的事情了。）

**Comment by memset0** [comment]
大概懂您意思了

**Comment by shigma** [comment]
> 所以什么时候提上日程呢

按照计划是 4.10 (±1)。

**Comment by undefined-moe** [comment]
翻译：3.10~5.10 会支持

**Comment by memset0** [comment]
听起来好大工作量，每个平台对于不严格标准的 markdown 的解析逻辑都不大一样（）

**Comment by memset0** [comment]
以及譬如 image 等二进制文件，可提供统一的转换到 Buffer / Base64 方法，用于开发者调用和跨平台的 adapter 适配。

现在对于这类二进制文件的处理方面，koishi 的使用体验就比较差，如想发送一张图片：

1. 到 Telegram 需要先转换成 base64，再由 adapter 上传文件
2. 但到 KOOK，如果转换成 base64 就会因消息段过大而 400，反而直接上传第三方图片外链会有官方服务器会帮你转储（虽然官方推荐的方法是调用 asset 接口上传）

如果是 Telegram 上的 video stickers 和 GIF，直接用先有代码甚至都无法发送。

希望早日咕完（x）

**Comment by undefined-moe** [comment]
至少对于目前设计来说 kook出400 是adapter的问题，得修。

**Comment by memset0** [comment]
这个确实，kook 的 adapter 似乎都没写上传静态文件的方法（？）

**Comment by MaikoTan** [comment]
Things has been changed, now koishi allow you to have a custom message element, which makes this feature implemetable.

**Comment by MaikoTan** [comment]
> 目前 `bot.sendMessage` 函数已经有 `options` 参数了，可以在这上面添加此选项。

While in the retrospect of this issue, I think this feature should be worth to be a adapter option for telegram. Which means we should change the code in telegram adapter instead of other regular plugins side. What do you think?

**Comment by MaikoTan** [comment]
Exactly!
That is what I mean.

**Comment by shigma** [comment]
So what should the option be called? `disableWebPreview`?

**Comment by Anillc** [comment]
how about just `preview`

**Comment by shigma** [comment]
We may also need to do some investigations on the Discord side before we get to work on this.

cc @XxLittleCxX Is there a similar way to disable previews for links for Discord?

**Comment by XxLittleCxX** [comment]
> We may also need to do some investigations on the Discord side before we get to work on this.
> 
> cc @XxLittleCxX Is there a similar way to disable previews for links for Discord?

you may try `<>` (e.g. `segment.escape('<https://koishi.chat>')`)

**Comment by Anillc** [comment]
Should we add `<>` for `a` element when preview is enabled in discord adapter?

**Comment by MaikoTan** [comment]
It looks like that Discord doesn't support `a` element. So links could be only sent as a plain URL. So I think it is better to wrap the URL in `<>` to disable the preview.

**Comment by Anillc** [comment]
I mean the `a` element of koishi, not the discord's.

Discord doesn't even support links like `[]()`.

https://github.com/satorijs/satori/blob/050ec4de73b0e957251dda2701f43db80d2dbd32/adapters/discord/src/message.ts#L122
