### ISSUE TITLE
Bug: orm的 $.eq 等方法不支持 Date 类型

### ISSUE THREAD

**Issue by nmMmnmMmn** [koishijs/koishi#771]
### Describe the bug

orm的 $.eq 等方法不支持 Date 类型

### Steps to reproduce

```ts
import { $ } from 'koishi'

declare module 'koishi' {
  interface User {
    createdAt: Date
    updatedAt: Date
  }
}

ctx.database.get('user', row => $.eq(row.createdAt, row.updatedAt))
```

### Expected behavior

支持比较 Date

### Screenshots

![image](https://user-images.githubusercontent.com/21982381/182053472-9907aa3e-0bc5-4a81-9d8a-24490bba1971.png)

### Versions

- Koishi version: 4.7.6

**Comment by shigma** [comment]
fixed by shigma/minato@44f59964b206791d013212179915c8d8332a97f9
