### ISSUE TITLE
Feature: 沙盒需要个一键清除LOG功能

### ISSUE THREAD

**Issue by emicoto** [koishijs/koishi#774]
### Describe the problem related to the feature request

沙盒的信息多了十分卡，并且有奇怪的BUG无法看到最新信息。
希望能有个一键清除LOG的功能。

### Describe the solution you'd like

在沙盒的界面加个清除LOG的按钮？

**Comment by shigma** [comment]
好像直接在左侧叉掉当前用户可以解决。不过仅限私聊，群聊还是需要统一的清空方案。

**Comment by shigma** [comment]
我们增加了一个 clear 指令，在沙盒中输入可以清空当前页面聊天记录。
