### ISSUE TITLE
Feature: 新增获取及删除群公告

### ISSUE THREAD

**Issue by RainChain-Zero** [koishijs/koishi#776]
### Describe the problem related to the feature request

在多群协同管理的情况下，经常需要通过机器人在几个群同时发送公告，但在后续删除中就存在不少麻烦，所以想请问一下是否可以添加获取和删除群公告的功能呢？

### Describe the solution you'd like

去go-cqhttp处查找了一番，它文档中并未提及删除群公告的api，但在[该issue](https://github.com/Mrs4s/go-cqhttp/issues/1564)中提及并已经完成 ~~(大概)~~，或许可以对其进行实现。

**Comment by shigma** [comment]
go-cqhttp 那里疑似没有合并到 master 分支？

**Comment by shigma** [comment]
无论如何我发了个版本，支持了新的 API：

```ts
// Session API
session.onebot.getGroupNotice()
session.onebot.delGroupNotice()

// Bot API
bot.internal.getGroupNotice()
bot.internal.delGroupNotice()
```

**Comment by RainChain-Zero** [comment]
> 无论如何我发了个版本，支持了新的 API：
> 
> ```ts
> // Session API
> session.onebot.getGroupNotice()
> session.onebot.delGroupNotice()
> 
> // Bot API
> bot.internal.getGroupNotice()
> bot.internal.delGroupNotice()
> ```

非常感谢您，但在测试时发现无法通过`getGroupNotice()`获取notice_id，而这正是`delGroupNotice()`的第二个参数。

**Comment by shigma** [comment]
能提供一下 get 获得的数据嘛？

**Comment by RainChain-Zero** [comment]
好的，get获得的数据是这样子的
```json
[
    {
        "sender_id": "这是qq，number",
        "publish_time": 1660386344,
        "message": {
            "text": "测试",
            "images": []
        }
    },
    {
        "sender_id": "这是qq，number",
        "publish_time": 1660384814,
        "message": {
            "text": "no",
            "images": []
        }
    },
    {
        "sender_id": "这是qq，number",
        "publish_time": 1660384576,
        "message": {
            "text": "yes",
            "images": []
        }
    }
]
```

**Comment by shigma** [comment]
我这里就是原样传回数据的，应该是 go-cqhttp 就没有发送 notice_id，具体原因未知（MiraiGo 实现了这个属性，但似乎确实没有值）。要不要试试直接请求 go-cqhttp（结果应该跟你上面发的一样）然后去 MiraiGo 提 issue？

**Comment by RainChain-Zero** [comment]
的确依旧如此，麻烦您了，我去冲另一边(
