### ISSUE TITLE
Bug: 无法获取telegram端用户头像

### ISSUE THREAD

**Issue by rhyryy** [koishijs/koishi#778]
### Describe the bug

telegram用户对象中的avatar字段始终为undefined

### Steps to reproduce

export function apply(ctx: Context) {
  ctx.middleware(async (session, next) => {
      //.......
      session.author.avatar //undefined
      const userInfo = await session.bot.getUser(session.userId)
      userInfo.avatar //undefined
      //........
    }
  )

### Expected behavior

avatar属性应为用户头像的url或者base64

### Versions

- OS: linux
- Platform: telegram
- Node version: 16.15.0
- Koishi version: 4.8.5

**Comment by shigma** [comment]
tg 并没有实现 getUser 方法吧？

**Comment by rhyryy** [comment]
> tg 并没有实现 getUser 方法吧？

getUser似乎返回的是telegram api的User对象,包含id,is_bot之类的信息,确实不包含avatar,但是telegram是可以获取用户头像的  
telegram bot api [getUserProfilePhotos](https://core.telegram.org/bots/api#getuserprofilephotos)可以通过user_id返回  userprofilephotos对象,该对象的photos的第一项理应就是对应用户头像的信息,包含头像的file_id等  
然后getFile就可以获取到头像的file_path  
是否能添加相关的方法使得avatar不再为undefined

**Comment by shigma** [comment]
是的，satorijs/satori#20 已经实现了这一点。

但是 telegram 确实没有实现 getUser 啊……你为啥能使用？你用的是 getSelf 吗？

**Comment by rhyryy** [comment]
> 是的，[satorijs/satori#20](https://github.com/satorijs/satori/pull/20) 已经实现了这一点。之后会发布更新。
> 
> 但是 telegram 确实没有实现 getUser 啊……你为啥能使用？你用的是 getSelf 吗？

抱歉,刚刚测试了一下,确实没有实现getUser,之前尝试获取avatar的时候测试了多种方法,写issue的时候记混了,大概是使用的getSelf

**Comment by shigma** [comment]
ok，那 getSelf() 下个版本就能支持 avatar 了

**Comment by rhyryy** [comment]
> ok，那 getSelf() 下个版本就能支持 avatar 了

谢谢您

**Comment by shigma** [comment]
新版本已发布。

**Comment by rhyryy** [comment]
> ok，那 getSelf() 下个版本就能支持 avatar 了

是否能支持session.author.avatar

**Comment by shigma** [comment]
这个目前没有做，建议手动获取。主要是考虑到如果对收到的每条消息都做这样一个请求的话，会降低性能，对不需要此属性的用户带来负面的影响。
