### ISSUE TITLE
Feature: once(ctx, name) => Promise

### ISSUE THREAD

**Issue by simon300000** [koishijs/koishi#779]
### Describe the problem related to the feature request

https://nodejs.org/api/events.html#eventsonceemitter-name-options
这个 once 有时有用，但是由于 koishi 的 ctx 不是 NodeEventTarget 所以在特定环境会导致类型检查报错

### Describe the solution you'd like

node 自带的 events.once 应该兼容 cordis，应该可以直接给 events.once 第一个参数增加一个 type 重载

**Comment by shigma** [comment]
为什么会有报错……cordis 的事件本来就不兼容 Node，返回值都不一样的啊。

文档：https://github.com/shigma/cordis#listen-to-events

**Comment by simon300000** [comment]
报错是正常的，我的意思是新功能请求，这个once有时有用，我想koishi也可以有一个

**Comment by shigma** [comment]
我还是不太清楚你想要的是什么写法……node 那个 API 应该是与 node 耦合的，而 cordis 是不依赖 node 可以在浏览器运行的。

**Comment by simon300000** [comment]
其实有几种可能
第一个就是我上面提出的直接让node自带的once加上一个type，但是也有一些别的问题
node这个惊人的有一定兼容性 确实可以直接用
https://github.com/nodejs/node/blob/fddc701d3c0eb4520f2af570876cc987ae6b4ba2/lib/events.js#L984

第二个是让 ctx.once 没有 第二个参数 的时候返回一个promise 这个兼容性应该是最好的

第三个是在utils里面写一个once，就类似这种

```javascript
once = (ctx, name) => new Promise(resolve => ctx.once(name, (…args)=>resolve(args)))
```

**Comment by shigma** [comment]
我倾向于 2

**Comment by shigma** [comment]
感觉都有问题
1 对 node 有侵入性
2 与原有 once 类型不匹配
3 增加了不符合 AOP 风格的 API

**Comment by shigma** [comment]
cordis 事件系统与 node 最大的区别在于，它强调所有东西都是 disposable 的，而这个 API 显然不满足这一点。我认为引入这个 API 会对系统安全性造成负面的影响。建议还是不要追求这个语法糖，直接写 `ctx.once()` 比较好。

**Comment by simon300000** [comment]
有道理哎
