### ISSUE TITLE
Feature: bypass limits

### ISSUE THREAD

**Issue by Dragon-Fish** [koishijs/koishi#781]
### Describe the problem related to the feature request

部分群聊设置了 `!switch switch` 或者 `!switch user`，导致 bot 管理员进行维护工作非常麻烦

### Describe the solution you'd like

为 `rate-limit` 和 `switch` 增加一个 `bypassAuthorization` 配置项（或者其他名字whatever），允许高于一定权限的用户可以不受限制使用所有指令

**Comment by shigma** [comment]
rate-limit 可以做。

switch 本来的用途就是阻止插件/指令生效，所以无法 bypass。如果你想只让特定权限的用户访问，可以直接给指令上 authority，而不是 switch。

**Comment by Dragon-Fish** [comment]
同一个指令可以在不同上下文采用不同的 authority 吗

**Comment by shigma** [comment]
也没有办法……这种复杂的需求建议特判，本身就没有多少普适性。
