### ISSUE TITLE
Bug: No matching export in "node_modules/cordis/lib/index.mjs" for import "Disposable"

### ISSUE THREAD

**Issue by maxoyed** [koishijs/koishi#782]
### Describe the bug

按照官网创建模板项指引，创建项目后，使用 `yarn start` 可以成功运行，但是通过 `yarn dev` 运行后，浏览器无法打开页面，且会报错

### Steps to reproduce

yarn create koishi

cd koishi-app

yarn dev

### Expected behavior

`yarn dev` 可以正常运行

### Screenshots

![QQ截图20220827060718](https://user-images.githubusercontent.com/25519245/186996868-cb55dfbf-6f14-46a5-9116-f4648c00d3f5.png)

### Versions

- OS: Window11
- Platform: 
- Node version: 16.14.2
- Koishi version: 4.8.6

**Comment by shigma** [comment]
已复现，感谢反馈，预计下版本修复。

**Comment by HuanLinMaster** [comment]
兄弟，一样问题，群里反馈了说修复，我刚刚init的现在还有这个问题

**Comment by maxoyed** [comment]
> 已复现，感谢反馈，预计下版本修复。

@HuanLinMaster
