### ISSUE TITLE
Safari compatibility with console plugin

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#784]
### Describe the bug

Safari不支持某一个正则表达式的写法
在debug console里是可以看到报错的。

### Steps to reproduce

打开console
只能看到Home界面

### Expected behavior

可以看到所有页面

### Screenshots

![Uploading 1CF77E9B-84E2-4EB1-9BFD-28273F84339A.png…]()

(我在safari好像也上传不来截图)

### Versions

- OS: iOS, macOS (Safari)
- Platform: -
- Node version: ^16.0.0
- Koishi version: ^4.8.0

**Comment by simon300000** [comment]
能带一个Safari版本号吗，在右上角Safari 关于 Safari

**Comment by arily** [comment]
macOS: Version 15.6.1 (17613.3.9.1.16)
iOS: 16.1 Public Beta

截图我等了5分钟左右。iOS safari的github我觉得可能也有bug，等下我提一个macOS的截图

**Comment by arily** [comment]
![image](https://user-images.githubusercontent.com/10007589/187837625-18b617aa-ad42-442b-a7b4-68300a4f670b.png)
macOS可以传，问题和iOS是一样的

**Comment by shigma** [comment]
Safari 不支持重要的正则表达式特性：https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#browser_compatibility

目前没有特别好的方法兼容，建议自行安装 Chrome 等浏览器。

**Comment by arily** [comment]
没有其他workaround吗？
iOS就算装了chrome 最后内核应该也还是webkit。
手头没电脑的话用不了console了。

console改版之前（4.7）的时候是兼容safari的。

**Comment by shigma** [comment]
我打算把 koishi 中的所有用到相关语法的正则表达式都替换掉，需要一到两个小版本。

**Comment by shigma** [comment]
Fixed by shigma/cosmokit@02299e9a7fa296e1efe81820e2eda2fdfe0ae63e, koishijs/koishi@da65568a3e1b8aac61b8f649322e6700d6c86aa0, koishijs/console@8ef875cddecfcd1b4f06953816046308a72154f1
