### ISSUE TITLE
Bug: 发送图片响应超时后 发送异常

### ISSUE THREAD

**Issue by huigetql** [koishijs/koishi#785]
### Describe the bug

![image](https://user-images.githubusercontent.com/66297001/187874830-75e44969-2898-41f9-b3b0-a9443c77169e.png)

发送图片响应超时后 报错  请问能怎么 自动重启（一报错机器人就垮了。。。。

然后隔一段时间过后那个消息竟然发出去了。。。。但是是这样的。。。

![image](https://user-images.githubusercontent.com/66297001/187875819-34dd1735-e60b-4117-a801-0aca03db9838.png)

### Steps to reproduce

似乎发送一个特别大的图片就会这样。。。

https://i.pixiv.re/img-original/img/2022/06/26/18/12/00/99318222_p0.jpg

### Expected behavior

1

### Screenshots

![image](https://user-images.githubusercontent.com/66297001/187875413-b91b0a81-ecd9-48b0-961c-b2dee85fa50f.png)

### Versions

- OS: MacOS x86
- Backend service: go-cqhttp v1.0.0-rc3 
- Node version: v15.11.0
- Koishi version: 3.14.2

**Comment by shigma** [comment]
感谢反馈！目前你可以通过配置 responseTimeout 解决此问题。

这个配置项默认为 5000（5 秒），你可以改成 60000（1 分钟）。鉴于你遇到的情况，我们后续也会考虑增加默认的等待时间。

**Comment by huigetql** [comment]
> 感谢反馈！目前你可以通过配置 responseTimeout 解决此问题。
> 
> 这个配置项默认为 5000（5 秒），你可以改成 60000（1 分钟）。鉴于你遇到的情况，我们后续也会考虑增加默认的等待时间。

![image](https://user-images.githubusercontent.com/66297001/187882766-e8a017ca-594b-4991-81e8-b67475e29b51.png)
像是这样吗。。。

**Comment by shigma** [comment]
你用的哪个版本的 koishi……

**Comment by huigetql** [comment]
> 你用的哪个版本的 koishi……

![image](https://user-images.githubusercontent.com/66297001/187914805-cda6cf36-2638-495f-867e-1345a160c0ae.png)
....3.14.2

**Comment by shigma** [comment]
抱歉没注意 🤣 

v3 应该是有这个配置项的，你可以直接加上这个配置试试，如果不行就没办法了。事到如今我们也不会继续维护 v3 了。
