### ISSUE TITLE
Feature: 为subcommand加入alias设置

### ISSUE THREAD

**Issue by Lipraty** [koishijs/koishi#786]
### Describe the problem related to the feature request

在编写插件时需要注册一个完整名字的sunbcommand。并在基础上提供简写形式以方便快速输入：
```TypeScript
ctx.command('cmd', ...).subcommand('.subcmd', 'cmddesc').alias('.c')
```
在Koishi 4.8.7下使用上述方法注册子命令后，在调用`cmd.subcmd -h`时会提示该命令拥有别名：
```
cmd.subcmd
cmddeasc
别名：.c。
```
但是调用`cmd.c`时并不会响应该命令。

### Describe the solution you'd like

(*/ω＼*)增加一下subcommand对别名的支持呗。

### Describe alternatives you've considered

将别名`.c`额外注册为subcammand，但是这在help中会显得十分丑陋。
```TypeScript
ctx.command('cmd', ...)
    .subcommand('.subcmd', 'cmddesc')
    .subcommand('.c', 'cmddesc')
```

**Comment by shigma** [comment]
```ts
ctx.command('cmd', ...).subcommand('.subcmd', 'cmddesc').alias('cmd.c')
```

**Comment by Lipraty** [comment]
原来是这样，学到了！
