### ISSUE TITLE
Bug: 热重载功能不稳定

### ISSUE THREAD

**Issue by Harry-zklcdc** [koishijs/koishi#791]
### Describe the bug

开发模式下，插件源文件中出现语法错误后，之后便无法热重载，插件维持在最后一个可用版本（即使之后修复语法错误）

### Steps to reproduce

如上，插件源文件出现语法错误时

### Expected behavior

后期修复语法错误后，插件能被正常重载

### Versions

- OS: Ubuntu 20.04
- Platform: OneBot, Sandbox
- Node version: 14.18.3
- Koishi version: 4.9.0

**Comment by shigma** [comment]
请更新 cordis 到最新版，看是否仍有此问题。

**Comment by shigma** [comment]
暂时认为已解决。如果仍有出现可以另开 issue。
