### ISSUE TITLE
Bug: onebot驱动器设置显示出错

### ISSUE THREAD

**Issue by HuanLinMaster** [koishijs/koishi#794]
### Describe the bug

![image](https://user-images.githubusercontent.com/94176676/189563094-992ccfe5-65ac-49a4-9d40-56a1ba2a0fb5.png)
显示了这么多 刷新也不会消失
![%J(~4XM2`7`WC8K7BA X{}D](https://user-images.githubusercontent.com/94176676/189563200-93431e01-b992-4c65-ae20-3f379907c786.png)
好像分开算的

### Steps to reproduce

图片1：多次重启onebot驱动器
图片2：点了一下最上面的那个“是否自动创建 go-cqhttp 子进程。”

### Expected behavior

起码别给我显示这么多吧

### Screenshots

上面已经有了

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
请更新 cordis 到最新版，看是否仍有此问题。

**Comment by shigma** [comment]
刚刚在群里又发现了同样的问题。

**Comment by shigma** [comment]
console 插件最新版 4.6.11 已修复此问题。
