### ISSUE TITLE
commandPrefix使用array做参数会抛出TypeError

### ISSUE THREAD

**Issue by arily** [koishijs/koishi#8]
**Describe the bug**
https://koishijs.github.io/guide/command-system.html#指令前缀
根据这里的文档commandPrefix可以提供array来实现多前缀触发指令。
但当我提供array时会抛出错误。
/node_modules/escape-string-regexp/index.js:7
		throw new TypeError('Expected a string');

**To Reproduce**
```
const app = new App({
...
  commandPrefix: ["!","！"],
})
```

**Expected behavior**
数组中提供的所有前缀都可触发bot指令

**Screenshots**
<img width="682" alt="image" src="https://user-images.githubusercontent.com/10007589/71651679-d57ceb00-2d62-11ea-834d-24a6def6f0ae.png">

**Versions**

- OS:macOS
- Node Version:12.13.0
- CoolQ Version:5.15.5A
- CQHTTP Version:4.12.3
- Koishi Version: 1.0.0-alpha.8

**Additional context**

**Comment by Shigma** [comment]
@arily 这个特性应该是 1.0.0-alpha.9 引入的，尽量更新到最新版吧

**Comment by arily** [comment]
Ok
