### ISSUE TITLE
Bug: discord适配器無法使用

### ISSUE THREAD

**Issue by cherry0804** [koishijs/koishi#804]
### Describe the bug

discord适配器  adapter Disallowed intent(s)., will retry in 5s...，就這樣一直无限重试

### Steps to reproduce

设置完token後，启用插件，就出現這樣

### Expected behavior

想讓我的discord bot正常上線

### Screenshots

![image](https://user-images.githubusercontent.com/72689056/194602983-4f1929fb-27dc-4b17-9eee-d4a7a6d1eb9c.png)

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
1. 前往 https://discord.com/developers/applications
2. 点击你的 bot application
3. 在左侧选择「Bot」
4. Privileged Gateway Intents 下面的三个全部勾上
