### ISSUE TITLE
Bug: 高版本@koishijs/plugin-database-mysql影响其他插件运行

### ISSUE THREAD

**Issue by zangguojun** [koishijs/koishi#805]
### Describe the bug

无法通过`ctx.middleware`监听群聊消息
但`ctx.command`依然可以监听

### Steps to reproduce

DEMO：`git@github.com:zangguojun/koishi-test.git`
将package.json 中的 @koishijs/plugin-database-mysql 替换成高版本

### Expected behavior

解决`ctx.middleware`无法监听群聊消息

### Screenshots

gocq以及ws连接均无报错
koish以及database-mysql插件也无报错
<img width="701" alt="image" src="https://user-images.githubusercontent.com/49148972/194696742-6ea8b610-88e3-4b2f-8202-4b238355ee3f.png">
<img width="232" alt="image" src="https://user-images.githubusercontent.com/49148972/194696759-6f72dcc7-a8b4-4133-84e3-638ed718fd5c.png">

### Versions

- OS: macOS Monterey 12.6
- Platform:  Onebot
- Node version: v16.17.0
- Koishi version: ^4.9.4
- database-mysql version
    - ^4.6.0  error
    - ^4.4.3  success

**Comment by shigma** [comment]
我这里就用的是最高版本的代码，没有遇到你的问题。如果可以的话请提供最小复现或指出高低版本 diff 中可能有问题的地方。

**Comment by shigma** [comment]
再延长一个月的等待时间，看看有没有相关的反馈……
