### ISSUE TITLE
Feature: 为中间件栈添加错误处理中间件功能

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#806]
### Describe the problem related to the feature request

现在我们的bot需要集中处理在中间件栈中出现的错误，但目前只能分别通过try/catch块（这只适用于我们自己定义的中间件）或监听UncaughtError（这又会多出许多范围之外的error），并没有一个可以通过中间件栈本身的功能来处理错误的接口。

### Describe the solution you'd like

在[express](https://github.com/expressjs/express)的中间件栈中，我们可以通过next(err)的方式在中间件栈内抛出错误并通过带有err参数的中间件（对于express是"err,req,res,next"，而在koishi里是"err,session,next"）来处理错误。
希望koishi的中间件栈也能添加一个类似的功能。

### Describe alternatives you've considered

我还在 shigma/cordis#2 中提出可以增加ctx.error内置服务来抛出错误并通过这个服务的相关方法增加错误处理器来处理错误，但经过讨论这个方案并不具有可行性。本方案的可行性相对较高（已由express等实现），故在此提出。

**Comment by shigma** [comment]
只需使用下面的代码：

```ts
ctx.middleware(async (session, next) => {
  try {
    return await next()
  } catch (error) {
    // handle error
  }
}, true)
```
