### ISSUE TITLE
Feature: Noise和Strength客製化

### ISSUE THREAD

**Issue by f9207000** [koishijs/koishi#809]
### Describe the problem related to the feature request

在novelAI裡，可以根據Noise和Strength去改變生成圖片與原本圖片的差距。
我看index.ts裡的Noise和Strength都是預設值，感覺有點可惜
不知道shigma大大有沒有想要添加這個功能呢？

### Describe the solution you'd like

將Noise和Strength變成options

**Comment by shigma** [comment]
别关，会做

**Comment by f9207000** [comment]
我不小心發錯地方了，抱歉
