### ISSUE TITLE
Bug: plugin-database-mysql连接数据库有问题

### ISSUE THREAD

**Issue by dalamudx** [koishijs/koishi#816]
### Describe the bug

host默认为localhost
但是实际情况保存完成启动后，后台连接数据库却使用127.0.0.1，会导致数据库用户只授权localhost访问的情况下被拒绝连接

### Steps to reproduce

host配置为localhost，数据库授权用户仅允许localhost连接

### Expected behavior

当页面配置中host设置为localhost后，进行数据库连接时也使用localhost去建立连接

### Screenshots

控制台配置
![image](https://user-images.githubusercontent.com/88395653/195972343-1a9f9bd0-f572-4ddb-88bc-9069eac2cbd5.png)
日志
![image](https://user-images.githubusercontent.com/88395653/195972362-e76763b9-9229-4fc0-a3fd-0b2556fafdf7.png)
数据库连接测试
![image](https://user-images.githubusercontent.com/88395653/195972769-14372f70-0351-4e1e-822c-6a55461be654.png)

### Versions

- OS: Ubuntu 22.04.1 LTS
- Platform: Discord
- Node version: v16.17.1
- Koishi version: 4.9.5

**Comment by MaikoTan** [comment]
Do you edited your my.cnf file (the configuration file of MariaDB) before?
Please check it out whether there is a property `skip-name-resolve`. If true, just remove it and restart MariaDB.

你以前是否编辑过你的my.cnf文件（MariaDB的配置文件）？
请检查是否有`skip-name-resolve`属性。如果是的话，请删除它并重新启动MariaDB。

**Comment by MaikoTan** [comment]
If you DO want to keep `skip-name-resolve` property (as it improves performance), you can just alter your MariaDB database to allow connecting from `127.0.0.1`.
Such as:

如果你确实想保留`skip-name-resolve`属性（因为它能提高性能），你可以直接改变你的MariaDB数据库，允许从`127.0.0.1`连接。
比如说：

```sql
CREATE USER 'root'@'127.0.0.1' IDENTIFIED BY 'root-password';
CREATE USER 'root'@'::1' IDENTIFIED BY 'root-password';
FLUSH PRIVILEGES;
```

**Comment by dalamudx** [comment]
嗯，直接用127.0.0.1了
