### ISSUE TITLE
Bug: Command.shortcut 行为不符合预期

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi#818]
### Describe the bug

koishi core 升级到 4.9.x 后，`Command.shortcut` 的行为与之前不一致，详见下方描述

### Steps to reproduce

**最小复现代码**

```ts
import { Context } from 'koishi'

export default class PluginFoo {
  constructor(public ctx: Context) {
    ctx
      .command('说 <content:text>')
      .shortcut(/^很别致但是并不短的捷径$/, {
        args: ['我是一个非同寻常的参数'],
        options: {
          user: '我是一个无与伦比的选项',
        },
      })
      .option('user', '<user:string>', { hidden: true })
      .action(({ session, options }, content) => {
        return `${options?.user || session?.username}说道：${content || '然而什么也没说'}`
      })
  }
}
```

**行为**

- 用户A输入：“很别致但是并不短的捷径”
- bot回复：“A说道：然而什么也没说”

### Expected behavior

**行为**

- 用户A输入：“很别致但是并不短的捷径”
- bot回复：“我是一个无与伦比的选项说道：我是一个非同寻常的参数”

### Screenshots

如果你需要的话，我这里有一个实际使用的例子：
![图片](https://user-images.githubusercontent.com/44761872/196006706-9ff7cd2a-9596-4b9f-afc9-c805b8cd1816.png)

在之前的版本中，他按预期工作的样子是这样的（此处出现的亚当与下文的SILI在业务逻辑上使用同一套逻辑，只是账号不同）：
![图片](https://user-images.githubusercontent.com/44761872/196006639-b92e182a-4ade-4e3c-9c82-c2153c5f3cd2.png)

但她现在变成傲娇了：
![图片](https://user-images.githubusercontent.com/44761872/196006687-44b00db4-3d75-40c1-8ded-a0478d9b7b50.png)

### Versions

- OS: win server
- Platform: 
- Node version: 16.x
- Koishi version: 4.9.5
  - koishi 官方插件均使用与核心同期的 latest 版本

**Comment by Dragon-Fish** [comment]
补充测试：与prefix无关
![image](https://gchat.qpic.cn/gchatpic_new/824399619/3916230045-2532377386-340F2E6DC1AC75DC952AFE0806793553/0?term=3)

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by Anillc** [comment]
问题定位:
https://github.com/koishijs/koishi/blob/e017de872e7c60c98afa3a25e054b3f6eacedcd4/packages/core/src/command/parser.ts#L499
这个函数中，`argv` 参数中的 `args` 和 `options` 被后面的两个参数覆盖，所以返回的 `argv` 中的 `args` 和 `options` 变成了 `[]` 和 `{}`。

搜索了一下代码，似乎只有一个地方用到了后面的参数，其实可以就用 `argv` 对象中的 `args` 和 `options`？不太清楚这里为什么多设计了两个参数

**Comment by shigma** [comment]
刚刚看了一下，现在的行为又变了（但也是错的）。已修。
