### ISSUE TITLE
Bug: sandbox内手动发送的图片无法正常显示

### ISSUE THREAD

**Issue by 13130200183** [koishijs/koishi#821]
### Describe the bug

在控制台的沙盒里 手动发送图片给机器人 所发送的图片无法正常显示（图片裂开）
![image](https://user-images.githubusercontent.com/54051043/196098687-6b9158da-7343-44aa-b977-6f369a98b541.png)

F12审查元素发现图片经过base64转化 但url的base64前缀不完整（不正确？）
![image](https://user-images.githubusercontent.com/54051043/196098792-ceceb20d-4807-48af-af43-a506bc6c601b.png)

手动修正前缀后 图片能够正常显示（”base64://”修改为 ”data:image/png;base64,”）
![image](https://user-images.githubusercontent.com/54051043/196099272-e0bd8c42-882e-42b8-9cc8-985fd597d589.png)

### Steps to reproduce

１.在沙盒中添加一个用户
２.复制或拖拽一张图片到沙盒的消息发送区域 图片会自动发送
３.图片裂开

### Expected behavior

复制或拖拽一张图片到沙盒的消息发送区域 图片正常显示

### Versions

- plugin-console 4.6.7
- plugin-sandbox 2.3.2

**Comment by shigma** [comment]
我这里似乎没有复现此问题……？

**Comment by 13130200183** [comment]
> 我这里似乎没有复现此问题……？

我这里在开发模式下运行可稳定复现，刚看了下普通模式下图片显示的确是正常的（因为在写插件一直是开发模式）

**Comment by shigma** [comment]
刚刚想到了另一种可能性。沙盒受到一定大小的存储空间限制（5M），超出空间后会无法显示新的图片。

如果你是这种情况，请尝试在发送过图片的沙盒频道发送 `clear` 指令以清空相应的聊天记录。
