### ISSUE TITLE
Bug: kook无法发送图片

### ISSUE THREAD

**Issue by MXDexRazero** [koishijs/koishi#824]
### Describe the bug

kook适配器插件和novelai已为最新版本，但在kook里机器人无法发送图片，导致本地novelai跑完了图片只有参数发送回到kook频道但是没有图片
![3e2338d7296b6536](https://user-images.githubusercontent.com/112014237/196488076-9bf437c6-49c2-4661-b3a0-bc8f6a77613e.jpg)
![-79cdca4846b0d6ca](https://user-images.githubusercontent.com/112014237/196488100-00c77537-c3e1-48e0-9ea8-8619afc55bf6.jpg)

### Steps to reproduce

在kook频道输入
画画 cat

### Expected behavior

kook机器人可以正常发送图片

### Screenshots

![3e2338d7296b6536](https://user-images.githubusercontent.com/112014237/196488460-f69ae7c3-b873-4d5a-bd21-f321562882f0.jpg)
![-79cdca4846b0d6ca](https://user-images.githubusercontent.com/112014237/196488474-98eef807-78cd-4dbe-b270-e371401a73e0.jpg)

### Versions

- OS: 
- Platform: 
- Koishi version:

**Comment by shigma** [comment]
duplicate of #822

解决方法也相同。

**Comment by MXDexRazero** [comment]
> duplicate of #822
> 
> 解决方法也相同。

谢谢你，在看了在看了

**Comment by shigma** [comment]
最新版已经修复此问题。
