### ISSUE TITLE
Feature: 网页后台是否可以设置密码

### ISSUE THREAD

**Issue by Mrqqeat** [koishijs/koishi#825]
### Describe the problem related to the feature request

访问网页后台是否可以设置密码

### Describe the solution you'd like

访问网页后台是否可以设置密码

### Describe alternatives you've considered

访问网页后台是否可以设置密码

### Additional context

访问网页后台是否可以设置密码

**Comment by shigma** [comment]
你在说什么？

**Comment by Mrqqeat** [comment]
> 你在说什么？

我是说网页的控制台谁都可以进入，可不可以设置一个密码需要密码才能进入

**Comment by Seidko** [comment]
插件市场搜索auth插件

**Comment by H4M5TER** [comment]
默认情况下网页控制台只对本地开放，如果你需要对公网开放请参考
https://github.com/koishijs/novelai-bot/issues/13

**Comment by shigma** [comment]
https://github.com/koishijs/novelai-bot/issues/13

**Comment by Mrqqeat** [comment]
> auth插件



> 插件市场搜索auth插件

明白了，谢谢

**Comment by Mrqqeat** [comment]
> [koishijs/novelai-bot#13](https://github.com/koishijs/novelai-bot/issues/13)

收到，感谢
