### ISSUE TITLE
Bug: 无法在Docker中启动OneBot

### ISSUE THREAD

**Issue by borraken** [koishijs/koishi#827]
### Describe the bug

我无法在Docker中启动OneBot。
未连接到 go-cqhttp 子进程。
我一开始尝试在群晖docker中启动，日志显示超时。
后面我尝试在window10中启动，日志未报错，但一样显示未连接到子进程

### Steps to reproduce

```
docker pull koishijs/koishi:latest-puppeteer
docker run -p 5140:5140 koishijs/koishi:latest-puppeteer

```

### Expected behavior

使用ONEBOT登录QQ并正常使用其他插件

### Screenshots

market AxiosError: timeout of 30000ms exceeded
                            at RedirectableRequest.handleRequestTimeout (/home/koishi/koishi-app/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2504:16)
                            at RedirectableRequest.emit (node:events:513:28)
                            at Timeout.<anonymous> (/home/koishi/koishi-app/node_modules/follow-redirects/index.js:169:12)
                            at listOnTimeout (node:internal/timers:559:17)
                            at processTimers (node:internal/timers:502:7)
此报错仅在群晖docker中出现,win10 docker中没有
其他插件的安装，启动均正常无报错，但我无法启动QQ所以无法测试实际功能

### Versions

- OS: docker(in window 10/synology ds220+)
- Backend service: onebot 5.2.7/go-cqhttp 3.1.3
- Node version: 14.17.0
- Koishi version: 4.9.6

**Comment by borraken** [comment]
C:\Users\Administrator>docker version
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:09:02 2022
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


C:\Users\Administrator>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 7
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 6.023GiB
 Name: docker-desktop
 ID: FP2A:GBY3:4MG3:EU6I:HYK3:M2B7:PWGN:YLGA:SOIF:DSCA:7MDU:4E4J
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by Anillc** [comment]
内核版本可以使用 `uname -a` 查看

**Comment by MaikoTan** [comment]
An easy instruction:
Go to `Control Panel` -> `Task Scheduler`, click `Create` -> `Scheduled Task` -> `User-defined script`, then enter `uname -a`, also check email notification.
Then just start to run this script.
一个简单的指令： 转到“控制面板”->“任务计划程序”，点击“创建”->“计划任务”->“用户自定义脚本”，然后输入“uname -a”，同时查看邮件通知。 然后开始运行这个脚本。

**Comment by MaikoTan** [comment]
![image](https://user-images.githubusercontent.com/19927330/196908277-5db33a7d-1efc-47cd-b315-2deda44f96e8.png)

L'image sur les paramètres du planificateur de tâches.
任务计划程序设置上的图像。

**Comment by borraken** [comment]
Linux Synology_bork 4.4.180+ #42962 SMP Tue Sep 20 22:35:56 CST 2022 x86_64 GNU/Linux synology_geminilake_220+
是这个吗

**Comment by MaikoTan** [comment]
Yes, you are right.

@Anillc Also 4.4, same with me (?)
是的你是对的。 @Anillc 也是 4.4，和我一样（？）

**Comment by borraken** [comment]
Linux 59661540fb89 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 Linux
另外这是win10的，也不能使用

**Comment by shigma** [comment]
这个问题是不是已经修复了？

cc @H4M5TER @Anillc

**Comment by Anillc** [comment]
应该是的
