### ISSUE TITLE
Feature: new command type - `paragraph`

### ISSUE THREAD

**Issue by NWYLZW** [koishijs/koishi#829]
### Describe the problem related to the feature request

基于以下几种常见的场景
```text
cmd0 <prompt:paragraph> <negativePrompt:paragraph>
绘画
prompt,asdasd,bsbiadbij,sbdiuasbfijxknkjansijbdi,sadbiasbdasudbiusabdiba
negativePrompt,giusbid,wqeiqwons,asadbiuwbdsakndlknbiucbxiuajwkeggiusaixbkjabiudgiuwqjbkjbxsakjbdjhsabd
cmd1 <title:string> [desc:paragraph] [content:text]
新增代办 TODO001
这是一个 TODO001 的介绍
这是 TODO001 的具体内容
```

### Describe the solution you'd like

新增一种指令类型用于处理`文本段`类型

* 该类型参数前面可以是空格、回车，但是不会去捕获
* 该类型参数后面可以是空格、回车、或者截止符，但是也不会捕获
  * 若该参数后还存在必填参数，则触发分条逻辑
```text
cmd0 <prompt:paragraph> <negativePrompt:paragraph>
> A: 绘画 prompt,asdasd,bsbiadbij,sbdiuasbfijxknkjansijbdi,sadbiasbdasudbiusabdiba
> B: 请继续输入下一个必填参数
# if > timeout
> B: 超时未输入下一个必填参数
# else
> A: negativePrompt,giusbid,wqeiqwons,asadbiuwbdsakndlknbiucbxiuajwkeggiusaixbkjabiudgiuwqjbkjbxsakjbdjhsabd
> B: girl.png
# end
```
* 该类型参数内部出现了空格会视为该参数内部内容，会完整捕获空格

**Comment by Anillc** [comment]
有没有什么更好的写法呢，感觉换行还是不太友好。比如在 `checkArgCount: true` 的时候使用分条发送的方式，或者使用已有的引号方案

**Comment by NWYLZW** [comment]
> 有没有什么更好的写法呢，感觉换行还是不太友好。比如在 `checkArgCount: true` 的时候使用分条发送的方式，或者使用已有的引号方案

其实我不是很懂换行在哪里不友好，我手机端聊天的时候也经常用换行呀

我这里的类型语意主要还是文段，感觉用换行做切割没啥太大的问题吧？

**Comment by Anillc** [comment]
在开启了 qq 设置中的回车发送消息的情况下没有办法输入换行。貌似有的设备上长按输入框有输入换行的选项，但是我这里实测没有，如果使用换行的话就很难受

**Comment by NWYLZW** [comment]
> 在开启了 qq 设置中的回车发送消息的情况下没有办法输入换行。貌似有的设备上长按输入框有输入换行的选项，但是我这里实测没有，如果使用换行的话就很难受

那我有俩套方案，一个是使用兼容的写法，一个是引入新语法
这俩个方案的目的都是为了解决更好的桌面端交互（我这个方案主要还是考虑习惯使用回车的用户）

1. `cmd (<prompt:paragraph> <negativePrompt:paragraph>) | (prompt:text)` action 的代码里面做逻辑处理
2. `cmd (<prompt:paragraph> <negativePrompt:paragraph>)`

...待补充（先吃饭去了）

**Comment by NWYLZW** [comment]
https://github.com/koishijs/koishi/issues/829#issuecomment-1286784543

这个的话我觉得应该属于新的指令交互形式，应该另外开一个 issue 讨论

`connection: keep-alive`

**Comment by shigma** [comment]
I basically agree with @Anillc that there may be compatibility issues with this feature. But some use cases here are still worth considering. I will leave this issue open.

**Comment by NWYLZW** [comment]
> I basically agree with @Anillc that there may be compatibility issues with this feature. But some use cases here are still worth considering. I will leave this issue open.

updated
