### ISSUE TITLE
Feature: Recall插件从最近的消息开始撤回

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#832]
### Describe the problem related to the feature request

目前Recall插件会从最久远的消息开始撤回，不符合通常使用此插件的场景，比如当想要撤回bot刚刚发送的nsfw图片时。

### Describe the solution you'd like

修改为从最近消息开始撤回；
或在配置项中选择优先撤回最近消息还是最早消息；
或通过参数（如负数或 - 参数）确定撤回最近消息还是最早消息。

**Comment by MaikoTan** [comment]
I imagined a workaround, see if this satisfy you:

- Add an configuration field, say "order-to-recall", which has values as "oldest first" and "latest first"
  - If you have this config set, enter `recall <count>` would recall messages individually that follow the `order-to-recall` config.
- Add two options, say "--oldest-first, -o" and "--latest-first, -O".
  - If you have any of this two options set, no matter the `order-to-recall` is, it would recall the messages just as the option you selected.

我想了一个解决方法，看看是否能满足你。

- 添加一个配置字段，例如 "order-to-recall"，它的值是 "oldest first "和 "latest first"
  - 如果你设置了这个配置，输入 `recall <count>` 就可以单独调用遵循 "order-to-recall" 配置的邮件。
- 添加两个选项，例如 `--最旧的先，-o` 和 `--最新的先，-O`。
  - 如果你设置了这两个选项中的任何一个，无论`order-to-recall`是什么，它都会按照你选择的选项来调用信息。

**Comment by MirrorCY** [comment]
谢谢你Maiko，这就是我想要的

**Comment by shigma** [comment]
目前的行为是 bug，我写错了。下个版本会直接修复。:rofl:

> 谢谢你 Maiko

**Comment by MaikoTan** [comment]
> 目前的行为是 bug，我写错了。下个版本会直接修复。rofl
> 
> > 谢谢你 Maiko

Looks like I scored an own goal in this case. 🤣 
Thank you Shigma as well, for tracking it immediately

看来我在这种情况下打了一个自己的球。🤣 
也谢谢Shigma，因为他立即跟踪了它。

**Comment by shigma** [comment]
感谢反馈！最新版 1.2.0 已修复此问题。
