### ISSUE TITLE
Bug: proxyAgent does not handle http proxy correctly

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#835]
### Describe the bug

Parametric `proxyAgent` does not work well with http proxies. It appears that the proxy agent transforms the endpoint port to the proxy protocol default port. 
But here's the weird thing, it works good with socks5 proxy.​ (it doesn't convert port to 1080)
For example:
proxyAgent: http://192.168.1.1:7890
endpoint url: https://api.telegram.org    (:443)
actually visited endpoint url: https://api.telegram.org:80

在适配器插件中配置 http 代理似乎会把访问的端口转换为代理协议的默认端口，比如使用 http://192.168.1.1:7980 作为代理时访问 https://api.telegram.org 会在代理的日志中发现，实际访问的地址为 https://api.telegram.org:80 
但是使用 socks://192.168.1.1:7890 就不会出现这个问题，遇到这个问题的小伙伴可以先这样用顶一顶。

### Steps to reproduce

Install and configure Fndroid/clash_for_windows_pkg 0.20.6
open `Allow LAN`
configure `proxyAgent` an http proxy in @koishijs/plugin-adapter-telegram, e.g. `http://192.168.1.1:7890`
start adapter and see connection in clash

### Expected behavior

follow endpoint port when using proxy

### Screenshots

![WQ`2GMR {V2FTXAQ41 G260](https://user-images.githubusercontent.com/37006258/199826247-5f5dc929-89dd-4d2d-9dae-880464cbfe2a.png)

### Versions

- OS: Ubuntu-serever 22.04 docker
- Proxy OS: windows10 10.0.19044
- Koishi version: 4.9.9
- adapter-telegram version: 3.5.0
- clash_for_windows_pkg version: 0.20.6

### Additional context

谢谢你 Maiko，如果有语法错误请指出！

**Comment by MaikoTan** [comment]
The `proxyAgent` feature of an adapter is actually implemented in [satorijs/satori](https://github.com/satorijs/satori) (@satorijs).

We are currently using the [`http-proxy-agent`](https://github.com/TooTallNate/node-http-proxy-agent) package to support it.
Does this bug happens as well on other adapters like discord or kook or something?

------

一个适配器的 `proxyAgent` 功能实际上是在[satorijs/satori](https://github.com/satorijs/satori) (@satorijs) 中实现的。

我们目前正在使用 [`http-proxy-agent`](https://github.com/TooTallNate/node-http-proxy-agent) 包来支持它。
这个缺陷是否也发生在其他适配器上，如Discord或kook或某事？

**Comment by MirrorCY** [comment]
是的&nbsp; 我测试它发生在telegram和discord适配器上&nbsp; 其余的没有测试&nbsp; 如果有需要我可以尽可能都测试一遍




---Original---
From: "Maiko Sinkyaet ***@***.***&gt;
Date: Fri, Nov 4, 2022 11:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [koishijs/koishi] Bug: proxyAgent does not handle http proxycorrectly (Issue #835)




 
The proxyAgent feature of an adapter is actually implemented in satorijs/satori ***@***.***).
 
We are currently using the http-proxy-agent package to support it.
 Does this bug happens as well on other adapters like discord or kook or something?
 
 
一个适配器的 proxyAgent 功能实际上是在satorijs/satori ***@***.***) 中实现的。
 
我们目前正在使用 http-proxy-agent 包来支持它。
 这个缺陷是否也发生在其他适配器上，如Discord或kook或某事？

**Comment by shigma** [comment]
参考：https://github.com/satorijs/satori/blob/master/packages/satori/src/axios.ts

我倾向于把这个 issue 开在 satorijs/satori 中。我明天去 transfer 一下。

**Comment by MaikoTan** [comment]
> 我倾向于把这个 issue 开在 satorijs/satori 中。我明天去 transfer 一下。

I wanted to transfer it, but found that I have no permission to do such. >_<

我想要传送它，但是发现那个我没有权限去做。 >_<

**Comment by shigma** [comment]
GitHub 不允许跨 org 传送 issue。需要一些特别的手法。

**Comment by MirrorCY** [comment]
好的 我去 satorijs/satori 开一个 本问题关闭。
