### ISSUE TITLE
Podman启动失败：app Error: EACCES: permission denied, mkdir '/home/koishi/koishi/logs'

### ISSUE THREAD

**Issue by Z-fly** [koishijs/koishi#836]
### Describe the bug

![image](https://user-images.githubusercontent.com/10470892/199897829-0a03def7-48a3-49d9-b4fe-3ea9a3701bfd.png)

### Steps to reproduce

podman run -p 5140:5140 docker.io/koishijs/koishi:latest-puppeteer

### Versions

- OS: CentOS Linux 7
- Platform: X64

**Comment by MaikoTan** [comment]
It looks like you are running podman as root, but koishi is running as rootless user.
I didn't use podman before, but I think it is the issue.
Have you tried `--userns=keep-id` with podman? Does it solve your problem?

Refu: https://github.com/containers/podman/blob/main/troubleshooting.md#2-cant-use-volume-mount-get-permission-denied

------

看起来你是以root身份运行podman，但koishi是以无root用户身份运行。
我以前没有用过podman，但我想这是问题所在。
你有没有试过用podman的`--userns=keep-id`？它能解决你的问题吗？

拒绝：https://github.com/containers/podman/blob/main/troubleshooting.md#2-cant-use-volume-mount-get-permission-denied

**Comment by Anillc** [comment]
这看上去是我们的问题，稍后会修复

**Comment by MaikoTan** [comment]
Excuse-moi, I read the wrong file and lead to the wrong conclusion.
It can be fixed on our side, please wait patiently.

------

原谅我，我读了错误的文件导向错误的结论。
它可以在我们这边修复，请耐心地等待。

**Comment by shigma** [comment]
This should be fixed by 3e2f6b05ccd5f8f3f765b8c8b950eb3ae5205919.

**Comment by Z-fly** [comment]
看到了
