### ISSUE TITLE
typo?

### ISSUE THREAD

**Issue by masnn** [koishijs/koishi#84]
https://github.com/koishijs/koishi/blob/7b5d8472cae814c0a09cd28796970115cea5853e/packages/plugin-tools/src/qrcode.ts#L16

（？

**Comment by Shigma** [comment]
嗯是这样，我无脑复制了

**Comment by masnn** [comment]
23333

**Comment by Shigma** [comment]
Fixed by 5fac56ae8309b54e10f1dec945d63c55f7aff862.
