### ISSUE TITLE
Bug: Discord适配器无法正常使用

### ISSUE THREAD

**Issue by zxzxy** [koishijs/koishi#840]
### Describe the bug

Discord适配器无法正常使用，一直报 adapter failed to connect to wss://gateway.discord.gg/, code: 1006

### Steps to reproduce

在Discord里打开Privileged Gateway Intents的三个选项并在koishi填入token启用后一直无法连接
![image](https://user-images.githubusercontent.com/73475219/200154870-97655508-81ab-4886-a6de-8f0651487c17.png)
![image](https://user-images.githubusercontent.com/73475219/200154659-cde9399e-1f51-4bad-8cf2-0a8bf18ae1fc.png)
在配置了代理后仍然无法连接，使用的代理是Clash for Windows，能够在浏览器中正常访问Discord
![image](https://user-images.githubusercontent.com/73475219/200154824-f166a4c8-87ad-436d-ac79-bb8593d2c763.png)

![image](https://user-images.githubusercontent.com/73475219/200154707-9850f5ab-a729-4383-9b40-eb323cefafab.png)

### Expected behavior

能够正常使用Discord适配器

### Versions

- OS: Windows 11
- Platform: Discord
- Node version: v16.17.0
- Koishi version: 4.10.0

**Comment by MirrorCY** [comment]
请参考 https://github.com/satorijs/satori/issues/39

**Comment by MirrorCY** [comment]
请测试将 `proxyAgent` 设置为 `socks://127.0.0.1:7890` 后可以连接吗？

**Comment by zxzxy** [comment]
可以了！谢谢！

**Comment by MirrorCY** [comment]
是不是很快的响应~ 🚀

**Comment by zxzxy** [comment]
我还想着要等上个半天才回有人理我呢😂，没想到这么快

**Comment by MirrorCY** [comment]
![image](https://user-images.githubusercontent.com/37006258/200155292-e07cf8ba-61fd-47c8-a4c7-755a488949d6.png)
本项目可是上过榜的~（
如果问题已解决，你可以关闭该问题了
btw，这个问题在 #835 提出过，下次可以先查一查~
