### ISSUE TITLE
Bug: 设置 status 后会出现多个状态面板

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#841]
### Describe the bug

设置 status 并重载设置后会出现多个状态面板

### Steps to reproduce

1. 进入插件配置
2. 修改 status 插件参数
3. 重载配置
4. 查看下方状态栏
5. 查看欢迎界面状态面板

### Expected behavior

设置 status 并重载设置后**不会**出现多个状态面板

### Screenshots

![image](https://user-images.githubusercontent.com/37006258/200238936-3a58152b-f11c-4585-868d-b4f1943368a1.png)
![image](https://user-images.githubusercontent.com/37006258/200238982-0645b7dd-7578-4c38-8698-cc2a27ada4e7.png)

### Versions

- OS: ubuntu docker
- Koishi version: 4.10.0

**Comment by shigma** [comment]
console 插件最新版 4.6.11 已修复此问题。
