### ISSUE TITLE
Bug: database-mysql在处理list类型时出错

### ISSUE THREAD

**Issue by ConstasJ** [koishijs/koishi#865]
### Describe the bug

我是在使用forward插件时发现这个问题的。当我使用forward.add添加转发频道后并没有正常转发，而使用forward.list查看了一下后发现结果严重不符合预期。后来我自己写了一个测试插件后发现可能是database-mysql对list的处理不正常（详见下图）。
具体来说，就是会在list的项中出现"""、"\","[]"等不应该出现的字符。

### Steps to reproduce

1. 初始化模板项目
2. 配置好database-mysql
3. 使用任意一个需要在database中存储list的插件
4. 出现错误

### Expected behavior

应该和其他database插件一样正常存储list类型的数据。

### Screenshots

![}FT)0GP MYTKPZVI8Q`8WZ6](https://user-images.githubusercontent.com/61967203/205481155-c3679533-37d0-4d5a-88b3-13d8f6703795.png)
![9NJ0ALP`69UET%SB)5O{(~E](https://user-images.githubusercontent.com/61967203/205481157-8ac7ea65-4451-4f02-b424-f5018bf771c0.png)
![ZO1K4$%V0{S@VA$M_KN)FZ0](https://user-images.githubusercontent.com/61967203/205481198-2b40f3b1-3af8-4fe5-84bc-ace7c088fd26.png)
![XNF}){QOB0{UG(T6QMY8JWB](https://user-images.githubusercontent.com/61967203/205481205-8849d41a-a792-493d-a815-5156823a61b8.png)

### Versions

- OS: Windows 11 & Ubuntu 20.04 LTS
- Platform: 与平台无关
- Node version: 18.4.0(Win)/18.6.0(Ubuntu)
- Koishi version: 4.10.4

### Additional context

稍后我会在[minato](https://github.com/shigma/minato)那边也提出一个同样的issue。

**Comment by shigma** [comment]
看起来确实有问题。我会尽快修复。
