### ISSUE TITLE
Feature: 插件开发可以使用js与ts混合开发吗或者有纯js开发的文档吗

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#867]
### Describe the problem related to the feature request

目前我的插件使用的是js和ts混合开发，yarn dev没有问题。但是yarn build则会报错。我想问问是不是不可以ts和js混合开发，如果不可以，请问有纯js开发插件的文档吗
目前我的tsconfig.js已经加上
```
"allowJs": true
```
yarn build 发生下面错误

![image](https://user-images.githubusercontent.com/113200130/205920876-bb56bc18-8414-492b-846f-5859d66b32d5.png)

我的目录结构
![image](https://user-images.githubusercontent.com/113200130/205920949-c4f6211f-2ee3-474c-8436-cf2b4a539213.png)

src里面是纯ts代码，其他的都是被引用的js。yarn dev运行良好

### Describe the solution you'd like

我希望能使用js加ts混合开发

**Comment by ghostcatu** [comment]
> 可以混合开发。但看起来我写的构建脚本没有考虑到您的情况。请问你的项目有开源吗？我想具体研究一下你的项目结构。

仓库：https://github.com/ghostcatu/kuroshio-genshin-plugin
依赖：
- mongoDB
另外本地需要安装redis，修改config/default_config/redis.yaml 下的配置链接redis
不安装redis会提示无法连接redis终止运行

**Comment by ghostcatu** [comment]
> 你的问题现已修复。请尝试更新 yakumo-tsc 到 0.3.7 或以上版本。

build 倒是ok了，但是yarn dev出现了先的问题，是否需要提新的issue
![image](https://user-images.githubusercontent.com/113200130/206835421-ff779eac-39a8-41d5-b212-d5f5ec123a9b.png)

**Comment by ghostcatu** [comment]
> > 你的问题现已修复。请尝试更新 yakumo-tsc 到 0.3.7 或以上版本。
> 
> build 倒是ok了，但是yarn dev出现了新的问题，是否需要提新的issue ![image](https://user-images.githubusercontent.com/113200130/206835421-ff779eac-39a8-41d5-b212-d5f5ec123a9b.png)

version： @koishijs/plugin-database-mongo | 4.0.3 
                koishi | 4.10.5

**Comment by shigma** [comment]
我猜是你 mongo 后端版本过低导致的。不过我试着发了一版更新 4.0.4 或许能解决你的问题？

**Comment by ghostcatu** [comment]
> 我猜是你 mongo 后端版本过低导致的。不过我试着发了一版更新 4.0.4 或许能解决你的问题？

升级到4.0.4，问题解决了，但是又出现了新的问题，某些指令的shortcut会报错（升级前可用），触发command是有效的，但是触发shortcut会报错

指令代码
```
 ctx.command('#攻略说明')
      .shortcut(/^#?攻略(说明|帮助)?$/, { args: ['$1'] })
      .action(async ({session}) => {
        new app.strategy(ctx, session).strategy_help()
 })
```

# 使用【#攻略说明】触发时一切ok
![image](https://user-images.githubusercontent.com/113200130/206853685-71b2fe33-dec8-4265-89c1-1feed8385baf.png)
![image](https://user-images.githubusercontent.com/113200130/206853692-8baff241-63ef-41bf-ae5b-642fb40c120b.png)

# 使用【#攻略（shortcut）】触发时后台报错
![image](https://user-images.githubusercontent.com/113200130/206853733-4d3ff024-2c37-49ad-8c1c-3ed896c80251.png)


# 版本
@satorijs/satori ： 1.4.8
koishi：4.10.5

我是否需要升级@satorijs/satori来解决这个问题，或者是不是我的api已经过时，我遇到的问题比较多，麻烦你了

**Comment by shigma** [comment]
好怪啊我看不出来问题.jpg

我怀疑是 Koishi 的 bug，我晚点再研究一下。

上面的「一切 OK」也有报错，真的能叫 OK 吗（）

**Comment by ghostcatu** [comment]
> 好怪啊我看不出来问题.jpg
> 
> 我怀疑是 Koishi 的 bug，我晚点再研究一下。
> 
> 上面的「一切 OK」也有报错，真的能叫 OK 吗（）

上面那个是warning，以前也一直有，但是不影响输出结果（我觉得ok）

**Comment by ghostcatu** [comment]
> 好怪啊我看不出来问题.jpg
> 
> 我怀疑是 Koishi 的 bug，我晚点再研究一下。
> 
> 上面的「一切 OK」也有报错，真的能叫 OK 吗（）

build完后还有一个问题，yarn start的时候提示js文件不能引入外部node_module

`
![image](https://user-images.githubusercontent.com/113200130/206912162-1900590b-5f73-474d-aee0-ef710e7ae568.png)
`

**Comment by shigma** [comment]
> build完后还有一个问题，yarn start的时候提示js文件不能引入外部node_module

@ghostcatu 这是因为你使用了 pure esm 的依赖。目前 Koishi 生态尚未支持 pure esm，你需要降低依赖的版本（在你的例子里是降低 redis 的版本）。

**Comment by ghostcatu** [comment]
> > build完后还有一个问题，yarn start的时候提示js文件不能引入外部node_module
> 
> ~@ghostcatu 这是因为你使用了 pure esm 的依赖。目前 Koishi 生态尚未支持 pure esm，你需要降低依赖的版本（在你的例子里是降低 redis 的版本）。~
> 
> 更正：请问你是如何构建的呢？正常情况下构建的目录应该是 lib 而不是 dist 才对。

这是因为我修改了pakage.json和tsconfig.js。 因为我比较习惯用dist作为输出，这个应该不影响，我没修改前也是这样

![image](https://user-images.githubusercontent.com/113200130/206913967-50c6e707-964d-4370-abd2-0d20631fedfa.png)

![image](https://user-images.githubusercontent.com/113200130/206914064-97208d4b-0615-4e55-941c-c5541192205a.png)

**Comment by shigma** [comment]
我不确定，但看起来相当可能与源码结构有关系。源码中 redis 这个文件是 ts 还是 js？

**Comment by shigma** [comment]
我看了一下，大概原因是源码使用 pure esm 的 js，在 Koishi 项目中必须经过转译才能使用。但是默认的构建流程不转译这些文件。你可以将它们后缀名改为 ts 试试。

**Comment by ghostcatu** [comment]
> 我看了一下，大概原因是源码使用 pure esm 的 js，在 Koishi 项目中必须经过转译才能使用。但是默认的构建流程不转译这些文件。你可以将它们后缀名改为 ts 试试。

转成ts会产生很多报错，请问还有别的方法吗

**Comment by shigma** [comment]
后续我们会跟进对混合项目的构建支持。就目前而言，你可以在文件头添加：

```ts
// @ts-nocheck
```

来屏蔽报错。

**Comment by ilharp** [comment]
个人的推荐是不使用任何 esm 的依赖。目前应该没有任何场景下会出现只能使用 esm 依赖的情况，绝大部分场景都有对应的 cjs 包以解决此问题。

**Comment by ghostcatu** [comment]
> 好怪啊我看不出来问题.jpg
> 
> 我怀疑是 Koishi 的 bug，我晚点再研究一下。
> 
> 上面的「一切 OK」也有报错，真的能叫 OK 吗（）

我可以判断是正则的问题了，但是我感觉我的正则没有错的，你能看出是什么问题吗

![image](https://user-images.githubusercontent.com/113200130/207786441-cdde2546-afa7-4059-b4a9-33e0c016f682.png)

![image](https://user-images.githubusercontent.com/113200130/207786465-a11ed25d-bfaa-4853-8821-24d8ae76eb6e.png)

**Comment by shigma** [comment]
我看了一下，你的问题在于不应该写这个 `args: ['$1']`。

```ts
ctx.command('#攻略说明')
   .shortcut(/^#?攻略(说明|帮助)?$/, { args: ['$1'] })
   .action(async ({session}) => {
      new app.strategy(ctx, session).strategy_help()
   })
```

`$1` 的意思是第一个捕获组。当输入 `#攻略` 时。这个捕获组是空的导致了报错 (当然 Koishi 应当处理这种情况)。

删去 `args: ['$1']` 即可正常使用。

此外个人建议使用英文作为 command 的标识符，然后通过 shortcut 作为调用方式。例如：

```ts
ctx.command('genshin.strategy')
   .shortcut(...)
```

**Comment by shigma** [comment]
至此这个 issue 中提及的所有问题应该算是解决了。后续还有其他疑问可以另开 issue。
