### ISSUE TITLE
Feat: Clone the repository using `koishi-script`

### ISSUE THREAD

**Issue by TimeBather** [koishijs/koishi#870]
### Describe the problem related to the feature request

 - For freshmen, they did not how to clone a repository to local
 - For other developers, it's may complex for them to initilize a plugin repository with existing source code because of they need to consider the struct (where the plugin file should place)

### Describe the solution you'd like

Using `clone` script  instead.(`yarn clone/npm run clone`)
The yarn clone command will do:
1. If  none parameter provided , `yarn clone` will check the configure of the toolchain(`tsconfig.json`) 's configure and call `yarn/npm`
2. If the provided paramter is a git URL , then clone it;If the provided parameter is a vaild npm package , try to quest the vcs URL to the npm;If the provided parameter is a vaild directory , copy the directory
4. Move the directory to the path where it need do so.
5. Auto configure the toolchain(`tsconfig.json`) and automaticlly call the `yarn/npm`

**Comment by shigma** [comment]
This feature has been supported by latest the version of `@koishijs/scripts`.
