### ISSUE TITLE
Feature: “插件配置”的“选择插件”增加搜索功能

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#878]
### Describe the problem related to the feature request

想要搜索

### Describe the solution you'd like

加个搜索框

**Comment by shigma** [comment]
你说的是添加插件吗？

Maybe duplicate of https://github.com/koishijs/console/issues/56.

**Comment by idanran** [comment]
> 你说的是添加插件吗？
> 
> Maybe duplicate of [koishijs/console#56](https://github.com/koishijs/console/issues/56).

草，这么巧的吗

**Comment by shigma** [comment]
《15 分钟前》

**Comment by idanran** [comment]
🤣🤣
