### ISSUE TITLE
Bug: 按文档的代码写配置项，无法打印出来

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#884]
### Describe the bug

我参考文档的代码
![image](https://user-images.githubusercontent.com/113200130/208033023-0c9617cc-ce11-45d7-8df3-ee033fa4807b.png)

写自己的配置项
![image](https://user-images.githubusercontent.com/113200130/208033565-095e4b6e-b094-4be4-93dc-33392d4091d7.png)

但是后台无法打印出来，是缺了哪几步吗

### Steps to reproduce

拷贝文档代码运行

### Expected behavior

能打印出配置项

### Screenshots

![image](https://user-images.githubusercontent.com/113200130/208033196-adb0f5a9-0c9b-4b1d-be84-4a48d4319a2d.png)

### Versions

- OS: Win10
- Platform: sanbox
- Node version: 16
- Koishi version: 4.10.5

**Comment by shigma** [comment]
如果要使用默认导出类，请这样写：

```ts
class Foo {
  constructor(ctx: Context, config: Foo.Config) {}
}

namespace Foo {
  export interface Config {}
  export const Config: Schema<Config> = Schema.object({})
}

export default Foo
```

这是因为你那种写法中，模块的默认导出 `Foo` 并没有一个叫 `Config` 的属性。

**Comment by ghostcatu** [comment]
> ```ts
> export default Foo
> ```

好使，解决，感谢
