### ISSUE TITLE
Feature: 实现一个统一的接口存放插件的一些零碎数据

### ISSUE THREAD

**Issue by Seidko** [koishijs/koishi#887]
### Describe the problem related to the feature request

目前的 koishi 插件只能在数据库中或者自己创建一个本地文件来存储一些全局的kv变量：比如marry插件，需要记录上次清除结婚数据的时间，但是存在数据库中又显得很没有必要：

![image](https://user-images.githubusercontent.com/64234553/208922576-c3380c62-7d13-40b3-8fed-06c5fe1ada29.png)

看！专门创建了一个表只是为了存储这个`latestCleanUpTime`
而且代码也显得很冗长：

```ts
interface MarryData {
  id: number
  latestCleanUpTime: Date
}

declare module 'koishi' {
  interface Tables {
    marry_data: MarryData
  }
}

export function apply(ctx: Context, config: Config) {
  ctx.model.extend('marry_data', {
    id: 'unsigned',
    latestCleanUpTime: 'timestamp',
  })
  // ...
}
```

而且数据库操作也很麻烦，如果用本地文件存储的话就更不用说了，会造成管理混乱，甚至插件冲突等问题。

有人可能会说：可以存在配置文件里呀？是可以的，但是配置文件是存储插件设置的地方，而不是存储插件数据的地方，配置文件不应该被滥用，应该有一个专门的地方来存储这些零碎的数据。

所以可不可以有一种方法来存储这些零碎的、全局的变量呢？

### 解决方法一

创建一个新的，统一的yaml（或者json）来存储这些kv数据，像这样：
```yaml
plugins:
  marry:
    latestCleanUpTime: 0
  other-plugin:
    xxx: str
  # ...
```
然后通过`ctx.data`来get和set这些数据

### 解决方法二

`ctx.database`提供一个 kv db 简化接口，如：
```ts
declare module 'koishi' {
  interface Data {
    latestCleanUpTime: Date
  }
}

ctx.database.setData('latestCleanUpTime', new Date())
const latestCleanUpTime = ctx.database.getData('latestCleanUpTime')
```
| plugins | key | value |
| - | - | - |
| marry | latestCleanUpTime | 16000000 |
| other-plugin | xxx | str |

跨插件读取数据可以像这样：
```ts
// other-plugin
const latestCleanUpTime = ctx.database.getData('latestCleanUpTime', 'marry')
ctx.database.setData('latestCleanUpTime', new Date(), 'marry')
```

### Additional context

欢迎讨论，提供更多的想法~

**Comment by shigma** [comment]
可以做。

![J9UJNGXP`Q)R~5I_$S1 $%U](https://user-images.githubusercontent.com/33423008/208932298-3885b06d-12c4-4e7d-857d-235bbe84f02b.png)

**Comment by simon300000** [comment]
看起来你们甚至需要一个 koishi-plugin- adapter-koishi

**Comment by ghostcatu** [comment]
我觉得可以用缓存来存取这些数据，存取速度快也方便。我使用的是redis，官方的@koishijs/plugin-database-memory应该也是个不错的选择

**Comment by shigma** [comment]
现在已经有标准化的缓存服务了：<https://cache.koishi.chat>

**Comment by Pluckypan** [comment]
> 现在已经有标准化的缓存服务了：https://cache.koishi.chat

文档你没有发布吧，访问不了，看到项目了 https://github.com/koishijs/cache/blob/main/docs/zh-CN/index.md
建议丰富一下使用案例，跟 quick start 的形式一样

**Comment by Pluckypan** [comment]
> > 现在已经有标准化的缓存服务了：https://cache.koishi.chat
> 
> 文档你没有发布吧，访问不了，看到项目了 https://github.com/koishijs/cache/blob/main/docs/zh-CN/index.md 建议丰富一下使用案例，跟 quick start 的形式一样

<img width="936" alt="image" src="https://github.com/koishijs/koishi/assets/12028060/c041b427-5585-4fb5-a479-8a5bd6a4f497">
