### ISSUE TITLE
Bug: 更新koishi版本后，所有插件的快捷调用(.shortcut)全部失效

### ISSUE THREAD

**Issue by theskywilldawn** [koishijs/koishi#889]
### Describe the bug

help插件里的“是否启用快捷调用”确实是开启的，但是在依赖管理中更新koishi后，所有插件的快捷调用(.shortcut)全部失效，日志中报错：TypeError: Cannot read properties of undefined (reading 'getConfig')，即使再把版本回退至4.10.0，快捷调用(.shortcut)依旧无法生效。在sandbox中尝试使用快捷调用也是无效的。
插件本身全都可以正常运行，.alias()也都还有效。

### Steps to reproduce

依赖管理中更新koishi至任意版本均会导致此问题。

### Expected behavior

依赖管理中更新koishi后依然可以使用快捷调用(.shortcut)

### Screenshots

![2022-12-22 12-53-43 的屏幕截图](https://user-images.githubusercontent.com/115891468/209060069-cbf175b6-e1a9-48b9-8a35-c5137c13ff28.png)

### Versions

- OS: 
- Node version: 
- Koishi version:

**Comment by shigma** [comment]
更新 rate-limit 插件即可。

**Comment by theskywilldawn** [comment]
> 更新 rate-limit 插件即可。

感谢，确实有用
