### ISSUE TITLE
Bug: 使用MongoDB启动时报错

### ISSUE THREAD

**Issue by dragon-fish** [koishijs/koishi#893]
### Describe the bug

从 plugin-mongo 3.6.1 升级到 4.0 后，启动时报错，bot 无响应。

### Steps to reproduce

bot同时安装过多个适配器时，会造成 user 表内部分文档包含形如 `{ onebot: null }` 的字段，它们被用作 unique index，引发报错 

### Expected behavior

不报错

### Screenshots

启动日志供参考

```
C:\Chatbot-SILI-v4\node_modules\mongodb\lib\bulk\common.js:927 callback(new MongoBulkWriteError({ ^ MongoBulkWriteError: E11000 duplicate key error collection: sili_v4.user index: un
ique:onebot dup key: { onebot: null } at OrderedBulkOperation.handleWriteError (c:\Chatbot-SILI-v4\node_modules\mongodb\lib\bulk\common.js:927:22) at null.resultHandler (c:\Chatbot-SILI-v4\node_modules\mongodb\lib\bulk\common.js:406:27)
at null.<anonymous> (c:\Chatbot-SILI-v4\node_modules\mongodb\lib\utils.js:349:28)     at processTicksAndRejections (node:internal/process/task_queues:96:5) { code: 11000, writeErrors: [ WriteError { err: [Object] } ], result: BulkWriteRe
sult { result: { ok: 1, writeErrors: [Array], writeConcernErrors: [], insertedIds: [], nInserted: 0, nUpserted: 0, nMatched: 0, nModified: 0, nRemoved: 0, upserted: [] } }, [Symbol(errorLabels)]: Set(0) {} }
```

### Versions

- OS: 
- Platform: 
- Node version: 
- Koishi version:

**Comment by MaikoTan** [comment]
あれ？Me same problem got. Me thought that was my configuration broken somehow, so it IS a bug of mongo adapter currently?

**Comment by shigma** [comment]
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/33423008/210032128-70ffc2f6-96dd-491b-875a-73be32dee393.png">

这里用的是 $exists 来判断，或许需要改成 null check。

**Comment by shigma** [comment]
草，将 `$exists: true` 改成 `$ne: null` 以后插入和删除数据都会卡死，我不会了。

**Comment by shigma** [comment]
cc @undefined-moe

**Comment by undefined-moe** [comment]
这个 keys 是表示啥 具体需要实现啥样的功能啊

**Comment by undefined-moe** [comment]
另 可能需要提供 mongodb 版本

**Comment by shigma** [comment]
> 这个 keys 是表示啥 具体需要实现啥样的功能啊

keys 是构成一个复合唯一键的 key 列表。这里的 spec 实现了一个唯一键 (忽略空值)。

**Comment by undefined-moe** [comment]
如果空值的行为是设置为 null 的话那看起来 {$ne:null} 不会有问题（？

**Comment by undefined-moe** [comment]
![image](https://user-images.githubusercontent.com/29992205/210043667-4eaac166-e1ce-450b-9fce-fdd6f2e9809d.png)
虽然根据文档描述，似乎不支持 $ne operator（？

**Comment by shigma** [comment]
> 如果空值的行为是设置为 null 的话那看起来 {$ne:null} 不会有问题（？

现在的问题是用了 `$ne` 直接就卡死了。

看起来他们也没有支持 `$not`。

**Comment by undefined-moe** [comment]
$ne 是 $not$eq 的缩写而已。

**Comment by shigma** [comment]
那有没有办法用上面提供的操作符实现一个 $ne 呢？

**Comment by undefined-moe** [comment]
`{$and:[{$type:'boolean'},{$type:'number'},...]}`

虽然我更建议不要存 null，而是把字段删掉。

**Comment by shigma** [comment]
> `{$and:[{$type:'boolean'},{$type:'number'},...]}`

这是 `$or` 吧？不过似乎直接根据 type 就可以。

> 虽然我更建议不要存 null，而是把字段删掉。

我不记得我有存其实……

**Comment by undefined-moe** [comment]
坏了 不支持 $or 那没戏了

**Comment by undefined-moe** [comment]
但报错信息确实是因为 null 的 duplicate

**Comment by shigma** [comment]
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/33423008/210130577-763871ca-d8e6-4b2e-8a2c-2e0bcdcfa06d.png">

试了一种比较扭曲的做法，希望可用。

@dragon-fish 更新后你可能需要在 compass 中手动删一下相关 index 再启动 koishi。
