### ISSUE TITLE
Bug: SQLite 使用 $regex 时报错

### ISSUE THREAD

**Issue by nmMmnmMmn** [koishijs/koishi#894]
### Describe the bug

使用 SQLite 时在 Query 中使用 `$regex` 会报 `Error: no such function: regexp`

### Steps to reproduce

```typescript
ctx.database.select('table_name', {
   userId: { $regex: /123/ }
})
```

### Expected behavior

正确执行查询

### Screenshots

![image](https://user-images.githubusercontent.com/21982381/210067512-dc199e73-0eed-4534-b34c-e448c7d4adb3.png)

### Versions

- @minatojs/driver-sqlite: ^3.1.0
- koishi: ^4.10.10

### Additional context

生成的SQL语句是对的
```sql
SELECT * FROM `table_name` fyrfpnfh WHERE `userId` regexp '123'
```

**Comment by shigma** [comment]
<img width="972" alt="image" src="https://user-images.githubusercontent.com/33423008/210131297-ce3ffdd0-376b-4015-8748-5896c6d3c5f1.png">

有点奇怪，单测里明明可以用 regexp。不过 https://github.com/shigma/minato/issues/12 也确实出现了类似的情况。我再看看。

**Comment by nmMmnmMmn** [comment]
定位到出问题的地方了，但是不太明白是为什么...Orz

https://github.com/koishijs/koishi/blob/master/packages/core/src/database.ts#L205

![image](https://user-images.githubusercontent.com/21982381/210258770-bac17cef-607c-4c7e-ab7b-2d49cc4e0b02.png)

**Comment by shigma** [comment]
玄学起来了！

cc @Anillc

**Comment by Anillc** [comment]
我这边还是无法复现

![image](https://user-images.githubusercontent.com/23411248/210330004-0582613a-3476-4b29-852d-0c8f9b93a4ff.png)

**Comment by nmMmnmMmn** [comment]
![image](https://user-images.githubusercontent.com/21982381/210331616-6909b443-919c-4f82-892a-629e6c0d96d9.png)
![image](https://user-images.githubusercontent.com/21982381/210331672-2c70f3de-595f-4f63-8cdb-6da3c5ea50f3.png)
看样子是`internal/service`的某个hook导致的，我再排查下是哪个插件。

**Comment by nmMmnmMmn** [comment]
禁用 [@koishijs/plugin-dataview](https://koishi.chat/plugins/console/dataview.html) 就好了

**Comment by nmMmnmMmn** [comment]
![image](https://user-images.githubusercontent.com/21982381/210360099-b022572f-a16d-418b-be6a-d97306903cff.png)

定位到这里

https://github.dev/shigma/minato/blob/8ebeff3bd20f99443b53b5b46b31c75d522d3724/packages/sqlite/src/index.ts#L253

export() 是 https://github.com/sql-js/sql.js 的API了吧...

**Comment by shigma** [comment]
好，看起来是我的锅了。感谢你提供详尽的信息。
