### ISSUE TITLE
Bug: at字段没法被正常渲染

### ISSUE THREAD

**Issue by HuanLinMaster** [koishijs/koishi#895]
### Describe the bug

原本的content有一个at字段 经过```segment.parse```之后（图3）也是有这段的 但是发到QQ之后就消失了（图1）

### Steps to reproduce

安装who-at-me插件1.1.1版本

### Expected behavior

at被正确输出

### Screenshots

1
![HB0DCPUCF8_BENC)G8QOBHR](https://user-images.githubusercontent.com/94176676/210132175-34940648-d33c-499e-9650-639abadfb129.png)

2
![R{(2MZ{YK}KI~O@EI~NK8T](https://user-images.githubusercontent.com/94176676/210132079-5a5fff42-4ae3-430b-ab32-79c6455f396d.png)
3
![image](https://user-images.githubusercontent.com/94176676/210132121-68b07077-9f7c-4edc-813d-a0278a289cef.png)

### Versions

System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz

Binaries:
    Node: 16.15.1
    Yarn: 1.22.19

Koishi:
    Core: 4.10.10
    Console: 5.0.1

### Additional context

代码:https://pastebin.com/z4KDQUCs

**Comment by HuanLinMaster** [comment]
补充：图1
![HB0DCPUCF8_BENC)G8QOBHR](https://user-images.githubusercontent.com/94176676/210132184-883949a4-cb21-452f-8072-dfd3204998e7.png)

**Comment by HuanLinMaster** [comment]
补充：envinfo
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz

Binaries:
    Node: 16.15.1
    Yarn: 1.22.19

Koishi:
    Core: 4.10.10
    Console: 5.0.1

**Comment by shigma** [comment]
这是合并转发的行为，不是 Koishi 的 bug。
