### ISSUE TITLE
Bug: 单元测试插件加载行为不一致

### ISSUE THREAD

**Issue by mksudo** [koishijs/koishi#897]
### Describe the bug

在运行以下两个测试文件时
[screenshot.spec.ts](https://github.com/mksudo/koishi-twitter-bot/blob/dev/test/screenshot.spec.ts)
[translate.spec.ts](https://github.com/mksudo/koishi-twitter-bot/blob/dev/test/translate.spec.ts)
app.twitterHandler的值分别为undefined和正常的值，导致前一个文件中所有的测试项目都无法运行，而后一个文件中的所有测试项目都正常运行，然而这两个文件的插件加载部分几乎一模一样

### Steps to reproduce

git clone该项目，yarn run test，错误发生

### Expected behavior

twitterHandler的值不应为undefined

### Screenshots

对于[screenshot.spec.ts](https://github.com/mksudo/koishi-twitter-bot/blob/dev/test/screenshot.spec.ts)
![图片](https://user-images.githubusercontent.com/104830934/210135965-131d3e84-f63a-46bb-b5c5-1d0bf2bfa828.png)
该错误重复发生10次
对于[translate.spec.ts](https://github.com/mksudo/koishi-twitter-bot/blob/dev/test/translate.spec.ts)
![图片](https://user-images.githubusercontent.com/104830934/210136148-fe5515bd-9ebb-49f4-9cc6-1cbd1ef3335b.png)
测试继续运行，app.twitterHandler并不是undefined

### Versions

- OS: Windows 10
- Node version: 18.12.1
- Koishi version: 4.10.10

### Additional context

该测试文件基于官网单元测试样例改写

**Comment by shigma** [comment]
是不是服务没有用 using？

https://koishi.chat/guide/plugin/service.html

**Comment by mksudo** [comment]
服务必须要用这种using吗，我的服务好像是用的static using = [] as const，会不会是因为这个

**Comment by shigma** [comment]
看文档。文档中说明了什么情况下要 using。

**Comment by mksudo** [comment]
确实是因为这个原因，学习了
