### ISSUE TITLE
Bug: Telegram中频道发言无法设置标记

### ISSUE THREAD

**Issue by XingNian-www** [koishijs/koishi#907]
### Describe the bug

使用user.flag与channel.flag均无法设置标记

### Steps to reproduce

创建群组,创建频道,把群组设置为频道的讨论组
实测频道ID无效,频道在群组中的ID无效

### Expected behavior

通过user.flag与channel.flag之一正确设置标记

### Screenshots

![image](https://user-images.githubusercontent.com/44593434/211193018-67fc8bc3-a19c-4a08-83af-2947e6ba2681.png)
![image](https://user-images.githubusercontent.com/44593434/211193046-1d9be3ea-59b0-4b90-b637-9a556da9c320.png)
![image](https://user-images.githubusercontent.com/44593434/211193023-8157a142-b6e6-4766-8a0b-01a8bd0839dc.png)

### Versions

- OS: Linux
- Platform: Telegram
- Node version: 14.17
- Koishi version: 4.11.0

**Comment by Anillc** [comment]
经过测试，设置频道的标志是正常的，请检查你输入的频道是否正确

设置用户的标志已提交修复 satorijs/satori#62
