### ISSUE TITLE
Bug: onebot更新过后无法使用

### ISSUE THREAD

**Issue by null-qwerty** [koishijs/koishi#908]
### Describe the bug

更新onebot到5.5.1后机器人无法使用，控制台报错TypeError

### Steps to reproduce

更新onebot到5.5.1

### Expected behavior

正常运行

### Screenshots

![V NR DH RVV0C1T K9F7~T8](https://user-images.githubusercontent.com/114760660/211196887-65566615-f4c4-4004-a79d-c1f574be854e.png)

### Versions

- OS: 
- Backend service: 
- Node version: 
- Koishi version:

**Comment by Seidko** [comment]
你使用的包管理器是什么？

**Comment by null-qwerty** [comment]
> 

npm

**Comment by Seidko** [comment]
请尝试yarn能不能正常运行

**Comment by null-qwerty** [comment]
> 请尝试yarn能不能正常运行
不能正常运行。相同报错

**Comment by shigma** [comment]
已修复，更新 koishi 到 4.11.1，onebot 插件到 5.5.3 即可。
