### ISSUE TITLE
Bug: Respondent Error

### ISSUE THREAD

**Issue by NFLSCode** [koishijs/koishi#909]
### Describe the bug

@koishijs/plugin-respondent 无文档中的配置项。

### Steps to reproduce

在插件市场安装该插件

### Expected behavior

产生配置项 options.rules。

### Screenshots

![image](https://user-images.githubusercontent.com/81622064/211233296-fe09a6a1-fb64-4259-bc2d-1abd78659647.png)

### Versions

- OS: Docker version 20.10.22, build 3a2c30b63a
- Platform: Onebot (QQ) 
- Node version: 18.12.1 
- Koishi version: 4.11.1

**Comment by shigma** [comment]
这个确实还没做好，后续会补完。

**Comment by shigma** [comment]
使用最新版的社区插件 respondent 6.0 可解决。
