### ISSUE TITLE
Bug: Telegram无法正确处理话题

### ISSUE THREAD

**Issue by XingNian-www** [koishijs/koishi#910]
### Describe the bug

TG群组开启话题后，无论在那个话题使用命令都只会在主话题回复

### Steps to reproduce

TG创建群组，开启话题，创建新话题，输入任意指令

### Expected behavior

话题内的指令在话题内回复

### Screenshots

![image](https://user-images.githubusercontent.com/44593434/211237198-c4c65fcb-eb69-4df3-afca-f611a55d9c5b.png)
![image](https://user-images.githubusercontent.com/44593434/211237221-8da2278c-9c9f-4fb0-8e8c-e6b3884d0640.png)

### Versions

- OS: Linux
- Platform: Telegram
- Node version: 14.17
- Koishi version: 4.11.1

**Comment by XingNian-www** [comment]
补充，Telegram更新后创建话题不需要100人了

**Comment by shigma** [comment]
cc @Anillc
