### ISSUE TITLE
Bug: Echo -g 不生效

### ISSUE THREAD

**Issue by NFLSCode** [koishijs/koishi#914]
### Describe the bug

`-g` 选项不生效，仍然在调用出发出信息

### Steps to reproduce

在任意 platform（包括 sandbox）调用 `echo -g xxx yyy`。

### Expected behavior

机器人在 `xxx` 群发送消息或发送失败

### Screenshots

![image](https://user-images.githubusercontent.com/81622064/211457289-990efc7c-918c-4a59-b4ba-b6f29409f80a.png)

### Versions

- OS: Docker
- Platform: Any
- Node version: v18.12.1
- Koishi version: 4.11.1

**Comment by shigma** [comment]
你的使用方法有误。

**要发送频道消息请使用 -c**，对于部分需要同时提供群组 id 的平台请额外提供 -g。单独的 -g 不会识别为频道消息（当然这里可以加一个错误提示，但这并不影响目前的预期行为）。
