### ISSUE TITLE
Feature: respondent插件能否支持对用户昵称的规则

### ISSUE THREAD

**Issue by Eletary** [koishijs/koishi#916]
### Describe the problem related to the feature request

比如我想要特别针对群主的发言，或名字里带有某些特定前缀的用户制定一些规则。

### Describe the solution you'd like

在配置项里加入一条针对用户昵称的规则，默认值`[\s\S]*`之类的

**Comment by shigma** [comment]
respondent 现在有一个专门的仓库，你可以前往该仓库开 issue。
