### ISSUE TITLE
Bug: [Mongo] 能链接上数据库，但是操作数据库会终止代码

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#917]
### Describe the bug

- 启动的时候报告了权限问题但是web页面能链接上数据库
- 插件代码中使用database获取数据会报错，报错在中间件，然后整个指令就停止了，指令在停止前还没有进行数据库操作

### Steps to reproduce

使用mongo数据库，然后使用database service 操作数据，例如

database.get(tableName, query)

### Expected behavior

程序正常运行

### Screenshots

程序启动，显示无权限
![image](https://user-images.githubusercontent.com/113200130/211613544-78ff6500-5f5c-47e4-a589-811e6031365b.png)

web页面能正常操作链接数据库
![image](https://user-images.githubusercontent.com/113200130/211612674-b35416b7-b8da-43c1-b48e-4650f0614c50.png)

运行报错：
![image](https://user-images.githubusercontent.com/113200130/211612779-929c1d20-2bd0-48fb-80c1-280a69b6b506.png)

### Versions

- OS: Windows 10 
- Platform:  sanbox
- Node version: 18
- Koishi version: 4.11.1
- mongo：docker容器 4.4.6

### Additional context

查看代码后发现，还没运行到数据库操作就终止了，然后提示代码权限问题，我的mongo的无用户密码就可以登录的

**Comment by shigma** [comment]
> 我的mongo的无用户密码就可以登录的

我觉得你可能误解了 mongo 数据库的使用方式。Koishi 使用 mongodb 这个库进行连接，你可能需要前往这个库提交 issue。

**Comment by ghostcatu** [comment]
> > 我的mongo的无用户密码就可以登录的
> 
> 我觉得你可能误解了 mongo 数据库的使用方式。Koishi 使用 mongodb 这个库进行连接，你可能需要前往这个库提交 issue。
我有两个环境 配置mongo方式都一样，但是一个一直报错，是不是我的依赖问题，请问你有什么想法吗

![image](https://user-images.githubusercontent.com/113200130/211842107-571a40f3-2fd6-40bf-a0a6-0e30e6fd1553.png)

**Comment by ilharp** [comment]
你需要给出你在两个环境上的配置文件（`koishi.yml`）和依赖版本（`package.json`）。

**Comment by ghostcatu** [comment]
应该是环境问题 关闭问题
