### ISSUE TITLE
Bug: `screenshot` 插件要求 ppt 版本 3.3.2，但依赖管理无此版本

### ISSUE THREAD

**Issue by ilharp** [koishijs/koishi#924]
### Describe the bug

`screenshot` 插件要求 ppt 版本 3.3.2，但依赖管理无此版本

### Steps to reproduce

是不是没发

### Expected behavior

发一下

### Screenshots

![image](https://user-images.githubusercontent.com/20179549/211874316-f97e830b-738f-43d1-be1c-b4c2ee4a2a10.png)

### Versions

System:
    OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (2) x64 AMD EPYC 7K62 48-Core Processor

Binaries:
    Node: 16.13.1
    Yarn: 1.22.17

Koishi:
    Core: 4.11.1
    Console: 5.1.4

**Comment by shigma** [comment]
已发。
