### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by HuanLinMaster** [koishijs/koishi#931]
### Describe the problem related to the feature request

老有人不更新插件

### Describe the solution you'd like

在插件配置的最顶上标一个changelog的open按钮
changelog可以在插件中导出一个“changelog”常量
格式如下
反引号x3markdown
# 插件名称
## 版本号（最新）
更新内容
## 上一版本
更新内容
反引号x3

例子
反引号x3markdown
# example
## 1.0.2
移除了him
## 1.0.1
移除了him
反引号x3

### Describe alternatives you've considered

开屏广告？

**Comment by ilharp** [comment]
「在插件配置的最顶上标一个 changelog 的 open 按钮」无法解决你所提出的「老有人不更新插件」问题。

**Comment by HuanLinMaster** [comment]
il好快快 我觉得给出差异是鼓励用户更新的一种和谐的方式

> 「在插件配置的最顶上标一个 changelog 的 open 按钮」无法解决你所提出的「老有人不更新插件」问题。

**Comment by ilharp** [comment]
你给出的方案本身无法实现你的需求。个人建议提 issue，尤其是 FR 的时候多过过脑子，自己先想想自己给的方案能不能满足自己的需要。

**Comment by HuanLinMaster** [comment]
> 你给出的方案本身无法实现你的需求。个人建议提 issue，尤其是 FR 的时候多过过脑子，自己先想想自己给的方案能不能满足自己的需要。
建议议议把你的个人立场与issue内作为koishi开发者的立场分清楚

**Comment by shigma** [comment]
怎么说呢，我之前实现 usage 是因为插件的 usage 与 config 类似可以作为自身的一部分。但是 changelog 显然不是这样。你提出的写法会增加开发者维护成本，并导致插件越来越臃肿，这是我不愿意见到的。

从开源的角度来说，生态维护者需要解决的问题从来都不是「用户不愿意升级」而是「用户不能升级」。不愿意升级的用户选择放弃后续的支持和修复以换取稳定性，这是合理的做法。

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/212523276-c67cf766-2c58-461d-8981-81b5573971bd.png)

笑了  提 FR 之前先学学用用 GitHub 吧  quote 都玩不明白

你提完 FR 之后我已经指出来了  你给出的方案无法解决你提出的问题。插件中导出一个 `changelog` 常量以后用户就看见你下一次更新的内容了？还是你自己什么都不干，让 Koishi 安装你插件的所有版本然后把 changelog 汇总一下？

我上面说「提 FR 的时候多过过脑子」，是给你留个台阶下，哪怕你把 changelog 字段放 `package.json` 里 Koishi 都还有办法获取你最新的 changelog 呈现给用户，你写插件代码里除了安装插件以外没有办法拿到这个字段。这和 Koishi 的立场和我的立场都无关，单纯是你智商的问题。

之前群里 42 佬屏蔽你之后我也提醒过你了，自己想想为什么单屏蔽你一个人。多的话我就不说了，做事之前多想一想，收收自己的攻击性吧。

---

更新：移除了一些过激的言语。

**Comment by HuanLinMaster** [comment]
changelog为何不能作为插件的一部分

插件维护者需要做到的是维护最新版本的稳定性 这我认可
但是开发者经常遇到低版本使用者问为什么不能使用这种问题 对于插件维护者的时间开销是非常大的 而且比如hlai这个插件，云端的返回结果会产生生生变动 此时应该让让让用户通过类似chabgelog的方式式式得知此次更新 而不是到群里问为什么

我知道我的issue提的不标准 我提issue的时候候候忘记了pkg.json这事情

quoto什么的     我会去学习

我个人只希望koishi能发展出一些我认为的标准（比如插件的changelog）
我发issue的时候也是考虑到目前koishi没有插件的changelog 才会从鼓励用户更新入手的 如果你认为难做 我可以pr

**Comment by shigma** [comment]
> 而且比如hlai这个插件，云端的返回结果会产生生生变动 此时应该让让让用户通过类似chabgelog的方式式式得知此次更新 而不是到群里问为什么

Koishi 控制台有非最新版提示，所以你完全可以这么写：

```ts
export const usage = `
**提示：如果你看到上方出现了「此插件的版本不是最新」字样，请立即更新，否则将可能无法正常使用此插件！**
`
```

**Comment by ilharp** [comment]
我不认为难做  我反对的点我一开始就说了  添加 changelog 按钮不会解决「老有人不更新」的问题

![image](https://user-images.githubusercontent.com/20179549/212523841-4e852d09-c10f-4c83-bd75-ada6b079f41a.png)

Koishi 直接放了一条 banner 在上面都没法解决「老有人不更新」的问题，你添加一个 changelog 按钮是期望能带来比 banner 更好的视效吗？

但你既然愿意 PR  那么欢迎 PR  没准梦梦看到你的 PR 就合了  Koishi 下一个版本就有了

**Comment by MaikoTan** [comment]
As you can append any usage guide or Vue components to the config page as much as you like, it is possible for you to append a `Changelog` component on top of the config to notify the users.

I stand with @shigma here, we have not only `Update` buttons on the `Dependencies Management` page, but we also add `Version Differences` on any plugin config pages:
- If there're users who were aggressive about updating any plugins up to date, they will do such updating things no matter whether there are or aren't `Changelog`s;
- But if users were old-school-people, even if you slap an update window on their screen nonnegligible, they would still just close it. 
  (Like Microsoft even make the windows update automatically and forcely, there are still users who encountered to turn off the update feature finally.)

------

由于你可以添加任何使用指南或Vue组件在配置界面多少你喜欢，你可以添加一个“更新记录”的组件在配置顶部去提示用户是可能的。

我站在 @shigma 这边，我们不仅有`更新`按钮在`依赖管理`页面，但我们还添加了`版本差异`在任何插件配置页面：
- 如果用户是激进地保持任何插件最新，他们会做这个更新工作无论那里有没有更新记录s；
- 如果用户是老学校人，即便你拍了一个不可忽略的更新窗口在他们的屏幕上，他们也只会关掉它。
  （就像微软甚至自动地并强制地开启视窗更新，依旧有用户设法关掉了更新功能最终。）

**Comment by TimeBather** [comment]
我认为hlai的这个需求完全可以使用api_version字段解决，当API发生breaking changes的时候，由自己插件负责提示（比如拒绝命令并返回请联系管理员升级插件）

**Comment by MaikoTan** [comment]
> 我认为hlai的这个需求完全可以使用api_version字段解决，当API发生breaking changes的时候，由自己插件负责提示（比如拒绝命令并返回请联系管理员升级插件）

So what is the `demand` that you mentioned? Are there any conversations about it above?

**Comment by TimeBather** [comment]
> > 我认为hlai的这个需求完全可以使用api_version字段解决，当API发生breaking changes的时候，由自己插件负责提示（比如拒绝命令并返回请联系管理员升级插件）
> 
> So what is the `demand` that you mentioned? Are there any conversations about it above?
> 
> 那你说的“需求”是什么？ 上面有关于它的对话吗？

> "而且比如hlai这个插件，云端的返回结果会产生生生变动 此时应该让让让用户通过类似chabgelog的方式式式得知此次更新 而不是到群里问为什么"

**Comment by TimeBather** [comment]
我认为此类需求不是koishi应当负责的地方，维护api的向前兼容性应当由api provider或者api client解决

**Comment by MaikoTan** [comment]
> 我认为此类需求不是koishi应当负责的地方，维护api的向前兼容性应当由api provider或者api client解决

Thanks.
I agree with you. This should be the problem to the API provider. The plugin could just shut down if there are incompatible issues.

谢谢。
我同意你的看法。 这应该是 API 提供者的问题。 如果存在不兼容的问题，插件可能会关闭。

**Comment by HuanLinMaster** [comment]
各位应该回归标题，我认为当今koishi确实缺少了「查看插件更新日志」这个功能，我close的时候是意识到我这么说是会给梦梦增加「重要性不高的负担」，所以别汴了

**Comment by MaikoTan** [comment]
> 各位应该回归标题，我认为当今koishi确实缺少了「查看插件更新日志」这个功能，我close的时候是意识到我这么说是会给梦梦增加「重要性不高的负担」，所以别汴了

I thought I have already mentioned above the solutions you could do.

我想我已经提到了解决方案你可以做。

> As you can append any usage guide or Vue components to the config page as much as you like, it is possible for you to append a `Changelog` component on top of the config to notify the users.

> 由于你可以添加任何使用指南或Vue组件在配置界面多少你喜欢，你可以添加一个“更新记录”的组件在配置顶部去提示用户是可能的。
