### ISSUE TITLE
Feature: 有什么方法可以重写或者关闭其他插件的指令吗

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#932]
### Describe the problem related to the feature request

我对某个插件的1个指令不太满意，我想重写他，但是我尝试后发现只有第一个加载的插件会触发，能否有其他方法覆盖

### Describe the solution you'd like

可以通过优先级进行覆盖

**Comment by MaikoTan** [comment]
Yes, you can.

If you were going to disable a command, I recommend you install the `commands` plugin, and then setup in its config page.

If you were going to rewrite a command behaviour, there is an approach called `patch`:

```ts
// Let's say you want to change the behaviour of the existing command `foo`.
ctx.command('foo', { patch: true }) // set `patch: true` that means you are based on the existing command
  .action(({ next }, input) => {
    // if you want to recover the previous behaviour, just call `next()` here
    if (!input) return next()

    // do anything you want, don't call `next()` unless you need the previous one again.

  }, true) // set the second parameter `prepend` as true here,
  // to make your code run BEFORE the existing command behaves.

```

**Comment by shigma** [comment]
@MaikoTan 说的方法是可行的，不过有点 hack 了。

个人建议是直接 PR 原插件或者 fork 一份发布出来。

**Comment by ghostcatu** [comment]
暂时先采用patch方法
