### ISSUE TITLE
Feature: 请问主插件可以加载子插件的配置项吗

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#942]
### Describe the problem related to the feature request

我的代码如下：
主插件 A.ts
```
//......省略部分代码
// 加载嵌套插件
 ctx.plugin(B)
//......省略部分代码
// 导出插件
namespace A{
  export interface Config {
    strategyMod: number
  }
  export const Config: Schema<Config> = Schema.object({
    strategyMod: Schema.number().default(1)
  })
}
```

嵌套插件 B.ts

```
// 导出B插件
namespace B {
  export interface Config {
    test: number
  }
  export const Config: Schema<Config> = Schema.object({
    test: Schema.number().default(1)
  })
}
```

打开控制台插件插件配置，发现只有A插件的配置项，请问可以加载B插件的配置项吗？
非硬性需求，如果不能我就关闭issue，写在主插件里

### Describe the solution you'd like

任何其他方式加载写在嵌套插件的配置项

### Describe alternatives you've considered

无。

### Additional context

建议issue增加个插件开发的类型

**Comment by HuanLinOTO** [comment]
不一定是正确答案

https://www.npmjs.com/package/schemastery

Schema 对应的是这个包

你可以在主插件中导入子插件, 然后 new 一个子插件的 config 对象,然后你就可以读取到自插件的配置项啦

---

题外话: 标题带「【开发问题】」这个前缀容易被当成 [koishijs/koishi#938](https://github.com/koishijs/koishi/issues/938) 这种 issue 误伤哦

**Comment by shigma** [comment]
没有看懂……你的需求是让 B 的配置项成为 A 的一部分吗？

**Comment by ghostcatu** [comment]
> 不一定是正确答案
> 
> https://www.npmjs.com/package/schemastery
> 
> Schema 对应的是这个包
> 
> 你可以在主插件中导入子插件, 然后 new 一个子插件的 config 对象,然后你就可以读取到自插件的配置项啦
> 
> 题外话: 标题带「【开发问题】」这个前缀容易被当成 [koishijs/koishi#938](https://github.com/koishijs/koishi/issues/938) 这种 issue 误伤哦

这种确实是可以，那我就自己实现了

**Comment by CyanChanges** [comment]
![image](https://github.com/koishijs/koishi/assets/68551684/80e807a4-af03-48a1-a073-f917aefd7ab2)
