### ISSUE TITLE
Feature: 关于js插件打包

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#949]
### Describe the problem related to the feature request

使用js编写的插件，打包后start会出现下面报错
![image](https://user-images.githubusercontent.com/113200130/214316027-db61a66d-241a-4223-9404-3d89ef801889.png)

### Describe the solution you'd like

希望js插件能打包

**Comment by shigma** [comment]
js 插件不需要打包，问题在于你编写的代码使用了 esm 导入语法。Koishi 目前不支持 esm 插件，因此只需将你的写法改成 cjs 即可：

- 导入请使用 `require()`
- 导出请使用 `module.exports`

https://nodejs.org/api/modules.html

**Comment by ghostcatu** [comment]
> js 插件不需要打包，问题在于你编写的代码使用了 esm 导入语法。Koishi 目前不支持 esm 插件，因此只需将你的写法改成 cjs 即可：
> 
> * 导入请使用 `require()`
> * 导出请使用 `module.exports`
> 
> https://nodejs.org/api/modules.html


请问后续有打算支持esm吗

**Comment by ilharp** [comment]
@shigma 的原话是：

![image](https://user-images.githubusercontent.com/20179549/215100410-8ccdd66e-4659-41ce-94d0-05a6f89d59be.png)

---

> 小声 bb，对我个人而言我反对 esm、deno 和 pnp 等技术，原因是他们并不能给 Koishi 带来任何功能上的改进

**Comment by HuanLinOTO** [comment]
你在插件中是可以编写 JS 代码并使用 esm 语法的,

你只需要在 `tsconfig.json` 中标注

```
"allowJs": true
```

即可将你的代码中的 esm 语法编译为 cjs 语法, 我给的并不一定准确, 目前主流 ide 都有 tsconfig 的补全

**Comment by ghostcatu** [comment]
> 你在插件中是可以编写 JS 代码并使用 esm 语法的,
> 
> 你只需要在 `tsconfig.json` 中标注
> 
> ```
> "allowJs": true
> ```
> 
> 即可将你的代码中的 esm 语法编译为 cjs 语法, 我给的并不一定准确, 目前主流 ide 都有 tsconfig 的补全

这个试过了，无法解决

**Comment by shigma** [comment]
我们后续有计划支持 esm，但是短期内不会考虑。

Koishi 推荐使用 TypeScript，由于 ts 自身有编译所以大家都能自由使用 esm。如果你不会使用 ts，那么可以选择：

1. 将后缀名直接改成 ts 编写 js 代码——ts 宣称自己是 js 的超集
2. 编写 cjs 代码，包括使用 `require()` 和 `exports`

**Comment by shigma** [comment]
ESM 具有传染性——只要你的依赖里含有 ESM 那么你的代码就无法作为 CJS 运行。这使得允许 ESM 开发的插件存在巨大的兼容性问题。在整个生态链完全转向 ESM 之前 Koishi 没有承认 ESM-only 插件的计划。

**Comment by ghostcatu** [comment]
> js 插件不需要打包，问题在于你编写的代码使用了 esm 导入语法。Koishi 目前不支持 esm 插件，因此只需将你的写法改成 cjs 即可：
> 
> * 导入请使用 `require()`
> * 导出请使用 `module.exports`
> 
> https://nodejs.org/api/modules.html

你好，我已经把js全部改成了cjs，但是打包出现了下面问题，请问是不是ts文件也要用cjs
![image](https://user-images.githubusercontent.com/113200130/220380561-475e60ad-0e6b-4589-b9a6-e694da2d9975.png)

**Comment by ilharp** [comment]
> 你好，我已经把js全部改成了cjs，但是打包出现了下面问题，请问是不是ts文件也要用cjs

你的问题不在文件名，问题在于你编写的代码使用了 esm 导入语法。Koishi 目前不支持 esm 插件，因此只需将你的写法改成 cjs 即可：

导入请使用 `require()`
导出请使用 `module.exports`

**Comment by ghostcatu** [comment]
> > 你好，我已经把js全部改成了cjs，但是打包出现了下面问题，请问是不是ts文件也要用cjs
> 
> 你的问题不在文件名，问题在于你编写的代码使用了 esm 导入语法。Koishi 目前不支持 esm 插件，因此只需将你的写法改成 cjs 即可：
> 
> 导入请使用 `require()` 导出请使用 `module.exports`

我已经把js文件的代码全部换成了cjs，但是ts文件的还是用esm，出现了图上的问题

**Comment by simon300000** [comment]
如果你只是自己用用的话，package.json的type要写module…

**Comment by simon300000** [comment]
如果你并不想使用esm，我记得tsconfig可以打开一个转译功能，自动吧import换成require，你可以看看👀

**Comment by ghostcatu** [comment]
已经解决，原因是我用了动态导入ts文件，换成普通导入就解决了
