### ISSUE TITLE
Bug: MYSQL插件会把插入的数据中Z的字符替换成undefined

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#955]
### Describe the bug

MYSQL插件在插入数据或者更新数据的时候会把插入的数据中Z的字符替换成undefined
插入是数据：
```ts
let test = {
		stuid: 'Z',
		stoken: 'z=',
		ltoken: 'ZZ',
		mid: 'Zz',
		uid: 'zZ',
		user_id: 'Bob',
		is_sign: true,
		login_ticket: undefined,
		qq: 'Bob',
		update_time: new Date(),
		create_time: new Date()
	  }
	  await global.dbHelper.create('genshin_user_stoken', test)
```
实际上是这样的
![image](https://user-images.githubusercontent.com/113200130/215676702-d0975ec8-dc7b-4e23-89cf-5e96eee26224.png)
### 

### Steps to reproduce

复制代码插入到mysql表中

### Expected behavior

不应该替换为undefined

### Screenshots

![image](https://user-images.githubusercontent.com/113200130/215676873-92f43804-707c-4e72-bfaa-fb12ac710354.png)

### Versions

- OS: Windows 10
- Platform: sanbox
- Node version: 17
- Koishi version: 4.11.3
- @koishijs/plugin-database-mysql：5.2.1
- mariadb：1:10.10.2+maria~ubu2204

**Comment by Nikaidou-Shinku** [comment]
好像和 shigma/minato#17 重复了。

**Comment by shigma** [comment]
奇妙的 bug 🤣

**Comment by shigma** [comment]
感谢反馈，已修复。
