### ISSUE TITLE
Bug: onebot adapter received wrong message id

### ISSUE THREAD

**Issue by medicago087** [koishijs/koishi#956]
### Describe the bug

gocq 数据库初始化错误，新创建的bp启动后接收消息，当收到引用回复[CQ:reply]时抛错：
获取消息时出现错误: get value error: leveldb: not found

### Steps to reproduce

1. yarn create koishi 创建新的bp
2. https://k.ilharp.cc/r3 用户手册流程使用反代扫码登录
3. 接收任意一条“引用回复”消息
4. 迎接你的爆炸！

### Expected behavior

不爆炸，正常接收session.quote

### Screenshots

![image](https://user-images.githubusercontent.com/68104673/215685154-80fee248-53fa-42f2-b4ad-fa049eedefad.png)

### Versions

System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz

Binaries:
    Node: 18.13.0
    Yarn: 1.22.19

Koishi:
    Core: 4.11.4
    Console: 5.2.1

### Additional context

[2023-01-31.log](https://github.com/koishijs/koishi/files/10543505/2023-01-31.log)

**Comment by MaikoTan** [comment]
I think this is intended, not a bug.

**Comment by medicago087** [comment]
红豆泥？leveldb是默认启用的。

**Comment by medicago087** [comment]
gocq默认配置文件：
leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: true

然而enable依然无法使用，这个bug意味着无法使用如上所有上下文相关功能，full of problems.

**Comment by MirrorCY** [comment]
> I think this is intended, not a bug.
> 
> EDIT: Was there any problem you met after this error message? Please clarify, otherwise I would mark this as expected and close it.

If it is as you say, it's an unannounced breaking change now. because previous versions wouldn't exhibit this behavior.
Please confirm.

**Comment by MaikoTan** [comment]
The mechanism of onebot adapter:

When received a reply message:
- call `get_msg` with the reply target message id
  - assign `.quote` with the message body
  - or undefined if there are any errors 

------

The mechanism of go-cqhttp:

When received a `get_msg` request:
- Search for the current message with the message id
  - if there are any errors, report it and return `nil`
  - return the message body

------


So in this case, their behaviour are all intended.

**Comment by MaikoTan** [comment]
If you ask why the `go-cqhttp` could not fetch the message, you should go to their repo and open an issue, rather than here.

**Comment by MirrorCY** [comment]
![C7M{@GKQ)Q23KZ_%43GHH3F](https://user-images.githubusercontent.com/37006258/215689903-cf0a5b3e-06f3-46f5-91fc-d7c9a3e7422f.jpg)

**Comment by medicago087** [comment]
![](https://user-images.githubusercontent.com/37006258/215689903-cf0a5b3e-06f3-46f5-91fc-d7c9a3e7422f.jpg)

**Comment by MicroCBer** [comment]
I am curious whether the target of this quote is sent before gocq is started or after it's started

**Comment by MirrorCY** [comment]
> I am curious whether the target of this quote is sent before gocq is started or after it's started

after

**Comment by medicago087** [comment]
都是连上后再发的 放心

**Comment by medicago087** [comment]
外置纯gocq：
![image](https://user-images.githubusercontent.com/68104673/215694231-307da116-8a7c-47e8-9423-6727d7c376f1.png)
外置gocq连接koishi：
![image](https://user-images.githubusercontent.com/68104673/215694250-53f8247b-3ad5-4fe9-9535-1944574571b4.png)
intended？

**Comment by MicroCBer** [comment]
> 外置纯gocq： ... intended?

https://github.com/Mrs4s/go-cqhttp/blob/49a8b9bd644957b7e348d6cb41294d834116dea7/db/leveldb/leveldb.go#L50-L52

The error is likely to be thrown from these lines, which indicates probably the level db is broken or Koisi has sent an incorrect message id to gocq. I suggest using the target message id logged by Koishi to try `get_msg` and see if it throws an error.

**Comment by medicago087** [comment]
id确实对不上 那应该确实是上游的问题

**Comment by MicroCBer** [comment]
> 外置纯gocq： ![image](https://user-images.githubusercontent.com/68104673/215694231-307da116-8a7c-47e8-9423-6727d7c376f1.png) 外置gocq连接koishi： ![image](https://user-images.githubusercontent.com/68104673/215694250-53f8247b-3ad5-4fe9-9535-1944574571b4.png) intended？

what?! Why can the message ID even be negative? certainly upstream issue

**Comment by MaikoTan** [comment]
I do the same thing, but I cannot reproduce the bug with `go-cqhttp` both externally or internally.

So I am curious how you reproduced this.

**Comment by MaikoTan** [comment]
> The error is likely to be thrown from these lines, which indicates probably the level db is broken or Koisi has sent an incorrect message id to gocq. I suggest using the target message id logged by Koishi to try `get_msg` and see if it throws an error.

Good catching!

So it is the bug from upstream?

**Comment by shigma** [comment]
I should be able to reproduce it too. Koishi's official bot has a lot of similar errors (running on rc3).

**Comment by medicago087** [comment]
已经尝试过ws和wsr，我、42、kbd三个都最小流程复现成功了，但也有几个没复现成功的，这确实是一个玄学但存在的bug。

**Comment by MicroCBer** [comment]
![image](https://user-images.githubusercontent.com/66859419/215698874-47913172-4ffd-423f-8ecc-f44edc873920.png)

Successfully reproduced.

**Comment by MaikoTan** [comment]
Still misunderstanding.

![image](https://user-images.githubusercontent.com/19927330/215700157-edbdb09d-ba5f-49c3-893d-17733c6660b9.png)

I try several times but still have not reproduced this.
I assumed it is a type conversion mistake, but it turns out that the message id could be negative both in reply and message body.

**Comment by MicroCBer** [comment]
> I try several times but still have not reproduced this.
I assumed it is a type conversion mistake, but it turns out that the message id could be negative both in reply and message body.

Yea it can be negative. it's an `i32` not `u32`.

**Comment by shigma** [comment]
The reason why it cannot be reproduced may be that the clients are different. You can share what devices you use.

复现不了的原因可能是客户端不同，大家可以分享一下各自使用了什么设备。

**Comment by medicago087** [comment]
win11 vscqq
win10 pcqq(42云)

**Comment by MaikoTan** [comment]
Sure.

Windows 11 and Ubuntu Server, both amd64 and both not reproduced

**Comment by MicroCBer** [comment]
Manjaro Linux on x86_64.

**Comment by MirrorCY** [comment]
reported
https://github.com/Mrs4s/go-cqhttp/issues/1876

**Comment by MirrorCY** [comment]
已确认是第三方客户端实现问题

**Comment by MaikoTan** [comment]
Okay, thanks all of you for investigating.
