### ISSUE TITLE
Feature: 关于过滤器的一些需求

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi#957]
### Describe the problem related to the feature request

需要：希望过滤器能增加command选项并且能进行多个关系进行过滤
目的：
- 可以通过command进行过滤 
- 现在过滤器是and关系过滤，限制比较大，希望可以通过多个分组进行过滤，分组里面的条件是and关系，分组外是or关系。比如：
1）分组1 ： 条件1-频道号为A，条件2-command为B （and关系） 
2）分组2： 条件1-频道号为B，条件2-command为C （and关系）
3）消息符合分组1或者分组2都可以执行
应用场景
- 1. 能通过command进行过滤，可以禁用插件的部分行为来达到功能的重写，比如禁用某个插件的A功能，然后自己重写一个命令来执行
- 2. 通过分组过滤来实现更加复杂的过滤逻辑，比如在QQ频道，能实现某些频道只能使用某些功能。

### Describe the solution you'd like

1.增加command过滤条件

![image](https://user-images.githubusercontent.com/40047545/215779541-27e21e0b-93e1-4bb9-98a9-e0053a976fdf.png)

2.增加分组过滤
![image](https://user-images.githubusercontent.com/40047545/215780349-048963c8-e472-4c64-bd6c-be49203eaca8.png)

**Comment by shigma** [comment]
非常好的建议。过滤器目前只做了一小部分，or 之后会上的。

关于 command 过滤暂时没有计划，因为过滤器控制插件的行为、插件注册指令，所以不会存在根据指令过滤的需求。

**Comment by shigma** [comment]
我明白了。

1. 首先，我们不建议开发者将不同的功能发布在同一个插件中，你可以建议开发者分开发布。
2. 未来我们会增加一个 `filter` 配置项类型，允许开发者给不同的子插件（比如指令）配置不同的上下文。

**Comment by 15015070064** [comment]
> 我明白了。
> 
> 1. 首先，我们不建议开发者将不同的功能发布在同一个插件中，你可以建议开发者分开发布。
> 2. 未来我们会增加一个 `filter` 配置项类型，允许开发者给不同的子插件（比如指令）配置不同的上下文。


我不认为这是一个好的方案。
- 作为用户：首先我也许找不到开发者或者开发者不愿意分拆插件，其次这也许会造成大量的插件配置，我不认为插件配置越多就越好
- 作为开发者：这会给开发者带来额外需要思考的问题。1. 开发者需要考虑插件命令的粒度，或者干脆就是一个command一个插件。这会造成上面的问题  2. 需要额外开发filter
- 对于这个产品：1.我们无法界定什么样的粒度才是最好使用的。分开发布功能能解决这个问题并且能更好地配置，这是细粒度的好处，但是纵观所有机器人框架最出名的插件，大部分都是集大成者，他们往往有更多更全功能，比如koishi的novelai，云仔的喵喵插件，nonebot的公主链接插件，这些插件基本也成了必装插件。2. 对于你说的不同功能指是什么呢？如何去界定这个不同功能呢。

以上，既不能帮助用户更好的使用还会给开发者带来额外的问题。

**Comment by shigma** [comment]
感谢您的回复。你提出了非常有价值的观点，我也愿意向你解释我们设计的初衷。我们如此设计是考虑到更加复杂的情况。

- 关于用户：插件市场中的每一个插件，我们倾向于认为其功能是一个整体。一个插件中的中间件可能调用该插件中的指令，不同的指令也可能互相调用。**如果插件的使用者在不知道这一切的情况下仅仅调整某一个指令的过滤器，就会导致功能上的异常**。这是我们不希望用户遇到的。

- 关于开发者：如果这些功能之间没有依赖关系，那么将它们分离成多个插件，又或者提供不同的 filter 都是非常合理的选择。良好的模块化往往是奠定优秀软件的基础。关于你所说的 nai，喵喵，pcr 插件，我也倾向于认为这些都只是一个比较大的功能，而不是多个功能（如果你去查看 novelai-bot 的 issue，你会看到一些希望拆分的意见，只不过我们没有采纳。）

- 关于功能：我所说的功能是从逻辑上考虑，只要它们存在被拆分的价值，就可以被拆分。插件往往是根据作者自身的需求来编写的，很难考虑到别人的用法。如果用户希望它们分别配置而它们实际上没有被拆分，那其实就是没有充分实现用户需求。此时用户可以选择建议开发者进行调整，或者 fork 出来自行修改。

- 关于粒度：一个插件往往由多个部分组成，其内部逻辑往往是相互联系的（正如上面所说）。如果我们专门提供指令级别的过滤，未来就面临需要提供中间件级别、甚至是选项级别的过滤等问题。因此，与其投入无限精力解决可能带来额外问题的特性，不如引导开发者构建更好的插件生态。

**Comment by 15015070064** [comment]
> 感谢您的回复。你提出了非常有价值的观点，我也愿意向你解释我们设计的初衷。我们如此设计是考虑到更加复杂的情况。
> 
> * 关于用户：插件市场中的每一个插件，我们倾向于认为其功能是一个整体。一个插件中的中间件可能调用该插件中的指令，不同的指令也可能互相调用。**如果插件的使用者在不知道这一切的情况下仅仅调整某一个指令的过滤器，就会导致功能上的异常**。这是我们不希望用户遇到的。
> * 关于开发者：如果这些功能之间没有依赖关系，那么将它们分离成多个插件，又或者提供不同的 filter 都是非常合理的选择。良好的模块化往往是奠定优秀软件的基础。关于你所说的 nai，喵喵，pcr 插件，我也倾向于认为这些都只是一个比较大的功能，而不是多个功能（如果你去查看 novelai-bot 的 issue，你会看到一些希望拆分的意见，只不过我们没有采纳。）
> * 关于功能：我所说的功能是从逻辑上考虑，只要它们存在被拆分的价值，就可以被拆分。插件往往是根据作者自身的需求来编写的，很难考虑到别人的用法。如果用户希望它们分别配置而它们实际上没有被拆分，那其实就是没有充分实现用户需求。此时用户可以选择建议开发者进行调整，或者 fork 出来自行修改。
> * 关于粒度：一个插件往往由多个部分组成，其内部逻辑往往是相互联系的（正如上面所说）。如果我们专门提供指令级别的过滤，未来就面临需要提供中间件级别、甚至是选项级别的过滤等问题。因此，与其投入无限精力解决可能带来额外问题的特性，不如引导开发者构建更好的插件生态。

1. 用户要求开发者修改，这个我觉得是不太实际的
2. 技术上不能实现只针对直接调用command的过滤吗
3. 我现在的koishi.yml 已经超长，真的不想未来会更长

**Comment by MaikoTan** [comment]
1. The user profuce their issues, and then the developer solve the problem, this is the normal and healthy open source software cooperation workflow.

2. It could. But we don't want to. The reason was above.

3. The `koishi.yml` is supposed to be changed by koishi console the GUI instead of yourself.

**Comment by shigma** [comment]
> 用户要求开发者修改，这个我觉得是不太实际的

你可以发 issue 或者论坛贴，这都是开源社区中比较通用的做法。用户与开发者的交流也能促进生态的良性发展。

我们正在努力建设 Koishi 论坛，你可以去看看。论坛上有非常优秀的开发者，如果你去发一个拆分插件的需求贴他们很快就能把插件拆分出来供你使用了。

> 技术上不能实现只针对直接调用command的过滤吗

技术上非常好实现。但允许用户瞎配会导致大量插件不可用。我担心这些负面影响。

> 我现在的koishi.yml 已经超长，真的不想未来会更长

koishi.yml 是配置文件，本身不是用于编辑的，理想情况下所有的功能都可以在控制台内完成，你大可不必点开看它的长度。

**Comment by shigma** [comment]
虽然作者自己关掉了不过还是提一下目前的进度（截至 4.11.8 发布前）：

- and / or 两层结构：已经完全实现
- command 过滤器：未来会实现，我想到了比较安全的做法

**Comment by Willyoucallme** [comment]
> 虽然作者自己关掉了不过还是提一下目前的进度（截至 4.11.8 发布前）：
> 
> * and / or 两层结构：已经完全实现
> * command 过滤器：未来会实现，我想到了比较安全的做法

阿哲，还以为不做了，那我还是打开吧

**Comment by KuroshioDev** [comment]
3.0.0的command可以解决这个问题
