### ISSUE TITLE
Bug: 偶现插件无法收到消息的情况

### ISSUE THREAD

**Issue by idanran** [koishijs/koishi#961]
### Describe the bug

当数据库的 channel 表的 assignee 为空时，插件将会无法收到消息。
我也不知道 assignee 为啥会出现为空的情况，但它确实出现了。

### Steps to reproduce

过于诡异，未知重现方法。

### Expected behavior

确保 assignee 不为空，或在 assignee 为空的情况下，也能接收消息。

### Versions

- OS: Windows 10
- Platform: OneBot
- Node version: 19.5.0
- Koishi version: 4.11.4

**Comment by shigma** [comment]
没有复现确实无法解决。请尝试在禁用大部分功能性插件的情况下重现此问题。

**Comment by idanran** [comment]
> 没有复现确实无法解决。请尝试在禁用大部分功能性插件的情况下重现此问题。

不过可以手动把 assignee 删掉。

**Comment by shigma** [comment]
手动删除 assignee 后不作响应是预期行为。assignee 是为了防止多个 Koishi 机器人加入同一个群出现多回复或者循环触发而设计的，每个群只有一个 bot 能在不 at 的情况下对所有功能做出响应。删除 assignee 意味着该群中的机器人都需要 at 才会响应。

**Comment by idanran** [comment]
> 手动删除 assignee 后不作响应是预期行为。assignee 是为了防止多个 Koishi 机器人加入同一个群出现多回复或者循环触发而设计的，每个群只有一个 bot 能在不 at 的情况下对所有功能做出响应。删除 assignee 意味着该群中的机器人都需要 at 才会响应。

啊这，目前还是没找到复现的方法。

**Comment by idanran** [comment]
或许可以在 assignee 为空时填入值或将整条数据删掉。
