### ISSUE TITLE
Bug: QQ频道Adapter两个BUG

### ISSUE THREAD

**Issue by KuroshioDev** [koishijs/koishi#965]
### Describe the bug

1. 私域机器人无法收到私信内容
2. 无法发送图片

### 无法收到私信内容
1. 注册一个私域机器人
2. 安装[adapter-qqguild](https://koishi.chat/plugins/adapter/qqguild.html)插件
3. 在插件配置中打开全部监听消息
![image](https://user-images.githubusercontent.com/40047545/216806565-de860317-9974-4f56-a861-57611f1078e0.png)
4.在公共频道发送channel
![image](https://user-images.githubusercontent.com/40047545/216806633-f5724f0c-56a2-4bce-a453-ac2c85bab48f.png)

5. 私信机器人channel
![image](https://user-images.githubusercontent.com/40047545/216806619-360bb573-d42c-49be-94f8-d65b7a0871bc.png)

### 无法发送图片
1. 注册一个私域机器人
2. 安装[adapter-qqguild](https://koishi.chat/plugins/adapter/qqguild.html)插件，并登录
3. 在公共频道发送图片
![image](https://user-images.githubusercontent.com/40047545/216806648-2e79e0c6-bb62-407f-b005-b68a914d21dc.png)

### Expected behavior

1.能收到私信消息
2.能发图片

### Versions

- OS: windows10
- Platform: QQ Guild
- Node version:18
- Koishi version: 4.11.4

### Additional context
1.顺便一提OneBot也收不到频道的私聊信息，不知道是不是没这个功能
_No response_

**Comment by NWYLZW** [comment]
我一直测试不了私聊，我不确定是啥问题导致的
（因为我没找到私聊机器人的按钮）
这几周我抽空看一下私聊的问题
图片感觉应该是 windows 系统的适配问题，需要讨论一下
如果不麻烦大概这周会修复

**Comment by Willyoucallme** [comment]
> 我一直测试不了私聊，我不确定是啥问题导致的 （因为我没找到私聊机器人的按钮） 这几周我抽空看一下私聊的问题 图片感觉应该是 windows 系统的适配问题，需要讨论一下 如果不麻烦大概这周会修复

1.私聊的话你要先用手机私聊一次机器人，然后PC上按小信箱按钮（否则看不见）
![image](https://user-images.githubusercontent.com/40047545/216826121-ee947998-3c53-42a0-90b6-5d8c297a38c9.png)

2.  能否增加QQ GUILD的logs显示，因为我无法确定是否接受到信息

**Comment by NWYLZW** [comment]
> > 我一直测试不了私聊，我不确定是啥问题导致的 （因为我没找到私聊机器人的按钮） 这几周我抽空看一下私聊的问题 图片感觉应该是 windows 系统的适配问题，需要讨论一下 如果不麻烦大概这周会修复
> 
> 1.私聊的话你要先用手机私聊一次机器人，然后PC上按小信箱按钮（否则看不见） ![image](https://user-images.githubusercontent.com/40047545/216826121-ee947998-3c53-42a0-90b6-5d8c297a38c9.png)
> 
> 2. 能否增加QQ GUILD的logs显示，因为我无法确定是否接受到信息

1 我试试看
2 我看一下是单独加一个配置项合适还是默认输出，因为一般来说消息很多，放在 log 里面很干扰对于 koishi 应用的排错

**Comment by NWYLZW** [comment]
这个是频道作为应用来说的自身解析问题，我并没有做多余的数据处理
（虽然我确实也能和我同事反馈这个问题就是了）

**Comment by shigma** [comment]
您好，file not found

**Comment by ilharp** [comment]
![image](https://user-images.githubusercontent.com/20179549/217542087-bf62b2d7-65b7-4808-b69f-b2c586a5f0b9.png)

**Comment by Willyoucallme** [comment]
自己提的issue就应该由自己修复(nmd,为什么)
https://github.com/satorijs/qq-guild-sdk/pull/7
https://github.com/satorijs/satori/pull/76

已经解决两个问题，确认后麻烦帮我关闭

**Comment by shigma** [comment]
优秀的开发者自己提 issue 自己修，太棒了！

**Comment by NWYLZW** [comment]
> 自己提的issue就应该由自己修复(nmd,为什么) [satorijs/qq-guild-sdk#7](https://github.com/satorijs/qq-guild-sdk/pull/7) [satorijs/satori#76](https://github.com/satorijs/satori/pull/76)
> 
> 已经解决两个问题，确认后麻烦帮我关闭

这俩个修复看起来并没有解决相应的问题

* 这里需要使用 dms 相应的 api 创建对应的会话
* 其次需要管理程序运行过程已有的会话，并复用
* 存在被动消息与主动消息的问题
* 处理不同操作系统下的路径

如果你仍有兴趣处理相关问题，欢迎继续跟进

**Comment by NWYLZW** [comment]
这个应该是因为你的会话存在，我刚刚看了一下自己代码
我好像并没有主动创建会话逻辑？？？
难道我代码会自己给自己加功能了吗

**Comment by Willyoucallme** [comment]
> 这个应该是因为你的会话存在，我刚刚看了一下自己代码 我好像并没有主动创建会话逻辑？？？ 难道我代码会自己给自己加功能了吗

我只是粗略的看了一下你的代码，你这里是这样写的
![image](https://user-images.githubusercontent.com/40047545/221479314-38a271f7-c533-488e-ba9c-0e8e4c77766a.png)

可能我理解的不对，但是他是可以用的。

**Comment by NWYLZW** [comment]
> > 这个应该是因为你的会话存在，我刚刚看了一下自己代码 我好像并没有主动创建会话逻辑？？？ 难道我代码会自己给自己加功能了吗
> 
> 我只是粗略的看了一下你的代码，你这里是这样写的 ![image](https://user-images.githubusercontent.com/40047545/221479314-38a271f7-c533-488e-ba9c-0e8e4c77766a.png)
> 
> 可能我理解的不对，但是他是可以用的。

那就没错，这里没办法主动创建 dms 会话
这里只能处理已存在的会话

**Comment by Willyoucallme** [comment]
> > > 这个应该是因为你的会话存在，我刚刚看了一下自己代码 我好像并没有主动创建会话逻辑？？？ 难道我代码会自己给自己加功能了吗
> > 
> > 
> > 我只是粗略的看了一下你的代码，你这里是这样写的 ![image](https://user-images.githubusercontent.com/40047545/221479314-38a271f7-c533-488e-ba9c-0e8e4c77766a.png)
> > 可能我理解的不对，但是他是可以用的。
> 
> 那就没错，这里没办法主动创建 dms 会话 这里只能处理已存在的会话

那还是大佬你来处理一下吧？

**Comment by NWYLZW** [comment]
嗯，我已经开了一个分支在处理了
