### ISSUE TITLE
Bug: OneBot在QQ频道只能响应有@的命令

### ISSUE THREAD

**Issue by Willyoucallme** [koishijs/koishi#969]
### Describe the bug

在QQ频道发送不带@的命令，gocq无log
当发送带@的命令时，gocq有log
不知道是不是gocq的问题
![9b27fb62044d595a11dd0aa9fd68388e](https://user-images.githubusercontent.com/40047545/217588279-1429e22d-dd63-4d67-8349-5430ef48bf77.png)

### Steps to reproduce

1. 安装onebot插件
2. 往QQ频道发送不带@的channel命令

### Expected behavior

希望能响应不带@的命令

### Versions

- OS: windows 10
- Platform:  QQ Guild
- Node version: 17
- Koishi version: 4.11.5

**Comment by MaikoTan** [comment]
Did you have any `prefix`-es set in the global settings?

你是否有任何`前缀`-es设定在全局设置？

**Comment by Willyoucallme** [comment]
> Did you have any `prefix`-es set in the global settings?
> 
> 你是否有任何`前缀`-es设定在全局设置？

这个吗，应该没有的，因为在QQ群不用@也能触发
![image](https://user-images.githubusercontent.com/40047545/217591534-1b77bd4e-af1f-4ae8-8669-b0b7deece196.png)
qq群
![image](https://user-images.githubusercontent.com/40047545/217591606-5c58d058-dd7d-46f6-9b79-6d41ab5d09d1.png)

**Comment by Willyoucallme** [comment]
OneBot 在QQ频道下无法使用问答或者bind功能
![4VQ83MTJIJ C5RG@_T1Y _M](https://user-images.githubusercontent.com/40047545/217610125-4987a349-e292-4321-858c-e62f0342d619.png)

推测原因：
QQ频道的element会自带空格
![PCH5K)4`G4LP MAELOX26O](https://user-images.githubusercontent.com/40047545/217610245-b247e574-873e-42c8-8fd8-a56a6a46762a.png)

**Comment by shigma** [comment]
这个空格的 char code 是 32 吗？

**Comment by shigma** [comment]
这个问题有后续进展吗？

**Comment by Willyoucallme** [comment]
> 这个问题有后续进展吗？

后续来了，是我的问题，和QQguild一起用的时候忘记assign回去了

**Comment by KuanTT** [comment]
> > 这个问题有后续进展吗？
> 
> 后续来了，是我的问题，和QQguild一起用的时候忘记assign回去了

我也遇到这个问题了，大佬，应该怎么解决呢
