### ISSUE TITLE
RFC: i18n configurations

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi#977]
未来计划增加的与国际化相关的配置项。

## locale

全局默认语言。类型为 `string`。

未来可能会支持 `string[]`。

## i18n.output

输出语言设置。有两个可选值：

- prefer-user：优先使用用户语言，其次使用频道语言、群组语言
- prefer-channel：优先使用频道语言、群组语言，其次使用用户语言

## i18n.match

当用户语言和频道语言与 `ctx.match()` 设置的语言不兼容时的行为。有三个可选值：

- strict：匹配失败
- prefer-input：优先使用输入语言，即写在 locales 中的语言
- prefer-output：优先使用输出语言，行为基于 `i18n.output`

**Comment by shigma** [comment]
关于限定机器人的可用语言大致有两种方案：

- 方案 1：增加配置项 `allowedLocales`，类型为 `string[]`。行为如下：
  - 用户无法在 `locale` 指令中设置此列表以外的语言
  - 输出的语言序列中自动剔除此列表以外的语言，如果清空则使用默认语言
- 方案 2：`i18n.output` 配置项增加一个 `fixed` 可选值，表示只接受全局配置 `locales` 作为语言

**Comment by shigma** [comment]
cc @MaikoTan

**Comment by MaikoTan** [comment]
Maiko agreed with the first floor.

And as for the second floor:

> * 方案 1：增加配置项 `allowedLocales`，类型为 `string[]`。行为如下：
>   
>   * 用户无法在 `locale` 指令中设置此列表以外的语言
>   * 输出的语言序列中自动剔除此列表以外的语言，如果清空则使用默认语言
> * 方案 2：`i18n.output` 配置项增加一个 `fixed` 可选值，表示只接受全局配置 `locales` 作为语言

Maiko thinks the Approach 1) would be better compared in these two.
But is it possible to make `locales` as a checkbox group and then user could select one or more of them, also `select all` and `deselect all`?
(This needs `schemastery` and `schemastery-vue` changes, but Maiko thinks it is worth to do the such thing)

**Comment by shigma** [comment]
> But is it possible to make locales as a checkbox group

在显示一个 checkbox group 之前首先得决定显示什么。要手动枚举世界上所有的语言吗？

**Comment by shigma** [comment]
可以手动添加元素的列表现在就已经是支持的。

**Comment by MaikoTan** [comment]
> > But is it possible to make locales as a checkbox group
> 
> 在显示一个 checkbox group 之前首先得决定显示什么。要手动枚举世界上所有的语言吗？

Well, is it possible to dump every available languages from plugins? Not actually need to have languages "all over the world", only available currently.

If this is impossible for now, I think the approach 1) that you have written above would be a better one.

**Comment by shigma** [comment]
> Well, is it possible to dump every available languages from plugins?

我认为这是不合理的。插件会动态变化，这样做将意味着随着插件的变化，用户可配置的范围也会改变。

**Comment by shigma** [comment]
match 暂不实现。其余两个配置项已经实现完毕。
