### ISSUE TITLE
Bug: onebot接入QQ频道后一段时间稳定报错

### ISSUE THREAD

**Issue by ghostcatu** [koishijs/koishi#978]
### Describe the bug

报错机器人是在线状态，但是不再响应onebot消息，其他平台可以使用
![image](https://user-images.githubusercontent.com/113200130/218896608-0c329436-a931-4b8f-9ae3-64796382f020.png)

### Steps to reproduce

onebot接入QQ频道，挂机一段时间

### Expected behavior

不报错

### Versions

- OS: ubuntu
- Platform: QQGuild
- Node version: <17
- Koishi version: 4.11.5

**Comment by ghostcatu** [comment]
dev模式的问题

**Comment by shigma** [comment]
咦真的吗，我有点想象不出来跟 dev 有什么关系（
