### ISSUE TITLE
Bug: CLI cannot start of koishi.yml is read only.

### ISSUE THREAD

**Issue by purerosefallen** [koishijs/koishi#986]
### Describe the bug

If koishi.yml is readonly, like, volumed in ro type, or in a readonly-mounted filesystem, it can't start.

### Steps to reproduce

docker run -it --rm -v  ./koishi.yml:/koishi/koishi.yml koishijs/koishi:latest

### Expected behavior

It should start well with a readonly config file.

### Screenshots

Looks like it parsed this yaml file as a js file.

### Versions

- OS:  Debian 11
- Platform:  OneBot
- Node version:  18.14.2
- Koishi version:  4.11.7

**Comment by purerosefallen** [comment]
![Screenshot_20230223_174218](https://user-images.githubusercontent.com/19840160/220879055-dd742ee4-a695-4c4f-a84a-47514cabf2cd.jpg)

**Comment by shigma** [comment]
额，这是把你的配置文件当成 ts 来读了吧，跟 readonly 有啥关系？
