### ISSUE TITLE
Feature: add command prefix hints for the `help` command

### ISSUE THREAD

**Issue by MirrorCY** [koishijs/koishi#989]
### Describe the problem related to the feature request

The `帮助` command can be used to obtain a list of available commands for the bot, but there is currently no way to retrieve the command prefix for the bot. This can be particularly inconvenient in group settings with multiple bots, as it can be difficult to remember the prefix for each bot.

### Describe the solution you'd like

add an option in the plugin `help` to control whether to display the command prefix

**Comment by shigma** [comment]
So what's your ideal output for `help` with prefix such as `.`?

**Comment by MirrorCY** [comment]
or more extreme?
```
当前可用的指令有：
    .echo  向当前上下文发送消息
输入“.help 指令名”查看特定指令的语法和使用示例。
输入“.help”查看此帮助信息。
```

**Comment by Anillc** [comment]
指令前缀可能有多个，在每条指令前加一个前缀不太可取。

如果要列出所有前缀的话我认为不应该用过于书面的表达，用户可能难以看懂，最好同时还添加一些示范。

**Comment by shigma** [comment]
> 指令前缀可能有多个，在每条指令前加一个前缀不太可取。

其实可以用第一个。第一个表示推荐的前缀挺合理的。

**Comment by ilharp** [comment]
个人觉得在指令列表后提示 `使用「{0} + 指令名」调用指令。` 就足够。

**Comment by MirrorCY** [comment]
> 个人觉得在指令列表后提示 `使用「{0} + 指令名」调用指令。` 就足够。

`使用「+ + 指令名」调用指令`
`使用「. + 指令名」调用指令`

好像也行

**Comment by Anillc** [comment]
根据我多年观察别人用 bot 的经验，只加一句话在后面提示，用户一定看不懂（，要么就在命令前都加前缀，要么就写详细点

**Comment by Anillc** [comment]
大部分人都不知道指令的逻辑，他们只会复制关键词或者直接复制别人用的命令来修改。甚至很详细的解释也没有用。

现在我也认为用第一个前缀加到指令上的方案比较好了。

**Comment by MaikoTan** [comment]
Agreed.

And if we goes this way, the corresponding commands should be changed as well, Let's say the `prefix` is `.`(dot) here:

- `.help` with command could be `.help .<command>` or `.help <command>` (as the help command should strip the prefix out before finding the command)
- "command not found" message could be ".hlep not found. Do you mean .help ?"
