### ISSUE TITLE
无法稳定接入market

### ISSUE THREAD

**Issue by JoonSumisu** [koishijs/koishi#993]
![截屏2023-02-28 00 33 07](https://user-images.githubusercontent.com/77182770/221623421-2bd14fb8-c077-4989-b745-2a8f68e527a8.png)
![截屏2023-02-28 00 35 21](https://user-images.githubusercontent.com/77182770/221623526-a8a757eb-e1d7-49a3-a9ff-c9e0ab7a7b31.png)

安装好后出现无法接入market的问题
但是又一次却又可以

网络环境 使用了clash的规则跟自动选择

谢谢

**Comment by MaikoTan** [comment]
Since you are using `clash` as the proxy software, you could add `*.koishi.chat` into the whitelist of the clash to make clash ignoring those traffic.

**Comment by JoonSumisu** [comment]
> 

Thx
