### ISSUE TITLE
Feature: `create koishi` 在生产环境中去掉开发依赖

### ISSUE THREAD

**Issue by Seidko** [koishijs/koishi#994]
### Describe the problem related to the feature request

在现在的 `create koishi` 中，生产环境仍然会安装开发依赖，如果去掉这些依赖的话可以有效减少生产环境中的 koishi 模板项目的体积。

### Describe the solution you'd like

增加一个 `--prod` 参数，`koishi script` 接收到这个参数后把模板项目带有的 `devDependencies` 删除。

**Comment by ilharp** [comment]
我觉得有能力使用 `create-koishi` 的人自己运行 `--production` 应该不是问题

**Comment by Seidko** [comment]
现在`create-koishi`已经可以`--production`了吗（

**Comment by shigma** [comment]
> 我觉得有能力使用 `create-koishi` 的人自己运行 `--production` 应该不是问题

楼主的意思是，create 之后不会删除 devDep，同时在插件市场安装插件时会再次执行 `yarn` 把开发依赖也下下来。

**Comment by ilharp** [comment]
理解了。实现方面，我认为使用 [master 分支](https://github.com/koishijs/boilerplate/tree/master) 是一个比单纯删去 devDeps 更好的方案。

**Comment by shigma** [comment]
master 分支不是有 devDependencies 吗？

**Comment by ilharp** [comment]
ohh...

其实我是想复用整合包打包的逻辑，也就是说我们目前的整合包打包并没有把产物推到某个分支上？那还是有一点麻烦的

**Comment by shigma** [comment]
你认为需要这样做吗？

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by ilharp** [comment]
我对此没有偏好，不过我觉得我们至少需要一种方式复用现有的整合包打包逻辑，这样 `package.json` 才是适合此 issue 需求的。

**Comment by shigma** [comment]
> 我们至少需要一种方式复用现有的整合包打包逻辑，这样 package.json 才是适合此 issue 需求的

不应该复用完整的打包吧，我们只需要 package.json，不需要 node_modules。

**Comment by purerosefallen** [comment]
can it be done by NODE_ENV=production?

**Comment by shigma** [comment]
> can it be done by NODE_ENV=production?

Yes, but `yarn start` does not (and should not) set this environment variable, because whenever one runs koishi without this environment variable and installs any plugin, the devDependencies will be installed back.

So maybe it's better to delete all devDependencies?
