### ISSUE TITLE
Feature: 梦梦是个笨蛋ww

### ISSUE THREAD

**Issue by Smile-DK** [koishijs/koishi#999]
### Describe the problem related to the feature request

aaa

### Describe the solution you'd like

aaa

### Describe alternatives you've considered

aaa

### Additional context

<at id="2837314711" /> 是不是呀？
<at id="708968511" /> Maiko 似乎也好笨的样子。

**Comment by ilharp** [comment]
Reported as spam content

**Comment by MaikoTan** [comment]
Reported as abuse content

**Comment by Seidko** [comment]
1. 此 issue 在利用 [GitHub](https://github.com/koishijs/koishi-plugin-github/issues/27) 插件的漏洞进行 xss 攻击
![image](https://user-images.githubusercontent.com/64234553/222341106-a88d620d-9878-4f15-96b8-32bedc81466e.png)
2. 不清楚此人的身份，暂且不做评价。
3. 合理怀疑此 issue 带有恶意。
4. 奉劝某些人不要把个人行为上升到项目。
